### ISSUE TITLE
Design: Public Use and Syndication Text

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#100]
> **ESTIMATE** Story Points TBD

> Discovery Ticket: Discovery Kickoff: Article and Related Inline Content Features #62

### Description of Design request:
Design for the public use and syndication text that appears on content-rich content types. 

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Sub-Task
- [ ] Sub-Task
- [ ] Sub-Task

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Consider using https://www.cancer.org/latest-news/six-ways-to-lower-your-risk-for-colon-cancer.html#reviewed_by

##

**Comment by anthonycuellar** [comment]
Note: This may be shifting from Sprint 5 to 6
