### ISSUE TITLE
Remove utility classes from nci-hero markup. 

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1007]
Remove all utility classes in nci-hero. Be sure to check:
- [x] gatsby documentation site
- [x] ncids-js-testing example site
- [x] ncids-css-testing storybook 
 
This util dependency is unnecessary and the hero can be used without the classes stinking up the place.

**Comment by bennettcc** [comment]
This ticket is in a PR and ready for review - moving to on hold until we get through the 2.1 crunch
