### ISSUE TITLE
[Change Request] Add Radius to Guide Cards with Image & Description

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#1010]
### Change Request Description
Guide Cards with Image & Description will be updated to have a radius of 4px. They currently do not have a radius, and this will be completed after the R2.1 launch.

**IMPORTANT NOTES:**
* This will **not** be part of R2.1 launch
* Consider addressing this change request while building out the 3-card guide card row (R2.2) since this component also has the radius and these two components should be consistent.
* At the time of creating this change, confirm with Designers/Product if there is a border in addition to the drop shadow on this component

### What's the Expected Change?
- Add a radius of 4px to the Guide Card with Image & Description component

### What's the Current Functionality?
- The Guide Card with Image & Description component has no radius

### What's the updated acceptance criteria?
```gherkin
Scenario: User views a page with a Guide Card with Image & Description
Given a user is viewing a landing page with a Guide Card with Image & Description
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Guide Card with Image & Description on the example site
  And the Guide Card with Image & Description will have a radius of 4px
  And the Guide Card will match the updated comp on Figma
```

### Additional details / screenshot
- See the comp on the Figma here: https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?type=design&node-id=2162-3511&t=yNnv7DrjpZ2TP5D9-0

Corner with Radius:
![image](https://github.com/NCIOCPL/ncids/assets/115043734/ef4e8b3c-116e-46e5-a61b-72b140dfb34b)

### Related Tickets
* Original Story Ticket #614 
* Original PR Ticket #774

**Comment by arcepaul** [comment]
spoke with @monika-jaeger, the figma comps will be updated so that the guide cards with img and description will have all have rounded corners at all breakpoints

**Comment by alinai** [comment]
This looks good to me on ODE584. cc @KateMashkinaNIH
