### ISSUE TITLE
Remove `usa-section--nci-cta-strip` from CTA Strip Examples

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#1013]
### Issue description
> **ESTIMATE** TBD

There seems to be an extra `usa-section--nci-cta-strip` class added to the CTA Strip examples (including storybook). This should be removed.

Please also remove the `aria-label="Call to action"` on all the examples too and in the documentation site if it is there. The aria-label should not be used if it is going to be "junk".

**Comment by bennettcc** [comment]
This is ready for review - moving to on hold until we're out of the 2.1 dev crunch
