### ISSUE TITLE
Another sometimes failing test - input suffix/prefix 

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1014]
Sometimes the regression test fails for the input suffix/prefix component. 

![failed_diff_ncids_usa-input-prefix-suffix_suffix_click_0_document_0_mobile](https://github.com/NCIOCPL/ncids/assets/85901679/21f5ae26-506a-40df-8651-2675a2bb14be)

Dev note: it probably needs some kind of await selector like the others.

**Comment by sarinapadilla** [comment]
Closing since we haven't seen this fail in a while. We can reopen if it comes up again.
