### ISSUE TITLE
nci-card a11y 

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1015]
In CGDP we agreed to update all feature cards with `labelledby` attributes that link to required headings. It was decided that guide cards should behave similarly.

1. We need to discuss in depth all variants of cards to ensure we have accessible labels and what will be DS features or CGDP-only features. 
 - Feature card needs this as part of the component
 - Guide card with image and description needs this as part of the pattern
3. Afterwards, we need to go back to the DS and update: 
    - [ ] All documentation site examples
    - [ ] All storybook examples
    - [ ] All example site examples

**Comment by sarinapadilla** [comment]
Closing this ticket because this is out of date from a content perspective.
