### ISSUE TITLE
NCI Hero with CTA strip heading/tagline should set color

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1017]
NCI Hero with CTA strip heading/tagline should set color

Color is being overriden to accent-cool. And it should be ____?

Related: #1016

![Screenshot 2023-05-30 at 3 49 52 PM](https://github.com/NCIOCPL/ncids/assets/110177947/cfc1c7ff-178c-4ad0-8a95-f4af295d92f9)
Note: The hero is `usa-section--dark` in this screenshot

**Comment by dlescarbeau** [comment]
@olitharp-nci This seems to be a non-issue that only occurs when the usa-section being applied is a `usa-section--dark` rather than `usa-section--light`

**Comment by dlescarbeau** [comment]
Closing this ticket, currently there is no scenario in which we would apply `usa-section--dark` to the NCI Hero with CTA Strip, so this issue with the tagline color will never occur.
