### ISSUE TITLE
Update sample pages on example site and storybook with content from cgov-digital-platform

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1026]
### Change Request Description
The requested change is to update the Example site so that it matches the ODE exactly to improve testing. The pages to be updated on the Example site and their equivalent on the ODE are listed below.

### Expected Change
Update the following on the Example Site (https://designsystem-dev.cancer.gov/develop/example-site/)

- [x] Make the [CancerGov Home Page](https://designsystem-dev.cancer.gov/develop/example-site/example-pages/cgov-home.html) match the [ODE Home Page](https://www-dev-ac.cancer.gov/)
- [x] Make the [Landing Page](https://designsystem-dev.cancer.gov/develop/example-site/example-pages/landing-page.html) match the [Grants and Training Landing page](https://www-dev-ac.cancer.gov/grants-training)
- [x] Create new Fake Landing Page 1 to match the [ODE Sample Page 1](https://www-dev-ac.cancer.gov/sample-page-1)
- [x] Create new Fake Landing Page 2 to match the [ODE Sample Page 2](https://www-dev-ac.cancer.gov/sample-page-2)
  * Update to use a 3 guide card row (choose link titles as you wish)
- [x] Create new Fake Landing Page 3 to match the [ODE Sample Page 3](https://www-dev-ac.cancer.gov/sample-page-3)
  * Update to remove the title
  * Update the hero to be a dark hero with primary CTA
  * Update the second promo block to have image right
- [x] Create new Fake Landing Page 4 to match the [ODE Sample Page 4](https://www-dev-ac.cancer.gov/sample-page-4)
  * Update to use a 3 guide card row (choose link titles as you wish)

### Acceptance Criteria
```gherkin
Scenario: The DS Example Site matches the test pages on the ODE
Given a user is viewing the DS Example Site
Then the DS Example Site exactly matches the test pages on the ODE
```

**Comment by bennettcc** [comment]
Based on internal conversation on 6/27, this story is on hold. Action items to follow:

- Monika replace homepage png images to be jpegs (where required) on ACSF test
- Bryan retest page speed on acsf-test after Monika's images changes
- Monika + Laurel replace images in Prod CMS (and shared teams folders used by content team) ahead of 7/13 content launch (so the correct jpegs are added into the new [c.gov](http://c.gov/) launched pages)
- Laurel create design backlog ticket to develop documentation/guidance for when jpegs vs pngs should be used on [c.gov/microsites](http://c.gov/microsites)
- Sarina/Andy create digi platform GH ticket to update YAML with new jpeg images (to match what Monika is changing on acsf and eventually prod)

**Comment by laurelthrash** [comment]
Determined during 7/13 UX meeting that we need to provide the following:

1. Link to Teams folder with images (@monika-jaeger )
2. Link to content templates: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates?csf=1&web=1&e=i2zFxX

Team to reference what is published to production on 7/13. Cc: @bennettcc @sarinapadilla

**Comment by laurelthrash** [comment]
Marking as "Done" on design board as design has shared necessary information.

**Comment by bennettcc** [comment]
Moved this from 'on hold' on the Dev board. It will need to be completed after https://github.com/NCIOCPL/ncids/issues/948
