### ISSUE TITLE
Baseline Discovery: Related Resources and Recommended Content

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#103]
## Baseline Discovery: Related Resources and Recommended Content 

Do baseline discovery for the group of components that supply supplementary or complimentary information
- article and other types - Related Resources
- blogs - Recommended Content (clickbait cards) 

Component Details and examples: https://www.notion.so/Related-Resources-and-Recommended-Content-baafce07e4364532879d548abd74461f

- Findings should be captured in the Notion for discussion. 

> **ESTIMATE** TBD

## POTENTIAL Tasks

- [x] Drupal report of pages with feature
- [ ] Synthesis of any existing analytics Data around use and function 
- [ ] High-level heuristic review of feature
- [ ] Technical or accessibility flags
- [ ] Best practices around feature

### Resources
* Notion: https://www.notion.so/Related-Resources-and-Recommended-Content-baafce07e4364532879d548abd74461f

### Notes
*Some complementary notes if necessary:*

**Comment by VictoriaSunNIH** [comment]
Closing this as we have designs for related resources (articles) and recommended content (blogs)
