### ISSUE TITLE
[R2.1 Content] Research Spanish Feature Card Image may need a new crop

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1033]
Basic Information: "Informe Annual a la Nación" Feature Card may need a new crop to fit 4:3.

Sub-tasks:
- [x] Update crop 
- [x] Receive approval from creative director (if needed)
- [x] Add new 1:1 crop to "NCIDS Promo Art" selection field in existing ACSF-test CMS image (Adriana)

----
URL: https://www-test-acsf.cancer.gov/espanol/investigacion

Desired Outcome: Figma Comp: https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=142-10130&viewport=621%2C717%2C0.5&scaling=min-zoom

Steps to Reproduce
1. Image is in CMS
Media Name: CGOV-17200_Annual-Report-to-the-Nation-PR-Graphic_ES_1024122_V1
Link: https://www.cancer.gov/sites/g/files/xnrzdm211/files/cgov_image/media_image/2022-10/CGOV-17200_Annual-Report-to-the-Nation-PR-Graphic_ES_10

**Comment by monika-jaeger** [comment]
New crops are located in this folder on Teams: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/Research/Feature%20Cards?csf=1&web=1&e=p5YYal

@laurelthrash & @adrianacastaneda these are ready to be added into the CMS after additional creative approval.

**Comment by laurelthrash** [comment]
@monika-jaeger - do you feel this image crop requires approval from Chuck? If so, will you please coordinate approval with him and note it in this card? Thank you!

**Comment by monika-jaeger** [comment]
Updated crops have been created for 4:3 & 16:9, approved by Chuck, and are located [in this folder on Teams](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/Research/Feature%20Cards?csf=1&web=1&e=Tdk5S4). These are ready to be added to ACSF. @laurelthrash @adrianacastaneda

**Comment by laurelthrash** [comment]
@monika-jaeger - received - will you please add this to your list as an image for which we will need to add the new crops to production?

@adrianacastaneda - will you please meantime update the file in ACSF-test?

**Comment by monika-jaeger** [comment]
@laurelthrash yep! Added that to the [image audit in Figjam](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=36%3A8521&t=UzG29MoVsFEV66LV-1)

**Comment by laurelthrash** [comment]
Moved to Ready for Pickup for @adrianacastaneda.

**Comment by adrianacastaneda** [comment]
@monika-jaeger got this error message when I tried to upload the 16x9 image. Can you resize it please? thank you!

![Image](https://github.com/NCIOCPL/ncids/assets/114433873/9877fd10-2497-4169-99b5-e9a178fd1299)

**Comment by monika-jaeger** [comment]
@adrianacastaneda updated the 16:9 image. Let me know if this works! [Teams folder here](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/Research/Feature%20Cards?csf=1&web=1&e=OqX2nX).

**Comment by adrianacastaneda** [comment]
Updated in ACSF!  cc: @monika-jaeger @laurelthrash

**Comment by laurelthrash** [comment]
Excellent! Going ahead and moving this to closed. Cc: @adrianacastaneda @monika-jaeger
