### ISSUE TITLE
[R2.1 Requested Change] Add NCP to Research and About NCI

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1034]
**Description:** Reported by Anna on 6.9 that we need to add the National Cancer Plan (NCP) to both Research and About NCI landing pages (English). 

Notes: Original idea proposed by Anna is to use the promo block that's also used on the homepage, or the feature card that's used on the Grants & Training page. 

- [x] Verify with Adriana from IA perspective that this is appropriate
- [x] Use generic language that is being used elsewhere 
- [x] Place in the location/order that makes the most sense on the page
- [x] Share updated comps with internal team, as necessary, for internal sign off [N/A]
- [x] Share updated comps with Anna for review/sign off
- [x] Update on (both Research and About NCI):
    - [x] Figma comps (Monika)
    - [x] Content template (Adriana)
    - [x] ACSF-test (Adriana, Laurel)
    - [x] Image FigJam (Monika)
    - [x] v3 Mural board shared with Stakeholders (Laurel)
- [x] Receive updated promo language for this from Kelli/Lakshmi and update: 
    - [x] Figma comps (Monika)
    - [x] Content template (Adriana)
    - [x] ACSF-test (Adriana) **[N/A]**
    - [x] Image FigJam (Monika) **[N/A]**
    - [x] v3 Mural board shared with Stakeholders (Laurel)
    - [x] Production (Laurel)
    - [x] QC Production (Adriana)

**Comment by laurelthrash** [comment]
Hi, @monika-jaeger ! On Thursday (after ACSF testing is concluded) - will you please update the comps for Research and About NCI with the above? We are adding NCP (using existing language) to both comps. The placement is noted in the above comment. 

Please let me know once complete. We will share with Anna for sign-off and implementation. Cc: @adrianacastaneda

**Comment by monika-jaeger** [comment]
Updates are made to the [Research comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=1405-18240&viewport=465%2C628%2C0.25&scaling=min-zoom) and [About NCI comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&type=design&node-id=21-4038&viewport=543%2C332%2C0.25&scaling=min-zoom). These images are also updated in the [Figjam for Image Audit](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=LUC1HMLfUcMrUXkk-1).
cc @laurelthrash @adrianacastaneda

**Comment by laurelthrash** [comment]
6/20: Sent to Anna via Teams chat for approval. Cc: @adrianacastaneda @lburack @monika-jaeger

**Comment by laurelthrash** [comment]
@monika-jaeger @adrianacastaneda Anna confirmed placement looks fine, though we are still awaiting updated promo language from Lakshmi (coordinating with Kelli). For the time being, can we please ensure these promo blocks are updated with the current language as-is in the following place:
- [x] Figma Comps (Monika) - already done!
- [ ] FigJam images board, as needed (Monika)
- [ ] Content template (Adriana)
- [ ] ACSF-test (Adriana)
- [ ] v3 Mural (Laurel)

**Comment by laurelthrash** [comment]
Updated in v3 Mural. This card is on hold until we receive the updated promotional language from Lakshmi/Kelli. Adding this ticket to "on hold" for the time being.

**Comment by laurelthrash** [comment]
Discussed with Anna that we will make a determination EOD Tues. 07/11 to either launch with 1) the language from our approved comps, or 2) newly approved (Lakshmi and Kelli) language that is ready for posting.

**Comment by laurelthrash** [comment]
Updated language received for promo blocks (Research and About NCI) and feature card (Grants & Training). 

Requested text: [Promo Block Text for National Cancer Plan_2023.07.12.docx](https://github.com/NCIOCPL/ncids/files/12028315/Promo.Block.Text.for.National.Cancer.Plan_2023.07.12.docx)

**Comment by monika-jaeger** [comment]
Updates made to comps:

- [Research Page English](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=1405-18240&viewport=54%2C1321%2C0.5&t=LPlbrWqCoUtGmsMr-1&scaling=min-zoom&mode=design): Promo Block
- [About NCI English](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&type=design&node-id=21-4038&viewport=153%2C335%2C0.25&t=QXblko7cgYaKx9fN-1&scaling=scale-down-width&mode=design): Promo Block
- [Grants & Training English](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&type=design&node-id=142-11355&viewport=186%2C1404%2C0.5&t=sYfvFy8pIOwAQwx4-1&scaling=min-zoom&mode=design): Feature Card

cc: @laurelthrash @adrianacastaneda
