### ISSUE TITLE
[R2.1 Requested Change] About Cancer - Add Childhood Cancer

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1035]
**Description:** Per discussion in About Cancer Teams chat, Nelvis requested we add a link related to childhood cancer resources. 

Potential Solutions: 

1. Replace one of the "Cancer Care and Support Resources" feature cards.  Benefit: Keeps the page tight. Down side: These were carefully chosen together based on analytics and collaborative conversation with Becky, Robin, Anne & Lakshmi.  Which would we drop
2. Add a promo block that highlights this collection. Benefit: Dedicated promotion. Down side: Farther down the page before you see it, may push other resources further down.
3. SUGGESTED ADDITION FROM ANNE > Use imagery (hero, guide card, other) related to childhood cancer. Could be in addition to or instead of 1 & 2. Benefit: Clear, quick visual cue. Down side: Finding good, fresh images that aren't already used. Doesn't connect to a resource.
4. Something else that the team recommends. 

Sub-Tasks:
- [x] Connect with Adriana/Lindsay on recommendation for this page
- [x] Share with Anna for approval
- [x] Convey to stakeholders
- [x] Ensure this is reflected on related documents for English and Spanish: (In Progress)
    - [x] Figma comps (Monika) [Spanish updates still needed]
    - [x] Content template (Adriana)
    - [x] ACSF-test (Adriana, Laurel)
    - [x] Image Excel doc (Monika) [Spanish updates still needed]
    - [x] v3 Mural board shared with Stakeholders (Laurel)
- [x] Swap "Symptoms" and "Diagnosis & Staging" in the left guide card [English and Spanish]
    - [x] Figma comps (Monika) 
    - [x] Content template (Adriana)
    - [x] ACSF-test (Adriana)
    - [x] Image Excel doc (Monika) [N/A]
    - [x] v3 Mural board shared with Stakeholders (Laurel)

**Comment by laurelthrash** [comment]
Adding this to the list to discuss with Anna on Tuesday 6/20.

**Comment by laurelthrash** [comment]
@monika-jaeger @adrianacastaneda Anna selected option # 1 (feature card approach) via Teams. Will you please make the appropriate updates to following? 

- [ ] Figma Comps (Monika)
- [ ] FigJam images board, as needed (Monika)
- [ ] Content template (Adriana)
- [ ] ACSF-test (Adriana)
- [ ] v3 Mural (Laurel)

**Comment by monika-jaeger** [comment]
Updated [Figma About Cancer](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=20-2546&viewport=1431%2C218%2C0.5&scaling=min-zoom) comp. Also updated [FigJam image audit](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=40%3A10127&t=OD4leJTLMnfGelfM-1).

Note: it appears that the promo image for the [Support for Families When a Child Has Cancer](https://www.cancer.gov/about-cancer/coping/caregiver-support/parents) article is the [Child and Hand Making Heart](https://www-cms.cancer.gov/sites/g/files/xnrzdm211/files/cgov_image/media_image/2020-09/child-and-adult-hands-making-heart.jpg) image. If this happens to be the case, we may want to select a different image for the Treatment guide card (top right) so we don't have 2 'hands making a heart' images on the page.

cc @laurelthrash @adrianacastaneda 
cc-ing @chuckhrose for image awareness &possibility to select a new image.

**Comment by laurelthrash** [comment]
Next Steps
- [ ] Confer with Chuck on if we recommend updating the image @monika-jaeger 
- [ ] Laurel add a note to the v3 Mural 
- [ ] Laurel to ask Anna if this change also needs to be applied to Spanish (Cc: @adrianacastaneda )

**Comment by laurelthrash** [comment]
@adrianacastaneda confirmed this should be applied to Spanish as well. Will you please put together a recommendation and send in our group Teams chat?

**Comment by adrianacastaneda** [comment]
Made this change in ACSF and the content template. 

@monika-jaeger can you make the same changes that we made in English to the Spanish page mock as well. They're detailed below. 

- Replace "Adaptación al cáncer" with "Hacer frente al cáncer" 
- Replace the Hacer frente al cancer page in the feature card row with [this page](https://www.cancer.gov/espanol/cancer/sobrellevar/apoyo-a-quien-cuida/padres). 
   - Card title: Papás que tienen a un niño con cáncer
   - Description: Sugerencias para ayudar a niños y a padres a salir adelante, y respuestas a preguntas frecuentes.

cc: @laurelthrash

**Comment by monika-jaeger** [comment]
- Made updated to comps for guide card & feature card for [About Cancer Spanish](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=32-6750&viewport=-194%2C250%2C0.5&scaling=min-zoom&mode=design&t=bEHfBBM1uMBKzyQi-1).
- Updated image info for "Papás que tienen a un niño con cáncer" card (line 54) in the [R2.1 Image Evaluation](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/R2.1%20Image%20Evaluation.xlsx?d=wf73f22b0ac4940efab072e943c23df08&csf=1&web=1&e=g9cCGB) sheet.

cc @laurelthrash @adrianacastaneda

**Comment by adrianacastaneda** [comment]
Above has been done in the content template and ACSF @laurelthrash

**Comment by monika-jaeger** [comment]
Updated in the [About Cancer Spanish](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=32-6750&viewport=-194%2C250%2C0.5&scaling=min-zoom&mode=design&t=bEHfBBM1uMBKzyQi-1) Comps. 

cc @laurelthrash @adrianacastaneda
