### ISSUE TITLE
[R2.1 Content] Research English Feature Card Image Discrepancy

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1036]
**For discussion:** Laurel reviewed on 6/11. Ask if there was a reason we chose the art from the comp and align internally. Will want sign off from Anna. 
- Update 6/12: Follow same process as hand heart image. Propose using override image with image from comp. Laurel to tee up to Chuck via Slack. Receive approval/alignment. Share with Anna for final confirmation. 

**Basic Information:** "Clinical Trials Innovation Unit (CTIU)" Feature Card Image Discrepancy 

URL: https://www-test-acsf.cancer.gov/research

Desired Outcome: Figma Comp: https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=1405-18240&viewport=621%2C717%2C0.5&scaling=min-zoom

Steps to Reproduce
1. Image is in CMS
Media Name: clinical trial consultation
Link: https://www-cms.cancer.gov/media/1169551

**Comment by laurelthrash** [comment]
**Recommendation (verified with Chuck and Monika):** Use the override image we selected (https://www-cms.cancer.gov/media/1169551) over the existing promo image (https://www-cms-test.cancer.gov/media/1170361) for the Clinical Trials Innovation Unit (CTIU) feature card.

**Comment by laurelthrash** [comment]
**Decision:** **Use image approved in the comps and potentially recommend for future card on the page**

**Comment by laurelthrash** [comment]
@adrianacastaneda - tagging you in to please assist with the above sub-tasks - thank you! Cc: @monika-jaeger

**Comment by adrianacastaneda** [comment]
@laurelthrash all set!

**Comment by laurelthrash** [comment]
@adrianacastaneda - verified in ACSF-test and on the content template. Closing ticket!
