### ISSUE TITLE
[R2.1 Content] About NCI Spanish Feature Card Image Discrepancy

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1037]
**Proposed next step:** Get Monika/Chuck alignment on image recommendation, then seek confirmation from Anna. 
- Update 6/12: Laurel tee up to Chuck in Slack. Receive approval/alignment. Share with Anna for approval.  

**Basic Information:** Crop for "Cómo contribuir a la investigación del cáncer" Feature Card Image in our comps was the lead image, not the promotional image. Recommend using the approved promotional image instead.

Issue: Mismatched image

URL: https://www-test-acsf.cancer.gov/espanol/instituto

![Image](https://user-images.githubusercontent.com/109552399/244769231-58ab56c0-b69b-4919-af6b-f18b2cf2337f.png)

Desired Outcome: Figma: https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&type=design&node-id=23-4503&viewport=-2014%2C-398%2C1&scaling=min-zoom

![Image](https://user-images.githubusercontent.com/109552399/244769594-d2226955-b0c1-4289-a728-2187cc4b2600.png)

Steps to Reproduce
1) Image in CMS:
Media Name: Research Lab - Spanish
Link: https://www-cms.cancer.gov/media/1142325

**Comment by laurelthrash** [comment]
Sent to Chuck via Slack for confirmation.

**Comment by laurelthrash** [comment]
**Recommendation (verified with Chuck and Monika):** Use the promo image (Handing Heart - Spanish - https://www-cms-test.cancer.gov/espanol/media/1142323) for the Cómo contribuir a la investigación del cáncer" Feature Card Image, as opposed to the image proposed in the comps (lead image for the page).

**Comment by laurelthrash** [comment]
**Decision:** note on v3 in Mural that we chose to use the promo image from the CMS. No need to send around a notification.

**Comment by monika-jaeger** [comment]
@laurelthrash this is now updated in [Figma](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&type=design&node-id=23-4503&viewport=232%2C399%2C0.25&scaling=min-zoom) and [Figjam](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=UPEZObSmoY5TaNni-1).

**Comment by laurelthrash** [comment]
Great, @monika-jaeger ! Going ahead and closing this issue.
