### ISSUE TITLE
Design: Pull Quotes

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#104]
> **ESTIMATE** Story Points TBD

### Description of Design request:

Design style for pullquotes/block quotes

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Sub-Task
- [ ] Sub-Task
- [ ] Sub-Task

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Related Tickets: Discovery Kickoff: Article and Related Inline Content Features #62 
* Pull list of current pages where pull quote with image is used #102 
* Drupal Report: https://lion.box.com/s/es6v12o2vqonoy9xu4t2yy4ii6lfxn2d
* Analysis: https://www.notion.so/Pull-Quote-Block-Quote-4185fcf3b3be456bbb6c638f38f9c02b

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
