### ISSUE TITLE
[R2.1 Content] Update Promo Image for New Hero Banners

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1040]
**Next Steps**
- FYI for Anna: we are adding two promo images
- Receive approval/alignment
- Turn into real ticket
- Slot into R2.1

**Description**
Home and landing pages have the promotional image field on them. This is an existing field for all pages that pulls the 4x3 crop of the associated cgov_image when shared in social media or sharing links on platforms like Microsoft Teams. 

1. Need a resized image of the hero banner that can work well in the Drupal cropping tool 
2. In Drupal, create a cgov_image for each of the hero banners and set the crops with the cropping tool
3. Update the Promotional Image on each of the home and landing pages

**Confirmed from Lindsay:** this only applied to new hero images:
- [x] Homepage
- [x] Research

**Decision:** Approved by Anna on /13

**Comment by laurelthrash** [comment]
@monika-jaeger we received approval from Anna 9/13 to add the promo crops for the two new home page images. Please add to the appropriate "image" folder and tag these images as ones that require update in production. Cc: @lburack

**Comment by monika-jaeger** [comment]
@chuckhrose are you ok with these image crops for the Homepage and Research? This is for the 4:3 crops needed for promotional images.

- [Homepage](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/Homepage/Promo%20Image%20(Hero)?csf=1&web=1&e=4w2IBS)
- [Research](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/Research/Promo%20Image%20(Hero)?csf=1&web=1&e=6iOnNO)

**Comment by chuckroseNIH** [comment]
@monika-jaeger Roger that!

**Comment by laurelthrash** [comment]
Excellent! Thanks for the confirmation, @chuckroseNIH. Going to go ahead and mark this ticket as complete. Cc: @monika-jaeger
