### ISSUE TITLE
[R2.1 Content] Research - Button Change for Cancer Moonshot

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1041]
**Description:** Button for Cancer Moonshot promo block previously said "View Infographic" when it should say "Learn More." Update this accordingly on Figma comp, content template, and ACSF-test. 

Change "Learn more" to "Learn More."

Sub-tasks:
- [x] Update figma Comp (Monika)
- [x] Update Content Template (Laurel)
- [x] Update ACSF-test (Laurel) [was already complete here]

**Image**
![Image](https://user-images.githubusercontent.com/102998716/245323147-9bdf7195-c692-4d3d-b69e-e74c8e4a7b87.png)

**Comment by laurelthrash** [comment]
Notified Anna on 6/13 that we will make these small types of changes (changing from "View Infographic" to "Learn More." During that time, Laurel noticed the word "More" needs to be capitalized.

**Comment by monika-jaeger** [comment]
@laurelthrash this has been updated in [the comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=1405-18240&viewport=310%2C2312%2C1&scaling=min-zoom) and ready for review.

**Comment by laurelthrash** [comment]
@monika-jaeger - verified on the comp - closing this ticket.
