### ISSUE TITLE
[R2.1 Content] Homepage (Spanish) - “Telemedicina” Feature Card Description Update

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1043]
**Description:** Feature card, “Telemedicina,” headline issue: Mural has “tiempo, viajes y dinero” while ACSF has “tiempo y dinero.” 

Need to update the comp so that the description includes what is in the CMS: "La telemedicina ahorra tiempo y dinero a las personas con cáncer”.

**Sub-tasks:**
- [x] Update Figma comp (Monika)
- [x] Update content template to reflect that this should be pulled from the CMS (Adriana)

**Comment by laurelthrash** [comment]
@monika-jaeger please make the initial changes mentioned above and then tag @adrianacastaneda for the content template update - thank you!

**Comment by monika-jaeger** [comment]
@laurelthrash updates made to [Homepage Spanish comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&type=design&node-id=142-8600&viewport=-2623%2C3713%2C1&scaling=min-zoom).
@adrianacastaneda this is ready for the content template update.

**Comment by adrianacastaneda** [comment]
Content template indicates that card title and description will be pulled from CMS

Cc: @laurelthrash @monika-jaeger

**Comment by laurelthrash** [comment]
@adrianacastaneda @monika-jaeger verified that this is updated in the content template and comp. Closing this ticket.
