### ISSUE TITLE
[R2.1 Content] Research Spanish - Update Cancer Spelling in Comp

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1054]
**Description:** Comp includes incorrect Spanish spelling for Cancer in left guide card. Spelled correctly in ACSF-test. 

![Image](https://user-images.githubusercontent.com/102998716/245913314-d31ea847-1300-48e5-b24e-398e02bc5397.png)

**Comment by laurelthrash** [comment]
@monika-jaeger - will you please correct this discrepancy in the Figma comp? Thank you!

**Comment by monika-jaeger** [comment]
Updated [Research Spanish Comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=142-10130&viewport=-976%2C1230%2C0.5&scaling=scale-down-width) with correct guide card labels.
cc @laurelthrash

**Comment by laurelthrash** [comment]
@monika-jaeger verified on the comps. Closing this issue - thank you!
