### ISSUE TITLE
[R2.1 Content] G&T - Tablet and Mobile Pixelated Images

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1057]
**Description:** [Grants and Training](https://www-test-acsf.cancer.gov/grants-training) > Promo block images > Tablet and mobile. The chatbot and diversity images are incredibly pixelated at tablet and mobile sizes.

**Next Steps:**
- [x] Laurel reached out to team via Slack to confirm if this is a content/image sizing issue or a technical/functional issue. Holding on converting this to an issue until this is resolved.
    - Note from internal team 6/14: Believe CRCHD image has appropriate resolution 
- [x] Upload a new crop and confirm if its a content issue (Monika)
- [x] Internal alignment
- [x] Confirmation from client that image is sufficient
- [x] Update:
    - [x] Content template (Adriana) - NOT NEEDED
    - [x] Add to FigJam as an update needed in production (Monika)

**Comment by monika-jaeger** [comment]
New chatbot graphic added for 16:9 (for tablet and mobile sizes)
Folder is located [here in Teams](https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/Eu5Gbi-Y9xFDmcANmZj9x8gBeKvxPFtpxS1Z5CA7BrtmSw?e=DAjcCi).

Ready to be added to ACSF for testing @laurelthrash

**Comment by adrianacastaneda** [comment]
chatbot graphic is uploaded to ACSF promo block @laurelthrash @monika-jaeger

**Comment by laurelthrash** [comment]
Anna confirmed 6/16 that the new image is much crisper for tablet breakpoints. 

@adrianacastaneda @monika-jaeger please update in the locations noted in the description.

**Comment by monika-jaeger** [comment]
- Images all updated in [Grants & Training](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&type=design&node-id=142-11355&viewport=329%2C761%2C0.25&scaling=min-zoom) comps 
- Changes noted in [Figjam image audit](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=OD4leJTLMnfGelfM-1)

cc @laurelthrash

**Comment by laurelthrash** [comment]
Marking this ticket as closed as all sub-tasks are complete. Cc: @adrianacastaneda @monika-jaeger
