### ISSUE TITLE
[R2.1 Content] Image Pixelated - Home Page Spanish

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1060]
**Description:** Following issues reported by Jorge: https://www-test-acsf.cancer.gov/espanol

1. Pixelation on 2nd Main Card (Profesionales de Salud) 

**Next step:** 
- [x] Initial try to locate original image (Monika, Chuck)
- [x] If cannot find, convey to Anna that this is an older image for which we don't have the source (Laurel) [N/A]

**Comment by laurelthrash** [comment]
Update: Anna confirmed via Teams chat 6/15 that she is comfortable moving forward with our plan to: 

1. Take a reasonable amount of time to try to locate the original image to prepare new crops
2. Be comfortable with the existing crop, if the original image is not easily identifiable, and 
3. Allow the future Home and Landing page teams to revisit these images in the future, if desired 

Cc: @meglake @chuckhrose @monika-jaeger

**Comment by monika-jaeger** [comment]
Located source image here: https://visualsonline.cancer.gov/details.cfm?imageid=10294
Working on new crops.
cc @laurelthrash @meglake @chuckhrose

**Comment by monika-jaeger** [comment]
New crops are available in [Teams folder here](https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/EnrjFNSHU6RAlWnnvrgTMr0B-BPZCRCn4DXZ7q2rPAxjIw?e=X7bk0R).
These are ready to be added to ACSF.
cc @laurelthrash

**Comment by laurelthrash** [comment]
Assigning over to @adrianacastaneda to please add to ACSF-test. @monika-jaeger please verify once added that the new crops did the trick!

**Comment by laurelthrash** [comment]
@monika-jaeger - added to ACSF-test!

**Comment by monika-jaeger** [comment]
@laurelthrash All looks good on all breakpoints. I am good with closing this ticket.
