### ISSUE TITLE
[R2.1 Content] Image Issue - Research Spanish

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1061]
**Description:** Reported that there is a non optimal image on “Iniciativas” feature cards (statistics on mortality) 

https://www-test-acsf.cancer.gov/espanol/investigacion 

**Status:** Laurel asked via comment for Jorge to verify the definition of "non optimal" 

**Next step:** 
- [x] Initial try to locate original image (Monika, Chuck)
- [x] If cannot find, convey to Anna that this is an older image for which we don't have the source (Laurel)
- [x] Add to ACSF-test (Adriana)

**Comment by laurelthrash** [comment]
Update: Anna confirmed via Teams chat 6/15 that she is comfortable moving forward with our plan to: 

1. Take a reasonable amount of time to try to locate the original image to prepare new crops
2. Be comfortable with the existing crop, if the original image is not easily identifiable, and 
3. Allow the future Home and Landing page teams to revisit these images in the future, if desired 

Cc: @meglake @chuckhrose @monika-jaeger

**Comment by monika-jaeger** [comment]
Image located in Visuals Online: https://visualsonline.cancer.gov/details.cfm?imageid=9695
Creating crops now.
cc @chuckhrose @laurelthrash @meglake

**Comment by monika-jaeger** [comment]
New images for "Inviativas" guide card are uploaded to the [Teams folder](https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/Ei4RzO4PAu1Llw8Rcu_7FWIBVmhbu-PVOG-PBAz1SWAswg?e=eepGLM).
These are ready to be tested in ACSF cc @laurelthrash

**Comment by laurelthrash** [comment]
Assigning over to @adrianacastaneda to please add to ACSF-test - ty!

**Comment by laurelthrash** [comment]
Per conversation today, @monika-jaeger please also verify that once uploaded that the new crops do the trick! Cc: @meglake @adrianacastaneda

**Comment by adrianacastaneda** [comment]
@laurelthrash these look very pixelated. Confirming that I'll wait until @monika-jaeger confirms the above ^

**Comment by laurelthrash** [comment]
Received - @monika-jaeger - will you please diagnose the above and update your image spreadsheet accordingly?

**Comment by monika-jaeger** [comment]
@laurelthrash @adrianacastaneda were the new images for the "Iniciativas clave del NCI" added to ACSF from the [Teams folder](https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/Ei4RzO4PAu1Llw8Rcu_7FWIBVmhbu-PVOG-PBAz1SWAswg?e=N05qOb)?

Just want to confirm before I re-try to create new images. It appears that they haven't been switched out yet for the new uploads in teams, since the new crops I created have some better coloring from the source image I found. Let me know if that's the case, thanks!

**Comment by adrianacastaneda** [comment]
@laurelthrash @monika-jaeger all set :) Thank you!

**Comment by laurelthrash** [comment]
Awesome! @monika-jaeger - will you please update the image tracker to indicate that the new crops fixed the issue? Then please feel free to close out this ticket - thank you!

**Comment by monika-jaeger** [comment]
@laurelthrash done! Closing the ticket.

**Comment by monika-jaeger** [comment]
@laurelthrash I take that back, I don't think I have permissions to close tickets. I can only move tickets on the board.

**Comment by laurelthrash** [comment]
Not sure why that is! I am closing it now.
