### ISSUE TITLE
Design: References + Citations 

### ISSUE THREAD

**Issue by erinsansone** [NCIOCPL/ncids#107]
> ESTIMATE Story Points TBD

### **Description of task to be worked on**

Design for references section, including link/footnote functionality and tooltip/hover display of inline reference

### **Problems to solve**
_Identified during discovery work_
- Usability of hover v. jump link (clicking on number takes down, with no back to top, hover on same link produces tooltip)

### **Questions to answer**
_Identified during discovery work_
- Is the hover/tooltip function useful enough to require keeping?
- How well do these work on mobile?

### **Related Tickets**
- Baseline Discovery: References/Citations #98

### **Resources**
- Notion: https://www.notion.so/References-0909b58bb087456681e792d154816e6a

### **Notes**
*Some complementary notes if necessary:*

# Outputs

### **Design Files**
_Links to invision comps or other design assets_

### **Technical Notes**
_More notes, or technical nuances/direction_

**Comment by mworrest** [comment]
@anthonycuellar is this not part of sprint 8? This should have been in sprint 8 as it is part of article.

**Comment by mworrest** [comment]
Will truncate list at 5. 
<img width="767" alt="image (9)" src="https://user-images.githubusercontent.com/4921685/121564515-845a3780-c9e9-11eb-9e7a-8a8d6e912634.png">

**Comment by mworrest** [comment]
Using out of the box tooltip for 
<img width="296" alt="Screen Shot 2021-06-16 at 10 50 41 AM" src="https://user-images.githubusercontent.com/4921685/122241642-b7d90e00-ce90-11eb-8ffa-ea18353b4f5b.png">
