### ISSUE TITLE
Discovery: Date Display research and analysis

### ISSUE THREAD

**Issue by erinsansone** [NCIOCPL/ncids#108]
- Confirm Google's preference on date location (if there is one)
- Look at analysis of dates on current content - captured in file (https://lion.box.com/s/4czcyyue09r1mtyoypwkacxrf4ylu2ng)

> **ESTIMATE** TBD

### Resources:
* Notion: https://www.notion.so/Date-f5c4e2d76ab84725b4c99a733605d281

**Comment by claireblaustein** [comment]
Analysis complete - can talk through during demo @anthonycuellar 
https://www.notion.so/Date-f5c4e2d76ab84725b4c99a733605d281
