### ISSUE TITLE
Discovery: LiveHelp Analysis

### ISSUE THREAD

**Issue by erinsansone** [NCIOCPL/ncids#109]
# LiveHelp Analysis

- Content Question: LiveHelp is presented in a LOT of ways site wide (footer, popups, utility). Document the different places  someone could access the live help chat and differences in the experiences. 

This came up in the context of talking through the Modal component. Baseline Discovery: Modal #101

**Comment by VictoriaSunNIH** [comment]
Convert to discovery when we're ready
