### ISSUE TITLE
META: Create auto-initialization scripts for JS components

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1108]
### JS Component List

- [x] #1162
- [x] #1157
- [x] #1160
- [x] #1159
- [x] #1161
- [x] #1428

**Comment by bennettcc** [comment]
Per 9/7 discussion: Moving this Meta into the Hard Launch bucket. The remaining two init scripts for autocomplete and subscribe do not need to be completed as part of the DS Pilot

**Comment by sarinapadilla** [comment]
Closing because we did all the things.
