### ISSUE TITLE
Spacing Issue for Default Guide Card

### ISSUE THREAD

**Issue by dev-rana-publicis** [NCIOCPL/ncids#1123]
### Issue description
There is 0px spacing between the guide cards between 880px - 1023px. According to the figma, the spacing needs to be changed to 32px. 

> **ESTIMATE** TBD

### What's the expected result?
- 32px spacing between 880px - 1023px

### What's the actual result?
- 0px spacing between 880px - 1023px

### Additional details / screenshot
<img width="934" alt="Screenshot 2023-07-18 at 3 11 00 PM" src="https://github.com/NCIOCPL/ncids/assets/110177947/fb0f669f-8ca6-42b0-b5de-114002e01163">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by SupriyaSaxena0605** [comment]
@KateMashkinaNIH The spacing looks good on ODE.
![image](https://github.com/NCIOCPL/ncids/assets/31008800/90c94c08-e95d-4188-b610-888756c4287e)

![image](https://github.com/NCIOCPL/ncids/assets/31008800/ad4470be-4570-4f88-a8c5-0b74703b6750)
