### ISSUE TITLE
NCIDS for All Pilot - Home Page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1135]
## As a site user, I want to see the home page, so that I can make sure I'm in the right place and be directed to content.

The documentation site needs a home page!

* Ideally, we would use home and landing page components
* What components do we use, and what content do we feature or direct to?

Markdown text:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/homepage_markdown.txt?csf=1&web=1&e=UTjo2Q

[homepage_markdown.txt](https://github.com/NCIOCPL/ncids/files/12753236/homepage_markdown.txt)

### Resources / Notes

---

### Tasks
- [x] Determine content to be displayed 
- [x] Determine components used

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bennettcc** [comment]
Per 8/9 - @adrianacastaneda and @lburack will create mockup/content strategy for what is displayed on the homepage.

We will initially approach this with a focus on the Pilot - what should iteration 1 of the homepage look like?

Then, following the Pilot we can determine what changes/additions should be made based on feedback + pilot findings + technical spike to determine what is possible to develop/show on the page.

cc: @sarinapadilla @andyvanavery

**Comment by bennettcc** [comment]
Markdown has been added to this ticket - it is ready to be built out on the doc site
