### ISSUE TITLE
Revisit and synthesize design burst for section navigation 

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#114]
Take a look at the ideas surfaced for secondary navigation in the design burst and identify themes.

Should be approached when secondary nav is going to be approached more holistically, rather than as extension of USWDS.

Notion: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1617994245461/f3ec3fa9ae24134ad7b6d4d0c944759dfeeac72f
Outcome Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1617994245461/f3ec3fa9ae24134ad7b6d4d0c944759dfeeac72f

**Comment by VictoriaSunNIH** [comment]
Prototyping has been completed in #168
