### ISSUE TITLE
Story: Patch USWDS Collections to Create NCIDS Collections

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#1149]
### Requirements
- Match the appearance to the Media thumbnail variant, which is the bottom row on the [Figma design](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System---Master?type=design&node-id=1892-4622&mode=design&t=Y1hnyTecjfkLo1HF-0) of the Collections section.
- Paragraphs for the Media variant patch will include:
  - Title (required)
  - Link (required)
  - Thumbnail (required)
  - Description (required)
  - By Line (optional)
  - Date (required)
  - Tags (optional)
- Paragraphs will not include (different than USWDS storybook):
  - Heading with line underneath
  - Lines in-between each collection item
- The solution will be a patch on the USWDS collections component

### DoR DS Tasks
- [x] Update the design style of the component
- [x] Create scenarios for testing
- [x] Determine how these will meet accessibility standards
- [x] Create Analytics Requirements and Acceptance Criteria
- [x] Internal review of AC's

### DoD DS Tasks
- [ ] Develop DS component from Figma comp
  - [ ] Documentation site: Remove documentation of as a USWDS component and add it to the NCIDS section
  - [ ] Move the component in the Figma file from the USWDS section to the NCIDS section
  - [ ] To be completed in ticket #1405 : Update content on Documentation Site
  - [ ] Update Storybook
  - [ ] Update Example Site
- [ ] Update the Figma community file with the final design (with the inclusion of all paragraphs)
- [ ] Draft Governance

### Resources

- [Mockups](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=1892-4622&mode=design&t=lIuwRYfvlvwOfJHq-0)
- [USWDS Component](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/uswds-components-collection--media)
- [News & Events Comp](https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=0-1&mode=design&t=YSGqMpPEhY3qyQkS-0)
- [Scenarios](https://nih.sharepoint.com/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/doc.aspx?sourcedoc={0a412b32-3033-4596-a587-e4465f9b89b4}&action=edit)

### Acceptance Criteria
**Design Style**
```gherkin
Scenario: A user views a page with an NCIDS Collections component
  Given a page editor has added an NCIDS Collections component to the page
    And the NCIDS Collections component has been implemented in the Design System
  When the user views a page with an NCIDS Collections component
  Then the NCIDS Collections will match the comp (see link in Requirements section)
    And the title of each item in the collection will be clickable
  When the user hovers over the title of an item in the collection
  Then the title item being hovered over will show the link hover state
  When the user clicks or tabs to the title of an item in the collection
  Then the blue outline box will appear around that title
  When the user selects the title of an item in a collection
  Then they will be redirected to the page of that item
    And the title link will change to the opened-link state 
```

**Documentation**
```gherkin
Scenario: An NCIDS for All user goes to the Documentation site for information on the NCIDS Collections component
  Given A user has access to the NCIDS for All documentation site
    And the NCIDS for All documentation site has been updated for this patch
  Then the NCIDS Collections component page will exist under the NCIDS Components page
    And page for the NCIDS Collections component will be in the same style as all component pages on the Documentation Site
    And all of the information on the page will be updated in accordance with the information provided on all component pages on the Documentation site
    And there will be no page for Collections on the USWDS Pass-Through pages
```

**Figma**
```gherkin
Scenario: An NCIDS for All user goes to the Figma file for information on the NCIDS Collections component
  Given A user has access to the NCIDS for All Figma file
    And the NCIDS for All Figma file has been updated for this patch
  Then the NCIDS Collections component will exist on the NCIDS Components page
    And the NCIDS Collections component will display the all paragraphs able to be included on the component
    And there will be no comp for Collections on the USWDS Pass-Through page
```

### Notes

---

**Comment by bennettcc** [comment]
Moving to on hold - Dev OOO until 10/16
