### ISSUE TITLE
Baseline Design: USWDS adaptation Secondary (Left) Nav

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#115]
> ESTIMATE Story Points TBD

### **Description of task to be worked on**
Update design of USWDS left navigation component to work for our current context.

https://designsystem.digital.gov/components/side-navigation/

### **Related Tickets**
- Baseline Discovery: Section Navigation #51

### **Resources**
- Notion: https://www.notion.so/Secondary-Navigation-1a075f20a14c431da4050436083455bc

### **Notes**
- USWDS left nav supports L1-L3, nothing further.

# Outputs

### **Design Files**

*Links to invision comps or other design assets*

### **Technical Notes**

*More notes, or technical nuances/direction*

**Comment by VictoriaSunNIH** [comment]
This has been completed and prototyped in #168
