### ISSUE TITLE
Story: Create NCIDS Heading Class

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#1150]
### Requirements
- The nci-heading class will be created
- There will be an nci-heading--display class which will be responsive. 
  - For widescreen, desktop, & tablet large: 3xl will be used
  - For tablet, mobile large, & mobile: xl will be used
- There will be nci-heading-h# for using the h1:h6 typeset mixins
  - The sizes and styles for these modifiers will be set per the created Figma
- There will be a `--label` modifier which will include a line under the heading which will span the width of the column of which the heading is contained in.
- The `--label` modifier shall function with all 6 of the different h1:h6 typeset mixins
- See the comment from Lilian from 29SEP2023 for further notes

### Notes
- The `h*` mixin uses the `$theme-h*-font-size` theme settings
- `usa-prose` uses the `@h*-typeset` mixins that add margins and other useful items

### DoR DS Tasks
- [x] Create/Update design of nci-heading for all modifiers as identified in the Requirements section. Put the solution into its own class space on Figma
- [x] Refine user story statement
- [x] Create Scenarios
- [x] Internal review of any changes to the Design solution for nci-heading and its modifiers on Figma
- [x] Update the Figma with this class and appropriate classes
- [x] Internal review of DS AC's

### DoD DS Tasks
- [ ] Develop DS class from design Figma comp
  - [ ] Update Documentation Site
    - [ ] Draft the guidance and all sections necessary for addition to the NCIDS for All Documentation Site. #1382 
  - [ ] Update Storybook Site
  - [ ] Update Example Site
- [ ] Internal review of the DS solution
    - [ ] Demo DS solution to client

### Resources:
* [Mockups](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=4573-10890&mode=design&t=pzrA1ckmivpPjMLA-0)
* [Scenarios Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.3/Development%20Scenarios/nci-headings%20Scenarios.docx?d=wdcdc903560674989854c3172ad37d6a8&csf=1&web=1&e=O6sfie)

### Acceptance Criteria

**Example Site & Storybook**

```gherkin
Scenario: A user views a page with an nci-heading-display class on it
  Given the nci-heading-display class has been added to a page
    And the NCIDS Heading class has been created in the Design System
  Then the nci-heading-display will match the comp
  When the width of the browser is at tablet large or greater (>= 880px)
  Then the nci-heading-display will be displayed at 3xl
  When the nci-heading-display is smaller than tablet large (less than 880px)
  Then the nci-heading-display will be shown at xl
```

```gherkin
Scenario: A user views a page with the six variations of nci-heading-h# class on it
  Given the nci-heading-h1 through nci-heading-h6 class have been added to a page
    And the NCIDS Heading class has been created in the Design System
  Then the nci-heading-h1 through nci-heading-h6 class will match the comp
```

```gherkin
Scenario: A user views a page with the six variations of the nci-heading-h#--label class on it
  Given the nci-heading-h1--label through nci-heading-h6--label class have been added to a page
    And the NCIDS Heading class has been created in the Design System
  Then the nci-heading-h1--label through nci-heading-h6--label class will match the comp
    And the line under the heading will span the width of the container of the class
  When the browser width changes
  Then the line under the heading will adjust to match the width of the container of the class
```

**Documentation Site**

```gherkin
Scenario: An NCIDS for All user goes to the Documentation site for information on the NCIDS Heading class
  Given A user has access to the NCIDS Documentation Site
    And the NCIDS for All documentation site has been updated with this class
  Then the NCIDS Heading class page will exist under the path, Foundations > Typography > Headings
    And the default class will be nci-headings-h#, where h# stands for the six available sizes h1:h6
    And the variants will be nci-headings-display and nci-headings-h#--label, where h# stands for the six available sizes h1:h6
    And page for the NCIDS Heading class will be in the same style as all pages in the Foundations section
```

**Figma Community File**

```gherkin
Scenario: An NCIDS for All user goes to the NCIDS Design Kit for information on the NCIDS Heading class
  Given A user has access to the NCIDS Design Kit
    And the NCIDS for All Figma file has been updated for this class
  Then the NCIDS Heading text style will exist on the Tokens & Utilities Page
    And the NCIDS Heading text style will be available for designers to use under Text Styles > Heading Styles
```

**Comment by monika-jaeger** [comment]
[WIP] [NCIDS Headings Class](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=4573%3A10890&mode=design&t=1skNZFWcXNglDp27-1) added to Figma.
cc: @blilianyu

**Comment by blilianyu** [comment]
@laurelthrash Heading Styles have been updated. Review with team on Tues meeting

Changes made:
- `nci-heading--biggum-title` changed to `nci-heading-display` that will be responsive
- `nci-heading--biggum-subheading` will just be a CGDP component not in the DS. If DS users want a subheading, they can use a Hero variant. 
- `nci-heading--page-title` will just be a normal H1
- normal H1-H6 will not be responsive (`nci-heading-h1` - `nci-heading-h6`)
- `nci-heading-label` is a Modifier to add a bottom border that will expand the width of the section 


Token Changes that are needed:
- `$theme-type-scale-md` from 6 to 8


**NCI HEADING STYLES**
- `nci-heading-display` - 3xl - landing page - 12 / 32px
- `nci-heading-h1` - 2xl - page title, normal h1 - 11 / 28px
- `nci-heading-h2` - xl - normal h2 - 10 / 24px
- `nci-heading-h3` - lg - normal h3 - 9 /22px
- `nci-heading-h4` - md - normal h4 - 8 /20px
- `nci-heading-h5` - sm - normal h5 - 7 / 18px
- `nci-heading-h6` - xs - normal h6 - 5 / 16px
- `nci-heading-label` - modifier that adds bottom 1px border with 12px spacing to `nci-heading-h1` - `nci-heading-h6`

cc: @monika-jaeger @olitharp-nci @andyvanavery

**Comment by olitharp-nci** [comment]
Developer notes

1. Patch will be needed to update heading font sizes. 

```diff
$theme-display-font-size: "3xl" !default;
$theme-h1-font-size: "2xl" !default;
$theme-h2-font-size: "xl" !default;
$theme-h3-font-size: "lg" !default;
- $theme-h4-font-size: "sm" !default;
+ $theme-h4-font-size: "md" !default;
- $theme-h5-font-size: "xs" !default;
+ $theme-h5-font-size: "sm" !default;
- $theme-h6-font-size: "3xs" !default;
+ $theme-h6-font-size: "xs" !default;
```

2. Type scales have already been patched.

3. Pseudocode/patches needed for headings

```scss
.nci-heading-display {
  @include typeset-h2 // xl
  @include u-margin-bottom(0)
  on tablet-lg { @include typeset-display } // 3xl
}

.nci-heading-h1 {
  @include typeset-h2 // xl
  @include at-media tablet-lg{ @include typset-h1 } // 2xl
}

.nci-heading-h(2-6) {
  @include typeset h(2-6)
}

.nci-heading--label {
  padding-bottom // ??
  border-bottom // 1px
}
```

Additionally, we'll need to create ticket to update `cgdp-title-area` to use new styles.

```scss
.cgdp-title-area {
    @include u-text('center');
    @include u-padding-top(3);

    &__subheading {
        @include u-display('block');
        @include u-font(body, 'md');
        @include u-margin-top(1);

        @include at-media(tablet-lg) {
            @include u-margin-top(1.5);
            @include u-font(body, 'xl');
        }
    }
}
```
