### ISSUE TITLE
[R2.2 Guidance Updates] Spike to Determine Which Materials Need Updates

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1158]
**Description:** Need to review the following resources to determine if updates need to be made based on the release of R2.2 components. Formal tickets will be created for materials that do require updates.

Resources for review: 
- [ ] Drupal 101 Training Materials @laurelthrash 
- [x] Drupal Guide on myNCI (https://mynci.cancer.gov/topics/drupal-guide) @adrianacastaneda 
- [x] Branding/Logo Guide on MyNCI (https://mynci.cancer.gov/topics/nci-branding-and-logo-use-guide) @dcvijanovic1k 
- [x] Digital Reference Guide (formerly the Digital Style Guide) on MyNCI (https://mynci.cancer.gov/topics/nci-digital-reference-guide) @dcvijanovic1k

**Comment by adrianacastaneda** [comment]
@laurelthrash — No updates need to be made to MyNCI since only the NCIDS component featured in the Drupal guide is the feature card component, and this component has not changed.

**Comment by laurelthrash** [comment]
Will need to update two slides as part of the Home and Landing Page training to demonstrate the new variants available. Will close this ticket and create a new ticket to track progress.
