### ISSUE TITLE
Spike: Investigate using home and landing components in Gatsby

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1163]
## In order to use home and landing page components on the home page of the documentation site, a developer needs to investigate implementing the components in Gatsby.
> **Estimate** *# point* 

### Expected Deliverables:
* Approach to implement home and landing page components in Gatsby

### Additional Notes:
* Currently, we do not have any templates and create all of the markdown in .md files. In order to implement these components, we need to determine what we want on the pages and how Gatsby will work with it.

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by sarinapadilla** [comment]
When working on components, we realized that you can't easily set what you want the template to be in a markdown page.

Hacky way is to copy the HTML from our home and landing pages and see if that shows when in the markdown. We'll be doing this for the spike.

**Comment by bennettcc** [comment]
Discussed with Anna on 2/20 - confirmed we will not rethink this page's layout or consider the addition of page components. Closing the ticket is approved
