### ISSUE TITLE
Create template for component pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1164]
## As a developer, I want a template for the metadata needed on each component page, so that I can create the pages with the correct information.

The result of this ticket will be a markdown template for the component pages. The template will have all of the sections that could be on a component page, but each individual component will be different in which sections it needs.

> **ESTIMATE** TBD

### Resources:
- Variation FigJam: https://www.figma.com/file/mLlEkBBiU4bCjZqcgj2ewh/Component-Variations-Audit?type=whiteboard&node-id=0%3A1&t=qRxwPJX14HP1aGVW-1
- Component Figma: https://www.figma.com/file/8qu1psEjnehVDoZyWrH7ny/NCI-DS-For-All?type=design&node-id=0%3A1&mode=design&t=gnIwhwi6D18MTuME-1

### Notes
* We need a template for each of the component pages so that we can follow a similar structure for each component. Different data points should be set in the YAML front matter so that each of the sections can be placed on the page. Figma link, intro text, overview, updates, etc.
  * This metadata will help to create the components overview page by supplying the intro text for the components (if that is what will display)

---

### Prerequisites
- #945 

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by arcepaul** [comment]
Create these as test pages:
- Button (same, but a lot)
- Guide Card (has variants)
- CTA
