### ISSUE TITLE
Create Layout Grid page on documentation site

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1194]
### Request Description
This change request is to fully adopt the layout grid utilities on the doc site from being a pointer to USWDS to our full ownership. This change will require:

- [x] IA/development/design creates doc site page using the new utility page template (created in #1593)
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [ ] Developer updates to the code to adopt the layout grid utilities within the NCIDS

### What's the expected change?
- The doc site is updated to show users how to fully use layout grid utilities without pointing to USWDS
- The community Figma file will be updated to include the layout grid utilities
- The NCIDS code will be updated to fully adopt the layout grid utilities 

### What's the current functionality?
- The doc site directs users to USWDS [Layout Grid](https://designsystem.digital.gov/utilities/layout-grid/) utility page

### Related Tickets
* **Prerequisite:** #1593 
* Original Story Ticket #1207 
* Original PR #1256 
* Related Story Ticket #934

**Comment by laurelthrash** [comment]
Discussed during 10/11 UX backlog meeting and determined we will move these out of the Design backlog. Need further discussion from developer perspective if pages associated with "Layout and Positioning" are still needed and, if so, what modifications to the requirements of this ticket are required. @sarinapadilla @andyvanavery31

**Comment by laurelthrash** [comment]
@sarinapadilla I see this was added to the design board - will you please confirm what is needed from IA/design to move forward with this ticket? 

In October of last year, it was determined that IA/design needed more information before proceeding. This ticket may be good to discuss during a Requirements meeting to ensure we are aligned. I missed part of a recent Requirements meeting, so apologies if this ticket was discussed!
