### ISSUE TITLE
Discovery and Analysis for Secondary/Left Navigation

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#120]
# Discovery and Analysis for Secondary/Left Navigation

### **Questions to answer**

*Identified during discovery work*

- Can we limit expand/collapse to just nuclear family (siblings, parents and children) instead of extended family (cousins)
-  If not, what is the accordion behavior we need? 
- what will appear on mobile?
- USWDS left nav supports L1-L3, nothing further.

> **ESTIMATE** TBD

### SubTasks

- [ ] Discussion: what are the questions we're trying to answer

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Related Tickets
Baseline Design: USWDS adaptation Secondary (Left) Nav #115
Baseline Discovery: Section Navigation #51

**Comment by claireblaustein** [comment]
Finished analysis available on Notion: https://www.notion.so/Secondary-Navigation-Behavior-64aef479e77c4375b18e96483a1a2e7b

Will be brining to next client meeting on 6/22 to start talking through approach, and in the meantime will proceed with prototyping under this approach (#168 #169 )
