### ISSUE TITLE
Update Storybook with the Correct Structure of Pages

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1224]
### Change Description
The structure of the pages on the Storybook is to be updated per the GitHub Wiki page that contains the updated breakdown of the pages to be on Storybook. 

### What's the expected change?
- The Storybook pages and structure will match the structure outlined on the [GitHub Wiki page](https://github.com/NCIOCPL/ncids/wiki/Storybook-Structure)

### What's the current functionality?
- The Storybook pages and structure is currently shown [here](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-nci-autocomplete--default)

### Technical Notes
Storybook 7 REALLY does not like how we setup our stories. To be honest, it is not anywhere near the documented way either... So we need to change the stories as we are moving them.
1. ONLY files that have the default export with the story path should be marked as `XXX.stories.jsx`. 
2. The `XXX.stories.jsx` files should define and export the stories in those files. I.E. do not `export * from 'someotherfile.jsx'`. You can put sample HTML in separate files, but you must not export the stories in the way we do.
3. If we are updating all the stories, then we should look at https://github.com/storybookjs/eslint-plugin-storybook.

**Comment by sarinapadilla** [comment]
This is being broken down into stories for each individual component within storybook, so we're marking this ticket as In Progress while we get all of those tickets ready!

**Comment by sarinapadilla** [comment]
Tickets are done!!! All are linked above.
