### ISSUE TITLE
Update usa-banner to be the Default Component

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1231]
### Change Description
The usa-banner component is currently set as a variant by structure without a default of the component. The requested change is to update usa-banner such that the variant used is set as the default component.

### What's the expected change?
- The usa-banner component will be updated so that its variant will be set as the default.

### What's the current functionality?
- The usa-banner component that is used is set up as a variant without a default component.

**Comment by bennettcc** [comment]
Closing this ticket, needed actions were completed as a part of https://github.com/NCIOCPL/ncids/issues/653
