### ISSUE TITLE
Disable USWDS Tokens from the $tokens-color-basic

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1270]
### Change Request
Disable USWDS colors from the `$tokens-color-basic`. The NCIDS colors that exist as of 27SEP2023 shall stay. This generates the "Basic palette" colors on any foundation page that has colors.

The NCIDS colors defined today are:

- "cerulean": get-system-color('cerulean', 50, "vivid")
- "cranberry": get-system-color('cranberry', 50, "vivid")
- "golden": get-system-color('golden', 50, "vivid")
- "navy": get-system-color('navy', 50, "vivid")
- "teal": get-system-color('teal', 50, "vivid")

### What's the expected change?
- [x]  Disable the USWDS tokens from `$tokens-color-basic`
- [x]  Update NCIDS colors to:
  - 'cerulean' 50 #007BBD
  - 'cranberry' 60 #BB0E3D
  - 'golden' 50 #947100
  - 'navy' 80 #14315C
  - 'teal' 50 #298085
- [x]  Update NCIDS Utility Wiki Page with changes

### What's the current functionality?
- The USWDS tokens are in `$tokens-color-basic`

### Related Tickets
* Prerequisite of #1190

**Comment by karlikpj** [comment]
These three colors will remain active as they are used by USWDS in their storybook examples for usa-icon. 

  "red": get-system-color("red", 50, "vivid"),
  "green": get-system-color("green", 50, "vivid"),
  "blue": get-system-color("blue", 50, "vivid"),
