### ISSUE TITLE
`outline-05` util doesn't render

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1299]
Seems to be an issue with getting the uswds utility class `outline-05` working. Backlogging this issue for now.

_Originally posted by @olitharp-nci in https://github.com/NCIOCPL/ncids/pull/1250#discussion_r1355119649_

**Comment by olitharp-nci** [comment]
@karlikpj can you check to see if thisd was fixed with the uswds upgrade?

**Comment by karlikpj** [comment]
yes currently its looking correct to me in develop
```
.outline-05 {
    outline: .25rem solid !important;
}
```

**Comment by sarinapadilla** [comment]
Closing this ticket, since it was addressed with #1760 and #1792.
