### ISSUE TITLE
Conversation with Blog Team about intro text 

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#130]
# Discovery: Conversation with Blog Team about intro text 

*Description of what is to be accomplished.*
Gain an understanding about how the blog team approaches "intro text", to see if there are additional requirements for the component.  

Potential current behaviors
- alert of an update
- introduce a series
- introduce a writer 
- provide a summary of the content

Also using the styling in non-post places, like the home page. 

### Resources
- Discovery Mural:
https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1619466551549/8e21797763eeeab1a0ac5049afba2540feff886f
- Notion - Intro text - https://www.notion.so/Intro-Text-0ab24b99fad24864b731a81a951f71e1

Generated from Discovery Kickoff: Blog Post #73

### Sub-Tasks
-

**Comment by VictoriaSunNIH** [comment]
Closing as completed
