### ISSUE TITLE
Update Figma Links to Direct Location on NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1302]
### Change Request
Request to update the Figma links on the NCIDS Documentation site to link to the specific sections of the Figma instead of linking to the Figma's homepage.

### What's the expected change?
- Links on NCIDS Documentation Site to Figma will go to the specific component/class/section instead of always going to the Figma homepage.

### What's the current functionality?
- All Figma links on the NCIDS Documentation Site will go to the Figma homepage.

### Solution
- Create a base url for the Figma file that is respective to its version that can be taken with /* to the individual components on the Figma

### Additional details / screenshot
The following list are of all the locations on the Documentation Site that need to be updated with the location on the Figma, followed by the component on Figma. The locations are listed as L1 > L2 > L3 etc.

Updated links:
| Page | Updated link |
|---|---|
| Foundations > Typography > Headings > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5294%3A10398&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Autocomplete > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39978&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Banner > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39899&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Breadcrumb > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39866&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Button > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5314%3A9664&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Card > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38952&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Collection > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38604&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > CTA Strip > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A42672&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Footer > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7991&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Guide Card > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7481&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Header > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A45831&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Hero > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A45414&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Promo Block > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5322%3A6243&mo"de=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Side Navigation > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44558&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Site Alert > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44496&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Skipnav > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44701&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Templates > 3-Card Row > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38952&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Templates > Guide Card Row > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7481&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Templates > Summary Box Row > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5469%3A8156&mode=design&t=9xNemHVdk0y2K4UA-1 |

### Resources
https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&version-id=4994908981&node-id=715-3392&mode=design&viewport=3699%2C126%2C1.16&t=D26katiZkkoP1Ce4-0

https://help.figma.com/hc/en-us/articles/360038006754-View-a-file-s-version-history

https://www.figma.com/developers/api#version-history

**Comment by sarinapadilla** [comment]
@blilianyu please investigate whether Figma has a more permalink solution (rather than query params) for components. @arcepaul please investigate if there is any way to query the API so we can work smarter not harder.

**Comment by sarinapadilla** [comment]
In doc site config:
* Figma link
* Figma version
* Each component page needs a "thing" to represent the component

Generate the link from these three parameters.

**Comment by blilianyu** [comment]
We can have permalinks for components. There are pretty urls/short url plugins but some of the links expire so we it will be ugly. The way we copy over updates in Figma will need to change as deleting and replacing the page will change the permalink (cc: @dcvijanovic1k).

Examples: 
- Heading Styles: https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5294%3A10398&mode=design&t=yPT3mR0OVoW5D37e-1
- Footer: https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7991&mode=design&t=yPT3mR0OVoW5D37e-1

**Comment by blilianyu** [comment]
Figma permalinks

- Foundations > Typography > Headings > "View in Figma" || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5294%3A10398&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Autocomplete > "View in Figma" || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39978&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Banner > "View in Figma" || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39899&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Breadcrumb > "View in Figma" || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39866&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Button > "View in Figma" || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5314%3A9664&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Card > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38952&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Collection > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38604&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > CTA Strip > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A42672&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Footer > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7991&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Guide Card > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7481&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Header > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A45831&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Hero > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A45414&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Promo Block > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5322%3A6243&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Side Navigation > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44558&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Site Alert > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44496&mode=design&t=lGwrxbWFW3JAwAet-1
- Components > Skipnav > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44701&mode=design&t=lGwrxbWFW3JAwAet-1
- Templates > 3-Card Row > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38952&mode=design&t=lGwrxbWFW3JAwAet-1
- Templates > Guide Card Row > "View in Figma || https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7481&mode=design&t=lGwrxbWFW3JAwAet-1

**Comment by karlikpj** [comment]
Components > Collections doesn't exist in our repo as of this ticket
