### ISSUE TITLE
Update the Back To Top Button to NCI Version on NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1310]
### Change Request
The Back to Top (BTT) button on the NCIDS Documentation site currently uses the style from USWDS. This request is to update it to use the NCIDS version of the BTT which appears on the cgov platform.

### What's the expected change?
- The BTT button on the NCIDS Documentation Site looks and functions like the BTT button on the cgov platform

### What's the current functionality?
- The BTT button on the NCIDS Documentation SIte is the USWDS version.

### What's the updated acceptance criteria?
```gherkin
Scenario: A user visits a page on the NCIDS Documentation Site
  Given the BTT button has been updated
    And the user scrolls down on the page
  Then the user will see the NCIDS BTT button in the bottom right of the page
    And the BTT button will follow them in the bottom right of the page as they scroll
  When the user clicks on the BTT button
  Then the user will be returned to the top of the page they are on
```

### Additional details / screenshot
- Current USWDS BTT Button
![image](https://github.com/NCIOCPL/ncids/assets/143126208/ae464a53-1b30-4a9c-b08e-2c495a4b0e3e)

- NCIDS BTT Button
![image](https://github.com/NCIOCPL/ncids/assets/143126208/bf489be9-e6e8-4e19-9fdd-7484a1bbd24f)

### Related Tickets
* Making the BTT Button on NCIDS Documentation Site Functional: #1306

**Comment by bryanpizzillo** [comment]
@karlikpj This is not a change to the footer everywhere, right? Like there is nothing that should change on CGDP, right?
