### ISSUE TITLE
NCIDS Documentation Site Change Request Batch 1 - Content

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1312]
### Change Request
The following are **content** updates to the NCIDS Documentation Site as found through the development process and through batch 1 of the client review.

- [x] Update all instances of "Feature Card" to "Card" **On the Feature Card Page:**
    - [x] The name of the "Feature Card" page to "Card"
    - [x] The H1 of the Feature Card page
    - [x] Ensure that the side nav under Components is updated
    - [x] The h3 Under Code Snippets
    - [x] The url of the page
  
- [x] Update all instances of "Feature Card" to "Card" **On the Figma Guide Page:**
  - [x] Under the Using Our Templates section, first sentence, change "... component patterns such as Feature Card Rows..." to "... component patterns such as 3-Card Rows..." 
  - [x] Under Templates change the page title from Feature Card Row to 3-Card Row

- [x] "Components" Page > "Navigational" Section > "Link" component - change the text from "Link" to  "Link (USWDS)" to indicate this page takes you to the USWDS page. The link itself does not change [per Batch 1 ODDC feedback]
- [x] Update Opacity H2 with Opacity instead of Outline in last h2
- [x] "Components" Page > "Informational" Section > "Tooltip" link - keep text as is, and update the actual link such that it links to the [USWDS page](https://designsystem.digital.gov/components/tooltip/). [per Batch 1 ODDC feedback]
- [x] "Foundations" page > "Spacing Units" page > "Applying Spacing Units for Designers" section - Change text from "...refer to our [Figma Guide under Spacing Units](https://designsystem-dev.cancer.gov/get-started/figma-guide)." to "...refer to our [Figma Guide](https://designsystem-dev.cancer.gov/get-started/figma-guide)." Link remains the same. [per Batch 1 ODDC feedback]
- [x] Replace existing logo with the new blended logo from #1305 [per Batch 1 ODDC feedback]
- [x] "Components" Landing page - change order of primary groupings so they are in alphabetical order. The change should be ordered as: 1. Actions 2. Content Display 3. Forms, Input, & Selection 4. Informational 5. Navigational. Maintain the order of components under their respective groupings. [per Batch 1 ODDC feedback]
- [x] Update the initialisms on the site so that for every first instance, on every page they are spelled out (excluding NCI and NCIDS). See the [List here](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/NCIDS%20Documentation%20Site%20Initialisms%20Update.docx?d=w2cfded17e48e4d648ccabfe8dcac9fe2&csf=1&web=1&e=9sWrCJ) of all changes to be made.
- [x] Add banner image to home page below the H1 @blilianyu @monika-jaeger please attach the banner image to this ticket

**Comment by monika-jaeger** [comment]
Banner image added here:
![ncids-banner](https://github.com/NCIOCPL/ncids/assets/109552399/7afd8ae9-1010-49a9-bad6-9bbdc9b17faf)

cc: @blilianyu @laurelthrash @andyvanavery31

**Comment by blilianyu** [comment]
Updated banner image 
![ncids-banner](https://github.com/NCIOCPL/ncids/assets/51677926/cc7ae037-09c0-4b40-9023-81017ded92ef)
cc: @laurelthrash @monika-jaeger
