### ISSUE TITLE
Make Browser Titles Consistent on NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1326]
### Change Request
This request is to create a consistent format for the browser titles across the NCIDS Documentation site. Once the format is set, it needs to be put in place for all of the browser titles across the Documentation site.

### What's the expected change?
- A format for the browser title will be created and set across the NCIDS Documentation Site
- See the comment from Adriana below for the formal rule.

### What's the current functionality?
- Browser titles have inconsistencies in their formatting

### Tasks

- [x] @adrianacastaneda to create rule for which title is used for consistency between the page title and the browser title
- [ ] A developer will make the change on the documentation site

### Additional details / screenshot
![image](https://github.com/NCIOCPL/ncids/assets/143126208/7ac56e32-1ed0-4a92-a958-c45f35792394)

**Comment by laurelthrash** [comment]
Confirming with PM/POs what is needed from design side for this ticket.

**Comment by laurelthrash** [comment]
Need from IA: determine the browser title syntax and ensure it is consistent across the Documentation Site (e.g., groupings of Foundations pages, Component pages, etc.). The Browser Title is updated via the page markdown. May consider a developer taking the markdown updates so that the changes can be included in one PR. Will consider this after syntax is determined.

**Comment by adrianacastaneda** [comment]
@andyvanavery31 @laurelthrash the rule for this is below. Let me know if there are any questions! 

Rule: "Page title Name" | NCI Design System

**Examples:**

- Correct browser name: Accordion Component | NCI Design System
   - Previously: Accordion Component - NCI Design System | NCI Design System
   
- Correct browser name: Foundations | NCI Design System
   - Previously: NCI Design System - Foundations | NCI Design System

**Comment by laurelthrash** [comment]
Received, thank you, @adrianacastaneda! Adding to the development board and marking as complete on the UX board. Cc: @andyvanavery31  @sarinapadilla
