### ISSUE TITLE
Add Consistency in Pages Linking to USWDS on NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1327]
### Change Request
This request is to make the language consistent across all pages on the NCIDS Documentation Site that direct the user to view the USWDS site, and that is the only content on that page. Examples include: Opacity, Spacing Units, Height and Width, and Padding and Margin. Variations in those pages include:

- Intro text: [Spacing Units](https://designsystem-dev.cancer.gov/develop/foundations/spacing-units) clearly explains that NCIDS follows USWDS, but [Margin and Padding](https://designsystem-dev.cancer.gov/develop/foundations/spacing-units/padding-margin) simply explains what the component does.  
- Figma Section Header: I’m seeing “For Designers: [Extra Stuff]”, “[Stuff] for Designers”, and “Designer Notes.” 
- Figma Section Content: Some pages all but link to the Figma Guide. Others try to provide more context.

**Additionally**, see the [open discussion](https://github.com/NCIOCPL/cgov-digital-platform/discussions/4111) related to this ticket.

### What's the expected change?
- Consistent language is developed for indicating to a user that we are linking to the USWDS and implemented on pages where the only content is directing the user to the USWDS site.

### What's the current functionality?
- Language is inconsistent for users. See above description of variations.

**Comment by andyvanavery31** [comment]
If time can be spent on creating Utility pages that we own instead of linking to USWDS, we should focus on that instead of aligning these pages.

**Comment by laurelthrash** [comment]
Preference is to deprioritize content updates in favor of creating Utility page that we own (developer emphasis). However, if we move closer to launch and the Utility page is not able to be prioritized from developer side, may reconsider making content updates ahead of launch.

**Comment by andyvanavery31** [comment]
Decision to prioritize taking ownership of pages that are currently on the NCIDS Documentation Site to take full ownership of those components/utilities, followed by creating new pages that are needed for NCIDS Launch.

**Comment by andyvanavery31** [comment]
Closing this ticket since the decision was made to adopt these pages into NCIDS owernship.
