### ISSUE TITLE
Conduct Copy Edit of NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1329]
### Request Description
Conduct a Copy Edit of the NCIDS Documentation Site to ensure there is consistency in structure and One Voice. All edits must be updated on the Doc Site.

### What's the expected change?
- Content on Doc Site will be updated with the results of the Copy Edit

### What's the current functionality?
- The Doc Site requires a Copy Edit

**Comment by bennettcc** [comment]
Closing this ticket - making a separate ticket for known scope of batch 1 copy edits
