### ISSUE TITLE
Discovery + Analysis: Dynamic List Filtering

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#133]
*Description of what is to be accomplished.*
Understand the scope of filtering functionality across the site. Can be true filters (taxonomy based) or behaving like (blog categories)
* Blog Categories
* Press Releases by year
* inventory of examples of filter functionality through site
* behavior analysis and patterns

**Document on Notion Page: https://www.notion.so/Filters-b27bcfa40ff24978bb2e5961a1235320**

**Comment by VictoriaSunNIH** [comment]
Does this need to be broken out based on content type?

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
