### ISSUE TITLE
NCIDS Documentation Site Copy Edit Update

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1331]
### Change Description
The NCIDS Documentation Site needs to go through the Copy Edit process, and those changes need to be implemented on the Documentation site. This will include using "the" prior to "NCI", consistency in capitalization (caps in headlines), and spelling out initialisms during their first use on every page (excluding NCI and NCIDS).

Some identified locations of capitalization inconsistencies are:
- https://designsystem-dev.cancer.gov/develop/foundations/appearance/outline
- https://designsystem-dev.cancer.gov/develop/foundations/typography/text-styles  

### What's the expected change?
- The copy edit will be conducted on the NCIDS Documentation Site and the site will be updated with the edits.

**Comment by laurelthrash** [comment]
Note: this is a full copy edit of the documentation site and should wait until all other content changes are done. Adding toward end of "Approved to Schedule" backlog for hard launch items.

**Comment by bennettcc** [comment]
Closing this ticket, we'll track copy editing needs on https://github.com/NCIOCPL/ncids/issues/1712
