### ISSUE TITLE
NCIDS Documentation Site Increase Visual Distinction Between H2 and H3

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1332]
### Change Request
Request is to increase the visual distinction between H2 and H3 on the NCIDS Documentation Site. This may be able to be fixed by implementing the new nci-headings component being built in R2.3.

### What's the expected change?
- There will be greater visual distinction between H2 and H3 on the NCIDS Documentation Site.

### What's the current functionality?
- The H2 and H3 on the NCIDS Documentation Site are very similar.

### Requirements

For consistency across Cgov and DS site, the changes shall be:
- change h3 to 20px (md)
- change h4 to 18px (sm)
- change h5 to 16px (xs)
- change N&E landing page heading label from h3 to h2
- change on prod h2 23px to 24px (xl)
- Align font sizes in Cancer.gov and identify unique cases (e.g., Related Resources) and bring to the Product and Design team to make a determination on these cases

### Notes

Here is the Buttons page mocked up with the proposed h3 size: https://www.figma.com/file/C1Enki5evIhPZg95weS6rW/NCI-Headings-(H1-H6)?type=design&node-id=2729%3A2256&mode=design&t=x0IVarxZ1XtosNYK-1.

The following component/styles will be affected:

- NCI Heading Styles & Modifiers - update h3, h4 and h5 sizes
- Paragraph Styles in Figma (no change on DS site)
- Collections component - update in the DS to change h3 label to h2
- News and Events page in production - utilizes the headings style (mentioned above) so the labels will change to the H2 size on Collections & Right side bar

### Related Tickets
* Original Story Ticket #1150

**Comment by andyvanavery31** [comment]
The current h2 and h3's on the documentation site do not have a large enough distinction between the two per the client's feedback. However, these headings are using the usa-prose settings. Sending this to the design team to further investigate if changes need to be made to how usa-prose is styled across the design system. Need to come to a determination if we are changing the sizes of h2's and h3's across the site (both Doc Site and cgov), if we are not going to make this change, or if we are going to make specific changes to the Doc Site that is different than what is shown on cgov.

**Comment by laurelthrash** [comment]
Consulting @blilianyu @dcvijanovic1k if there is enough information on this ticket to get started. Or, if it would be helpful to confer during an upcoming UX team meeting before beginning investigation.

**Comment by laurelthrash** [comment]
Confirmed there is enough info to begin investigation. Adding to current iteration as "Ready for Pickup."

**Comment by blilianyu** [comment]
Currently on Cancer.gov, h2 is 23px and h3 is 20px. The new NCI Headings class & on DS site, h2 is 24px and h3 is 22px. 

For consistency across Cgov and DS site, our recommendation is to:
- change h3 to 20px (md)
- change h4 to 18px (sm)
- change h5 to 16px (xs)
- change N&E landing page heading label from h3 to h2
- change on prod h2 23px to 24px (xl)

We can walk through and discuss at the next UX meeting. Our findings and proposed changes can be found [here](https://www.figma.com/file/C1Enki5evIhPZg95weS6rW/NCI-Headings-(H1-H6)?type=design&node-id=2701%3A9534&mode=design&t=Z2lG0FD477oMT8YP-1).

cc: @dcvijanovic1k

**Comment by laurelthrash** [comment]
Above change request approved by UX. Ticket to be discussed and aligned upon at future requirements meeting with developers to confirm feasibility and LOE of above change request. If change request LOE is reasonable, plan to share with Anna and seek approval/alignment before proceeding.

**Comment by laurelthrash** [comment]
Discussed during 02/14 Requirements meeting. Developers confirmed there are no major concerns and LOE is low-medium. Will confirm alignment with Anna during EOS 02/20 before moving forward.

**Comment by laurelthrash** [comment]
Determined with federal team that we will proceed with proposed updates to update to the font sizes. We will need to align font sizes in Cancer.gov and identify unique cases (e.g., Related Resources) to make a determination.
