### ISSUE TITLE
NCIDS Documentation Site Clarify Footer Contact Information in Overview Section

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1335]
### Change Request
The request is to add clarification to annotation 4, Contact Information, within the [Footer Overview section](https://designsystem-dev.cancer.gov/develop/components/footer). This was brought to attention by Anna during the Batch 2 review with the comment, "DOCs I engage with are confused about this since the example you’re showing is for NCI enterprise, not for DOC level. “DCEG / at the National Cancer Institute.” "

### What's the expected change?
- Drafting clarification for the Contact Information annotation of the Footer Overview section, and implementing that on the NCIDS Documentation Site.

### What's the current functionality?
- The annotation 4 on the Footer page in the Overview section on the NCIDS Documentation Site is not clear to DOCs.

**Comment by adrianacastaneda** [comment]
@bryanpizzillo @andyvanavery31 @bennettcc 

Updates for this ticket, [ticket #1534](https://github.com/orgs/NCIOCPL/projects/16/views/15?pane=issue&itemId=53518835), and the next steps we had aligned on based on our requirements discussion to include more footer guidance on the NCIDS doc site are all included in the document below:

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Footer.docx?d=w75370034a6db4bb9b33d8121f7057e96&csf=1&web=1&e=E4Ht2x

**Comment by adrianacastaneda** [comment]
all updates addressed in the Footer doc: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Footer.docx?d=w75370034a6db4bb9b33d8121f7057e96&csf=1&web=1&e=sldwpg

cc: @andyvanavery31 @bryanpizzillo
