### ISSUE TITLE
NCIDS Documentation Site Add Figma Resource Links to the About the NCIDS Page

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1337]
_Note: This ticket was broken up into two tickets so as to separate changes into one ticket per page impacted._ 

_**Specific changes to be implemented based on this ticket**_
1. Remove current sentence that reads "[Visit our Figma Guide](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide) to download the file and learn how to start designing with the NCIDS." on the [About the NCI Design System](https://designsystem-dev.cancer.gov/develop/about#design-resources) page.
2. Add "[Learn how to design with the NCIDS and download the NCIDS Figma Design Kit.](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide)" as the final sentence of the "Design resources" Section.

_**Original Ticket Below**_
### Change Request
This request is to add links to the Figma Community File and the Figma Guide within the [About the NCI Design System page](https://designsystem-dev.cancer.gov/develop/about#design-resources) in the Design Resources section. Requested from Anna during the Batch 1 review of the NCIDS Documentation Site Pilot.

### What's the expected change?
- References to the Figma Community File and Figma Guide within the About the NCI Design System page in the Design Resources section will also be links to those resources.

### What's the current functionality?
- The Design Resources section is just plain text.

**Comment by andyvanavery31** [comment]
This is a Design/IA ticket, and the intent of the page vs the request should be reviewed for accuracy.

**Comment by laurelthrash** [comment]
Determined with Design/IA that we will not link "a Figma community file" to the Community File and will leave the "Design resources" section as-is. Closing this ticket.

**Comment by laurelthrash** [comment]
Shared decision above with Anna via Teams on 02/07. Determined that we wish to make updates to the [About the NCI Design System page](https://designsystem-dev.cancer.gov/develop/about#design-resources) after all. These are outlined below: 

1. Remove current sentence that reads "[Visit our Figma Guide](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide) to download the file and learn how to start designing with the NCIDS."
2. Add "[Learn how to design with the NCIDS and download the NCIDS Figma Design Kit.](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide)" as the final sentence of the "Design resources" Section.
    - Rationale: we want to be clear that the Figma Guide is not a guide that Figma created for people to learn how to use Figma, and it is easier to spot a link at the end of a paragraph. 
3. Change "[Getting Started with Figma](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide)" page title/H1 to "NCIDS Figma Guide" to avoid confusion and align with the left navigation.
