### ISSUE TITLE
NCIDS Documentation Site Updating Step-By-Step Language in Getting Started for Developers Page

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1338]
### Change Request
Request is to update the wording on the [Getting Started for Developers page](https://designsystem-dev.cancer.gov/develop/get-started/developers) on the NCIDS Documentation Site for clarity of the process of use. The request from Alex during the Batch 2 review of the NCIDS Pilot was, "We’re mismatching our language. The “Step-by-Step” section includes three phases. But each phase is subdivided into steps.  a. Either change “Step-by-Step” to “Phase-by-Phase” or change the three phases to steps and rename the current steps to something else. b. Really, don’t call the current steps anything. Change “Step 1,” “Step 2,” etc. to “1a,” “1b,” etc." The goal of this change is to update this page so that the language is consistent and understandable for users.

In addition, under Phase 2 of this page, the organization has been noted as confusing to the client upon Batch 2 review. The request is to mitigate the confusion about the following notes:

* I'm not sure why “About Sass Load Paths” is an H4 instead of an H3.  
* I’m not sure why “Sass Module Syntax” doesn’t have it’s own subsection. 
* If NCIDS Sass needs three things to compile properly, where did “Import NCIDS styles to your project” come from? Should that be it’s own phase? 
* I’d recommend following the same subsection model for Phase 2 that you use for Phase 1, such as 2a, 2b, 2c. 

### What's the expected change?
- The language on the Getting Started for Developers page gets edited for improved consistency and comprehension, and those edits get added to the NCIDS Documentation Site.

### What's the current functionality?
- There is inconsistency in the use of "Step-by-Step" and "Phases" and not indicating what are steps or phases on the Getting Started for Developers page on the NCIDS Documentation Site.

**Comment by bennettcc** [comment]
This is a content/language consideration (though it is on the developers page) - tagging @laurelthrash to assign this to an IA to consider and make the recommended content updates

**Comment by adrianacastaneda** [comment]
@bennettcc Made suggested changes to this doc. Also had some questions for devs and would love for them to review the changes I made. Who has the bandwidth to help review? Thanks!

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/For%20Developers.docx?d=w00d8d971648744f5a9310e41ef7eb4e5&csf=1&web=1&e=YqP7Fv

**Comment by adrianacastaneda** [comment]
@bennettcc Olivia reviewed and we're aligned so this doc should be good to go! Thanks!

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/For%20Developers.docx?d=w00d8d971648744f5a9310e41ef7eb4e5&csf=1&web=1&e=v8vdTE
