### ISSUE TITLE
Pull past research on use of button vs. text link for blog subscriptions

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#138]
Pull out and socialize any available data on past testing around use of text links v. buttons for blog subscriptions.

**Comment by mworrest** [comment]
Some of the blogs (at least RAS) have an exit notification icon on the subscribe link so that influenced our decision on choosing the link instead of button. I'll try to dig up any data we have.

**Comment by mworrest** [comment]
While the results of the Crazy Egg pilot test on styling the subscribe button were statistically insignificant, the link performed better than the button. 
[AB_Test_Pilot_Review_Updated.pptx](https://github.com/NCIOCPL/ncids/files/6408203/AB_Test_Pilot_Review_Updated.pptx)
