### ISSUE TITLE
Change the Twitter Logo on cancer.gov and microsite footers

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1385]
There is new HHS guidance which states that the Twitter logo should be replaced with the X logo on Federal websites.

1. Please update the twitter logo with the attached X logo. (Per Bryan, this may be a change in the NCIDS followed by manual updates within each CMS for each footer component)
2. The accessibility label/text should be 'Follow on X'

Example footer logo: look within the footer of https://www.cancer.gov/

![X Logo Icon-Yellow Circle](https://github.com/NCIOCPL/ncids/assets/22639543/c189089e-8b23-4a31-a649-3e1b3510ee28)

**Comment by karlikpj** [comment]
@bennettcc 

![Screenshot 2023-11-06 at 7 01 30 AM](https://github.com/NCIOCPL/ncids/assets/66697447/42e29829-eff6-47d2-924c-967f9b7b8d18)

going to need an updated SVG file that is only one color with no special clipping paths.
