### ISSUE TITLE
Update Twitter Icon on the Documentation Site Footer Overview Image

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1388]
There has been guidance from HHS that the twitter icon should be replaced with the X icon on federal websites

Please replace the twitter icon with the X icon on the documentation site, within the footer and within the anatomy/overview image:

https://designsystem-dev.cancer.gov/develop/

**Comment by dcvijanovic1k** [comment]
Hi @karlikpj @bennettcc - here's an updated screenshot of that footer component. Please let me know if you need anything else. 
<img width="1058" alt="footer_overview" src="https://github.com/NCIOCPL/ncids/assets/102183929/328bbf88-4325-45a6-a113-1c5e519d8163">
