### ISSUE TITLE
NCIDS Documentation Site Fix Content on Headers Page

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1389]
### Change Description
This request is to update the blank space that is on the Headers component page on the NCIDS Documentation site, under the Header logos - using SVGs section. https://designsystem-dev.cancer.gov/develop/components/header. The sentence before the blank space needs to be completed and the blank space needs to be removed.

Additionally, there is a heading titled "Arial-Label" which needs to be changed to "Aria-Label"

### What's the expected change?
- Updating the content of the Headers component page on the NCIDS Documentation Site so that there is no open ended sentence and blank space under the Header logos - using SVGs section.
- Update the "Arial-Label" to "Aria-Label"

### What's the current functionality?
- There is an open ended sentence and blank space under the Header logos - using SVGs section on the Headers component page on the NCIDS Documentation Site.
- There is a heading that is "Arial-Label"

### Notes
- Related to #1447

**Comment by andyvanavery31** [comment]
Evaluate if the [Headers Logos - SVGS](https://designsystem-dev.cancer.gov/develop/components/header#header-logos---using-svgs) Section is necessary and aligned to the expected use.

**Comment by laurelthrash** [comment]
Determined with Design/IA that we need to better understand the issue with the image. @adrianacastaneda to review the original Word document to identify the initial intentions for that section.

**Comment by bryanpizzillo** [comment]
This was actually closed in the content updates done during #1481.
