### ISSUE TITLE
NCIDS Documentation Site No Outline Appearing on Clicked Links on Safari

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1390]
### Bug description
When viewing the NCIDS Documentation Site on Safari, the links do not show the outline when they are clicked or tabbed over. This issue is not occurring on Chrome nor Firefox.

### What's the expected change?
- Link outlines should appear when clicked on or tabbed to when viewing the NCIDS Documentation Site on Safari.

### What's the current functionality?
- Link outlines do not appear when clicked or tabbed to when viewing the NCIDS Documentation Site on Safari.

**Comment by sarinapadilla** [comment]
This issue is due to a setting in Safari - once turned on, the outline displays when tabbing.
