### ISSUE TITLE
Story: Create the NCI Combo Box

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1397]
### Requirements

- The nci-combo-box will be created
- The nci-combo-box will have the same features and functionality as the USWDS component with the addition of the following changes:
  - Accessibility text will be provided for the combo in a non-visible `<div>` with `role=status` to indicate the contents of the combo box for screen reader users
  - When the user clicks or tabs into the combo box, the first five options from the associated list will appear in the dropdown
  - When a user types a full matching word/phrase by characters (capitalization does not matter) and presses enter, then the selection will appear in the combo box
  - If a user types a partial matching word and presses enter, then the text in the box will disappear
  - If a user has an option selected, and moves to another phrase, but doesn't select it, and leaves the combo box, then the previous selection will remain
  - The Error State will meet accessibility requirements when placed against a dark theme background - see comp

### Storybook

* 📁 Forms
   * 📁 Form elements
      * 📁 Form controls
         * 📁 Combo box
            * 📁 Default
               * 📁 **Default state**
               * 📁 **Disabled state**
               * 📁 **No JS**
            * 📁 Test cases
               * 📁 Cgov
                  * **Cgov input**
                  * **Cgov input error**

### Notes

- [x] ACTION ITEM: @arcepaul will review the issues related to the USWDS combo box to find what fixes should be made
- [x] ACTION ITEM: @karlikpj to determine what the error state is for a combo box with the outline from NCIDS/USWDS
- [x] ACTION ITEM: @blilianyu @monika-jaeger @dcvijanovic1k will update the comps to match the functional requirements listed above, include changing the third comp image to reflect the error state if a user presses 'Go' without an entry in the combo box.

### DoR DS Tasks

- [x] Update design of nci-combo-box for all visual and functional requirements identified above. Put the solution into its own class space on Figma
- [x] Refine user story statement
- [x]  Create Scenarios
- [ ]  Internal review of any changes to the Design solution for nci-combo-box on Figma
  - [x] Design Approval
  - [x] Development Approval
  - [x] IA Approval
- [ ]  Internal review of DS AC's
  - [x] Design Approval
  - [x] Development Approval
  - [x] IA Approval

### DoD

- [ ] Develop DS class from design Figma comp
  - [ ]  Update Documentation Site per Scenarios document
    - [ ]  **To be completed by #1409 :** Draft the guidance and all sections necessary for addition to the NCIDS for All Documentation Site
    - [ ] Create page for the Combo Box under the Components section in Doc Site
    - [ ] Update the [Components landing page](https://designsystem-dev.cancer.gov/develop/components/) so that the link to the Combo Box is on this page
  - [ ]  Update Storybook Site per Scenarios document
  - [ ]  Update Example Site per Scenarios document
- [ ]  Internal review of the DS solution
- [ ]  Demo DS solution to client

### Resources:
* [Cancer Types Comp](https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&node-id=0-1&mode=design&t=kO43db8PZZekaRcW-0)
* [Combo Box Comp](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=5869-11262&mode=design)
* [Combo Box Error State Comp](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=5869-11262&mode=design)
* [Scenarios](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Development%20and%20Testing/NCI%20Combo%20Box%20Scenarios.docx?d=w34abae13b5d34917bff344eddfeafd44&csf=1&web=1&e=ZqKMvb)
* [Doc Site Content](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B364941EA-078F-465F-8029-B53C74D286D5%7D&file=Combo%20Box.docx&wdLOR=cFB8AD81E-6B6F-E949-8089-D9CA2476D443&action=default&mobileredirect=true)

### Acceptance Criteria

```gherkin
Scenario: A user views a page with an nci-combo-box component
  Given a page editor has added an nci-combo-box component to the page
    And the nci-combo-box component has been implemented in the Design System
    And the nci-combo-box has a list of items to pull from
  When the user views the page with an nci-combo-box component
  Then the nci-combo-box will match the comp (see link in the Resources section)
  When the user clicks in the combo box
  Then the combo box will be outlined to indicate it has been clicked
    And the cursor will appear in the combo box
  When the user clicks the down arrow in the combo box
  Then all the options in the list of items will appear in alphabetical order
  When the user types a string of characters in the combo box
  Then the dropdown will display any options that contain that string (ignoring capitalization) in alphabetical order
  When a user types in a partial string into the combo box
    And presses enter
  Then no selection will be made
  When a user types a string into the combo box that is not contained within any of the options of the dropdown
  Then the only item in the dropdown will be "No results found"
  When a user types a fully matching string into the combo box
    And presses enter
  Then the matching string will populate the combo box
  When a user clicks on an option from the dropdown list
  Then the selection will populate the combo box
  When there is a selection populating the combo box
  Then an 'X' will appear at the right side of the combo box
  When there is a selection populating the combo box
    And the user clicks the 'X'
  Then the combo box will be cleared
  When there is a selection populating the combo box
    And the user backspaces/deletes/highlights and writes over the text in the combo box
    And presses enter
  Then the previous selection populating the combo box will remain populating the combo box
  When the user tabs to the combo box
  Then the combo box will be outlined to indicate it has been clicked
    And the cursor will appear in the combo box
  When the user presses the down arrow
  Then the dropdown will appear
    And the first option in the dropdown will be outlined
  When the user presses the down arrow N times
  Then the Nth option in the dropdown will be outlined
  When the user presses the up arrow
    And the user is on an item in the dropdown
    And is not in the text area of the combo box
  Then they will move up one item in the list
  When an item is outlined via keyboard navigation
    And the user presses enter
  Then the item that was outlined will populate the combo box as a selection
  When the dropdown list is visible to the user
    And the user presses the Esc key
  Then the dropdown list will collapse
  When the user has the combo box text area selected
    And there is text populating the combo box
    And the cursor is not at the far left (beginning of the populated word/phrase)
    And the user presses the left arrow key
  Then the cursor will move to the left by one character
  When the user has the combo box text area selected
    And there is text populating the combo box
    And the cursor is not at the far right (end of the populated word/phrase)
    And the user presses the right arrow key
  Then the cursor will move to the right by one character
  When the user selects the combo box
    And there is no text populating the combo box
    And the user presses the tab key
  Then the selection will move to the next object within the structure of the page - not in the combo box
  When the user selects the combo box
    And there is text populating the combo box
    And the user presses the tab key
  Then the hover state will move to the 'X'
  When the hover state is over the 'X'
    And the user presses the enter key
  Then the text in the combo box will be cleared
  When the hover state is over the 'X'
    And the user presses the tab key
  Then the selection will move to the next object within the structure of the page - not in the combo box
```

Combo box - Disabled State
```gherkin
Scenario: A user views a page with an nci-combo-box component in the disabled state
  Given a page editor has added an nci-combo-box component to the page
    And the nci-combo-box component has been implemented in the Design System
    And the nci-combo-box has a list of items to pull from
    And the nci-combo-box is in the disabled state
  When the user views the page with an nci-combo-box component
  Then the combo box will be greyed out
    And the user will not be able to interact with the combo box
```
### Technical Notes
- [Editable combobox example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/)
- W3C Recommended Keyboard interactions - [listbox example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)
- Open USWDS combo box issues: [https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+combo+box](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+combo+box)

**Comment by bryanpizzillo** [comment]
## Technical Solution

This will go into `ncids-js/usa-combo-box`. You will need to add `ncids-js/usa-combo-box` to both ncids-js/typedoc.json and package.json in the exports section.

### HTML

** Basic HTML **
(Before JS initializes)
```
```

Initialization Notes:
*

Initialization Flow:
*

### Component Options
*

### Data Attributes
*
 
### Public Component Methods
*

### Events (See above)

**Comment by arcepaul** [comment]
@adrianacastaneda When creating the **When to use** section, we should take extra care to describe the correct situations to use the combobox versus using a plain `select` or `autocomplete` component.

**Comment by adrianacastaneda** [comment]
@arcepaul that's a great point! I made a few modifications to [the doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Combo%20Box.docx?d=w364941ea078f465f8029b53c74d286d5&csf=1&web=1&e=8jfv7H)
