### ISSUE TITLE
Enabler: Setup ncids-js Sub-Repo

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#14]
# Setup ncids-js Sub-Repo

This is the implementation for VanillaJS components. Any site/application built using these components must also include ncids-css. The npm package will be published to the NCIOCPL organization's GitHub registry. The storybook output will be published to a subdirectly under the designsystem.cancer.gov site.

Things to do:
* [ ] import uswds js
   * [ ] export as modules (and like SASS, only export the things we need at this time)
* [ ] Update "[The Way](https://github.com/NCIOCPL/ncids/wiki/The-Way)" 
* [ ] Configure eslint rules
* [ ] Configure Babel 
* [ ] Configure webpack and rollup JS to bundle the javascript output
* [ ] Setup Jest for unit tests (removing mocha from uswds implementation)
* [ ] Configure anything else I missed that we would have in a JS repo.

Things NOT to include:
* [ ] Configure visual regression tests - to be added later.
* [ ] Other Github Actions to publish the package automatically
* [ ] Publishing the files to any cloud location (e.g. a CDN for serving up static JS & CSS)
* [ ] Configure Github Actions to build, lint and test on pull requests - i.e. fail a PR if the code is bad.
* [ ] Configure storybook
* [ ] Example sites
* [ ] Setup Cypress for behavioral tests

> **ESTIMATE** 5 story points

### Resources:
* https://github.com/NCIOCPL/ncids/wiki/Repos-Packages-Organization#ncids-js

### Prerequisites
- Enabler: Setup Design System Mono Repo #6 

### Notes
* Technically need a way to review files that go through the full build process. Remember, two use cases here:
   1. Non-developers can just add a reference to the css on a CDN and start using the design system without npm.
   2. Our team that will import this SASS and JS modules into our sites. (e.g. A Drupal theme)

**Comment by anthonycuellar** [comment]
Aiming to complete today
