### ISSUE TITLE
Create Figma community file publishing instructions

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1400]
**Description:** Create documentation for the steps to publish the Figma Community File.

**History:** When someone publishes a new version of the Figma community file, Figma does not save what was entered in the fields by another user on the team who pushed an update. Thus, it does not save the description or settings such as turning off comments. We must record the instructions for publishing the community file to ensure continuity. 

**Sub-tasks:**
- [x] Create documentation
- [x] Review internally
- [ ] Save to Teams files

**Comment by monika-jaeger** [comment]
@blilianyu @dcvijanovic1k here is a draft of the documentation steps. We will still have to discuss the release notes, but take a look and see if there is anything else missing.

cc: @laurelthrash 

------------------

### From [NCIDS Design Kit](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0%3A1&mode=design&t=gq3lJqrGUum2Llii-1) file...
- Select 'Share' button in upper right corner
- In the model, select 'Update Community file'
- Select button 'Publish update...'

### **In the model, enter the following content**
**Name:** NCIDS Design Kit
**Description:** NCIDS is the design system for the National Cancer Institute (NCI) based on the U.S. Web Design System (USWDS), a design system for the federal government. This library provides designers with components, tokens, and utilities in the NCIDS to create compositions and mockups.

NCI staff can contact NCI OCPL regarding suggestions or feedback via our [NCI OCPL Web Design System Teams channel](https://teams.microsoft.com/l/team/19%3aczPgjMLyJafICTCGz-n-NxlkmNF1tP1Ya6Eu2sZ1FTI1%40thread.tacv2/conversations?groupId=e3158cae-7c76-436f-ba14-4a879d7695c5&tenantId=14b77578-9773-42d5-8507-251ca2dc2b06).

_[insert release notes link: TBD]_

**Tags:** 'design system' 'national cancer institute' 'nci' 'ncids' 'uswds'
**Preview as:** File

**Advanced** (open panel)

- Support contact: leave blank
- Creators: National Cancer Institute (Team)
- Comments: leave box unchecked
- License: Creative Commons BY 4.0 (no changes)
- Remixes: check box "Allow Community members to publish files based on this resource."

### Once published, check the Community storefront page for [NCIDS Design Kit](https://www.figma.com/community/file/1288512334920909770/ncids-design-kit) for the following:
- There is NO email listed in the bottom right corner
- All links work in the description
- Comments are turns OFF (no comments are visible)

**Comment by blilianyu** [comment]
@laurelthrash @dcvijanovic1k  Added "Release Notes" page in Community file here: https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5110%3A6169&mode=design&t=RxBVgTBKH0xRaGvj-1.

This has also been added as a doc here: [Publishing Figma Community File](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Figma%20Design%20Kit%20(Community%20File)/How%20to%20Publish%20Figma%20Community%20File.docx?d=wd6e6a048a5324a91b060c27b8d3f9ad6&csf=1&web=1&e=JWnb9E)

**Comment by laurelthrash** [comment]
Thank you, @blilianyu ! Should we add the Release Notes Excel tracker to the Publishing Figma Community File for reference as to how the Release Notes in Figma are derived?

**Comment by laurelthrash** [comment]
Excellent, thank you, @blilianyu. We should be set on this ticket. I'll go ahead and close it out.
