### ISSUE TITLE
Create NCIDS Collections Content for Doc Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1405]
This ticket is to track the creation of the content needed to be added to the NCIDS Documentation Site for the NCIDS Collections component to be released as a part of R2.3.

**Parent Issue:** #1149

**DoD Tasks**

- [x] Draft NCIDS Documentation Site content
- [x] Review NCIDS Documentation Site content
- [x] Create Markdown from [Word doc](https://nih.sharepoint.com/:w:/s/NCI-OCPLNewCgovUXDesignSystem/EXy77Qj6lsFFs0sqXqrp9ooBk-YhWl_8PR7MaAcMUUIkZg) **[UX Team member to create then add to this ticket]**
    - Markdown text: https://nih.sharepoint.com/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Fe1d8E&cid=cc7d3307%2Dcb91%2D4bab%2Db41d%2Def5899dfd09e&FolderCTID=0x0120005F2FA21B2C6E704CB4EDDD13D67036B6&id=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%5FLaunch%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown%2F%5BDRAFT%5D%20Collection%2Etxt&parent=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%5FLaunch%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown
- [ ] Edit the NCIDS Documentation Site with the new Collections component content using the Editing the NCIDS Documentation Site procedure
- [ ] Product and Tech review of the NCIDS Documentation Site content

**Comment by adrianacastaneda** [comment]
@laurelthrash @lburack here's the [collection page](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Word%20Docs/[Collection.docx](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Collection.docx?d=w08edbb7c96fa45c1b34b2a5eaae9f68a&csf=1&web=1&e=dnsbHj)?d=w08edbb7c96fa45c1b34b2a5eaae9f68a&csf=1&web=1&e=dnsbHj) for review. Thanks!

**Comment by laurelthrash** [comment]
Accessibility language added to the Word document. Review in progress via Slack.

**Comment by laurelthrash** [comment]
Documentation site page aligned upon via Slack on 01/25. Awaiting confirmation that designers can proceed with creating the overview image.

**Comment by dcvijanovic1k** [comment]
Hi @arcepaul & @karlikpj - here's the overview image for you. Please let me know if you need anything else! cc @laurelthrash 
<img width="913" alt="collections_overview" src="https://github.com/NCIOCPL/ncids/assets/102183929/c7d0de10-b6c7-484d-a9d5-07902790a9b9">

**Comment by laurelthrash** [comment]
@andyvanavery31 - please remind me, is this ticket one where anyone can update the markdown and push a PR? Or, since there is an image associated with it, would be better for a developer to push through to the documentation site?

**Comment by olitharp-nci** [comment]
@laurelthrash @andyvanavery31 Couple of items came up for guidance that may need discussion

1. USWDS uses the [`<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) element to display the dates in the collection, but does not give any guidance on how to use it. The component requires the user implementing the component to hold a date time string (e.g., "2020-09-17T12:00:00+01:00"). 

2. Globe icon and label(?) on headings-only variant. I'm not even totally sure myself on what it means or if it passes accessibility. 
<img width="371" alt="Screenshot 2024-02-01 at 4 57 59 PM" src="https://github.com/NCIOCPL/ncids/assets/85901679/9cb790c9-b3f5-4f40-abab-5d9b7f26dc94">

**Comment by laurelthrash** [comment]
Thanks for flagging, @olitharp-nci. Adding these comments to Requirements this week to align with design/dev.

**Comment by laurelthrash** [comment]
@olitharp-nci added above language to the Word document. The language is intended to appear below "Code Snippets" and above the component preview.

**Comment by sarinapadilla** [comment]
Per requirements meeting on 2/14, we'll be excluding the headings-only variant in our first creation of the collections page.

**Comment by adrianacastaneda** [comment]
Made a few tweaks and struck through the variant table (noting that we'll keep it for our records but that it should not be added to the doc site based on our requirements conversation on 2/14). @laurelthrash

**Comment by laurelthrash** [comment]
Adriana reviewed updated "Code Snippets" language from Olivia. This concludes the final review of this Doc Site content.

**Comment by laurelthrash** [comment]
UX to create markdown for this then pass over to developers for implementation.

**Comment by dcvijanovic1k** [comment]
@laurelthrash Collections markdown attached for review. 
[collection.txt](https://github.com/NCIOCPL/ncids/files/14424742/collection.txt)

**Comment by laurelthrash** [comment]
Reviewed and approve markdown (linked in above comment). Passing this over to development for implementation and closing from Design board. Cc: @andyvanavery31 @sarinapadilla

Note for developers: Markdown for overview image will need to be verified and code snippet information added.

**Comment by bennettcc** [comment]
@olitharp-nci we have updated content from Adriana. Check out the variants table and usage section (Adriana marked the content she added with a comment)

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B08EDBB7C-96FA-45C1-B34B-2A5EAAE9F68A%7D&file=Collection.docx&action=default&mobileredirect=true
