### ISSUE TITLE
Update Button Page on NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1411]
### Change Request
This request is to update the [Button page](https://designsystem-dev.cancer.gov/develop/components/button) on the NCIDS Documentation Site so that it better reflects the modifiers and variants that are available to users, and the guidance is consistent with its usage. Currently the Button page has conflicting information about how the button can be used which can be confusing to users. This page will be updated to match the structure that has been identified in the new Storybook Structure that is listed [here](https://github.com/NCIOCPL/ncids/wiki/Storybook-Structure#button).

### What's the expected change?
- Revise the [Button page](https://designsystem-dev.cancer.gov/develop/components/button) on the NCIDS Documentation Site so that the information there is consistent with the outline provided on the [new Storybook Structure](https://designsystem-dev.cancer.gov/develop/components/button). Ensure that the content on this page is updated for consistency with the changes to the structure.

### What's the current functionality?
- The [Button page](https://designsystem-dev.cancer.gov/develop/components/button) has a structure that does not clearly identify the differences between the modifiers and variants for this component.

### Design Tasks

- [x] Draft content updates
- [x] Review updates (one reviewer from IA, Development, and Design)

### Development Tasks

- [x] Create markup
- [ ] Add revised markup to Github using the NCIDS Documentation Site Content Editing Procedure

### Notes
- New icons are in development per #580

**Comment by adrianacastaneda** [comment]
@laurelthrash Sent to devs for review over slack but adding updated word doc to ticket for reference: [Button.docx](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot_Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Button.docx?d=w681077ed93e04cb3a4a539b9c269d05b&csf=1&web=1&e=QNZInx)

**Comment by laurelthrash** [comment]
Confirmed via Slack that the updated language via Word document is approved Cc: @adrianacastaneda @olitharp-nci @arcepaul 

@olitharp-nci to provide updated code snippet information before UX proceeds with making the content update to the page. Cc: @bennettcc

**Comment by laurelthrash** [comment]
Work on this ticket complete from design side for the time being. Closing this out on the Design board.
