### ISSUE TITLE
Relative links from the root/index.mdx seem to be broken inconsistently 

### ISSUE THREAD

**Issue by karlikpj** [NCIOCPL/ncids#1414]
### Issue description
From several root pages like Get Started or Templates, links from the body content with relative pathing (IE ./) seem to fail and remove the site root path causing a 404 error.

Again this seems to be the parent URL's trailing slash

To fix this quickly we should use a
> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  go to https://designsystem-dev.cancer.gov/develop/templates
2. from the body content click on 3-Card Row or Guide Card Row
3. page will 404

### What's the expected result?
- URL https://designsystem-dev.cancer.gov/develop/get-started/3-card-row

### What's the actual result?
- URL https://designsystem-dev.cancer.gov/develop/3-card-row

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
This should be closed by
[* Issue #1413](https://github.com/NCIOCPL/ncids/pull/1413)

**Comment by karlikpj** [comment]
This should be closed by
[* Issue #1413](https://github.com/NCIOCPL/ncids/pull/1413)

**Comment by andyvanavery31** [comment]
Closing due to fix included in PR #1413
