### ISSUE TITLE
Remove background color from the small button

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1422]
Remove background color from the small button. The small size modifier should only make the button small. Color should be applied with a color modifier. 

This would be a breaking change for the button component.

Usage to recreate the same button:

```diff
- <a class="usa-button usa-button--nci-small>Button</a>
+ <a class="usa-button usa-button--nci-small usa-button--secondary>Button</a>
```

This will additionally affect the banner component language toggle. We need to decide if we want to update the banner component html and css to extend the correct classes with a custom button or expect users to correct the markup when updating packages. (That probably answered the question.)

```diff
// breaking change
- <a href="/espanol" id="lang-toggle" class="usa-button usa-button--nci-small" hreflang="es">Español</a>
+ <a href="/espanol" id="lang-toggle" class="usa-button usa-button-nci-small usa-button--secondary" hreflang="es">Español</a>
```

or
```diff
// backwards compatible 
- <a href="/espanol" id="lang-toggle" class="usa-button usa-button--nci-small" hreflang="es">Español</a>
+ <a href="/espanol" id="lang-toggle" class="usa-button" hreflang="es">Español</a>
```

**Comment by olitharp-nci** [comment]
Developers should solution this

**Comment by sarinapadilla** [comment]
We're going with the breaking change option to reduce future technical debt.
