### ISSUE TITLE
Add instructions for adding fonts to website on Getting started for developers documentation 

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1424]
Add instructions for adding fonts to website on Getting started for developers documentation.

The instructions currently exist in [Typography](https://designsystem-dev.cancer.gov/develop/foundations/typography/fonts#recommended-way-to-use-fonts). 

We should not duplicate the information but we should link to where to find instructions. Where the instructions should live to be decided.

**Comment by laurelthrash** [comment]
@andyvanavery31 @sarinapadilla - I've read this ticket a few times and am confused! Is the intent that the instructions currently found on [Typography > Font Size and Family](https://designsystem-dev.cancer.gov/develop/foundations/typography/fonts) are insufficient? Does the location of the instructions needs to change? It may be a combination of both. If you could please update the ticket with this information, that would be great. I can also huddle if easier - thank you!

**Comment by sarinapadilla** [comment]
@laurelthrash the links to download the Google fonts are in two locations:
* https://designsystem-dev.cancer.gov/develop/foundations/typography
* https://designsystem-dev.cancer.gov/develop/foundations/typography/fonts#recommended-way-to-use-fonts

We need UX input on where to put the "where to find the instructions" information so it isn't duplicative!

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash @sarinapadilla - looking at this, we are recommending adding the instructions information to this page: https://designsystem-dev.cancer.gov/develop/foundations/typography

Is there any way to see how it looks before it gets published? Happy to huddle as well to discuss placement on the page. cc @blilianyu

**Comment by blilianyu** [comment]
@dcvijanovic1k @laurelthrash @sarinapadilla @andyvanavery31 

Ok I believe there was some confusion but after our DMs we've made the following decisions.

- On [Getting Started for Developers](https://designsystem-dev.cancer.gov/develop/get-started/developers), add a new paragraph at the end of [Phase 1: Install](https://designsystem-dev.cancer.gov/develop/get-started/developers#phase-1-install): "To download fonts, refer to the [Typography](https://designsystem-dev.cancer.gov/develop/foundations/typography) page."
- Remove the font download links on [Font Size and Family](https://designsystem-dev.cancer.gov/develop/foundations/typography/fonts#recommended-way-to-use-fonts) page

**Comment by laurelthrash** [comment]
For simplicity, closing this ticket in favor of making the updates via two new tickets: 
- #1526 
- #1527 

Cc: @blilianyu @dcvijanovic1k @andyvanavery31 @sarinapadilla
