### ISSUE TITLE
Upgrade to newer USWDS 3.7.1

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#1427]
# Upgrade to newer USWDS
> **ESTIMATE** TBD

We need to update to a newer version of USWDS to take advantage of accessibility fixes and new feature/components. As of this writing the current version is 3.7.0 and we are on 3.3.0, however we should upgrade to whatever is the latest when this occurs. At the time of this writing there is an **open** PR 5398 in the USWDS repo that is implementing an "icon button". We basically implemented USWDS code for our version. So updating to a version that contains that change would be a good thing.

**Comment by sarinapadilla** [comment]
We need to figure out what to do with our icon button changes (#1458) to match USWDS's published version.

**Comment by bryanpizzillo** [comment]
## Technical Approach Notes
With the introduction of PNPM, patching got a little more complicated. These notes are to document the approach to going about updating our patch to support a newer version, NOT, how to fix USWDS items that have changed. (You are on your own for fixing USWDS.)

### 1. Rename the patch file to maintain history in git/github. 
The move of the file must be separate from any changes to the file. When we go to patch the new version of USWDS, many of the changes *should* still apply, and thus the blame log will still work for those unchanged lines.

1. `cd patches`
2. `git mv @uswds__uswds@A.B.C.patch @uswds__uswds@X.Y.Z.patch`
     * Where A.B.C is the current USWDS version and X.Y.Z is the version you are moving to. 
3. Edit the root package.json file to change the `patchedDependencies to be:
     ```
     "patchedDependencies": {
        "@uswds/uswds@A.B.C": "patches/@uswds__uswds@X.Y.Z.patch"
     }
     ```
4. `pnpm install`
     * This should just update the hash at the top and in the block for the USWDS package. Bug fix bumps may occur FYI.
5. Commit with a `Touches` comment instead of closes.

### 2. Update to the new USWDS package
So updating the USWDS will most likely cause lots of post-compilation tasks to fail hard. This is because we do not have a patch yet that will work with the new version.
1. `cd packages/ncids-css`
2. `pnpm update "@uswds/uswds@~X.Y.Z"`
    * You should see the dependency installation block, but post tasks will fail
    
...To be continued

**Comment by bryanpizzillo** [comment]
FYI for 3.7.1 the patch test results in:
```
patching file 'packages/usa-banner/_index.scss'
1 out of 1 hunks failed while patching 'packages/usa-banner/_index.scss'
patching file 'packages/usa-banner/src/styles/_usa-banner.scss'
2 out of 3 hunks failed while patching 'packages/usa-banner/src/styles/_usa-banner.scss'
patching file 'packages/usa-button/src/styles/_usa-button.scss'
patching file 'packages/usa-character-count/src/styles/_usa-character-count.scss'
patching file 'packages/usa-collection/src/styles/_usa-collection.scss'
patching file 'packages/usa-error-message/src/styles/_usa-error-message.scss'
patching file 'packages/usa-file-input/src/styles/_usa-file-input.scss'
patching file 'packages/usa-form-group/src/styles/_usa-form-group.scss'
patching file 'packages/usa-identifier/src/styles/_usa-identifier.scss'
patching file 'packages/usa-input-prefix-suffix/src/styles/_usa-input-prefix-suffix.scss'
patching file 'packages/usa-input/src/styles/_usa-input.scss'
patching file 'packages/usa-label/src/styles/_usa-label.scss'
patching file 'packages/usa-sidenav/src/styles/_usa-sidenav.scss'
patching file 'packages/usa-summary-box/src/styles/_usa-summary-box.scss'
patching file 'packages/uswds-core/src/styles/_properties.scss'
patching file 'packages/uswds-core/src/styles/mixins/general/icon.scss'
2 out of 2 hunks failed while patching 'packages/uswds-core/src/styles/mixins/general/icon.scss'
patching file 'packages/uswds-core/src/styles/mixins/typography/headings.scss'
patching file 'packages/uswds-core/src/styles/settings/_settings-color.scss'
patching file 'packages/uswds-core/src/styles/settings/_settings-components.scss'
patching file 'packages/uswds-core/src/styles/settings/_settings-spacing.scss'
patching file 'packages/uswds-core/src/styles/settings/_settings-typography.scss'
patching file 'packages/uswds-core/src/styles/settings/_settings-utilities.scss'
1 out of 1 hunks failed while patching 'packages/uswds-core/src/styles/settings/_settings-utilities.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/shortcodes-color-basic.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/shortcodes-color-system.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/system-colors.scss'
patching file 'packages/uswds-core/src/styles/tokens/font/typefaces.scss'
patching file 'packages/uswds-elements/lib/_normalize.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/_cerulean.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/_cranberry.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/_golden.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/_navy.scss'
patching file 'packages/uswds-core/src/styles/tokens/color/_teal.scss'
```

**Comment by bennettcc** [comment]
@bryanpizzillo @olitharp-nci 
3.7.1 regression issues + analysis has been added to teams: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/USWDS%203.0/3.7.1%20Upgrade?csf=1&web=1&e=QCPa94
