### ISSUE TITLE
Add auto initialization documentation to component pages

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1428]
## Add auto initialization documentation to component pages

Documentation pages should be updated with information on how to use the auto init scripts.

### Tasks

- [x] Header
- [x] Footer
- [ ] ~~Site alert~~ #1572

### Related

- #1108 
- #1157
- #1159
- #1161

**Comment by sarinapadilla** [comment]
Template:
```To enable the default JavaScript interactions you must add import '@nciocpl/ncids-js/<insert component here>/auto-init'; to the top of your JavaScript file.```

```If you need to customize the <insert component here>, visit [the ncids-js documentation site](link to component page here) for more information on developing your own custom JavaScript.```
