### ISSUE TITLE
Create documentation for advanced js

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1431]
## Create documentation for advanced js

In a nutshell, we need to create easily followable steps to how to set up sites to use mega menus and mobile menus.
See https://github.com/NCIOCPL/ncids/wiki/Technical-NCI-Header-Design

### Tasks

- [ ] Header mega menu source
- [ ] Header mobile menu source

**Comment by olitharp-nci** [comment]
wip content

# Advanced JS

## Mega menu source

A mega menu source is currently required for the Header with mega menu component. To customize the mega menu, you must...

## Mobile menu source 

A mobile menu source is not required for a mobile menu. The default source is used with auto initialization. However, to customize the mobile menu you must...

**Comment by bennettcc** [comment]
Closing as a dupe of https://github.com/NCIOCPL/ncids/issues/1432
