### ISSUE TITLE
TTC / MyPART R2 Homepage Content Next Step / Go-Live

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1439]
> Related to: #758 / #1381 / #1380

**Description:** This ticket represents content go-live steps for the TTC and MyPART home and landing page content launch. [Full calendar and checklist found here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Project%20Management/R2.1%20Landing%20Page%20Update%20Schedule.xlsx?d=w6976516d4d8048cb9f83258530f202b8&csf=1&web=1&e=Dn9pcl).

**TTC Sub-tasks:**
- [x] Review stakeholder feedback and make recommendations
- [x] Align on recommendations
- [x] Update comp and share final with stakeholders
- [x] Update source documents based on changes requested by TTC 
    - [x] Comp (Dragutin)
    - [x] Image inventory (Dragutin)
    - [x] Content template (Michael)
    - [x] Notation on Mural board (Laurel)
- [x] Obtain TTC hero image and approval of alt text
- [x] Send go-live communications
- [x] Finalize content template
- [x] Build pages
    - [x] Update comps following page review
    - [x] Add notations to Mural board
- [x] Review pages
- [x] Launch pages 

**MyPART Sub-tasks:**
- [x] Review stakeholder feedback and make recommendations
- [x] Align on recommendations
- [x] Update comp and share final with stakeholders
- [x] Replace one low resolution image
- [x] Request purchase and alt text approval for new iStock image
- [x] Obtain alt text for Spanish images and one translation approval for heading
- [x] Send go-live communications
- [x] Finalize content template
- [x] Build pages
    - [x] Update comps following page review
    - [x] Add notations to Mural board
- [x] Review pages
- [x] Launch pages

**Comment by laurelthrash** [comment]
@dcvijanovic1k @driscollmd TTC Changes based on stakeholder feedback and alignment with ODDC via Mural:

**Homepage**
- [ ] Add a CTA strip that includes the following:  "Available Technologies," "Prospective Partners," and "NHI Investigators"
- [ ] Add a Fellowship promo block above the video - using the promo meta information and image from the CMS (https://techtransfer.cancer.gov/fellowships-training/fellowships)
- [ ] Reorder "Available Technologies" links based on order of importance/clicks by users, instead of alphabetical. 

**Fellowships and Training**
- [ ] Identify a new image that does not represent lab work
- [ ] Add "Explore Fellowships" button to hero
- [ ] Replace three guide card row with a two guide card row with image and description
- [ ] Right guide card row: Fellowship Opportunities
    - [ ] Select new image (Dragutin)
    - [ ] Suggest sample description (Michael)
    - [ ] Buttons: Innovation, Negotiation, Business Development & Marketing, Transition to Industry (T2I)
- [ ] Left guide card row: Training Programs
    - [ ] Select new image (Dragutin)
    - [ ] Suggest sample description (Michael)
    - [ ] Buttons: Same as currently under "Training Programs" on the three guide card row
- [ ] Add promo block for T2I, using the meta information and promo image from the CMS

Outstanding (need clarification from TTC):
- [ ] Remove "Opportunities" feature card row?

**Comment by laurelthrash** [comment]
@dcvijanovic1k TTC indicated they would like [this image](https://www.istockphoto.com/editor/1365031712#doc=N4Ig5gpg9gthAuAnAniAXKA7gSwCbwAt0BGAZgFYAGAGhAImzAPnQCYBOAdlqkUewB2AQwA2AdTyESlVgBYefMINEAJBkxZoAbAA5WAXx4AjAFYQAxvADO6ANqg8JWvGQAHCOhAB5AEIApAH0ASQBZAEEAcQBREForRHNPZnhXKzQAenS4XGwhADpsK3gocwBrVwIoYrzzWHS8dLItKlJiTmJWdIqqqHSjAFcrQQgrKwBaOARBMDyTVzAAfisAXmIZWQAPNbkAMkxlwp3S5dZKHfNlv0pOAC0TFVxiYihSgEcAYRvyAGl%2B1gARAScXCcbDvAAyEUoAjGYCEiFkADVzKcBIgwAA5ACKy1i4GgcCQqAwIBw%2BCIaDIVFo9EYzDYXAU-GE4kkFO28hAvGZqnU9O0eloGxI5E4eR0sk4pFYelkslYnFkOloxLG5DyMq0rHI7HIsmI7AlnAVcXMoggAA0SHlWjoKOxSJxyKbzQBNa22%2B2O50gRBVITwbBQAToSj6fQAXX0QA) for the hero image for Fellowships & Training - can you please slot it in? Cc: @driscollmd

**Comment by laurelthrash** [comment]
Alex confirmed via Teams that TTC would like to remove the "Opportunities" feature card row @dcvijanovic1k @driscollmd

**Comment by laurelthrash** [comment]
@dcvijanovic1k @adrianacastaneda MyPART changes based on stakeholder feedback and alignment with ODDC via Mural:

- [ ] Adopt option 1, where the "MyPART (My Pediatric and Adult Rare Tumor) Network" header is above the first feature card row.
- [ ] First feature card row
    - [ ] Second feature card: update image for "Participate in our trial" to match image requested in Mural
    - [ ] Third feature card: 
        - [ ] Title: Why We Study Rare Cancers
        - [ ] Description: Rare cancers make up about a quarter of all cancer cases. Learn why we are committed to studying these cancers.
        - [ ] Update the image requested in Mural. 
- [ ] Add a second feature card row, with the header "Connect With Us" with the following cards: **[English and Spanish]**
    - [ ] First card: 
        - [ ] Title: Sign Up for Our Newsletter / Title: Comuníquese con MyPART
        - [ ] Description: Get updates on rare tumor news and events each month. / See Spanish description in CMS
        - [ ] See image in Mural
    - [ ] Second card (see Spanish equivalent in CMS) 
        - [ ] Title: Meet Our Partners
        - [ ] Description: Find advocacy organizations that partner with MyPART and learn how to become our partner. 
        - [ ] See image in Mural
    - [ ] Third card: (see Spanish equivalent in CMS) 
        - [ ] Title: Meet Our Team 
        - [ ] Description: Meet our diverse team of scientists, healthcare providers, and more 
        - [ ] See image in Mural
- [ ] Create one promo block (removing other promo blocks) **[English and Spanish]** **@adrianacastaneda - please confirm if we should reduce down to one promo block in Spanish as well**
    - [ ] Title: NIH Rare Tumor Clinics
    - [ ] Description: Bringing patients and families together with researchers and clinicians
    - [ ] CTA: Learn More
- [ ] Change the second research article listed in the bottom feature card row about brain tumors to the following cancer.gov article: https://www.cancer.gov/news-events/cancer-currents-blog/2020/selumetinib-nf1-fda-approval

**Comment by adrianacastaneda** [comment]
@laurelthrash Yes! One promo block for Spanish as well. Thanks!

**Comment by laurelthrash** [comment]
@dcvijanovic1k noting a few changes to the comps for both TTC and MyPART that came about while building out the page:

**TTC Homepage** Cc: @driscollmd 
- [ ] Update News and Events feature card row to reflect the three in the draft CMS page: https://techtransfer-cms.cancer.gov/node/1/latest
- [ ] Modify promo block to have image on left (consistent with our guidance)
- [ ] Modify TTC Fellowship Program promo block to match the description found on the draft CMS page (above)

**TTC Fellowships and Training** Cc: @driscollmd 
- [ ] Modify "Current Openings: Negotiator Fellowship" promo block to use same 1:1 crop as in the CMS for that image: https://techtransfer-cms.cancer.gov/media/436/edit
- [ ] Modify promo block to have image on left (consistent with our guidance)

**MyPART Homepage (English)** Cc: @adrianacastaneda 
- [ ] Modify feature card and promo block descriptions to match draft CMS page: https://mypart-cms.cancer.gov/pediatric-adult-rare-tumor/node/1133417/latest
    - Needed to use the card descriptions due to character limit for override field 
- [ ] Modify promo block to have image on left (consistent with our guidance)

**MyPART Homepage (Spanish)** Cc: @adrianacastaneda 
- [ ] Modify promo block description to match draft CMS page: https://mypart-cms.cancer.gov/pediatric-adult-rare-tumor/espanol/node/1133417/latest
    -  Needed to use the card descriptions due to character limit for override field 
- [ ] Modify promo block to have image on left (consistent with our guidance), followed by image on the right for second promo block

**Comment by laurelthrash** [comment]
Pages launched 01/18/24. Only remaining item is to obtain alt text translations for MyPART images. I will track that on my personal to do list. Closing this ticket - thank you!
