### ISSUE TITLE
SBIR R2 Homepage Content Next Step / Go-Live

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1440]
> Related to: #757

**Description:** This ticket represents content go-live steps for the TTC and MyPART home and landing page content launch. [Full calendar and checklist found here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Project%20Management/R2.1%20Landing%20Page%20Update%20Schedule.xlsx?d=w6976516d4d8048cb9f83258530f202b8&csf=1&web=1&e=nmQJPs).

**SBIR Sub-tasks:**
- [x] Prepare image specs for SBIR to reference for custom designers (Dragutin)
    - [x] Share with SBIR
- [x] Finalize stakeholder feedback (SBIR - On Hold)
- [x] Review stakeholder feedback and make recommendations
- [x] Align on recommendations
- [x] Update comp and share final with stakeholders
- [x] Purchase stock photos / approve alt text (N/A - existing images in the CMS)
- [x] Add stock photos to Drupal (N/A - existing images in the CMS)
- [x] Send go-live/content freeze communications
- [x] Finalize image(s) and featured content
- [x] Finalize content template
- [x] Build out page
- [x] QC page
- [x] Publish page

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here's a PDF of the image sizes for the various components. Please let me know if you need anything else. Thanks! 
[NCIDS-Image-Sizes.pdf](https://github.com/NCIOCPL/ncids/files/13675365/NCIDS-Image-Sizes.pdf)

**Comment by dcvijanovic1k** [comment]
Hi again @laurelthrash - updated PDF based on our conversations in Slack with Lilian and Adriana. Please let me know if you need anything else! 

[NCIDS-Image-Sizes.pdf.pdf](https://github.com/NCIOCPL/ncids/files/13730372/NCIDS-Image-Sizes.pdf.pdf)

**Comment by laurelthrash** [comment]
The PDF looks great, @dcvijanovic1k, thank you! We'll hold onto the PDF for when we resume work with SBIR at which point we can share with SBIR and invite questions.

**Comment by laurelthrash** [comment]
Seeing if obtain response from SBIR week of 01/01/24. Will review during this week's DOC PMO.

**Comment by laurelthrash** [comment]
Received homepage feedback via email from SBIR. @adrianacastaneda to review to identify concerns/questions for discussion.

**Comment by laurelthrash** [comment]
Homepage published 02/01. Closing this ticket.
