### ISSUE TITLE
NCIDS Documentation Site - Update Mega Menu HTML

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1443]
### Change Request
This request is to update the [NCIDS Documentation Site](https://designsystem-dev.cancer.gov/develop/) so that there is explicit information about the Mega Menu. The mega menu needs to have documentation relating to the anatomy of it and it should include sample html. Guidance is needed to explain how to organize the HTML for future use by external developers. 

### What's the expected change?
- Guidance, anatomy, and sample html will be created and added to the NCIDS Documentation Site explaining how to implement and use the mega menu.
- Decision for IA: Where will this be located? On the Header component or on its own page?

### What's the current functionality?
- Information about building the mega menu is not available for users of the NCIDS.

### Additional details / screenshot
![image](https://github.com/NCIOCPL/ncids/assets/143126208/23066ac4-7f01-4810-bd44-ac7f658fc49f)

**Comment by adrianacastaneda** [comment]
@laurelthrash @bryanpizzillo @lburack 

Here's the link to the draft of the [Mega Menu page](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Mega%20Menu.docx?d=w1e4cef94b46e4f3c8baf957e08cae83f&csf=1&web=1&e=moK2N8).

Information architecture: This page will be located a level under the [Header page](https://designsystem-dev.cancer.gov/pr-1356/components/header). 

**Below are the changes I propose making to the Header component page:**
- Change "[NCI extended header with mega menu](https://designsystem-dev.cancer.gov/pr-1356/components/header#nci-extended-header-with-mega-menu-2)" to "NCI Extended header" with text right below saying "If your site has a more complex site structure, use a Mega Menu to display a deeper information architecture." Mega Menu should link to the Mega Menu page.
- Move [Mega Menu events](https://designsystem-dev.cancer.gov/pr-1356/components/header#events) to the Mega Menu page
- Remove "Megamenu Nav Header" information under the [Image guidance and specs section](https://designsystem-dev.cancer.gov/pr-1356/components/header#image-guidance-and-specs)
- Add the following as a sub-bullet to the second bullet under the [When to use section](https://designsystem-dev.cancer.gov/pr-1356/components/header#when-to-use)
- "If your site has a more complex site structure, use a Mega Menu to display a deeper information architecture." Mega Menu should link to the Mega Menu page.

**Comment by lburack** [comment]
@adrianacastaneda If I'm tracking the redesign_ds Slack thread from today (12/14) correctly, @olitharp-nci  said the mega menu functionality is built into the "extended header with mega menu". Is the first bullet above accurate, to change "NCI extended header with mega menu" to "NCI extended header"? Am I overthinking this?

**Comment by andyvanavery31** [comment]
Include the fix to #1447 within this PR.

**Comment by dcvijanovic1k** [comment]
@karlikpj @adrianacastaneda @bryanpizzillo Annotated image attached, exported at 2x size to fix our previous issues. Please let me know if you need anything else!
<img width="1058" alt="mega-menu" src="https://github.com/NCIOCPL/ncids/assets/102183929/2505ab1f-5004-411d-b03f-680aca2b503e">

**Comment by bryanpizzillo** [comment]
@adrianacastaneda When you say:
>Change "[NCI extended header with mega menu](https://designsystem-dev.cancer.gov/pr-1356/components/header#nci-extended-header-with-mega-menu-2)" to "NCI Extended header" with text right below saying "If your site has a more complex site structure, use a Mega Menu to display a deeper information architecture." Mega Menu should link to the Mega Menu page.

Do you mean that it should show up between the header and the preview/code?
