### ISSUE TITLE
Enabler: Baseline Typography

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#145]
### Build Baseline Typography 
> **ESTIMATE** TBD

Github #45 

Adding Baseline Typography into our SCSS package for the NCIDS.
This is for documenting typography as seen on the USWDS site. 

### Acceptance Criteria
Description of Design request:
Text color: $theme-color-base-ink ( as per USWDS default theme token for body copy )
https://designsystem.digital.gov/design-tokens/color/theme-tokens/

Headings (H1-6) Desktop views
H1: Poppins SemiBold 30px/40px line height
H2: Poppins SemiBold 26px/34px line height
H3: Poppins SemiBold 22px/29px line height
H4: Poppins SemiBold 20px/27px line height
H5: Poppins SemiBold 18px/25px line height
H6: Poppins SemiBold Italic 17px/24px line height

Headings (H1-6) Mobile views
H1: Poppins SemiBold 24px/32px line height
H2: Poppins SemiBold 22px/30px line height
H3: Poppins SemiBold 18px/26px line height
H4: Poppins SemiBold 16px/23px line height
H5: Poppins SemiBold 16px/23px line height
H6: Poppins SemiBold Italic 16px/23px line height

Body Copy Desktop & Mobile
Body: Open Sans Regular 16px/24px line height
Link: Open Sans Regular 16px/24px line height (token: cerulean.50)
UL: Open Sans Regular 16px/24px line height
OL: Open Sans Regular 16px/24px line height

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ]  Draft needed internal documentation (insert Notion link)
- [ ]  Publish completed component in DSM

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
@karlikpj can you please make sure we implemented all these styles and that this ticket is truly just creating documentation.

**Comment by karlikpj** [comment]
@bryanpizzillo We have the correct fonts / weights - however the headings and some body copy sizes need to be set for desktop / mobile.

**Comment by VictoriaSunNIH** [comment]
@arcepaul - would this documentation be folded into the larger implementation of USWDS discussion we've been having around all of the styles that USWDS is setting, and what NCI DS styles will be?

**Comment by VictoriaSunNIH** [comment]
Closing - documentation tasks are accounted for in #352
