### ISSUE TITLE
R2.4 Unmoderated User Testing

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1450]
**Description**
On 12/19/23 in our federal team weekly meeting, it was suggested that we consider unmoderated user testing after we launch the new Cancer Types landing page content that utilizes the R2.4 components. We agreed to launch with existing components but to consider testing to validate choices and path forward. Will need to evaluate what projects exist at a future date and assess if we want to move forward with this type of testing. 

**Sub-tasks**
 - [ ] To be determined based on ticket being adopted

**Comment by bennettcc** [comment]
Closing this ticket as no longer needed, we opened this ticket to initiate A/B testing on the Cancer type landing page: https://github.com/NCIOCPL/ncids/issues/1895
