### ISSUE TITLE
Update NCIDS icon buttons to match platform implementation

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#1458]
As an NCIDS developer, implement changes made to NCIDS icon buttons on platform to the icon button in the design system, so that anyone using icon buttons do not run into some of the issues with the current implementation.

- It was found with full width buttons on platform not enough room was given to the icon and the icon would awkwardly overlap the button label at certain breakpoints.  To combat this, assume that the label is in a span with a width that would accommodate an icon on either side.  This might only apply to full width icons, as the text for non full-width may be left aligned.
- A `float:left` is applied beginning at tablet:small, it needs to be applied from the get go for proper alignment

> **ESTIMATE** 2

**BEFORE applying float fix for lower breakpoints**
![Screenshot 2023-12-15 at 9 17 58 AM](https://github.com/NCIOCPL/ncids/assets/45469809/cf1fc0bb-5bd3-40a6-a4e2-6e73a03057c1)

**BEFORE full-width span fix:**
<img width="197" alt="Screenshot 2023-12-21 at 1 39 54 PM" src="https://github.com/NCIOCPL/ncids/assets/45469809/486b1e64-e4cd-4414-a6fa-8ef65ed3f865">

**AFTER full-width fix:** 
<img width="196" alt="Screenshot 2023-12-21 at 1 41 01 PM" src="https://github.com/NCIOCPL/ncids/assets/45469809/ecd748bd-1b73-474e-8477-1b518c643b10">

## Developer notes:
- Once implemented, be sure to remove the patch implemented on the platform.
**ncids-home-landing.scss**
```.usa-button--nci-icon.usa-button--nci-full-width {
	.usa-icon {
		float: left;
	}
	> span {
    display: inline-block;
		width: calc(100% - 48px);
	}
}
```

**Comment by andyvanavery31** [comment]
Please document changes that are made that are different from a USWDS resolution - see USWDS' ticket 5359
@olitharp-nci to define best practice for documenting these changes.

**Comment by dlescarbeau** [comment]
Created this ticket in digital platform to track the removal of the patch code 
https://github.com/NCIOCPL/cgov-digital-platform/issues/4242
