### ISSUE TITLE
Color documentation

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1471]
## Automate color documentation 

We've been hit a few times with colors in code not matching colors in documentation and Figma. We should automate the documentation to match the code as much as we can for quicker troubleshooting.

### Tasks
- [ ] Update documentation site - remove all hard coded values. Nothing should be left to user error.
- [ ] Storybook - we should have a color swatch/color page with regressions.

**Comment by sarinapadilla** [comment]
Closing this as it will be included in #1649.
