### ISSUE TITLE
CR: Change Primary Vivid Token to Cerulean-60v

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1479]
### Change Request
- Change $theme-color-primary-vivid to cerulean-60v
- Change $theme-link-color to $theme-color-primary-vivid
- Change the heading for nci-card to use $theme-link-color
   -  Use mixin `typeset-link`. Which also sets text-decoration. 

### What's the expected change?
- Change the requested colors to their requested updated color as described above

### What's the current functionality?
- The colors listed above are in their original color as indicated above

### Related Tickets
* Original Story Ticket #1473 
* Original Story Ticket #9999

**Comment by olitharp-nci** [comment]
Confirming I only found a component link issue in nci-card - please use the appropriate mixin instead here!
