### ISSUE TITLE
CR: Update the Color of Calendar Collections

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1484]
### Request Description
This request is to change the border, date, and month of the Calendar collections to use `accent-cool-dark`. The current calendar collections uses `primary-vivid` for the month, but the date and border use a different color.

### What's the expected change?
- The calendar collections icon will use `accent-cool-dark` for the month, date, and border

### What's the current functionality?
- The calendar collections icon uses `primary-vivid` for the month, but a different color for the date and border

### What's the updated acceptance criteria?
```gherkin
Scenario: A user views a Calendar collection component on the NCIDS
  Given the color of the calendar component icon has been updated
  Then the user will see that the color of the calendar icon (the border, month, and date) will use accent-cool-dark
```

### Tasks

- [x] Have proposed color change reviewed and approved by client

### Additional details / screenshot
- Current color
![image](https://github.com/NCIOCPL/ncids/assets/143126208/8b8a67fa-03b1-4ce2-85e9-711f39245889)

- Updated color
![image](https://github.com/NCIOCPL/ncids/assets/143126208/3cf17c0f-8c95-4923-8666-22b69e269e3d)

### Related Tickets
* Original Story Ticket #1149

**Comment by bennettcc** [comment]
Approval to proceed with this CR received from Anna on 1/30
