### ISSUE TITLE
Technical Implementation template

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#1494]
## Technical Solution

This will go into `ncids-js/usa-combo-box`. You will need to add `ncids-js/usa-combo-box` to both ncids-js/typedoc.json and package.json in the exports section.

### HTML

** Basic HTML **
(Before JS initializes)
```
```

Initialization Notes:
*

Initialization Flow:
*

### Component Options
*

### Data Attributes
*
 
### Public Component Methods
*

**Comment by sarinapadilla** [comment]
Bryan says to delete this ticket.
