### ISSUE TITLE
[R3 Discovery] UX Research

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1499]
**Description: Release** 3.1 will focus on the Mini Landing Pages on Cancer.gov and the microsites. Please develop a UX/User research plan to document our recommended approach to gather audience input on the current state of mini landing pages. In this plan, please include the types of questions/information we will need as an output and document the research mechanisms we should use to gather the needed data. The goal will be to share this plan with the Federal team by mid to the end of February. And begin executing the plan by mid March.

**Dependency:** Before this plan can be developed, we will need to complete:
- [x] IA Analysis of the current state and use of MLP's
- [x] Analytics analysis of current MLP use/interaction

**Current Tasks:** See ["Next Steps" document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Discovery/R3.x%20MLPs%20-%20Next%20Steps.docx?d=wa490b36a1b31425abc31d155a738eb26&csf=1&web=1&e=DsQefQ) for full timeline

Resources:
- Analytics data (https://tracker.nci.nih.gov/browse/CGOV-20444)
- ["Next Steps" outline document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Measurement%20%26%20Evaluation/R2.1%20Analytics%20-%20Next%20Steps.docx?d=wa490b36a1b31425abc31d155a738eb26&csf=1&web=1&e=Ohkett)

**Comment by laurelthrash** [comment]
Requested changes to stakeholder guide based on 03/18 sync with Anna:

- [ ] Move “Office of HIV and AIDS Malignancy” from alternate to required
- [ ] Consider inviting stakeholders to the interviews, or at least include in the findings readout 

Cc: @lizsiciliano @lburack @adrianacastaneda

**Comment by laurelthrash** [comment]
Readout completed on 05/07 which concludes the UX Research process. Closing this ticket.
