### ISSUE TITLE
CR: Adopt Documentation Site Padding and Margin Page to NCIDS Ownership

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1504]
### Request Description
This change request is to fully adopt the margin and padding utilities on the doc site from being a pointer to USWDS to our full ownership. This change will require:

- [x] First and foremost, we need to update the left nav to say "Margin and Padding". We also need to update the URL to be /margin-padding!
- [x] IA/development/design updates to the [doc site page](https://designsystem-dev.cancer.gov/develop/foundations/spacing-units/padding-margin) with all content needed using the new utility page template (created in #1593)
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [x] Developer updates to the code to adopt the margin and padding utilities within the NCIDS

### What's the expected change?
- The doc site is updated to show users how to fully use margin and madding utilities without pointing to USWDS
- The community Figma file will be updated to include the margin and madding utilities
- The NCIDS code will be updated to fully adopt the margin and padding utilities

### What's the current functionality?
- The doc site directs users to USWDS [Margin and Padding](https://designsystem.digital.gov/utilities/margin-and-padding/) utility page

### Related Tickets
* **Prerequisite:** #1593 
* Original Story Ticket #1208 
* Original PR #1257
* Related Ticket #934  

### Notes
Margin:
* `margin-horizontal` will need to be split into three different tables for 'margin/margin bottom`. 'margin/margin top`, and 'margin/margin top and bottom`
* `margin-vertical` will need to be split into three different tables for 'margin/margin bottom`. 'margin/margin top`, and 'margin/margin top and bottom`

**Comment by karlikpj** [comment]
Approach:

Based on USWDS - this would require a component based on [border/outline](https://github.com/NCIOCPL/ncids/pull/1751/files#diff-39affd0d922b2dc589b4bf2b66e8cbd6e550f2244b9d2702cb59dd9081732ea2), however I would also need a new DOM element inside the container used to show an element position offset caused by the style.

mock example DOM
```
<div class="{additional_example_classes} padding-8">
            <div class="{additional_example_classes}"></div>
</div>
```

Columns
- Class Name
- Calculated value
- Example Dom element

**Comment by bryanpizzillo** [comment]
@karlikpj I see where you are going with this, but `additional_example_classes` are NOT the same for the outer div as they are for the inner div.
