### ISSUE TITLE
Update documentation site Paragraph Styles page content to use Utility page template

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1506]
### Request Description
This change request is to fully adopt the Paragraph Styles typography on the NCIDS from being a pointer to USWDS to our full ownership. This change will require:

- [ ] IA/Design updates to the [Doc Site page](https://designsystem-dev.cancer.gov/develop/foundations/typography/paragraph-styles) with full instructions on use
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [ ] Developer updates to the code to adopt the Paragraph Styles typography within the NCIDS

### Important Notes
* The content on this page will use the paragraph styles comp on the [mural board](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1708713324713/8c29da52a2d2584c52555e5439d99047355482e2?sender=uc0870c1f8489401535da0005), and will use the utility page template outlined in #1593.
* * [Utilities spreadsheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Development%20and%20Testing/USWDS_Utilities.xlsx?d=waeac153a696a4419941b142cc9b627f1&csf=1&web=1&e=8THgYK)

### What's the expected change?
- The Doc Site is updated to show users how to fully use Paragraph Styles typography on the NCIDS Doc Site without pointing to USWDS
- The community Figma file will be updated to include the Paragraph Styles typography
- The NCIDS code will be updated to fully adopt the Paragraph Styles typography

### What's the current functionality?
- The NCIDS directs users to USWDS to use Padding and Margin tokens

### Related Tickets
* #1593

**Comment by laurelthrash** [comment]
Work on this ticket complete from design side for the time being. Closing this out on the Design board.
