### ISSUE TITLE
CR: Adopt documentation site Spacing Units page to NCIDS ownership

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1508]
### Request Description
This change request is to fully adopt spacing unit tokens within the NCIDS from being a pointer to USWDS to our full ownership. This change will require:

- [ ] IA/design updates to the [Spacing Units doc site page](https://designsystem-dev.cancer.gov/develop/foundations/spacing-units) with full instructions on use
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [ ] Developer updates to the code to adopt the spacing unit tokens within the NCIDS

### What's the expected change?
- The doc site is updated to show users how to fully use spacing unit tokens without pointing to USWDS
- The community Figma file will be updated to include the spacing unit tokens
- The NCIDS code will be updated to fully adopt the spacing unit tokens

### What's the current functionality?
- The doc site directs users to [USWDS](https://designsystem.digital.gov/design-tokens/spacing-units/) information on how to use spacing unit tokens.

### Related Tickets
* Original story: #1193 
* Related story: #1327

**Comment by karlikpj** [comment]
Approach - Copy BoxModel/Padding Demonstration Table and update with extra column to show "Multiple". Examples are only for the first set of tokens 0 - 15 positive. Named and Negative tokens have no example.

**Comment by adrianacastaneda** [comment]
@andyvanavery31 @bryanpizzillo @karlikpj Noting here my recommendation for the IA of this section based on what we discussed in our huddle.

- Create a navigational page called "Spacing." This page will be a child page of Foundations. The Spacing page will have three child pages: "Spacing Unit Tokens," "Height and Width," and "Margin and Padding."

- The Spacing navigational page will require a quick description of the page similar to how the Layout and Positioning page has a quick overview and it will link to the three child pages with a brief description for each page. 

**Note:** Within the Spacing Unit Tokens page, I recommend removing the H2 "Sizing Tokens" underneath the heading, if there won't be any other H2s on the page. It seems repetitive to me. **This recommend _only applies if_ the template can be manipulated.**
