### ISSUE TITLE
Add/update alt text for overview images on documentation site

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1518]
When initially creating the pages for the documentation site, alt text for the overview images was never included. Overview images do have alt text, but it isn't necessarily the most descriptive

We need to do an inventory of all of the overview images that need alt text, and add that to the documentation site. Then, update the identified alt text on the documentation site to match the recommended version shared via Teams document:

https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B598081C8-BEB9-4697-82BB-EFF60A1EB56F%7D&file=Doc%20Site%20-%20Component%20Alt%20Text%20Inventory.xlsx&action=default&mobileredirect=true

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: Alt text is set on overview images
  Given a user is viewing a component page on the documentation site
  When the user inspects the element or uses a screenreader
  Then the alt text is set for the image
    And the alt text is descriptive
```

### Resources:
Alt text inventory: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B598081C8-BEB9-4697-82BB-EFF60A1EB56F%7D&file=Doc%20Site%20-%20Component%20Alt%20Text%20Inventory.xlsx&action=default&mobileredirect=true

* Web Page: [Breadcrumb](https://designsystem-dev.cancer.gov/develop/components/breadcrumb) component page, where alt text is "Breadcrumb overview"

**Comment by blilianyu** [comment]
@dcvijanovic1k and I have proposed new [alt text for overview images](https://nih-my.sharepoint.com/:x:/r/personal/cvijanovicds_nih_gov/_layouts/15/doc2.aspx?sourcedoc=%7B83A4B6E8-B0E9-40A1-9BFF-BC891185EFE6%7D&file=Book.xlsx&action=editnew&mobileredirect=true&wdNewAndOpenCt=1709220816505&ct=1709220817040&wdOrigin=OFFICECOM-WEB.START.NEW&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=fb232043-7765-475a-87cf-2172ab5e8de3&cid=0204aa4e-6db9-41c2-9d42-b24add8e8a6e).

It is ready for IA review @lburack @adrianacastaneda. 
cc: @laurelthrash

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - per your comment in standup, here's the [new location for the alt text inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20-%20Component%20Alt%20Text%20Inventory.xlsx?d=w598081c8beb9469782bbeff60a1eb56f&csf=1&web=1&e=dfZj7q). Please let me know if you have any issues accessing it.

cc @blilianyu @adrianacastaneda @lburack

**Comment by laurelthrash** [comment]
@dcvijanovic1k - received, thank you! Assigning over to @adrianacastaneda @lburack for review.

**Comment by adrianacastaneda** [comment]
@laurelthrash Made a few edits but otherwise looks great to me! Thank you @blilianyu!

cc: @lburack

**Comment by laurelthrash** [comment]
Alt text approved from design side and included in ticket description. Closing ticket on design board to pass to developer board.
