### ISSUE TITLE
Footer component page documentation - code snippets missing js

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1529]
The footer example of the footer component page does not have working javascript. It is missing javascript in the page template. 

https://designsystem-dev.cancer.gov/develop/components/footer

**Comment by dcvijanovic1k** [comment]
Updated overview image with "Back to Top" added cc @dlescarbeau @bennettcc 
<img width="962" alt="footer_overview" src="https://github.com/NCIOCPL/ncids/assets/102183929/43c3400a-a3b2-4045-9260-89a043e2992a">
