### ISSUE TITLE
Design: Glossified Text

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#155]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: As a patient, I want to see the definition of a term so that I can understand the information I am consuming.

### Description of Design request:
Variation on the large modal USWDS component for glossified text.
##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Dotted underline on inactive, solid underline on hover, modal popup onclick with shaded background
2. Onclick of speaker icon in modal, play audio pronunciation 
3. Onclick of "x" icon, close modal

##

### Assets:
* Mockups: open modal: https://publicis.invisionapp.com/share/Z911EFKGEHJX#/455637973_Immunotherapy_To_Treat_Cancer_-_Desktop_Open_Modal
* Closed modal: https://publicis.invisionapp.com/share/K91112N9ZU28#/451997992_Immunotherapy_To_Treat_Cancer_
* Web Page: https://www.cancer.gov/about-cancer/treatment/types/immunotherapy 

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by mworrest** [comment]
Will use out of the box tooltip from USWDS.

**Comment by blilianyu** [comment]
This was approved in today's client demo.
