### ISSUE TITLE
Update display of .text-transparent class on Colors page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1565]
### Issue description
The Global Palette table on the Colors page is currently taking `transparent` too literally, and you can't see what the actual class name is.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://designsystem-dev.cancer.gov/develop/foundations/color
2. Scroll down to the Global Palettes section

### What's the expected result?
- You can see the `.text-transparent` class name.

### What's the actual result?
- You can't see the `.text-transparent` class name.

### Additional details / screenshot
<img width="314" alt="Screenshot 2024-02-28 at 6 00 38 PM" src="https://github.com/NCIOCPL/ncids/assets/24591940/538b105d-2da7-454e-8719-a856e964a485">

**Comment by olitharp-nci** [comment]
Work completed in #1648
