### ISSUE TITLE
Design: Embedded Images

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#157]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: WYSIWYG Components

### Description of Design request:
Determiner how images should display when embedded via WYSIWYG.  Includes things like:

- how will images display? what are the different sizes and alignments available for embedding? - Need to keep all templates. They are all in use.
- enlarge and how it displays - similar to infographic
- Is there still a need for regular image versus contextual image? - Yes. There are still ~1600 contextual images on cgov alone.

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Enlarge: Underline text on hover and open in new window.
2. Option to show or hide lead image on mobile. Default is shown.
3. All templates become full width at 640 and smaller

##

### Assets:
* Mockups: https://publicis.invisionapp.com/share/Y811ED07RWBT
* Web Page (Same style of infographic enlarge text currently): https://www.cancer.gov/about-nci/overview 

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by mworrest** [comment]
Created component ticket: https://github.com/NCIOCPL/ncids/issues/206

**Comment by VictoriaSunNIH** [comment]
Closing this as completed - handoff ticket has been written.

**Comment by blilianyu** [comment]
7/27 Client working session: Changed "View image" to "View larger image".
