### ISSUE TITLE
Storybook changes: Collection and summary box

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1574]
We need to add back collection and summary box passthroughs so we can better test for regressions when we update USWDS. 

- [ ] Add collection passthrough (exact copy of what we had before)
- [ ] Remove USWDS test cases from NCIDS collection
- [ ] Add summary box passthrough (exact copy of what we had before)

**Comment by sarinapadilla** [comment]
Closing since we have #1582 and #1592.
