### ISSUE TITLE
Design: Caption & Credit/Source Display

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#158]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: #157 Images, #161 Videos, #160 WYSIWYG Components

### Description of Design request:
Determine holistic approach for how captions should display on images, infographics and videos
Determine how credit/source displays on images (english and spanish versions)
##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Blog team wants to be able to add a link to the source to comply with CC license: https://www.cancer.gov/news-events/cancer-currents-blog/2021/prostate-cancer-psma-radiopharmaceutical-vision
2. Best practice: https://wiki.creativecommons.org/wiki/Best_practices_for_attribution  

##

### Assets:
* Mockups: https://publicis.invisionapp.com/share/Y811ED07RWBT
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by mworrest** [comment]
Created component ticket: https://github.com/NCIOCPL/ncids/issues/206

**Comment by VictoriaSunNIH** [comment]
Closing as a component ticket has been written
