### ISSUE TITLE
Update storybook structure for usa-footer

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1584]
### `usa-footer` storybook structure
**Note**: NCI Big is our default, so we do not have a default folder

* 📁 Variants
  * 📁 NCI Big
    *  English
    * Spanish
  * 📁 Test Cases
    * No JS
    * Back to top
    

**Notes:** 
1. Test case > No JS: The back to top before it any javascript is initialized 
2. Test case > Back to top: The footer with lorem ipsum to add height to the viewport. This would allow us to do an onscroll to enable the back to top visibility.
3. NCI Big > English/Spanish would not show a back top top as it would not be the "scrolling" behavior. 

Other tasks:
* Clean up all of the regressions (redundant breakpoint scenarios) associated with this component
* Create ncids-twig template
* Make sure scenarios still reflect all of the test cases that we have, but we do not need them as examples in the storybook structure
* Clean up usa-footer > usa-error-message styles inside of the footer stylesheet and make use of `usa-error-message--nci-inverse` class
* And again, confirm there are no utility classes in the footer html, again.

> **ESTIMATE** TBD

### Additional details / screenshot
- [Storybook structure wiki](https://github.com/NCIOCPL/ncids/wiki/Storybook-Structure)

### Related Tickets
* Parent ticket: #1224

**Comment by olitharp-nci** [comment]
After some discussion with Bryan and Derek, I have made an updated request for the Storybook links. All notes are in the ticket, but I wanted to call out that this decision needed to be made due to enabling javascript on this component. It made testing for back to top a little tricky with how the regressions were laid out before. ✌️
