### ISSUE TITLE
NCIDS Documentation Site Remove Design Principles Page

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1598]
_Parent ticket: #942_

### Change Request
This content change request was established via #942 . 

### What's the expected change?
- Remove the ["Design Principles"](https://designsystem-dev.cancer.gov/develop/design-principles/) page from the Documentation Site and remove it from the primary navigation. This will remove the whole page and page content, including the page from the megamenu.
* Remove "Explore our Design Philosophy" link and associated text on the [home page](https://designsystem-dev.cancer.gov/develop/) of the doc site
* Remove "Design Principles" link in the footer of the doc site

### What's the current functionality?
- The ["Design Principles"](https://designsystem-dev.cancer.gov/develop/design-principles/) page exists on the Documentation Site and appears in the primary navigation.
- The "Explore our Design Philosophy" link on the home page of the Documentation Site links to the Design Principles page.
- The "Design Principles" link in the Documentation Site footer exists.

**Comment by laurelthrash** [comment]
Adding the the developer board as this requires an update to the Documentation Site primary navigation. Cc: @bennettcc @sarinapadilla

**Comment by sarinapadilla** [comment]
Added this to the requirements above, but we will also be removing:
* "Explore our Design Philosophy" link and associated text on the home page of the doc site
* "Design Principles" link in the footer of the doc site
