### ISSUE TITLE
Design: Embedded Infographics

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#160]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: WYSIWYG Components

### Description of Design request:
Determine how infographics should display when embedded via the wysiwyg.  This includes:
- Infographic (associated crop for display?)
- Sizes and alignment of display
- linking to "full infographic"

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Enlarge: Underline text on hover and open in new window.
2. All templates become full width at 640 and smaller
3. If mobile infographic is available, it will be swapped out at 640 and smaller

##

### Assets:
* Mockups: https://publicis.invisionapp.com/share/XE11GNWSACWZ
* Web Page: https://www.cancer.gov/about-nci/overview

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by blilianyu** [comment]
8/6 Demo: Changed "View and print infographic" to "View/print infographic".
