### ISSUE TITLE
CR: Update the Overview Image of Card on NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1633]
### Request Description
Due to the update of the colors on NCIDS, the Overview Image on the Card page on the NCIDS Documentation site has the wrong color displayed for the blue, linked title of the card. This request is to create a new image with the correct color, and then to update the NCIDS Documentation Site with the new image.

### What's the expected change?
- Overview Image of the Card on the NCIDS Documentation site is to be updated to have the correct color of the title

### What's the current functionality?
- The current Overview Image of the Card on the NCIDS Documentation site has an outdated color of the title

### What's the updated acceptance criteria?
```gherkin
Scenario: A user visits the NCIDS Documentation site and views the Card page
  Given as user is on the NCIDS Documentation site
    And the user is on the Card Page under Components
    And they are viewing the Overview Image
  When the user views the Overview Image
  Then the color of the title of the card will match the current color (hex code: #01679d)
```

### Additional details / screenshot
- Current Overview Image
![image](https://github.com/NCIOCPL/ncids/assets/143126208/8f2a5ef8-63d7-4fb4-8a7a-2f17924689bb)

- Correct Title Color Example
![image](https://github.com/NCIOCPL/ncids/assets/143126208/905c247b-26fa-48e1-b77b-a0e009ecf8d7)

### Related Tickets
* Original Story Ticket #1479

**Comment by laurelthrash** [comment]
Assigning over to @blilianyu @monika-jaeger - please pick up when you become available. Thanks!

**Comment by blilianyu** [comment]
Updated overview image attached. 
![card](https://github.com/NCIOCPL/ncids/assets/51677926/7b0ef803-c343-4924-bf2c-7cff9a0633d0)

cc: @monika-jaeger @laurelthrash
