### ISSUE TITLE
CR: Update the Overview Image of Guide Card on NCIDS Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1634]
### Request Description
Due to the update of the colors on NCIDS, the Overview Image on the Guide Card page on the NCIDS Documentation site has the wrong color displayed for the outline buttons on the card. This request is to create a new image with the correct color, and then to update the NCIDS Documentation Site with the new image.

### What's the expected change?
- Overview Image of the Guide Card on the NCIDS Documentation site is to be updated to have the correct color of the outline buttons

### What's the current functionality?
- The current Overview Image of the Guide Card on the NCIDS Documentation site has an outdated color of the outline buttons

### What's the updated acceptance criteria?
```gherkin
Scenario: A user visits the NCIDS Documentation site and views the Guide Card page
  Given as user is on the NCIDS Documentation site
    And the user is on the Guide Card Page under Components
    And they are viewing the Overview Image
  When the user views the Overview Image
  Then the color of the outline buttons of the card will match the current color (hex code: #298085)
```

### Additional details / screenshot
- Current Overview Image
![image](https://github.com/NCIOCPL/ncids/assets/143126208/79651abc-c6cb-4321-a54b-c9199808a09a)

- Updated Color Example
![image](https://github.com/NCIOCPL/ncids/assets/143126208/56cecc6b-c34a-4dc0-9545-97283f8b7be9)

### Related Tickets
* Original Story Ticket #1479

**Comment by laurelthrash** [comment]
Assigning over to @blilianyu @monika-jaeger - please pick up when you become available. Thanks!

**Comment by monika-jaeger** [comment]
Button outline color updated to current color (hex code: #298085). Reference in Figma [here](https://www.figma.com/file/8qu1psEjnehVDoZyWrH7ny/NCIDS-For-All?type=design&node-id=762%3A9327&mode=design&t=1xEFkoebSVhMobRG-1). Image for placement in code is also attached.

cc: @blilianyu @laurelthrash 
![component sample](https://github.com/NCIOCPL/ncids/assets/109552399/8ec5bdae-80de-49c5-827c-95126798d1f1)
