### ISSUE TITLE
CR: Update Guide Card Row Templates Page

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#1641]
### Issue description
On the Guide Card Row page (https://designsystem-dev.cancer.gov/develop/templates/guide-card-row). The 2-Guide Card Row overview image and code snippets shows the same number of buttons.

### What's the expected change?
- 2 guide card row overview image card 2 will have 4 buttons
- [Guide Card with Image & Description Component preview](https://designsystem-dev.cancer.gov/develop/templates/guide-card-row#guide-card-with-image-and-description) card 1 to have 6 buttons  
- [Guide Card without Image & Description Component preview](https://designsystem-dev.cancer.gov/develop/templates/guide-card-row#guide-card-without-image-and-description) card 1 to have 6 buttons and card 2 to have 2 buttons 

### What's the current functionality?
- The current overview image of the 2 Guide Card Row Pattern has equal number of buttons
- Component previews have equal number of buttons

### What's the updated acceptance criteria?
```gherkin
Scenario: A user visits the NCIDS Documentation site and views the Guide Card Row page
  Given as user is on the NCIDS Documentation site
    And the user is on the Guide Card Row Page under Templates
    And they are viewing the Overview Image for 2 guide card row pattern
      Then the first card will have 6 buttons
      Then the second card will have 4 buttons
    And when the user views the Component Preview for Guide Card with image and description
       Then the first card will have 6 buttons
        And the second card will have 4 buttons
    And when the user views the Component Preview for Guide Card without image and description
        Then the first card will have 6 buttons
        And the second card will have 2 buttons
        And the third card will have 4 buttons
```

### Additional details / screenshot
- 2 Guide Card Row Pattern image 
<img width="705" alt="Screenshot 2024-04-05 at 3 15 43 PM" src="https://github.com/NCIOCPL/ncids/assets/51677926/ca8d7240-844d-4c9e-80ff-99b8b3042095">

- Guide Card with image and description component preview
<img width="974" alt="Screenshot 2024-04-05 at 3 23 51 PM" src="https://github.com/NCIOCPL/ncids/assets/51677926/0b9f31ef-a0b5-477a-aa45-e1326287fc54">

- Guide Card without image and description component preview
<img width="904" alt="Screenshot 2024-04-05 at 3 23 59 PM" src="https://github.com/NCIOCPL/ncids/assets/51677926/42cefa9f-049a-492b-b31b-d7f8cd0dc07a">

### Related Tickets
* #1372

**Comment by laurelthrash** [comment]
Proceeding with this change. Assigning over to @blilianyu and adding to "Ready for Pickup" on the design board.

**Comment by monika-jaeger** [comment]
Moving this comment from the discussions ticket to here with the examples started.
Updated Overview image for team discussion [linked here](https://www.figma.com/file/8qu1psEjnehVDoZyWrH7ny/NCIDS-For-All?type=design&node-id=762%3A9327&mode=design&t=xW5MDJS4hgEDajLI-1). (scroll down to patterns)
This has one link removed from the right guide card to show the left card having 6 links and the right guide card having 4 links.
cc: @blilianyu @laurelthrash
