### ISSUE TITLE
Dev Task: Update section nav tree

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#165]
Update section nav tree to filter out "cousins" from current code

**Parent Issue:** #9999

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
This has been updated on the Gatsby prototype.
