### ISSUE TITLE
Dev Task: Build out content type templates 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#166]
Build out content type templates for home/landing pages, articles, blog series and mini landing pages.

For blog series and mini landing pages, please just display the title of the content on the page.  For home/landing pages and articles, show the content as it is right now in Gatsby.

**Parent Issue:** #9999

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
This has been done on the gatsby prototype. All content types should appear now.
