### ISSUE TITLE
Create annotated feedback for MCA Explorer Pilot Team

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1661]
Please create an annotated comp of the MCA Explorer dev page to relay the following feedback:

1.	Required: Please use the NCIDS Banner component: https://designsystem-dev.cancer.gov/develop/components/banner
2.	Required: Please use the NCIDS Header component: https://designsystem-dev.cancer.gov/develop/components/header/
3.	Required: Please use the NCIDS Footer component: https://designsystem-dev.cancer.gov/develop/components/footer
4.	Required: Need updated blended logo (MCA Explorer team can coordinate with Anna to get updated blended logo)
5.	Recommendation: Use the NCIDS fonts across the main navigation and body content: https://designsystem-dev.cancer.gov/develop/foundations/typography/fonts
6.	Recommendation: Use a Hero or Promo Block component for the mosaic chromosomal alteration explorer featured element

- https://designsystem-dev.cancer.gov/develop/components/hero

- https://designsystem-dev.cancer.gov/develop/components/promo-block

7.	Recommendation: Use NCIDS buttons: https://designsystem-dev.cancer.gov/develop/components/button
8.	See example site repo link; this includes project starter code examples that your team can leverage: https://github.com/NCIOCPL/ncids-example-sites

Dev site: https://mcaexplorer-dev.cancer.gov/#/ (must be logged into vpn)

These annotations will be sent to Anna for her review and additions, then sent to the MCA team

**Comment by blilianyu** [comment]
@bennettcc Here is the updated DCEG Desktop & Mobile blended logos 
![Logo_DCEG](https://github.com/NCIOCPL/ncids/assets/51677926/7c2475c5-c39a-4b89-bca6-6cde31ceebb0)

![Logo_DCEG_Mobile](https://github.com/NCIOCPL/ncids/assets/51677926/6a14dea0-ae9e-433f-8865-68969320132e)

**Comment by bennettcc** [comment]
Closing this ticket - the heuristic review was sent to MCA explorer after Anna review
