### ISSUE TITLE
Update documentation site Shadow page content to use Utility page template

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1665]
### Request Description
This change request is update the Shadow page on the NCIDS from only having basic information about shadow tokens to using our Utility page template.

- [ ] IA/Design updates to the [Shadow doc site page](https://designsystem-dev.cancer.gov/develop/foundations/appearance/shadow) with full instructions on use
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [x] Developer updates to the code to adopt Shadow within the NCIDS

### Important Notes
* The content on this page will use the utility page template outlined in #1593.
* [Utilities spreadsheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Development%20and%20Testing/USWDS_Utilities.xlsx?d=waeac153a696a4419941b142cc9b627f1&csf=1&web=1&e=8THgYK)
* [USWDS Shadow page](https://designsystem.digital.gov/utilities/shadow/)

### What's the expected change?
- The Doc Site is updated to show users how to fully use shadow utilities/tokens on the NCIDS Doc Site without pointing to USWDS
  - The existing tokens will be included on the page
- The community Figma file will be updated to include shadow utilities/tokens
- The NCIDS code will be updated to fully adopt shadow utilities/tokens

### What's the current functionality?
- The NCIDS has some information on Shadow tokens and updates from USWDS.

### Related Tickets
* #1593

**Comment by karlikpj** [comment]
Approach would be to use the box-model demonstration component as its look and columns match that of outline or border.
