### ISSUE TITLE
Update documentation site Font Size & Family page content to use Utility page template

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1666]
### Request Description
This change request is update the Font Size & Family page on the NCIDS from only having basic information about font tokens/utilities to using our Utility page template.

- [ ] IA/Design updates to the [Font Size & Family doc site page](https://designsystem-dev.cancer.gov/develop/foundations/typography/fonts) with full instructions on use
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [ ] Developer updates to the code to adopt Font Size & Family tokens/utilities within the NCIDS

### Important Notes
* The content on this page will use the utility page template outlined in #1593.
* [Utilities spreadsheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Development%20and%20Testing/USWDS_Utilities.xlsx?d=waeac153a696a4419941b142cc9b627f1&csf=1&web=1&e=8THgYK)
* [USWDS Font Size & Family page](https://designsystem.digital.gov/utilities/font-size-and-family/)

### What's the expected change?
- The Doc Site is updated to show users how to fully use font size & family tokens/utilities on the NCIDS Doc Site without pointing to USWDS
- The community Figma file will be updated to include font size & family tokens/utilities 
- The NCIDS code will be updated to fully adopt font size & family tokens/utilities 

### What's the current functionality?
- The NCIDS has some information on font size & family tokens.

### Related Tickets
* #1593

**Comment by karlikpj** [comment]
My Approach would be to use the existing TextDemonstration module for this page, no new components needed.

**Comment by bennettcc** [comment]
As discussed on 6/18 standup, Paul has questions for Bryan on this ticket before building up the PR. Will put it on pause and start the approach work for https://github.com/NCIOCPL/ncids/issues/1504
