### ISSUE TITLE
Update documentation site Text Styles page content to use Utility page template

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1667]
### Request Description
This change request is update the Text Styles page on the NCIDS from only having basic information about text style tokens/utilities to using our Utility page template.

- [ ] IA/Design updates to the [Text Styles doc site page](https://designsystem-dev.cancer.gov/develop/foundations/color) with full instructions on use
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [ ] Developer updates to the code to adopt text styles tokens/utilities within the NCIDS

### Important Notes
* The content on this page will use the utility page template outlined in #1593.
* [Utilities spreadsheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Development%20and%20Testing/USWDS_Utilities.xlsx?d=waeac153a696a4419941b142cc9b627f1&csf=1&web=1&e=8THgYK)
* [USWDS Text Styles page](https://designsystem.digital.gov/utilities/text-styles/)

### What's the expected change?
- The Doc Site is updated to show users how to fully use text style tokens/utilities on the NCIDS Doc Site without pointing to USWDS
- The community Figma file will be updated to include text style tokens/utilities 
- The NCIDS code will be updated to fully adopt text style tokens/utilities 

### What's the current functionality?
- The NCIDS has some information on text style tokens.

### Related Tickets
* #1593
* #1340

**Comment by dlescarbeau** [comment]
I think Text Styles and Border can actually share factory components, specifically for the color decoration stuff of Text Styles/Border colors, as well as for the simple display of the class name and example/calculated value for `letter-spacing` and `font-weight` and other text styles with simple display values.

Comment on Border page with approach: https://github.com/NCIOCPL/ncids/issues/1505#issuecomment-2145670896

**Comment by karlikpj** [comment]
**Approach:**
My thought here is that we should create 3 new display table components.

**Vertical Alignment:**
Will display an example text line, then a required class name,  a 2px high div floats between them that shows a visual result of the css alignment.
[USWDS Text Styles](https://designsystem.digital.gov/utilities/text-styles/#vertical-align)

**Whitespace:**
Will display an example text line, then a required class name,  a 2px high div floats between them that shows a visual result of the css alignment.
[USWDS Text Styles](https://designsystem.digital.gov/utilities/text-styles/#whitespace)

**Tabular Numerals:**
Will display an example numeric text block made of 3 lines of numbers xxx,xxx,xxx
Below that is the required class name in a gray box
[USWDS Text Styles](https://designsystem.digital.gov/utilities/text-styles/#font-feature-settings)
