### ISSUE TITLE
Atomic Component: Page Options

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#170]
### Handoff of page options component from design to development

> **ESTIMATE** TBD

### Acceptance Criteria
*Include specs:  List of colors (hex, token name), variants, and states.* 

### Acceptance Criteria

```gherkin
Scenario: User wants to share a c.gov page on desktop
  Given User is on a c.gov page on desktop
  Then the print and email icons show in the top right under the main nav and above the footer on the right
    And allow the user to print or email page
```

```gherkin
Scenario: User wants to share a c.gov page on mobile
  Given User is on a c.gov page on mobile
  Then no icons appear for sharing options
```

### Resources:
* Design ticket: https://github.com/NCIOCPL/ncids/issues/27
* Mockups: https://publicis.invisionapp.com/share/MW1112N6286R#/451934895_What_Is_Cancer-
* https://publicis.invisionapp.com/share/3C10NGGUXTYQ#/450524508_Mobile_-_Longest_Breadcrumb

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ]  Draft needed internal documentation (insert Notion link)
- [ ]  Publish completed component in DSM

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
@mworrest , @blilianyu  - please fill out the new component ticket form for this one

**Comment by blilianyu** [comment]
@VictoriaSunNIH  new component ticket has been created #215
