### ISSUE TITLE
Atomic Component: Header

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#171]
### Handoff of header component from design to development

> **ESTIMATE** TBD

### Acceptance Criteria
*Include specs:  List of colors (hex, token name), variants, and states.* 

### Acceptance Criteria
- desktop logo display, with search 
- on mobile, search is in a different location (not in the menu)
- Secondary links above the search bar can be ignored, as they will not be used on our site.
- links are on click, and to get to the landing page, will need to click "explore" link

```gherkin
Scenario: User is on c.gov page with USA banner
  Given the user is on c.gov page
  Then the USA banner will appear at the very top
```

```gherkin
Scenario: User is on c.gov clicking on language toggle (AC's specified here: https://github.com/NCIOCPL/ncids/issues/164)
  Given User is on a c.gov page with a translation equivalent
  When they click on the language toggle link
  Then the translation for that page will load
     And the label will change to the opposite language
```

```gherkin
Scenario: User is on c.gov clicking on language toggle on mobile
  Given User is on screen 1023px and smaller
     And User is on a c.gov page with a translation equivalent
  Then a pipe will appear between USA text and language toggle text
     And when clicked label will change to the opposite language
```

```gherkin
Scenario: User is on a c.gov page with Covid banner
  Given User is on a c.gov page
  Then the Covid banner will appear beneath the USA banner
```

```gherkin
Scenario: User is on c.gov clicking on logo
  Given User is on c.gov 
  When they click on the logo
  Then the homepage loads
```

```gherkin
Scenario: User is using Search on desktop
  Given the user is on a screen size 1024px and larger
  When the user clicks on the search box
  Then they will be able to enter text
     And autosuggest up to 10 items show
  When the user presses enter or clicks on the search icon
  Then the user will be taken to a search results page
  When the user clicks on suggested item and clicks on the search icon
  Then the user will be taken to a search results page
```

```gherkin
Scenario: User is using Search on Mobile
  Given the user is on a screen size 1023px or less
  Then the search box appears on the right of the Menu button
  When the user clicks on the search box
  Then they will be able to enter text
     And autosuggest up to 10 items show
  When the user presses enter or clicks on the search icon
  Then the user will be taken to a search results page
  When the user clicks on suggested item and clicks on the search icon
  Then the user will be taken to a search results page
```

```gherkin
Scenario: User is activating the megamenu
  Given user is on c.gov on desktop
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
     And the L1 will be highlighted in the main nav
     And the caret for the L1 will flip to point upwards
  When the user hovers on any link in the megamenu
  Then the link will receive an underline
  When the user clicks on the L1 item that appears in the megamenu ("Explore L1")
  Then the landing page will load
     And the megamenu will close
     And an indicator will appear in the main nav under that L1
  When an L2 is clicked on 
  Then the page will load
     And the megamenu will close
     And an indicator will appear in the main nav under the L1 parent
  When an L3 is clicked on 
  Then the page will load
     And the megamenu will close
     And an indicator will appear in the main nav under the L1 parent
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
  When the user clicks outside of the megamenu overlay or on the L1 again
  Then the megamenu will close
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
  When another L1 is clicked on
  Then the megamenu for that L1 will appear below 
```

```gherkin
Scenario: User is on mobile looking for menu
  Given User is a screen size 1023px or less
  Then the Menu button will appear on the left below the logo
```

### Resources:
Clickable prototypes (activate menus for looks and feel):
* Desktop: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062769_Header_-_Footer_-_Desktop
* Mobile: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454145716_Header_-_Footer_-_Mobile_V2

### Notes

*Interactions:*

* Desktop: megamenu is activated on click and user gets to L1 page by clicking "Explore L1 item" in megamenu.
* All text in megamenu is clickable and gets underline on hover
* Megamenu can be closed on click of L1 again or anywhere outside of the megamenu overlay.

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ]  Draft needed internal documentation (insert Notion link)
- [ ]  Publish completed component in DSM

### Notion documentation:
- [ ]  Include information from Notion here

**Comment by karlikpj** [comment]
* Nothing on Guidance/Usage for this component? or the specific atomic components.
* Can we get just the footer in an invision comp | / without all the other stuff we're not building.
* What grid are we using here (ok with anything) but not matching up to USWDS defaults.. if we're using another - than what is the size/breakpoints etc..
* Questions about font's in this area.. currently we only implemented light/normal/bold in Poppins as per ticket - but header shows it as semibold?
https://github.com/NCIOCPL/ncids/issues/91

**Comment by blilianyu** [comment]
@karlikpj 
- Guidance/usage we can hold off on for now. I don't think we've have anything yet.. 
- I've updated the wireframes so that it's only showing the header and footer. 
- For grid, we're using whatever is the USWDS sketch template. We haven't changed any of the breakpoints.
- We'd like to also have semi bold for Poppins. Can we add that or should that be a different ticket?

**Comment by karlikpj** [comment]
@blilianyu 
* Grid - Cool, we'll use that as the default - gutters/padding and any changes we can do once we see the whole page to tweak! 
* Guidance - will be FPO for now! (reminder to make separate ticket for that)

**Comment by VictoriaSunNIH** [comment]
Closing this as covered in #205
