### ISSUE TITLE
[R3 Analytics] MLP Analytics Prep - Update Tagging for Existing Components

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1725]
**Description:** Analytics team preparing for R3/MLP analytics. Primary tasks for this are tracked in the analytics Jira queue, but also represented on this board for context and overlap with Redesign project work.

This ticket represents work by the Analytics team to tag existing MLP components to have data to better track against following the launch of MLP components.

Related tickets:
- [CGOV-21385](https://tracker.nci.nih.gov/browse/CGOV-21385)
- [CGOV-21386](https://tracker.nci.nih.gov/browse/CGOV-21386)
- [CGOV-21387](https://tracker.nci.nih.gov/browse/CGOV-21387)
- [CGOV-21388](https://tracker.nci.nih.gov/browse/CGOV-21388)
- [CGOV-21393](https://tracker.nci.nih.gov/browse/CGOV-21393)

**Comment by laurelthrash** [comment]
Joe/Nicole/Bryan discussing how to address all tickets vs. individual tickets.

**Comment by laurelthrash** [comment]
Testing in progress for this ticket. Next steps: write rules in Adobe. Adding to "on hold" for the time being until Joe is available to assist with next steps.

**Comment by welshja** [comment]
Tagging updated to collect "pre" data for MLP pages. Closing this ticket.
