### ISSUE TITLE
Update Foundations page with copy edit recommendations

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1727]
Please update the Foundations page with the updates listed in tracked changes from the copy edit review:

https://designsystem-dev.cancer.gov/develop/foundations/

Foundations document: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7Ba777125a-00e2-4367-add5-1b0ef14d1795%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk_ns.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1717712444611&web=1

**Comment by laurelthrash** [comment]
Blocked by #1747
