### ISSUE TITLE
Update Get Started Documentation Site Content

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1728]
Please update the Get Started page with the updates listed in tracked changes from the copy edit review:

https://designsystem-dev.cancer.gov/develop/get-started/

Get Started document: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot_Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Copy%20Editing%20Feedback/Get%20Started%20with%20NCIDS_MM.docx?d=wd06e089eb7bf4d2b9cd63455bfba734b&csf=1&web=1&e=6ehAEe

**Comment by laurelthrash** [comment]
Blocked by #1747
