### ISSUE TITLE
Atomic Component: Intro Text

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#173]
### Handoff of intro text component from design to development

> **ESTIMATE** TBD

### Acceptance Criteria
*Include specs:  List of colors (hex, token name), variants, and states.* 

### Acceptance Criteria

```gherkin
Scenario: Intro text is populated
  Given the CMS user populates the intro text field
  Then the intro text shows on the page
```

### Resources:
* Mockups: https://publicis.invisionapp.com/share/MH10XGEY5QCV#/451376122_visual-Inventory-Article-USWDS-Components-In-Ncids-Styles

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ]  Draft needed internal documentation (insert Notion link)
- [ ]  Publish completed component in DSM

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
@mworrest , @blilianyu  - please fill out the new component ticket form for this one

**Comment by blilianyu** [comment]
@VictoriaSunNIH @mworrest new component ticket has been created #216
