### ISSUE TITLE
Atomic Component: Public Use and Syndication

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#174]
### Handoff of Public Use and Syndication component from design to development

> **ESTIMATE** TBD

### Acceptance Criteria
*Include specs:  List of colors (hex, token name), variants, and states.* 

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Mockups: https://publicis.invisionapp.com/share/MW1112N6286R#/451934895_What_Is_Cancer-

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ]  Draft needed internal documentation (insert Notion link)
- [ ]  Publish completed component in DSM

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
@mworrest , @blilianyu  - please fill out the new component ticket form for this one

**Comment by blilianyu** [comment]
@VictoriaSunNIH @mworrest New component ticket has been created #218
