### ISSUE TITLE
Update 'Applying other utilities' paragraph on Figma Guide page on Doc Site 

### ISSUE THREAD

**Issue by monika-jaeger** [NCIOCPL/ncids#1761]
### Issue description

Update copy on the doc site on the [Figma Guide](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide) page under the paragraph heading "[Applying other utilities that are not added to the NCIDS Design Kit library](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide#applying-other-utilities-that-are-not-added-to-the-ncids-design-kit-library)" to add more clarity that border, border radius and outline are utilities that can only be referenced in Figma, especially when linking from other areas in the doc site.

> **ESTIMATE** TBD

### What's the expected change?
Update heading and paragraph to read:

> #### Border, Border Radius and Outline Utilities 
> Not all utilities are available in the NCIDS Design Kit Library, which appears on the right-hand sidebar when you are designing a composition or prototype. Reference the [Tokens and Utilities](https://www.figma.com/community/file/1288512334920909770/ncids-design-kit) page in our Figma file to learn how to apply border, border radius and outline utilities to your designs.

### What's the current functionality?
Current heading and paragraph reads:

> #### Applying other utilities that are not added to the NCIDS Design Kit library
> On the Tokens and Utilities page you will see other utilities you can apply that are not added to the NCIDS Design Kit Library on the right-hand side bar when you are designing a composition or prototype. Border, border radius and outline are all utilities that can be referenced on this page on how to apply these styles to your designs.

### What's the updated acceptance criteria?
The copy is updated per the expected change.

### Related Tickets
* This came out of discussions from PR Ticket #1751

**Comment by monika-jaeger** [comment]
We will want UX/IA's to review this copy before working on this CR.
cc: @blilianyu @adrianacastaneda

**Comment by monika-jaeger** [comment]
@blilianyu and @adrianacastaneda / @lburack can you please review this copy or see anything missing? It's a small change to add clarity that utility parameters are referenced in Figma for designers since this paragraph is linked to in other areas of the doc site. Thanks!

**Comment by blilianyu** [comment]
@monika-jaeger this looks good to me! Do we want to link "Token & Utilities" to our Figma token page (https://www.figma.com/design/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?node-id=3917-6868&t=49CxxhdnTlFZ1EGh-1) like how we do for individual components?

**Comment by adrianacastaneda** [comment]
@monika-jaeger made a few changes below and agreed that we should link if it makes sense to you too! 

- Change heading from "Applying other utilities that are not added to the NCIDS Design Kit library" to "Border, Border Radius and Outline Utilities"

- Not all utilities are available in the NCIDS Design Kit Library, which appears on the right-hand sidebar when you are designing a composition or prototype. Reference the Token & Utilities page in our Figma file to learn how to apply border, border radius and outline utilities to your designs

cc: @laurelthrash

**Comment by monika-jaeger** [comment]
@adrianacastaneda @blilianyu 

Thank you! Updated the copy with both of your feedback. 
Changes are in the description above, and also below for reference.

> #### Border, Border Radius and Outline Utilities 
> Not all utilities are available in the NCIDS Design Kit Library, which appears on the right-hand sidebar when you are designing a composition or prototype. Reference the [Tokens and Utilities](https://www.figma.com/community/file/1288512334920909770/ncids-design-kit) page in our Figma file to learn how to apply border, border radius and outline utilities to your designs.

If all looks good, this change can be made to the doc site.
cc: @laurelthrash @lburack

**Comment by laurelthrash** [comment]
Confirmed alignment on language during standup. Assigning over to @blilianyu @monika-jaeger to please proceed with the content update to the Doc Site with the updated language.
