### ISSUE TITLE
Site wide search on the NCIDS Documentation Site

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1780]
In a 7/9 discussion with Anna, she requested that we develop an approach to design and build site wide search functionality into the NCIDS documentation site. https://designsystem-dev.cancer.gov/develop/

Per OCPL guidance (that we enforce across DOC sites) - every NCI owned site and application is required to have search capabilities.

This ticket is to capture that request; we'll need to determine an approach for indexing documentation site content as well as the interaction of search + search results on the documentation site.

This functionality is not required by go live of the documentation site, targeting 7/12.

~~The design system web pages should not appear in the NCI-wide search on cancer.gov.~~ It was decided 7/10/2024 that the design system site is a public site and should appear in NCI-wide search.

### Requirements
**Functional Requirements**
- The documentation search function shall only search through the NCIDS Documentation Site
- The results from the documentation search function shall only display results from content existing on the NCIDS Documentation Site

**Visual Requirements**
- The documentation search function shall appear to the users like the 
- The documentation search shall utilize NCIDS/USWDS styling

### Specifications

- The documentation search function will work like the PCP site
   - Layout template: https://github.com/NCIOCPL/gatsby-pcp/blob/develop/src/pages/search.js
- Use the site wide search app module

### DoR Tasks

- [ ] Create a PR that brings in the site wide search app module onto the Documentation Site without styling
- [ ] Review the PR with the unstyled app module and results with the Designers (@blilianyu and @monika-jaeger)
- [ ] Acceptance Criteria Drafted
- [ ] Acceptance Criteria Reviewed
  - [ ] Developer Review
  - [ ] IA Review
- [ ] Acceptance Criteria Approved
  - [ ] Developer Approval
  - [ ] IA Approval

### DoD Tasks

- [ ] PR Review (see PR for review and comments)
- [ ] Client Review with Demo

**Comment by welshja** [comment]
In talking to Bryan, this will need to involve:
* Sitewide search app needs a configuration setting to exclude certain URLs (to not crawl design system) (basically the opposite of this ticket: https://github.com/NCIOCPL/sitewide-search-api/issues/85) 
* Add sitewide search bar on Documentation site and setup search results page
* Add the documentation site into the seed list for the sitewide search crawler. Create ticket in https://github.com/NCIOCPL/sitewide-search-crawler (this will need to come after the exclusion configuration is added into the app)

This ticket is focused on the second bullet, but we should consider all these elements.

**Comment by bryanpizzillo** [comment]
@welshja We don't need to worry about excluding the designsystem site from the NCI-wide search results.
