### ISSUE TITLE
Enabler: Add analytics to Documentation Site

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#1781]
# Add analytics to Documentation Site
> **ESTIMATE** TBD

We need to add analytics to the documentation site. This should use our DOC Basic Property script, `<script src="https://assets.adobedtm.com/6a4249cd0a2c/785de09de161/launch-70d67a6a40a8.min.js" async></script>`.  This should be added to all layout pages, ~~as well as the 404 page~~. (We will not worry about the 404 page for now)

**Comment by welshja** [comment]
Updated Launch to add in values for the site and published. Tested on https://designsystem-dev.cancer.gov/pr-1782 and can see basic analytics firing.
