### ISSUE TITLE
Clean up regression images. Again.

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1786]
When the workflow Generate workflow images is used, the entire contents of the `/reference` image directory should be FIRST DELETED and THEN replaced by the generated images from the workflow.

This has not been done and now the repository needs to be cleaned up.

### Tasks

- [ ] Tagging @dlescarbeau and @karlikpj to write documentation to be added somewhere

**Comment by karlikpj** [comment]
Adding content to our ***[Developing NCIDS](https://github.com/NCIOCPL/ncids/wiki/Developing-NCIDS)*** page in the wiki. 

## Backstop Images
> [!IMPORTANT]
> On newer Macs (m1 and above) images created for visual regression by ***github actions*** must completely replace the existing `/reference` folder.

#### Steps to Create Reference Images

1. Go to `https://github.com/NCIOCPL/ncids/actions/workflows/generate-bs-images.yml`
   * Select the branch you wish to use under the ‘run workflow’ drop-down.
   * Wait for the process to complete, usually takes about 15/20 minutes.
2. Click on the `Generate Backstop Reference Images #xxx` that matches the branch you selected.
   * Scroll to the bottom of the page to download the `backstopjs-reference` zip file.
3. Rename the new file to `reference.zip` and extract to your local directory.
4. Fully delete the existing folder and replace your newly unzipped reference folder into its place `ncids/testing/ncids-css-testing/.backstop/`

**Comment by bennettcc** [comment]
Discussed on 10/14 - Closing ticket, no development changes needed
