### ISSUE TITLE
MLP Analytics New Pre-Data: Classification and Data Prep

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/ncids#1788]
Building on [1725](https://github.com/NCIOCPL/ncids/issues/1725), this ticket is to classify and do data prep for the additional new data being collected on MLP pages.

**Comment by laurelthrash** [comment]
Target to pickup week of 07/22.

**Comment by bennettcc** [comment]
As discussed on 8/29 standupo - @welshja and @nicolecrom will close this ticket with a comment.

**Comment by welshja** [comment]
This task has been completed and is available in Adobe reporting.
