### ISSUE TITLE
CR: Change Font Size on Summary Box

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1815]
### Request Description
The current NCIDS Summary Box uses h2 styling (token size LG) for its heading, which is oversized for the component type and usage. Therefore, this request is to reduce the size of the heading to token size MD (font size 20px/Line-height-2), while keeping the heading as an h2 for the page hierarchy.

### What's the expected change?
- Change the font size of the NCIDS Summary Box Heading to be token size MD (font size 20px/line-height-2) while keeping it as an h2 for the page hierarchy.

### What's the current functionality?
- The font size of the NCIDS Summary Box Heading is token size LG.

### Resources
- [Comp](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=3919-18314&t=CwQZuwWUEKmoJnpt-0)

### What's the updated acceptance criteria?
```gherkin
Scenario: A site visitor views an NCIDS Summary Box on a webpage
  Given a site visitor is on a webpage
    And the webpage has an NCIDS Summary Box
  When the visitor views the NCIDS Summary Box
    And the NCIDS Summary Box has a heading
  Then the heading will be token size MD (font size 20px/line-height-2)
    And the heading will be an h2 in the page hierarchy
```

### Related Tickets
* Digital Platform Ticket: [#4389](https://github.com/NCIOCPL/cgov-digital-platform/issues/4389)

**Comment by monika-jaeger** [comment]
@karlikpj Updated Summary Box component overview image attached for page: https://designsystem-dev.cancer.gov/pr-1817/components/summary-box

<img width="1058" alt="summary box-component sample" src="https://github.com/user-attachments/assets/9f6491bb-9b5a-4aa4-a11e-fbaaf6eff4f3">

cc: @andyvanavery31
