### ISSUE TITLE
Draft metadescription content for Doc Site Pages

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1816]
During the week of 8/5, the team identified that several pages of the documentation site do not have a metadescription. The metadescription field is used to populate a description in external and cancer.gov search results.

Please enter draft metadescription content for each of the pages listed in the linked inventory (column C).  We'll then create a separate ticket to update the documentation site with the drafted descriptions.

Inventory: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Docsite_metadescription.xlsx?d=w1fd537ce5b61487d9d8c317bc3ed0e87&csf=1&web=1&e=txjPM4

**Comment by adrianacastaneda** [comment]
@bennettcc @dlescarbeau sent over slack but also including here. Let me know if you have any questions! thanks!

https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Docsite_metadescription.xlsx?d=w1fd537ce5b61487d9d8c317bc3ed0e87&csf=1&web=1&e=AcxWN1

**Comment by bennettcc** [comment]
This is complete - the draft content has been reviewed and approved. I'll create a separate ticket for the implementation of this content within the doc site
