### ISSUE TITLE
MyNCI Documentation Creation for List R3.2

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1824]
This ticket is to track the creation and implementation of documentation about using the list with and without media on the MyNCI Drupal Guide.

### Resources

- **Related Development Ticket**: [# 4360](https://github.com/NCIOCPL/cgov-digital-platform/issues/4360)
- Link to Word Doc

### Sub-Tasks
- [x] Draft documentation for MyNCI Drupal Guide for List with and without media
- [ ] Update MyNCI Drupal Guide with the new documentation

**Comment by adrianacastaneda** [comment]
@lburack @andyvanavery31 wrote guidance for the list component. This guidance will be accompanied by screenshots or short video clips (depending on timing) to show content owners how to add components from the backend. 

Depending on insights from the measurement pages this guidance might get a small update.

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Component%20Guidance/Drupal%20Guide%20%E2%80%93%20Mini%20Landing%20Page%20Component%20Guidance.docx?d=we323236c90144dcd9f0e4fc6d913c049&csf=1&web=1&e=OqVYPZ&nav=eyJoIjoiOTk4MzkwNyJ9

cc: @bennettcc

**Comment by bennettcc** [comment]
Tagging @sarinapadilla to review for product - thanks!

**Comment by lburack** [comment]
Thanks, @adrianacastaneda! I've left a handful of comments on the list section. I think they are mostly straightforward but happy to hop on a huddle if needed for efficiency!

**Comment by adrianacastaneda** [comment]
@lburack @sarinapadilla addressed the comments for the list component. Let me know if everything looks good to you, thank you!

**Comment by lburack** [comment]
Thanks @adrianacastaneda  - looks like things were addressed. I added one new comment (tagged you in it). Otherwise, this should be good to go.

**Comment by bennettcc** [comment]
Per discussion on 9/16 - this story is on hold until the List component is released to the c.gov platform (estimated 10/3). After the component is released, myNCI documentation can be updated.

The content itself to update on myNCI has been created, reviewed, and approved

**Comment by lburack** [comment]
This has been added and published to myNCI: https://mynci.cancer.gov/topics/ncids-mini-landing-page-components
