### ISSUE TITLE
MyNCI Documentation Creation for Flag Card Group R3.2

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1825]
This ticket is to track the creation and implementation of documentation about using the Flag Card Group on the MyNCI Drupal Guide.

### Resources

- **Related Development Ticket**: [# 4389](https://github.com/NCIOCPL/cgov-digital-platform/issues/4389)
- Link to Word Doc

### Sub-Tasks
- [ ] Draft documentation for MyNCI Drupal Guide for the Flag Card Group (Completed in Iteration 53)
- [ ] Update MyNCI Drupal Guide with the new documentation (Completed in Iteration 54)

**Comment by adrianacastaneda** [comment]
@lburack @andyvanavery31 wrote guidance for the flag card group based on requirements. This guidance will be accompanied by screenshots or short video clips (depending on timing) to show content owners how to add components from the backend.

Depending on insights from the measurement pages this guidance might get a small update.

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Component%20Guidance/Drupal%20Guide%20%E2%80%93%20Mini%20Landing%20Page%20Component%20Guidance.docx?d=we323236c90144dcd9f0e4fc6d913c049&csf=1&web=1&e=OqVYPZ&nav=eyJoIjoiOTk4MzkwNyJ9

cc: @bennettcc

**Comment by bennettcc** [comment]
Tagging @sarinapadilla to review for product - thanks!

**Comment by bennettcc** [comment]
Per 9/16 discussion - this story is on hold until the flag card group is available for review on an ODE

**Comment by adrianacastaneda** [comment]
@lburack @sarinapadilla guidance was updated now that the flag card has been approved on the ODE: 

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Component%20Guidance/Drupal%20Guide%20%E2%80%93%20Mini%20Landing%20Page%20Component%20Guidance.docx?d=we323236c90144dcd9f0e4fc6d913c049&csf=1&web=1&e=SbBAPg&nav=eyJoIjoiMzI3OTY1NzY2In0%3D

cc: @bennettcc

**Comment by lburack** [comment]
@adrianacastaneda  I've left some comments on the document. They may be self explanatory but we can discuss when we meet this afternoon.

**Comment by lburack** [comment]
This has been added and published to myNCI: https://mynci.cancer.gov/topics/ncids-mini-landing-page-components
