### ISSUE TITLE
MyNCI Documentation Creation for Summary Box R3.2

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1826]
This ticket is to track the creation and implementation of documentation about using the Summary Box on the MyNCI Drupal Guide.

### Resources

- **Related Development Ticket**: [# 4379](https://github.com/NCIOCPL/cgov-digital-platform/issues/4379)
- Link to Word Doc

### Sub-Tasks
- [ ] Draft documentation for MyNCI Drupal Guide for Summary Box (Completed in Iteration 53)
- [ ] Update MyNCI Drupal Guide with the new documentation (Completed in Iteration 54)

**Comment by adrianacastaneda** [comment]
@lburack @andyvanavery31 wrote guidance for the summary box based on ACs and requirements. This guidance will be accompanied by screenshot or short video clips (depending on timing) to show content owners how to add components from the backend

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Component%20Guidance/Drupal%20Guide%20%E2%80%93%20Mini%20Landing%20Page%20Component%20Guidance.docx?d=we323236c90144dcd9f0e4fc6d913c049&csf=1&web=1&e=pjVoWa&nav=eyJoIjoiNzkyMjUyNjExIn0

cc: @bennettcc

**Comment by bennettcc** [comment]
Tagging @sarinapadilla to review for product - thanks!

**Comment by adrianacastaneda** [comment]
@sarinapadilla let me know if you've gotten a chance to review. Link below goes to the summary box section of the guidance. Thank you!

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Component%20Guidance/Drupal%20Guide%20%E2%80%93%20Mini%20Landing%20Page%20Component%20Guidance.docx?d=we323236c90144dcd9f0e4fc6d913c049&csf=1&web=1&e=I25H33&nav=eyJoIjoiNzkyMjUyNjExIn0

**Comment by lburack** [comment]
@adrianacastaneda  there's some back and forth in a recent slack thread about the summary box heading requirements. so for now I'm holding off on my review to ensure we have the latest updates included in here, particularly for the fields and how to use/create this in Drupal.

**Comment by bennettcc** [comment]
Per 9/16 discussion - this story is on hold until the recent summary box WYSIWYG changes are available for review on an ODE

**Comment by lburack** [comment]
This has been added and published to myNCI: https://mynci.cancer.gov/topics/ncids-mini-landing-page-components
