### ISSUE TITLE
MyNCI Documentation Creation for the 2 Column Layout R3.3

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1827]
This ticket is to track the creation and implementation of documentation about using the 2 Column Layout on the MyNCI Drupal Guide.

### Resources

- **Related Development Ticket**: [# 4400](https://github.com/NCIOCPL/cgov-digital-platform/issues/4400)
- Link to Word Doc

### Sub-Tasks
- [ ] Draft documentation for MyNCI Drupal Guide for 2 Column Layout (To be completed in Iteration 53 pending the component being built on the ODE)
- [ ] Update MyNCI Drupal Guide with the new documentation (To be completed in Iteration 54)

**Comment by adrianacastaneda** [comment]
@lburack @andyvanavery31 this one is also ready for review. Just noting that right now the the components are out of order in the word doc. All the components up for review are located towards the bottom

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BE323236C-9014-4DCD-9F0E-4FC6D913C049%7D&file=Drupal%20Guide%20%25u2013%20Mini%20Landing%20Page%20Component%20Guidance.docx&action=default&mobileredirect=true

cc: @bennettcc

**Comment by lburack** [comment]
This has been added and published to myNCI: https://mynci.cancer.gov/topics/ncids-mini-landing-page-components
