### ISSUE TITLE
MyNCI Documentation Updates to 2 Column Layout R3.5

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1828]
This ticket is to track the update to the documentation about using the 2 Column Layout with the addition of images and videos on the MyNCI Drupal Guide.

### Resources

- **Related Development Ticket**: [# 4414](https://github.com/NCIOCPL/cgov-digital-platform/issues/4414)
- Link to Word Doc

### Sub-Tasks
- [x] Draft updated documentation for MyNCI Drupal Guide for 2 Column Layout with Images and Videos
- [x] Update MyNCI Drupal Guide with the new documentation

**Comment by adrianacastaneda** [comment]
@lburack I slacked this update to you for another reason but here is the updated guidance for that section to cover images and video:

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BE323236C-9014-4DCD-9F0E-4FC6D913C049%7D&file=Drupal%20Guide%20%25u2013%20Mini%20Landing%20Page%20Component%20Guidance.docx&action=default&mobileredirect=true

**Comment by andyvanavery31** [comment]
Complete.
