### ISSUE TITLE
MyNCI Video Creation for Flag Card Group R3.2

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1833]
This ticket is to track the creation and implementation of video instructions for using the Flag Card Group on the MyNCI Drupal Guide.

### Resources
- Related Development Ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/4389
- Link to Word Doc

### Sub-Tasks

- [ ] Draft documentation for MyNCI Drupal Guide for Flag Card Group
- [ ] Update MyNCI Drupal Guide with the new documentation

**Comment by bennettcc** [comment]
Confirmed with Alex/Anna on 10/1; we will not be creating video instruction for MLP components as a part of training materials. Closing ticket
