### ISSUE TITLE
CR: NCIDS Card Font Sizes for Consistency on NCIDS

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1839]
### Request Description
The change to Cards has been approved by the client as of 26AUG2024. This request is to update the NCIDS Cards with the changes to the font. The result of the change will have the description text be token size xs (16px), the card title will be token size md (20px), and the group/row heading will be size xl (24px).

### What's the expected change?
- The NCIDS Cards will have their font styling updated so that the description text be token size xs (16px), the card title will be token size md (20px), and the group/row heading will be size xl (24px).
- The updates will be reflected on the NCIDS Documentation Site and the NCIDS Storybook.
- The overview image for NCIDS Cards and the template for the 3-Card Row will be updated with the correct font sizes
- Regression Images of these cards will be updated on NCIDS Storybook.

### What's the current functionality?
- NCIDS Cards have a description text size of 18px, card title text size of 22px, and group/row heading font size of 24px.

### What's the updated acceptance criteria?
```gherkin
Scenario: A site visitor views an NCIDS Feature Card component
  Given the site visitor is on the NCIDS Documentation Site or the NCIDS Storybook
    And the NCIDS Card font sizes have been updated
  When the visitor views the NCIDS Card
  Then the description text size of the card will be token size xs (16px)
    And the card title text size will be token size md (20px)
    And the card row heading text size will be token size xl (24px)
  When the visitor views the NCIDS Card on the 3-Card Row Page
  Then the description text size of the card will be token size xs (16px)
    And the card title text size will be token size md (20px)
    And the card row heading text size will be token size xl (24px)
```

**Comment by monika-jaeger** [comment]
Attached is the updated single card image and card row pattern image. 

<img width="1010" alt="card-row_pattern" src="https://github.com/user-attachments/assets/c6590ee7-c46f-4a7a-a584-f502b9069f50">
<img width="648" alt="card" src="https://github.com/user-attachments/assets/3aa92356-4888-494e-9c98-72d8713a747d">

cc: @andyvanavery31 @blilianyu @karlikpj
