### ISSUE TITLE
CR: Make the Example Site, Past Releases, and Search Pages Not Show Up on Search Results for Google and Site Wide Search

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1841]
### Request Description
This request is to create Robots.txt so that cetain pages do not get indexed for by Google nor by the Site Wide Search
* This should match anything that is `/example-site` `/past-releases', `/search`

### What's the expected change?
- Update search for Google and Site Wide Search so that example site, past releases, and search pages do not get indexed by Google nor the Site Wide Search

### What's the current functionality?
- Example site, past releases, and search pages are being indexed by Google and the Site Wide Search

**Comment by welshja** [comment]
Looks good to me.
