### ISSUE TITLE
Document R4 Measurements, Goals, and Expectations

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1860]
This ticket is to document the need to define and document broad goals, measurement, expectations for the R4 inner page release.

This deck with needs and goal statements should mimic what was done for R3: https://nih.sharepoint.com/:p:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Measurement%20and%20Evaluation/[MLP_R3_Measurement-Plan.pptx](https://nih.sharepoint.com/:p:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Measurement%20and%20Evaluation/MLP_R3_Measurement-Plan.pptx?d=wece13f623cd24abd91d5ef9f61db5d74&csf=1&web=1&e=s678Cf)?d=wece13f623cd24abd91d5ef9f61db5d74&csf=1&web=1&e=s678Cf

Please store the new document in this shared space: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%204/Measurement%20and%20Evaluation?csf=1&web=1&e=PfHkj3

Milestones:

- [x] Build draft document with R4 measurements, goals, and expectations (by 9/27)
- [x] Review document internally (starting week of 9/30)

**Comment by andyvanavery31** [comment]
Work is completed.
