### ISSUE TITLE
myNCI Documentation Creation for Wide Guide Card R3.4

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1869]
This ticket is to track the creation and implementation of documentation about using the Wide Guide Card on the MyNCI Drupal Guide.

Resources
Related Development Ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/4433
Link to Word Doc: 

Sub-Tasks
 

- [x] Draft documentation for MyNCI Drupal Guide for the Flag Card Group (Completed in Iteration 55)
- [x]  Update MyNCI Drupal Guide with the new documentation (Completed in Iteration 56)

**Comment by adrianacastaneda** [comment]
@lburack forgot to add the link here. Here's the wide guide card guidance: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Component%20Guidance/Drupal%20Guide%20%E2%80%93%20Mini%20Landing%20Page%20Component%20Guidance.docx?d=we323236c90144dcd9f0e4fc6d913c049&csf=1&web=1&e=8AsvxR&nav=eyJoIjoiOTA0Mjc2NzkyIn0%3D

**Comment by lburack** [comment]
@adrianacastaneda I've reviewed this and made a few updates and left some comments. Let me know if you have any questions otherwise the documentation part of this task is completed!

**Comment by adrianacastaneda** [comment]
@lburack Thanks for reviewing! Addressed all comments. Will update once components go live!

**Comment by andyvanavery31** [comment]
Complete.
