### ISSUE TITLE
Identify and Resolve Inconsistencies in Card Between Figma and Prod

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1873]
# Issue Description
Inconsistencies have been found between the Figma and Prod for the NCIDS Card, and this ticket will be used to document those differences. Resolutions to those differences will be determined and handled accordingly.

All noted differences can be viewed in the [Master Design Kit](https://www.figma.com/design/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?node-id=2302-4899&t=fLsl5icHRlgESyJi-1) with the 'notes' function turned on.

# Noted Differences
#### Widescreen
- Bottom of card: 24px on Figma, 16px on prod

#### Desktop
- Bottom of card: 24px on Figma, 16px on prod

#### Tablet Large
- Between title & description: 16px on Figma, 12px on prod
- Bottom of card: 24px on Figma, 16px on prod

#### Tablet
- Top/bottom of card: 16px on Figma, 20px on prod
- Between title & description: 16px on Figma, 12px on prod
- Left/right of card: 24px on Figma, 32px on prod
- Between cards: 24px on Figma, 32px on prod

#### Mobile Large
- _See notes at bottom_

#### Mobile
- _See notes at bottom_

#### Widescreen
- Bottom of card: 16px on Figma, 24px on ODE

#### Desktop
- Bottom of card: 16px on Figma, 24px on ODE

#### Tablet Large
- Right/left of card: 24px on Figma, 32px on ODE
- Top/bottom of card: 16px on Figma, 20px on ODE

#### Tablet
- Right/left of card: 24px on Figma, 32px on ODE
- Top/bottom of card: 16px on Figma, 20px on ODE

#### Mobile Large
- _See notes at bottom_

#### Mobile
- _See notes at bottom_

#### Widescreen
- Top/bottom of card: 20px in Figma, 16 px on prod

#### Desktop
- Top/bottom of card: 20px in Figma, 16 px on prod

#### Tablet Large
- Top/bottom of card: 20px in Figma, 16 px on prod

#### Tablet
- Left/right of card: 24px in Figma, 32px on prod
- Between cards: 24px on Figma, 32px on prod

#### Mobile Large
- Left/right of card: 24px in Figma, 40px on prod

#### Mobile
- Left/right of card: 24px in Figma, 32px on prod

#### _For mobile large and mobile breakpoints:_
We should have the default, flag and imageless cards all have the same spacing values, so if they are all used on one page they are consistent. We currently have various spacing sizes right/left & top/bottom.

### Guide Card 
_(no discrepancies between Figma/prod, but notes to match up consistencies between variants and other card components)_
Image & Description description: currently 18pt (sm), but match card descriptions at 16pt(xs)
Guide Card Row title: 28px (2xl)
Image & Description title: 28px (2xl)
Wide Guide Card title: 24px (xl)

### Promo Block
All descriptions: currently 18pt (sm), but match card descriptions at 16pt(xs)?
_We previously discussed this, but is it worth to do with other component updates based on the promo block performance?_

**Comment by monika-jaeger** [comment]
Added all differences in the description box, and these are also noted in Figma in the [Master Design Kit](https://www.figma.com/design/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?node-id=2302-4899&t=fLsl5icHRlgESyJi-1) with 'notes' 

cc: @andyvanavery31 @blilianyu

**Comment by monika-jaeger** [comment]
Also updated & pushed out the [Community file](https://www.figma.com/design/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?node-id=5280-38952&t=rZqCmHcpAdMMyjWS-1) to reflect spacing values on the Default Card of what's in prod.

cc: @andyvanavery31 @blilianyu

**Comment by blilianyu** [comment]
@andyvanavery31 @monika-jaeger depending on what the results are for removing the image from Image & Description Guide Card, I say we wait to make the updates to row title, card title, description to match the WGC.

**Comment by andyvanavery31** [comment]
Closing as the work to update the community file is complete. A new META ticket will be created to capture future steps for any changes that are decided on.

**Comment by monika-jaeger** [comment]
Also updated & pushed out the [Community file](https://www.figma.com/design/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?node-id=5280-38952&t=rZqCmHcpAdMMyjWS-1) to reflect spacing values on the Default Card of what's in prod.

cc: @andyvanavery31 @blilianyu
