### ISSUE TITLE
MyNCI Documentation Updates to Imageless Cards

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1878]
This ticket is to track the update to the myNCI documentation about using the Imageless Cards

**Resources**
Related Development Ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/4464
Link to Word Doc:

Sub-Tasks 

- [x] Draft updated documentation for MyNCI Drupal Guide for Imageless Card

- [x] Update MyNCI Drupal Guide with the new documentation

**Comment by adrianacastaneda** [comment]
@lburack here's the guidance for the imageless cards: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Component%20Guidance/Drupal%20Guide%20%E2%80%93%20Mini%20Landing%20Page%20Component%20Guidance.docx?d=we323236c90144dcd9f0e4fc6d913c049&csf=1&web=1&e=6DDOlD&nav=eyJoIjoiMTI0NjE4OTUyMSJ9

**Comment by lburack** [comment]
@adrianacastaneda  – I've made some minor copy edits and left one or two comments. This is looking good! Ready to be added to Drupal once the release goes live!!

**Comment by adrianacastaneda** [comment]
@lburack Thanks for reviewing! Addressed all comments. Will update once components go live!

**Comment by andyvanavery31** [comment]
Complete.
