### ISSUE TITLE
Phase 2 Doc Site Copy Edit: Coordinate timing with OCC to Complete

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1886]
### Task Description
This ticket is to track the alignment of timing for the Phase 2 of the Documentation Site Copy Edit.

Phase 2 content to be copy edited:

a. Header
b. Footer
c. Skipnav
d. Banner
e. For Designers
f. For Developers
g. Figma Guide
h. [Typography](https://designsystem.cancer.gov/foundations/typography) section
i. Colors

**Comment by bennettcc** [comment]
This is in progress as of 11/6. The scope of phase 2 copy editing has been defined; Anna/Cam are coordinating with OCC on the copy editing task

**Comment by bennettcc** [comment]
Closing this ticket - Copy editing has started with OCC, they'll aim to return notes to us by 12/20 for discussion/review in early 2025
