### ISSUE TITLE
Wide Guide Card (WGC) Heading - Fix line height

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/ncids#1892]
### Issue description
The line height spacing on the Wide Guide Card (WGC) is incorrect. You can see this when the heading wraps one more than one line (see screenshot below). 

> **ESTIMATE** TBD

### What's the expected change?
- The line-height should be token 2

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Image](https://github.com/user-attachments/assets/e8654bb4-d0fe-4d9c-8866-696e8a0009f4)

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by andyvanavery31** [comment]
Closing the ticket here since this is a Drupal issue, not NCIDS.
