### ISSUE TITLE
Create A/B Testing Options in CrazyEgg for CTHP

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1895]
This ticket is to track the creation of the two agreed upon testing options for CrazyEgg A/B Testing for the Cancer Types Homepage. The two options are:

- Removing the combo box section
- Changing the text in the combo box to "Find a cancer type using the search box below."
- Andy to send Reply All to the stakeholder meeting when this is launched

These will be launched following the stakeholder update meeting on 8NOV2024.

**Comment by bennettcc** [comment]
A/B testing launched on 11/15 - closing ticket
