### ISSUE TITLE
Enabler: Automatically Publish Documentation Site for Reviews

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#19]
# Automatically Publish Documentation Site for Reviews

When a commit, or PR is created, a build should occur for the documentation site so that it can be reviewed as part of that PR. This should be similar to what we do for React app development. 

The URL format should be:
* https://designsystem-dev.cancer.gov/<branch_or_pr>

As the documentation site holds not only the published documentation site, but the storybooks for the various packages, a review should be of all the changes to designsystem.cancer.gov. The location for story books is currently TBD until we determine what will be possible from a URL standpoint. 

> **ESTIMATE** 5 story points

### Resources:
* https://github.com/NCIOCPL/ncids/wiki/Repos-Packages-Organization

### Prerequisites
- [x] Akamai Netstorage & property rules configured
- [ ] Storybooks configured for ncids-css, ncids-react, ncids-js

## Solution Components
Ultimately it is the GitHub workflow that will build and upload the documentation site (incl storybooks) to Akamai and designsystem-dev/designsystem.cancer.gov. In order to streamline the Github action, we should break this solution into 2 parts:
1. A Yarn script to build and compile the web site artifact.
2. The Github workflow job to call that script and upload the resulting artifact to Akamai. (This will be very much like react-app-dev)

### build:docs-artifact Yarn Script
The following are the high-level steps are should be able to be performed at the root of the repository by performing an `yarn run build:docs-artifact`. (Note we are calling this build:docs-artifact as the job of this script is to create the zip file that holds all the documentation, which will be uploaded to Akamai. It is the Github Action that does the uploading.

1. Build the composite storybook site.
    * This may actually require all storybook sites to be built first. So let's assume there is a `yarn run build:storybook` available in the root as well.
2. Build the documentation site
3. Make a folder name `build` under the repo root
4. Make a folder named `documentation-site` under build (cause we probably will have more folders under build...)
3. Copy the `public` folder of the documentation site to `<repo_root>/build/documentation-site`.
4. Copy the CONTENTS of the built storybook folder (location unknown at this time) to `<repo_root>/build/documentation-site/storybook`
5. `cd <repo_root>/build/documentation-site`
6. `zip -r ../documentation-site.zip *`

>**_Stretch Goal:_** Have build:docs-artifact take an artifact name in as a param so the GH workflow does not need to rename itself. You can still default to documentation-site.zip.

### Github Workflow
1. Call `yarn run build:docs-artifact`
    * NOTE: A Public URL may be needed to handle images and such. This is what happens with create-react-app based sites. IDK yet if Gatsby or storybook will have a problem. If you need to know, the site will run as:
       * Dev: `designsystem-dev.cancer.gov/<brach_name>/`
       * Prod: `designsystem.cancer.gov/`
2. Rename `<repo_root>/documentation-site.zip` to the <branch's name>.zip
    * The code in react app playground to handle this is ` BRANCH_NAME=$(sed -E 's/refs\/(heads|tags)\///;' <<< $GITHUB_REF)` 
3. <Stretch Goal> Add a build.json file to the documentation-site.zip with details of this build and the job. (_Note: most of these you will only be able to get while the workflow is running, so don't try and add it to the documentation site build process_)
    * Time
    * Commit Hash
    * Branch Name
    * Github Actions Job ID 
4. Upload the Zip to netstorage
5. Clear the Akamai cache for the site.

**Comment by anthonycuellar** [comment]
@arcepaul @karlikpj Catching up here. Was there a subset of tickets created for this?

**Comment by bryanpizzillo** [comment]
Based on prototyping, we will not be publishing storybooks for now. So all the story book items on this ticket may be ignored. However the ticket  should be implemented in a way such that storybook *could* be added in.
