### ISSUE TITLE
Comp Recommended layout of Cancer Research Data Commons footer

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1905]
We met with the Proteomics Data Commons team on 10/24 to discuss the NCIDS adoption of https://proteomic.datacommons.cancer.gov/pdc/. The are a child site to the larger Cancer Research Data Commons site umbrellas.

The PDC team requested that we create a mockup of a footer to be used across all the Cancer Research Data Commons (CRDC) sites to support their adoption of the NCIDS footer to promote cohesion across all of the sites (that may eventually adopt NCIDS)

To support this request, Anna will be coordinating with the CBIIT team to identify which content pages/links are important to include within a CRDC site footer.  Once this data is shared with our team, please create a design comp of the CRDC (https://datacommons.cancer.gov/) site. This comp should include a recommendation of how links/content pages should be organized as well as what site logo should be included.

**Comment by andyvanavery31** [comment]
Closed as redundant and addressed by #1930
