### ISSUE TITLE
Task: Create Comps for External Link Icons

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1906]
This ticket will track the progress of comp creation and review with the internal team for the external link icons on Redesign (NCIDS, H&L, MLP) components.

**Parent Issue:** #1883 

### Sub-Tasks
- [x] Create comps
- [x] Review comps with internal team (Specs/Soln meeting Nov 13)

**Comment by bennettcc** [comment]
Per discussion at 11/21 standup, these updates are complete - closing ticket
