### ISSUE TITLE
MLP Content Launch Support Tier 1A: Build draft/recommended content in CMS (unpublished)

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1909]
### Task Description

This ticket is to track the creation of unpublished, recommended content in the CMS for the Tier 1A MLP pages.

Will go into Sprint 60.

Tier 1A pages include:

- [CCHE](https://www.cancer.gov/about-nci/organization/cche)
- [DCB](https://www.cancer.gov/about-nci/organization/dcb)
- [CGH](https://www.cancer.gov/about-nci/organization/cgh)
- [CCT](https://www.cancer.gov/grants-training/training)
- [CCDI](https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative)
- [PDQ Cancer Information for Health Professionals - English](https://www.cancer.gov/publications/pdq)
- [PDQ for Health Professionals - Spanish](https://www.cancer.gov/espanol/publicaciones/pdq)

Tracking Tier 1 pages here: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B9C3E77FE-F843-47F7-A9A5-CC95D315C25A%7D&file=Content%20Launch%20Tasks%20and%20LOE%20Estimates.xlsx&action=default&mobileredirect=true

**Comment by lburack** [comment]
- Note that DCB, CGH, and CCT were waiting on Wide Guide Card. With last week's release, we can now begin on building those drafts in the CMS. 
- Met with CCHE on 10/31 and have their recommendations in draft in the CMS.
- Met with CCDI on 11/8. Finalizing updates to the draft in the CMS. 
- PDQ English page is in draft in the CMS. Have been finalizing feedback with PDQ team. And have a [JIRA ticket](https://tracker.nci.nih.gov/browse/CGOV-22482) to create two more icons for two pages within their section.

**Comment by andyvanavery31** [comment]
Complete - Recommendations sent to stakeholders.
