### ISSUE TITLE
Track Analytics from CrazyEgg A/B CTLP Testing

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1921]
### Task Description

This ticket will track the execution and completion of the data analysis of the A/B Testing being conducted on the CTHP. Notable items to be determined are:

- Sample size/length of time for testing
- Planning the internal and external share outs

**Comment by bennettcc** [comment]
Closing this ticket as of 12/19 - we're completing the current Crazy Egg A/B test
