### ISSUE TITLE
Determine Media Templates still in use

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#193]
Work with Min to get a report of the media templates currently being used in drupal (and the number of uses) - and determine which templates are still needed/can be retired.

### Sub-Tasks
- [x] request reporting from Min
- [x] Do analysis

### Reporting
- report available on Notion: https://www.notion.so/Inline-Media-Analysis-b00571f1987648e68fb1aac2fa9f5f0c

**Comment by claireblaustein** [comment]
Requested Drupal reporting from @zhuomingao 

For all inline media (video, image, infographic)

Asset Name
Asset content type
page name
Page URL
page content type
placement specs (size and orientation)

**Comment by claireblaustein** [comment]
Analysis complete, and report available
