### ISSUE TITLE
Atomic Component: Megamenu

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#195]
### Handoff of xxx component from design to development

> **ESTIMATE** TBD

### Acceptance Criteria
*Include specs:  List of colors (hex, token name), variants, and states.* 

**Needs requirements.** 

### Acceptance Criteria

- Megamenu is manually curated (but not worry about spaces in the code please)
- Click to open the menu
- All headers should underline when you hover over so that users know they can click on it
- Carrot changes direction (points down to open and up to close)
- Animations for open or close?
- Megamenu is NOT sticky.
- Primary nav is underlined in megamenu (at the L1 level. See: https://publicis.invisionapp.com/share/MW1112N6286R#/screens/451934895_What_Is_Cancer-

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Mockups: https://publicis.invisionapp.com/share/FA10EYZRDWP2
* Web Page: *Here goes a URL to an existing web page*

### Notes
* Consider scroll bar for super large menu? or screen takeover for all menus
---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ]  Draft needed internal documentation (insert Notion link)
- [ ]  Publish completed component in DSM

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
Closing this - the ACs have been written as part of #205
