### ISSUE TITLE
Spike: Rebuild USWDS footer using sass 

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#201]
## Investigate rebuilding uswds footer as an exercise to validate our own scss architecture.

> **Estimated Timeframe** *2* 

Notes:
* Proposed SCSS Architecture in [The Way](https://github.com/NCIOCPL/ncids/wiki/The-Way)

### Expected Deliverables:
* *Validate or invalidate propsed file structure in [The Way](https://github.com/NCIOCPL/ncids/wiki/The-Way)*
* *USWDS footer broken up into its 3 variants outputting only what each variant requires for use*

**Comment by anthonycuellar** [comment]
Waiting to be merged
