### ISSUE TITLE
Embedded Images and Caption/Credit/Enlarge

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#206]
### Build Embedded Images component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### Variants Information
*No USWDS variant 

### Invision Mockups: 
*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
  * Page through mocks to different breakpoints:  https://publicis.invisionapp.com/share/Y811ED07RWBT

### Notion Documentation *Additional background information for requirements*:
https://www.notion.so/Inline-Media-Analysis-b00571f1987648e68fb1aac2fa9f5f0c

### Notes
*Some complementary notes if necessary:*
Enlarge "View Image": Underline text on hover and open in new window onclick.
Option to show or hide lead image on mobile. Default is shown.
All templates become full width at 640 and smaller

### Acceptance Criteria for Behaviors 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: Image displayed at small
   Given: The small image template is selected to display on the page and the page is 641 and larger
      And the right alignment is designated
   Then the image would appear at 25% of the container width on the right
   When the left alignment is designated
   Then the image would appear at 25% of the container width on the left
   When the center alignment is designated
   Then the image would appear at 25% of the container width in the center
```

```gherkin
Scenario: Image displayed at medium
   Given: The medium image template is selected to display on the page  and the page is 641 and larger
      And the right alignment is designated
   Then the image would appear at 40% of the container width on the right
   When the left alignment is designated
   Then the image would appear at 40% of the container width on the left
   When the center alignment is designated
   Then the image would appear at 40% of the container width in the center
```

```gherkin
Scenario: Image displayed at large
   Given: The large image template is selected to display on the page  and the page is 641 and larger
      And the right alignment is designated
   Then the image would appear at 75% of the container width on the right
   When the left alignment is designated
   Then the image would appear at 75% of the container width on the left
   When the center alignment is designated
   Then the image would appear at 75% of the container width in the center
```

```gherkin
Scenario: Image displayed at full
   Given: The full image template is selected to display on the page
      And the right alignment is designated
   Then the image would appear at 100% of the container width at center alignment
   When the left alignment is designated
   Then the image would appear at 100% of the container width at center alignment
   When the center alignment is designated
   Then the image would appear at 100% of the container width at center alignment
```

```gherkin
Scenario: Image displayed at small on mobile
   Given: The small image template is selected to display on the page and the page is 640 and smaller
      And the right alignment is designated
   Then the image would appear at 100% of the container width on the right
   When the left alignment is designated
   Then the image would appear at 100% of the container width on the left
   When the center alignment is designated
   Then the image would appear at 100% of the container width in the center
```

```gherkin
Scenario: Image displayed at medium on mobile
   Given: The medium image template is selected to display on the page  and the page is 640 and smaller
      And the right alignment is designated
   Then the image would appear at 100% of the container width on the right
   When the left alignment is designated
   Then the image would appear at 100% of the container width on the left
   When the center alignment is designated
   Then the image would appear at 100% of the container width in the center
```

```gherkin
Scenario: Image displayed at large on mobile
   Given: The large image template is selected to display on the page  and the page is 640 and smaller
      And the right alignment is designated
   Then the image would appear at 100% of the container width on the right
   When the left alignment is designated
   Then the image would appear at 100% of the container width on the left
   When the center alignment is designated
   Then the image would appear at 100% of the container width in the center
```

```gherkin
Scenario: Caption
   Given: The caption field is populated
   Then the caption text would appear underneath the image
     And a vertical line appears to the left
   When the credit field is populated
```

```gherkin
Scenario: Credit
   Given: The credit field is populated
   When the credit field is populated
   Then the credit text would appear underneath the image
      And a vertical line appears to the left
```

```gherkin
Scenario: Enlarge
   Given: The enlarge is set for the image
   Then the enlarge text "view image" would appear underneath the image
     And a vertical line appears to the left
     And open in a new window onclick
```
-OTHER PERMUTATIONS-

```gherkin
Scenario: Nothing
   Given: The caption field, credit and enlarge aren't populated/specified
   Then nothing would appear beneath the image
```
---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by VictoriaSunNIH** [comment]
@mworrest , @blilianyu  - Something that @bryanpizzillo reminded me of today...images can also be embedded in tables and we should likely account for this. If we are closing this ticket out, then we should capture that as part of table design?

**Comment by VictoriaSunNIH** [comment]
From this morning's session with Lynn - we need to think about adding a field for credit URL that would display, but not allow the credit text field to have html so we can put in links for credits.

**Comment by anthonycuellar** [comment]
Setting up 30 min to discuss this (Bryan, Michelle, Lindsay - optional, Paul A):
- Linking in the credit field
- Images and tables

**Comment by VictoriaSunNIH** [comment]
@anthonycuellar, @mworrest , @arcepaul - what was the outcome of the discussion?  Do I still need to open a ticket in Drupal to add this field?

**Comment by mworrest** [comment]
I got the report back from Min. There are 455 images that have the source field populated so repurposing it to display on the front end may not be an option. @VictoriaSunNIH we look at this mockup I did for the image content type in Drupal and discussed how we might accommodate the text that displays on the front-end and to link that text.
![credit-source-license](https://user-images.githubusercontent.com/4921685/132376292-f025da3a-3795-46fe-aa93-d2a9c05dad14.jpg)

**Comment by anthonycuellar** [comment]
Waiting for a response from Lynn & Fedora from Friday 9/10

**Comment by mworrest** [comment]
Lynn approved the updates to the drupal fields for the image content type. 
![drupal-image-source-license](https://user-images.githubusercontent.com/4921685/133449587-113f45d1-3b78-4263-b940-6e656b960cdf.jpg)

**Comment by lburack** [comment]
Reminder that we will have to update the Drupal Guide on myNCI when this goes live: https://mynci.cancer.gov/topics/drupal-guide-images-and-multimedia
