### ISSUE TITLE
Spike: How to test SASS partials

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#211]
## In order to test ncids sass partials we create,  developers need to investigate proposed testing methods that will effectively test sass partials in isolation.  

> **Estimated Timeframe** *# of days for completion* 

### Proposed Testing methods
- Storybook
- Olivia's unicorn shadow dom idea
- Some sort of fake website (maybe using some static site generator) that imports individual partials (and only the partials)
- Bryan's Express server thingy - express compiles sass

### Expected Deliverables:
- partials are tested in isolation and are served up and available for Cypress testing

### Additional Notes:
* Storybook (https://storybook.js.org/)
* Cypress (https://cypress.io)

### Results of Spike
*Enter the information, or links to any (non-sensitive) files with the findings here*

**Comment by anthonycuellar** [comment]
In PR waiting for review from @arcepaul @karlikpj

**Comment by anthonycuellar** [comment]
This is in progress, footer has been merged.

**Comment by anthonycuellar** [comment]
In PR
