### ISSUE TITLE
Build: Intro Text

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#216]
### Build Intro Text component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
* https://www.notion.so/Intro-Text-0ab24b99fad24864b731a81a951f71e1
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links: 

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component? No
* Related USWDS Links: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/components/preview/layout--docs.html 
  * p class="usa-intro"

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: https://publicis.invisionapp.com/share/MH10XGEY5QCV#/451376122_visual-Inventory-Article-USWDS-Components-In-Ncids-Styles
  * Tablet mockup: *insert link here, or N/A if not needed*
  * Mobile mockup: *insert link here, or N/A if not needed*

### Acceptance Criteria for Behaviors 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: Intro text is populated
  Given the CMS user populates the intro text field
  Then the intro text shows on the page
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by anthonycuellar** [comment]
This needs to be reviewed with Lynn and Fedora

**Comment by anthonycuellar** [comment]
Need to speak with the content team post- meeting with Lynn

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
