### ISSUE TITLE
Build: References

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#219]
### Build References component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
* https://www.notion.so/References-Citations-0909b58bb087456681e792d154816e6a
* Web page: https://www.cancer.gov/types/lymphoma/hp/adult-hodgkin-treatment-pdq
* This feature shows up multiple times on pdq hp pages
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: *Here goes a URL to an existing web page*

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: https://publicis.invisionapp.com/share/DU110OMZVT4R#/454713279_Cancer_Currents_Blog_Post_-_Future_V3B
  * Tablet mockup: Same w/out hover 
  * Mobile mockup: Same w/out hover 

### Acceptance Criteria for Behaviors 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User is on a page of a c.gov site with 5 or less references/citations
  Given user is on a page of a c.gov site with references/citations
  When user clicks on a reference number from within the body of the page
  Then the page jumps down to the reference section of the page (specifically to the number they clicked on)
    And no expand button shows
```

```gherkin
Scenario: User is on a page of a c.gov site with 5 or more references/citations
  Given user is on a page of a c.gov site with references/citations
  When user clicks on a reference number higher than 5 from within the body of the page
  Then the page jumps down to the reference section of the page (specifically to the number they clicked on)
    And the list is expanded automatically showing all references
    And the collapse button shows
  Then on click of the collapse button the list collapses down to the first 5 
    And the expand button shows
```

```gherkin
Scenario: User is on a page of a c.gov site with 5 or more references/citations
  Given user is on a page of a c.gov site with references/citations
  When user clicks on a reference number that is 5 or lower from within the body of the page
  Then the page scrolls jumps to the reference section of the page (specifically to the number they clicked on)
    And the list is collapsed by default showing the first 5 references
    And the expand button shows
  Then on click of the expand button the list expands to show all references
    And the collapse button shows
```

```gherkin
Scenario: User is on a page of a c.gov site with 5 or more references/citations
  Given user is on a page of a c.gov site with references/citations
  When user scrolls to reference section of the page
  Then the list is collapsed by default showing the first 5 references
    And the expand button shows
  Then on click of the expand button the list expands to show all references
    And the collapse button shows
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
