### ISSUE TITLE
Design: Breadcrumbs

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#22]
### **Description of task to be worked on**
Design of breadcrumbs for desktop and mobile views

**Design Goals:**
- minimizing conflict with other nav systems
- useful mobile experience

### **Problems to solve**
*Identified during discovery work*
- conflicts with home levels - differences between platforms
- Inconsistencies by templates and content types
- lack on mobile
- crazypants ouliers - some reeeeealy long breadcrumbs

### **Related Tickets**
- Baseline Discovery: Breadcrumbs #67

### **Resources**
Notion for Breadcrumbs: https://www.notion.so/Breadcrumbs-baf2759e1e2f4aada77493ef3c0df5de

### **Notes**
*Some complementary notes if necessary*

### **Design Files**

*Links to invision comps or other design assets*

### **Technical Notes**

*More notes, or technical nuances/direction*

**Comment by mworrest** [comment]
Undergoing usability testing on the article content type.

**Comment by mworrest** [comment]
The proposal for mobile is to show home and the parent and grandparent (if applicable). On deeper pages, ellipses will appear  between home and grandparent. It will behave how box breadcrumbs work.

**Comment by mworrest** [comment]
After talking to devs we have to have the same breadcrumbs on mobile and desktop, so we have to show everything on mobile.

**Comment by mworrest** [comment]
Also consider not including breadcrumbs on mobile. This is the longest breadcrumb: https://publicis.invisionapp.com/share/3C10NGGUXTYQ#/450524508_Mobile_-_Longest_Breadcrumb

**Comment by anthonycuellar** [comment]
We're not including breadcrumbs in mobile.

**Comment by mworrest** [comment]
Awaiting Lynn's approval.

**Comment by mworrest** [comment]
Lynn approved. Wrote AC's in https://github.com/NCIOCPL/ncids/issues/163
