### ISSUE TITLE
Initial Discovery: Landing Pages

### ISSUE THREAD

**Issue by sewallaa** [NCIOCPL/ncids#220]
A look at landing/navigational pages across the site to look for commonalities.

Look at the content types and break them down for discussion.

### Resources and Links
*Links to related content on Notion, mockups*
Analysis Notes on Notion: https://www.notion.so/nci-ps/Navigational-Pages-730d4a89725e4c80a370f0a37359bb8e

### Potential Tasks
*Update the list and remove Potential once the scope of the discovery has been set*
- [ ]  Drupal reporting
- [ ]  Synthesis of any existing analytics data around use and function
- [ ]  High-level heuristic review of feature
- [ ]  Technical or accessibility flag
- [ ]  Best practices around use of feature
- [ ]  Persona / user empathy exploration and synthesis

### Notes
*Some complementary notes if necessary.*

**Comment by claireblaustein** [comment]
Notes and analysis on Notion and Mural:
https://www.notion.so/nci-ps/Navigational-Pages-730d4a89725e4c80a370f0a37359bb8e
https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1621964812795/a2b579e22ffb87bfc2b655aeef2fe2c9b119538b?sender=claireblaustein5539
