### ISSUE TITLE
Research: Glossify Images in Articles

### ISSUE THREAD

**Issue by sewallaa** [NCIOCPL/ncids#221]
> Feature/Main User Story: [Enter user story ticket association here] 

### What do you want to learn from this research?
List the questions you would like to answer

1. Can users scroll through multiple images in an image carousel within the modal?
2. Are images useful in the pop up definition?
3. Question

##

### User / Audience
Who will be using this design? What personas / audiences are you considering?
Users of PDQ: patients and clinicians.
##

### Project Stage
- [x] Discovery
- [ ] Design
- [ ] Development
- [ ] Live

##

### Timeline
When would you need findings / insights?

##

### Resources
* Link to product brief:
* Github link:
* Screens or site: https://publicis.invisionapp.com/share/QV11KIJ53XEA#/457142048_Skin_Cancer_Treatment_-PDQ---Patient_Version_-_Desktop_Dictionary_Modal_With_Image_Carousel_-_1

##

### Additional Notes
*Any other comments or notes if needed:*

---
>Section to be completed by user research after ticket creation
### Research Activity
- [ ] Intake and Approach
- [ ] Research plan 
- [ ] Draft tasks, guides, materials
- [ ] Recruitment
- [ ] Study launch
- [ ] Analysis and report

**Comment by VictoriaSunNIH** [comment]
We will await more designs from the carousels before going forward with this

**Comment by anthonycuellar** [comment]
Update from @Salazarsi: she is checking in with @blilianyu on Monday

**Comment by blilianyu** [comment]
@anthonycuellar @Salazarsi This is on hold until carousels are approved. See @VictoriaSunNIH's comment above.

**Comment by anthonycuellar** [comment]
We are okay to move forward on this with Lynn's approval. @Salazarsi will be leading this work.
