### ISSUE TITLE
Spike: Investigate Linking in Image Credits

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#225]
## In order to link text in credits Drupal needs to accommodate linking and the text to be displayed for the link(s).

*Examples:*
* *Source: In order to link to DOI or other source urls in the credit, we need to accommodate a URL.
* *Licensing: In order to link to licensing in the credit, we need to accommodate a URL.
* * *Licensing: In order to link to licensing in the credit, we need to accommodate the text to display for the URL.
* Source example where URL can exist without display text (ex: "Source link"): https://www.cancer.gov/news-events/cancer-currents-blog/2021/medulloblastoma-low-dose-volume-radiation 
* Get report on how often source field is populated. Could we repurpose? **Not likely, it is used on 455 images.**
* Licensing example where URL cannot exist without display text (ex: "CC 4.0" this text would be linked to the licensing info) https://www.cancer.gov/news-events/cancer-currents-blog/2021/jaw-osteonecrosis-zoledronic-acid

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Additional Notes:
* note 1

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by anthonycuellar** [comment]
@VictoriaSunNIH

**Comment by mworrest** [comment]
Attached report from Min. There are 455 images that have the source field populated so repurposing it to display on the front end may not be an option. 
[image_source.csv](https://github.com/NCIOCPL/ncids/files/7122900/image_source.csv)
![credit-source-license](https://user-images.githubusercontent.com/4921685/132376534-0c19c260-cde0-4c51-bcb1-f1e5b10e9184.jpg)
