### ISSUE TITLE
Build: Breadcrumbs 

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#230]
### Build breadcrumb component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: https://designsystem.digital.gov/components/breadcrumb/

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: https://publicis.invisionapp.com/d/main#/console/21399181/451997992/preview
  * Tablet mockup: Same as desktop
  * Mobile mockup: https://publicis.invisionapp.com/d/main#/console/21399181/455032096/preview 

### Acceptance Criteria for Behaviors 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User is on  a c.gov site on a desktop device
  Given they are on an L2 or lower (e.g. Adjusting to Cancer)
  Then they will see all breadcrumbs starting with "Home" or "Página principal" and ending with the page they are on 
    And each level will be separated with a caret
    And each level will be a link to the page
    But the page they are on will not be hyperlinked
```

```gherkin
Scenario: User is on  a c.gov site on a L1 home or landing page
  Given they are on an L1 that uses the home and landing page content type (e.g. Cancer Types)
  Then they will not see breadcrumbs 
```

```gherkin
Scenario: User is on  a c.gov site on an L1 mini-landing page on desktop
  Given they are on an L1 that uses the mini-landing page content type (e.g. https://www.cancer.gov/nano/research & other doc sites)
  Then they will see the "Home" or "Página principal" breadcrumb
```

```gherkin
Scenario: User is on a c.gov site on a mobile device
  Given they are on a c.gov site on a mobile device >480
  Then they will only see the parent of the page they are on
  And it will be hyperlinked
  And there will be an arrow to the left of it
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by mworrest** [comment]
I have updated the AC's and comps to reflect the out of the box USDS component.

**Comment by anthonycuellar** [comment]
This is on hold until the navigation prototype testing is completed.

**Comment by VictoriaSunNIH** [comment]
Compelted, closed by https://github.com/NCIOCPL/ncids/pull/301
