### ISSUE TITLE
Discovery + Analysis: Video Templates

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/ncids#233]
New guidance has been released about changes to .gov requirements that video content exist on both YouTube and the .gov website. It is now acceptable for the video to live on the social sharing site and not have its own page on Cancer.gov.
Currently, our Drupal requirements automatically generate a page for a video media item (based on the selected site section and pretty URL provided). We should review how many of these video pages have content on them to help us determine if we want to keep this functionality or consider no longer having page-level videos. 

Additionally, we've received stakeholder feedback questioning the use of the small video template option on Cancer.gov. While users can click to view the video full screen or view on Youtube, there are concerns that users are watching the videos on the page and the small size isn't ideal. In gathering a video report, we should look into the pages videos are embedded on and at what template size.

### Potential Tasks
*Update the list and remove Potential once the scope of the discovery has been set*
- [x] Drupal reporting [(CGOV-14669](https://tracker.nci.nih.gov/browse/CGOV-14669)) Reports located here https://lion.box.com/s/zg1kcxxl1v1zxfzt08apmmelb68w63ci
- all video pages on Cgov (English & Spanish) and the microsites and their fields — whether the caption and body fields are filled in and what that content is
- include pages where the video is embedded and with which template option (small, medium, or large)
- [x]  ~~Synthesis of any existing analytics data around use and function~~ (note: analytics on videos is limited/not really existent)
- [ ]  High-level heuristic review of feature
- [ ]  Technical or accessibility flag
- [ ]  Best practices around use of feature
- [ ]  Persona / user empathy exploration and synthesis

### Resources and Links
https://www.notion.so/nci-ps/Video-Pages-241e777d1e894db7a767c1063ed9a3ef

### Notes
*Some complementary notes if necessary.*

**Comment by anthonycuellar** [comment]
Lindsay received the report from Min on Friday 9/10. Will find time this week, may ask Michelle and Amara for help.

**Comment by mworrest** [comment]
37/194 video pages have body field text populated.
