### ISSUE TITLE
Spike: SVG symbol approach for icon management

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#234]
## In order to manage icons within the NCIDS, devs should implement icons as svg symbols

When evaluating icon implementation, consider the following:
- performance; are assets cached?
- is it easy to add icons to the system for use?
- can icon colors be changed?

### Notes
- https://css-tricks.com/svg-symbol-good-choice-icons/

### Results of Spike
*Enter the information, or links to any (non-sensitive) files with the findings here*

**Comment by anthonycuellar** [comment]
Paul A OOO this week

**Comment by anthonycuellar** [comment]
Paul K has picked up this ticket, this work is in progress
