### ISSUE TITLE
Design: Iterate of Homepage Version B

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#235]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: [Enter user story ticket association here] 

### Description of Design request:
Based on decisions made coming out of the design sprint for homepages, please continue to iterate on "Version B"

https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1629467181607/e795f4809b026e8893c3eeb0f0d8e1df5981917f?sender=victoriasun2169

##

### List of sub-tasks (based on 9/14 conversation):
**Decisions**
- [ ] Determine if we want to create HTML prototype including creation of video content

**Design/UX  Tasks**
- [x] Consider new design or display for secondary action links in the patient and researcher sections
- [x] Add an area for NCI High Priority Initiatives (use NCA50 as the example)
- [x] Consider other images for patients/researchers while keeping the difference between warm and cool photos to indicate two sections side by side
- [x] Update link text to be more actionable in the News section ("Go to" instead of just the link to the blog/press release pages)
- [x] Change the social media icons to gold color but maybe a different treatment
- [x] revisit covid banner links — we currently have 4 links (2 to cgov pages; 1 to cdc; 1 to nih)

**Content Tasks** (Victoria / @lburack to set up meetings to discuss content selection with content owners)
- [x] Determine if we could develop content for newly diagnosed (continuing convo from CGov Platform meeting on 9/14)
- [x] Do we need to add training content to researchers? What about the CCT chatbot?
- [x] Determine which titles would display for the "secondary" news cards, and the content strategy for better title display since these wont have descriptions

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by VictoriaSunNIH** [comment]
Next step - regroup on what we are iterating on. @VictoriaSunNIH

**Comment by anthonycuellar** [comment]
There is a meeting tomorrow with Lynn and Fedora + team to discuss

**Comment by VictoriaSunNIH** [comment]
@russellwyatt , @mworrest , @lburack  - I've captured our notes in this ticket as subtasks for this sprint, but do look at https://publicis.invisionapp.com/share/JK11JWTCTSHC#/screens/456993454/comments/145281923 for more detailed comments.  Thanks!

**Comment by anthonycuellar** [comment]
Design is moving forward

**Comment by russellwyatt** [comment]
Desktop Explorations for static images and video.
![Static Image](https://user-images.githubusercontent.com/87999420/134925344-c16feecf-b373-4fd4-bd94-4244dc983fb9.png)
![Static Image 2](https://user-images.githubusercontent.com/87999420/134925389-d3514782-b398-4228-8e98-6b544619aae6.png)
![Static Image 3](https://user-images.githubusercontent.com/87999420/134925395-3fd253ca-6c03-44f3-842a-982c936c0ad8.png)
![Video 2](https://user-images.githubusercontent.com/87999420/134925406-dd32a410-7d56-4bd3-88c4-44c56793b2f6.png)
![Video](https://user-images.githubusercontent.com/87999420/134925408-865175ba-0d1d-4927-8e71-50cc05231ad8.png)

**Comment by russellwyatt** [comment]
Mobile explorations.
![Static Image](https://user-images.githubusercontent.com/87999420/134925562-0c67e83f-0120-4912-87dc-2640e1e973a8.jpg)
![Video](https://user-images.githubusercontent.com/87999420/134925564-eeddfc7f-ed8a-4dbb-8b2c-754447024366.jpg)
