### ISSUE TITLE
Discovery: Meet with Blog Team on Intro Text

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#238]
# Intro Text on Articles and Blogs

Schedule meeting with Becky + blog team to define the use for intro text. Ask Becky if additional content writers from her team should be included for perspective on intro text for Articles.  Decide whether there should be two versions of intro text (for articles and blogs separately), or if they can be the same.

### Potential Tasks
*Update the list and remove Potential once the scope of the discovery has been set*
- [ ]  Drupal reporting
- [ ]  Synthesis of any existing analytics data around use and function
- [ ]  High-level heuristic review of feature
- [ ]  Technical or accessibility flag
- [ ]  Best practices around use of feature
- [ ]  Persona / user empathy exploration and synthesis

### Resources and Links
*Links to related content on Notion, mockups*

### Notes
*Some complementary notes if necessary.*

**Comment by anthonycuellar** [comment]
Looking for a meeting time, may repurpose an existing meeting on Tuesday 9/14 to discuss with blog team

**Comment by anthonycuellar** [comment]
Meeting being scheduled today.
