### ISSUE TITLE
Create HTML prototype for Homepage Iteration

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#240]
Work with the design team to create a more interactive HTML prototype of the homepage design from https://github.com/NCIOCPL/ncids/issues/235, to be used in user testing.

**Parent Issue:** #235

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH is this a technical task?

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo  - yes, the intention is to add more details once we have finalized the comps.  Putting this on hold until designs are done.

**Comment by VictoriaSunNIH** [comment]
Convert to prototype ticket when ready

**Comment by VictoriaSunNIH** [comment]
Closing - we will test using comps only
