### ISSUE TITLE
Create a measurement/feedback plan for navigation, header and footer changes

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#242]
Part of planning the launch of the new navigation, header and footer for Cancer.gov, we will need to think through a way to collect feedback that allows us to measure the impact of our changes.  This ticket is to create the measurement plan from a feedback collection, analytics and SEO standpoint and make sure we have measurable outcomes that we can review once the changes launch.

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

**Comment by VictoriaSunNIH** [comment]
We will need this before we launch in late december 2022/early jan 2023

**Comment by meglake** [comment]
Moving to backlog and we'll readdress this ticket in a future sprint once MVP 1 timeline is determined.

**Comment by laurelthrash** [comment]
Target to discuss during backlog grooming in Sprint 41.

**Comment by laurelthrash** [comment]
Confirmed with @sarinapadilla that this task is complete. Analytics team has the measurement/feedback plan in place and it is in progress. Going ahead and closing out this ticket. Cc: @meglake
