### ISSUE TITLE
Discovery: Analytics for Landing Pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#243]
# Landing Pages - gain insights into what users are clicking through on landing pages.

Please gather analytics on user interactions for the following pages:

- https://www.cancer.gov/about-cancer
- https://www.cancer.gov/research
- https://www.cancer.gov/grants-training
- https://www.cancer.gov/about-nci
- https://dceg.cancer.gov/fellowship-training
- https://dceg.cancer.gov/news-events
- https://dceg.cancer.gov/
- https://www.cancer.gov/pediatric-adult-rare-tumor/
- https://www.cancer.gov/rare-brain-spine-tumor/
- https://www.cancer.gov/nano

Based on conversations, Lynn would like for us to think about the DOC homepages as part of this assessment, so I have included those URLs in here as well.

### Potential Tasks
*Update the list and remove Potential once the scope of the discovery has been set*
- [ ]  Drupal reporting
- [ ]  Synthesis of any existing analytics data around use and function
- [ ]  High-level heuristic review of feature
- [ ]  Technical or accessibility flag
- [ ]  Best practices around use of feature
- [ ]  Persona / user empathy exploration and synthesis

### Resources and Links
*Links to related content on Notion, mockups*

### Notes
*Some complementary notes if necessary.*

**Comment by nicolecrom** [comment]
PPT added to notion https://lion.box.com/s/qzfixsuqkdia1k3rz9fgttjehar2tcfe
