### ISSUE TITLE
New Prototype Navigation HTML/JS Setup

### ISSUE THREAD

**Issue by karlikpj** [NCIOCPL/ncids#263]
# New Prototype Navigation HTML/JS Setup

Because of the timeframe and current scope of the mobile nav / this prototype should be more inline with what the production version will be. IE remove react components using state and update to vanilla javascript / html and dom elements. 

This will include initial work for.
- Json / Data fetching or API 
- Sample static HTML for all states of navigation
- Basic JS for navigating up and down navigation nodes 
- fallbacks if required.

> **ESTIMATE** TBD

### Resources:
Invision mocks https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens

### Prerequisites
Original spike task to see if Gatsby (prototype site) can get all navigational links for demo / pros and cons around this.
https://github.com/NCIOCPL/ncids/issues/251

**Comment by bryanpizzillo** [comment]
This has been done and it now is published on netstorage.
