### ISSUE TITLE
Design: Update Language Toggle based on guidance

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#264]
Update the language toggle design based on the feedback recieved from an email from Fedora on 10/14:

The font for the Spanish toggle is pretty small. Especially on the desktop version, it looks like the font size is limited by the height of the “official website” header at the top of the page. I know that when the DOJ Civil Rights Division complaint portal was redesigned recently, they also put the non-English language indicators in the official website header, but there they changed the background color to black and made the text yellow so it would stand out more. I know those are not our colors but how can we make the toggle more noticeable? Ideally, it should be a button.
 
BTW, this is still in draft, but these are the guidelines from the multilingual group so far:
Websites with 2 languages:

Format Style:
Button 
Placement: 
Top right corner in all screen resolutions for consistency. Users accessing the site with assistive technology will have the option to switch to their preferred language before they read the rest of the content on the page.
Implementation/Functionality:
For easier implementation, make the language access button a single/independent element.
The button should take users to an equivalent page (toggle between pages with the same/similar content, or other pertinent resources)
Accessibility/Usability:
There should be enough color contrast between the button, the text inside the button, and the background.
Recommendation: provide a visual element that shows when text is a link. Example: permanent underline text or when hovering.
If the text visually will be presented as a button but coded as a link, it is recommended to add ARIA role="button" so that screen readers announce it as a button. Additionally, JavaScript will also need to be added so that keyboard users can activate the button using both the Enter and Spacebar keys. See for reference: https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html?cm_mc_uid=79615163929714381992345&cm_mc_sid_50200000=1449171451
The language of the page should be identified using the HTML lang attribute (<html lang='en'>, for example) Please see the link for reference https://www.w3.org/WAI/WCAG21/Techniques/html/H57
If the page is presented in the English language and some content/words are presented in different languages, then the second language should be defined using the lang attribute on a <span> tag wrapping the relevant text (e.g. “<span lang="es">Hola</span> means Hello”). Please see the link for reference  https://www.w3.org/WAI/WCAG21/Techniques/html/H58
 
Iconography:
Do not use any icons/graphics as they may mean/represent different things to people that share a language, but not a culture.
Languages:
Capitalization: The name of the language on the button should be capitalized. Example: English, Spanish, Italian.

**Comment by mworrest** [comment]
Build component ticket located here: https://github.com/NCIOCPL/ncids/issues/231

**Comment by mworrest** [comment]
Build component ticket located here: https://github.com/NCIOCPL/ncids/issues/231
