### ISSUE TITLE
Research: User Testing for Mobile Nav Proto

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#266]
> Feature/Main User Story: As a user, I want to find content easily within the structure of NCI's content.

### What do you want to learn from this research?
List the questions you would like to answer

1. Are users able to find content? 
2. Question
3. Question

##

### User / Audience
Who will be using this design? What personas / audiences are you considering?
Every user of cgov and docs
##

### Project Stage
- [x] Discovery
- [x] Design
- [x] Testing
- [ ] Development
- [ ] Live

##

### Timeline
When would you need findings / insights?

##

### Resources
* Link to product brief: https://nci-ps.notion.site/Plan-User-Testing-for-Mobile-Nav-Proto-0a6d5fc7e4724cb986c52e8564ad39f9
* Github link: https://github.com/NCIOCPL/ncids/issues/255
* Screens or site: https://designsystem-dev.cancer.gov/nav-proto/homepage

##

### Additional Notes
*Any other comments or notes if needed:*

---
>Section to be completed by user research after ticket creation
### Research Activity
- [x] Intake and Approach
- [x] Research plan 
- [x] Draft tasks, guides, materials
- [x] Recruitment
- [x] Study launch
- [ ] Analysis and report

**Comment by mworrest** [comment]
Test launched today.

**Comment by VictoriaSunNIH** [comment]
Closing as completed!
