### ISSUE TITLE
Design: Page Options

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#27]
> **ESTIMATE** 3 Story Points 

> Feature/Main User Story: [Enter user story ticket association here] 

## Feature description
Persistent page options - allows user to print, email, and share to social media. Font size adjustment available on certain content types.

## Description of Task to be worked on
Propose a design for the visual and function of page options. May include recommendations to add or remove features. 

### Problems to solve + Questions to Answer
Documented on Notion: https://www.notion.so/Page-Options-acbf5b361da143f6ae4f26c520c14231

## Sub-Tasks
*Add links to related tickets as needed.* 

- [ ]  Draft needed internal documentation
- [ ]  Publish completed component in DSM

## Inputs and References
*Links to discovery or research work to consider*
* Mural: https://app.mural.co/invitation/mural/publicissapient7269/1613685599666?sender=claireblaustein5539&key=9c64f6b7-7c3a-4512-84e2-75d19938bbc1
- Discovery Ticket: Discovery: Page Options #32

* Other sites using USWDS: https://designsystem.digital.gov/getting-started/showcase/all/
* Healthcare.gov has email and print at the top on desktop but drop them on mobile: https://www.healthcare.gov/lower-costs/save-on-monthly-premiums/
* medicare.gov has print on desktop, drops it on mobile.
* HHS, NIH, DHS, medicaid.gov use addthis on all breakpoints (see HHS and NIH screenshots below).
* EPA has facebook, twitter and email at the top on all breakpoints.
* USCIS, CIA, USDA has no page options.
* GSA has options at the bottom of the page on all breakpoints.
![Screen Shot 2021-04-20 at 3 29 34 PM](https://user-images.githubusercontent.com/4921685/115453139-4745a600-a1ed-11eb-9126-78d3f3d497ee.png)
 
*  whitehouse.gov has sticky sidebar on right with facebook, twitter, and link copier on desktop, drop it on mobile. They have a contrast editor and font resizer as a sticky sidebar on the left on desktop which switches to the right on mobile.
![Screen Shot 2021-04-20 at 3 48 46 PM](https://user-images.githubusercontent.com/4921685/115455617-2fbbec80-a1f0-11eb-9c18-5c7a702127b5.png)
![Screen Shot 2021-04-20 at 3 49 36 PM](https://user-images.githubusercontent.com/4921685/115455619-30548300-a1f0-11eb-87b3-6f73e5effbcf.png)

* Department of Commerce has a few options at the bottom of the page on all breakpoints:
![Screen Shot 2021-04-20 at 3 25 18 PM](https://user-images.githubusercontent.com/4921685/115452693-bf5f9c00-a1ec-11eb-81e4-ae77bfa200fe.png)

* NIH: https://www.nih.gov/news-events/news-releases/large-clinical-trial-study-repurposed-drugs-treat-covid-19-symptoms
![nih-page-options](https://user-images.githubusercontent.com/4921685/115451980-dd78cc80-a1eb-11eb-8b17-34bfc6f01ff2.jpg)

* HHS: https://www.hhs.gov/programs/hipaa/index.html
![hhs-page-options](https://user-images.githubusercontent.com/4921685/115452163-13b64c00-a1ec-11eb-93cf-4f8962c41e67.jpg)

### Design Research & Inspiration
*Space to add inspiration, moodboards,etc*

### Design Functionality
*Describe how the design should function, e.g. color changes on hover*
1. Specification
2. Specification
3. Specification

### Design specs / InVision
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*

1. Desktop: https://publicis.invisionapp.com/share/KN10COU5UYCW
2. Mobile: https://publicis.invisionapp.com/share/3C10NGGUXTYQ

### Assets
- Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*

**Comment by mworrest** [comment]
During the client demo today, it was determined that the social media icons were not needed in the page options. We have simplified the page options to print and email on desktop and email on mobile in the prototypes. We will talk to CIS then the FCI team to gain more insight.
Desktop: https://publicis.invisionapp.com/share/KN10COU5UYCW#/450121241_desktop_-_No_Dropdown
Mobile: https://publicis.invisionapp.com/share/3C10NGGUXTYQ#/450121813_2-Mobile

**Comment by blilianyu** [comment]
During the client working session today, it was determined that page options for email were not needed on mobile in the prototypes. We will rely on native share options.
