### ISSUE TITLE
Build: Create `all` scss partial for usa-list

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#271]
### Issue description
*Description of the issue*

> **ESTIMATE** TBD

### What's the expected change?
- Ability to import all lists with one partial.

### What's the current functionality?
- Each list is imported individually

### Related Tickets
*  #197 
* #241

**Comment by meglake** [comment]
Need to look into to see if this is still needed during release 2 work.

**Comment by sarinapadilla** [comment]
We haven't made any changes from USWDS, and with USWDS 3.0 we will be using their component instead of our own. Closing this ticket!
