### ISSUE TITLE
Design: Alerts & Notifications

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#275]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: [Enter user story ticket association here] 

### Description of Design request:

Review the alerts/notifications area in USWDS and create a build ticket for the variants we will need to build for the various alerts/notifications. This should include Covid alert, Shutdown alert, etc.

This is what the USWDS alerts look like. Nothing is aligned properly. We need variants on the alerts.
![Screen Shot 2021-12-02 at 11 27 08 AM](https://user-images.githubusercontent.com/4921685/144462709-9396594b-a32f-41c5-9f5c-bb734d0e41dd.png)

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Sub-Task
- [ ] Sub-Task
- [ ] Sub-Task

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. https://publicis.invisionapp.com/share/W3124BWJZGAH
2. InVision link
3. InVision link

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

**Comment by mworrest** [comment]
We have gotten approval on design. Writing AC's now.

**Comment by mworrest** [comment]
We are tracking the design bug with USWDS in ticket 4642 and awaiting their fix for the alignment of icons and text within the banner and alerts. They may also decide not to fix it :(
