### ISSUE TITLE
Design: Landing Pages (About Cancer, Grants & Training, myPART, NCI-CONNECT, DCEG Fellowships & Training)

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#283]
> **ESTIMATE** remaining work as of 3/2 is a 1

> Feature/Main User Story: Design Landing Pages (About Cancer, Grants & Training, myPART, NCI-CONNECT, DCEG Fellowships & Training)

### Description of Design request:
Design Landing Pages (About Cancer, Grants & Training, myPART, NCI-CONNECT, DCEG Fellowships & Training). These are different from the NCI homepage because they do not have the dual-audience that the homepage has.
##

### List of sub-tasks:
*Add links to related tickets below*
- [x] About Cancer
- [x] Grants & Training
- [x] myPART
- [x] NCI-CONNECT
- [x] DCEG Fellowships & Training
- [ ] DCEG homepage

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

@VictoriaSunNIH @anthonycuellar

**Comment by russellwyatt** [comment]
Link to the latest and greatest: [Landing Page Designs](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1638306879101/4adb7154efb0319ee806fbcd3052a180a57fb137?sender=u9aaac5df27e56121c2bb6797)

**Comment by VictoriaSunNIH** [comment]
Next steps: Complete meetings with DOCs to discuss the design.

**Comment by meglake** [comment]
This ticket is dependent on work being done in #338. Will add to sprint 25 to complete.

**Comment by meglake** [comment]
Closing out ticket as remaining tasks will be handled as part of #366
