### ISSUE TITLE
Add Vulnerability Disclosure link in footer under Policies

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#284]
### Issue description
Client requested a new link in the footer. "Vulnerability Disclosure" should be the last link under the Policies list. It should link to [awaiting link from Lynn. she doesn't have it yet] 
Updated comps here: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062769_Header_-_Footer_-_Desktop 

> **ESTIMATE** TBD

### What's the expected change?
- new link "Vulnerability Disclosure" should be the last link under the Policies list

### What's the current functionality?
- the link does not exist

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
![Screen Shot 2021-12-07 at 9 47 07 AM](https://user-images.githubusercontent.com/4921685/145050741-35a2ce46-76bc-4f5f-ac5f-3633f328c677.png)
![Screen Shot 2021-12-07 at 9 47 19 AM](https://user-images.githubusercontent.com/4921685/145050742-4befeda0-e2c6-47cb-afee-9cf89fb9496d.png)

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by VictoriaSunNIH** [comment]
Closing as covered in platform
