### ISSUE TITLE
Design: Sub-branding for DOC sites

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#287]
> **ESTIMATE** 8 (Goal is to find and comp a solution for a client review by end of sprint)
Discovery Ticket: #370 
> Feature/Main User Story: As a user, I want to know which site I am on. 
As a site owner, I want to communicate the program while showing its relationship to NCI and the DOC.

### Description of Design request:
Need a solution for branding on sites like these that have the same (CCR) logo:

https://www.cancer.gov/rare-brain-spine-tumor/
https://www.cancer.gov/pediatric-adult-rare-tumor/

Want to move away from the layer cake ribbon treatment which becomes more prominent on mobile.

DOC Microsite to Comp:

- Nano
- NCI-CONNECT
- MyPART
- Physics
- DCEG (update only for changes to header/footer since last comps)

##

### List of sub-tasks:
*Add links to related tickets below*
- [x] Update MVP 2 comps based on meeting notes (see comment from 4/20)
- [x] Create new MVP 1 comps to show release 1 changes plus header/footer updates from 4/20 meeting notes (in ticket comment: https://github.com/NCIOCPL/ncids/issues/287#issuecomment-1104023762) and the follow change:
-- For MyPART and NCI-CONNECT only - remove tagline on banner image and replace with 'A Center for Cancer Research Program' 
- [x] Complete comp refinement
- [x] Internal review 
- [x] Review MVP 1 and updated MVP 2 comps with Lynn
- [x] Review MVP 1 and 2 comps of MyPART and NCI-CONNECT with Li/CCR (Megan to set up meeting)
- [ ] NOTE - If NCI-CONNECT solution is approved then a blended program logo will also need to be created for Spanish (will need this to be translated).

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. _To be added_ 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. _InVision link to be added_
2. Mural Board: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1649863936838/ecee073784b1809475f409c51599bb4473c4558b?wid=0-1650900382853&outline=open
##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by VictoriaSunNIH** [comment]
@mworrest - I don't believe we have addressed this yet, but please confirm. Thanks!

**Comment by meglake** [comment]
@mworrest - based on feedback from 4/19 meeting (see notes in ticket #370) please update microsite comps to include blended logos with the program name only (not DOC name) and add the DOC name to the footer 'DOC at the National Cancer Institute'.

Additional footer work will be completed in ticket #424

**Comment by meglake** [comment]
Updates to make to microsite comps from 4/20 meeting with Lynn and Anna:
**Nano:**
- Program blended logo: Nanodelivery Systems and Devices
- H1: Nanodelivery Systems and Devices (remove branch)
- H2: Cancer Imaging Program
- Footer: Change footer to mimic new Cgov footer and add link to DCTD (spell out DOC name) under 'About' 

**NCI-CONNECT:**
Option 1:
- Program blended logo: 1. NCI-CONNECT 2. Comprehensive Oncology Network Evaluating Rare CNS Tumors
- H1: NCI-CONNECT Rare Brain & Spine Tumor Network
- H2: Center for Cancer Research
- Footer: Change footer to mimic new Cgov footer and add link to CCR (spell out DOC name) under 'About' 
 
Option 2 [Note - this is the option we want them to go with]:
- Same but remove H2
 
**MyPART:**
Option 1:
- Program blended logo: 1. MyPART 2. My Pediatric and Adult Rare Tumor Network
- H1: MyPART - My Pediatric and Adult Rare Tumor Network
- H2: Center for Cancer Research
- Footer: Change footer to mimic new Cgov footer and add link to CCR (spell out DOC name) under 'About'
Option 2 [Note - this is the option we want them to go with]:
- Same but remove H2
 
**Physics:**
- Program blended logo: Physical Sciences - Oncology Network
- H1: Physical Sciences - Oncology Network 
- H2: Division of Cancer Biology
- Note: need to ask DCB if we can lose the dash or what should the program be called - Lynn will email Claire

**Comment by meglake** [comment]
@mworrest - per email thread (Subject line: Physical Sciences in Oncology vs PS-ON) ON 4/20 please use "Physical Sciences in Oncology" as the name for the blended logo and in the footer of the Physics site. Thanks!

**Comment by mworrest** [comment]
NCI CONNECT needs the logo in Spanish, too.

**Comment by mworrest** [comment]
Attached the updated comps and added them to the mural https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1649863936838/ecee073784b1809475f409c51599bb4473c4558b?wid=0-1650900382853&outline=open


![CCR NCI-Connect Rare Brain   Spine Tumor Network Copy](https://user-images.githubusercontent.com/4921685/165128060-a97b8f00-b524-46f6-a12e-d600fa483887.jpg)
![CCR NCI-Connect Rare Brain   Spine Tumor Network](https://user-images.githubusercontent.com/4921685/165128064-c464dc7e-adbd-409a-a543-9e51667e9cf8.jpg)
![MyPart - Desktop Copy](https://user-images.githubusercontent.com/4921685/165128065-51b2370b-ae5f-4496-bd5b-15e7cffd0d55.jpg)
![MyPart - Desktop](https://user-images.githubusercontent.com/4921685/165128066-754685ac-974d-4f8d-a2e2-da447fc01929.jpg)
![Nano Homepage - Desktop](https://user-images.githubusercontent.com/4921685/165128067-8542e81f-8781-4273-bd2e-8740906321ff.jpg)
![PSON Homepage - Desktop](https://user-images.githubusercontent.com/4921685/165128070-961e286f-d96f-41fd-890e-05db2bfab2c8.jpg)

**Comment by meglake** [comment]
@mworrest Noting that logo sizing in header will be dependent on work done in #433 and that we need to get approval on NCI-CONNECT and MyPART blended logo before proceeding with sizing. Also, we should hold on further reviews until icon styling is confirmed as part of #431 all other updates should be made in the meantime.

**Comment by mworrest** [comment]
@meglake, @blilianyu helped me with the comps and they are ready for review: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1649863936838/ecee073784b1809475f409c51599bb4473c4558b?wid=0-1650900382853

**Comment by mworrest** [comment]
@blilianyu and I updated MVP1 comps to include #f0f0f0 as the background color.

**Comment by meglake** [comment]
@mworrest, next steps noted below:
* Update wording in footer link to DOC to be: Visit _DOC ACRONYM_
* NCI-Connect and MyPART: Update MVP1 comp to include this text in the hero image '_PROGRAM NAME_ is a Center for Cancer Research Program'
* PSON: Update footer to be consistent with other footer wording/order 
* Create presentation Mural for CCR program microsites only (labeling per Slack message)
* Create comp PDFs for CCR program microsites only with file names per Slack Message
* Megan to set up meeting with Li

**Comment by mworrest** [comment]
I created the new mural for CCR: https://app.mural.co/invitation/mural/publicissapient7269/1651597352249?sender=michellegallo6566&key=595377ae-6a80-480a-a921-e44c71bdfc71

**Comment by meglake** [comment]
@mworrest - Next steps per meeting with Li/CCR:
* Update MVP 1 comps to include this wording 'NCI-Connect is a part of the Center for Cancer Research' (same for MyPART)
* Send all comps to Megan for delivery
* Write up for why we are changing logos - Megan to start a slack thread to coordinate on this messaging

**Comment by mworrest** [comment]
I've updated the murals and attached the updated pdf for Li.
[CCR - NCI-CONNECT and MyPART comps.pdf](https://github.com/NCIOCPL/ncids/files/8633868/CCR.-.NCI-CONNECT.and.MyPART.comps.pdf)

**Comment by mworrest** [comment]
[CCR - NCI-CONNECT and MyPART comps.pdf](https://github.com/NCIOCPL/ncids/files/8641578/CCR.-.NCI-CONNECT.and.MyPART.comps.pdf)
Latest request from Lynn was to use the MVP1 acronym logos but with the text in the hero that is on the live site.

**Comment by meglake** [comment]
Hi @mworrest  we have approval to move forward with CCR microsites using the following blended logo language:
* NCI-CONNECT
* MyPART

See approved stickies on Mural board: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1651597352249/cce47102ed422eb7d69b557f3ffeec56489ba83c?sender=meganlake7790

@mworrest are there any other items to complete to close out this ticket?

**Comment by mworrest** [comment]
These are the final, approved comps for doc sites which I can work with devs on. Since the footer and hero text can be edited in the cms, design just needs to hand off the logo files to dev. @olitharp-nci please let us know if we are missing anything you/dev needs.

**MVP 1**

![image (13)](https://user-images.githubusercontent.com/4921685/174189472-e7c02a72-d2bd-4612-b22c-82cd0dc06bfa.jpg)

![image (15)](https://user-images.githubusercontent.com/4921685/174189501-cfec6970-d975-49e0-9e51-147688ae668d.jpg)

**MVP 2**

![image (14)](https://user-images.githubusercontent.com/4921685/174189541-d370c6fd-122c-41d8-9a89-b087362a15ee.jpg)

![image (16)](https://user-images.githubusercontent.com/4921685/174189550-316f3b30-b19c-406a-9f35-421ece74c149.jpg)

**Comment by laurelthrash** [comment]
Ticket is complete and will be closed. What was needed was pass to #433, which is also closed.
