### ISSUE TITLE
ncids-react does not properly lint

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#289]
### Issue description
> **ESTIMATE** TBD

The `.prettierrc` is missing and thus `ncids-react` does not correctly lint the code. As such there are hundreds of double-quoted strings.

The linting config should be updated to use https://github.com/NCIOCPL/cgov-standards-xt/tree/develop/packages/eslint-config-react. Additionally it should also use the .prettierrc
```
{
	"jsxBracketSameLine": true,
	"trailingComma": "es5",
	"tabWidth": 2,
	"semi": true,
	"singleQuote": true
}
```

**Comment by sarinapadilla** [comment]
This will be covered by https://github.com/NCIOCPL/ncids/issues/1235
