### ISSUE TITLE
Design: Pagination

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#29]
## In order to <achieve some goal> <a system or persona> needs to <some action>.

*Examples:*
* *In order to split the collection curve wizard story, the tech lead needs to do some detailed design. (Just enough to split the story.)*
* *In order to estimate the content task story, the PO needs to do identify how many pages are affected. (Just detailed enough to estimate the story.)*

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Additional Notes:
* note 1

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by claireblaustein** [comment]
Old ticket - not necessarily relevant. Closing
