### ISSUE TITLE
Change theme dark and darker colors

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#294]
### Issue description
While changing the footer colors from system to theme colors, we need to change the hex values.

This needs to be changed because we switched over to the theme colors instead of system colors and realized the colors needed to be adjusted.

> **ESTIMATE** 1

### What's the expected change?
- Primary dark: cerulean 70 #004971
- Primary darker: cerulean 80 #00314B
- Accent cool dark: navy 70 #284976
- Accent cool darker: navy 90 #06162D

### Related Tickets
* https://github.com/NCIOCPL/ncids/issues/290

cc @VictoriaSunNIH

**Comment by VictoriaSunNIH** [comment]
@mworrest , @arcepaul  - does this also need to be part of the larger conversation we need to have around the colors in the system?

**Comment by VictoriaSunNIH** [comment]
This will be done as part of #352
