### ISSUE TITLE
Enabler: Need outline button for secondary color theme

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#295]
### Issue description
We are starting to use an outline button using the secondary color so we need to support that. @mworrest to check with USWDS on the status of their implementation: https://github.com/uswds/uswds/discussions/4451
This is the pr they have on hold: https://github.com/uswds/uswds/pull/4257

> **ESTIMATE** 2

### What's the expected change?
- Need outline button for secondary color theme.

### What's the current functionality?
- Only have primary outline and inverse outline.

### Additional details / screenshot
- ![Screenshot]()

## Approach
This should be implemented by making the css for the combination of `usa-button usa-button--secondary usa-button--outline`. When USWDS finally implements this, we should be able to remove our CSS.

cc @VictoriaSunNIH

**Comment by meglake** [comment]
@mworrest Is this ticket still needed?

**Comment by meglake** [comment]
Moving to release 2 to look into and determine if this ticket is still needed and what next steps are.
