### ISSUE TITLE
NCIDS Icons are not usable by modern build tools

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#304]
### Issue description

Currently the NCIDS icons are baked into a single sprite svg image. There is no way to use just one icon without the rest using this approach. Additionally, it does not appear that these sprites are usable in the sass files as uswds uses the `place-icon` method for referencing and masking icons. This uswds method requires the images be separate files. Using some images for some things and some for others is confusing.

At the end of the day, the ncids-css package **should** build a sprite for those wanting to use our documented approach (`<svg> tags in the DOM).  For those that would like to use a CSS-based Sprite approach in SASS we should allow them to do that as well, and provide the separate images and a way to reference them in sass. (I mean USWDS uses CSS sprites as well, and our team is doing that in places too.)

This issue was identified during our fix for Storybook images combined with a noticed bug in the example NCI Big Footer HTML, which uses the sprite approach and not the `<svg>` tag approach, with incorrect sprites.

### Tasks

- [ ] @arcepaul to investigate the current process for using icons/sprites

### TODOS:
* Create a new `$ncids-image-path` variable for others to override. This should default to `../img`. This will be used as the `path` property for any ncids icon object.
   * NOTE: In USWDS If the `path` is not specified on the icon-object passed into `place-icon` then it will use NCIDS `$theme-image-path` as the default path.
   * NOTE 2: Having 2 different paths allows us to have separate locations for USWDS images and NCIDS images for use in webpack configurations.
* create documentation on how to use `place-icon` on the icon component page, or somewhere else if it makes more sense. But there is 0 documentation on how to use it.

**Comment by meglake** [comment]
This should be replaced by https://github.com/NCIOCPL/ncids/issues/434, this ticket can be closed out once 434 is completed and confirmed that this ticket is replaced.

**Comment by meglake** [comment]
Moving to release 2 tickets per ticket #434

**Comment by bennettcc** [comment]
Closing per discussion on 11/7 - no additional action is required for this ticket
