### ISSUE TITLE
Enabler: pulls symbols out of svg-sprite into separate svgs

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#310]
There are a number of sprites that make up the current svg sprite in ncids-css.  Pull out the symbols and break each out into its own respective standalone svg.  These svgs should be available in the ncids-css dist.

> **ESTIMATE** TBD

**Comment by meglake** [comment]
@arcepaul, is this ticket still needed? If so, is it priority for MVP 1 launch?

**Comment by sarinapadilla** [comment]
Closing this ticket, as we aren't sure whether we need more details for implementing this for MVP1.
