### ISSUE TITLE
Discovery: Survey on Cancer Types Landing Page 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#321]
# Survey on Cancer Types Landing Page 
To better understand the journey of users who are coming to the cancer types landing page straight from google results, we would like to add a survey to capture information from those users.

### Potential Tasks
- [x] Write up summary of what we are hoping to learn and who we are trying to reach (@russellwyatt , @blilianyu , @mworrest )

**Goal**
How might we enable users to complete tasks (aka finding cancer type) as quickly and easily as possible?

**Problem Statement**
NCI provides a dedicated page of an A-Z list for cancer types to assist users that are looking for additional information related to a specific cancer type, but 52% of the page entries received no engagement. We suspect the organization of the content and lack of supporting features are not what users are expecting to be presented with when landing on this page.

**Hypothesis**
Users that enter the A-Z landing page will engage with the content by selecting the appropriate cancer type within a reasonable amount of time. If we redesign the way content is organized, written in plain language, and provides additional supporting features such as a quick page search or filtering options. We believe this redesign will lead to an increase in engagement with the content and it’s features as measured by (a) clicking on a cancer type link, (b) searching for and clicking on a cancer type, (c) a reduction in the entries that leave with no engagement.

**Summary:  What we’re expecting to discover**

Our primary goal is to better understand the journey of user who are coming to the cancer types landing page straight from the search engine’s results page. We would also some specifics like to know who they are, why decided to come to the cancer types landing page, what are we doing right and wrong, and what their on-page behaviors look like.

-	Who are they?
o	Patients
o	Researchers
o	Caregivers
o	Etc
-	Why did they click on that specific link in the search engine’s results?
-	What were they expecting to see or discover when landing on the A-Z landing page?
o	Did they have a specific task or goal in mind? What was it?
-	Is the format of the page helpful? Why or why not?
-	Where are you expecting to go after clicking on the cancer type?
-	What do their interaction behaviors look like?
o	Are they scrolling to a point and then bouncing?
o	Are they using any specific feature regularly on the page?
	Index
	Common links
	 Back to top
	Menu
	Search

- [ ] Engage with VOC team to create questions and discuss how best to capture results (above + @nicolecrom)
- [ ] Launch survey
- [ ] Review results

### Resources and Links

[Survey Link](https://nci.az1.qualtrics.com/jfe/preview/SV_0GjuTEFxefN0lr8?Q_CHL=preview&Q_SurveyVersionID=current)

**Comment by russellwyatt** [comment]
@VictoriaSunNIH added to the ticket and marked task as complete.

**Comment by VictoriaSunNIH** [comment]
Launched on Friday 2/18
