### ISSUE TITLE
Design: Exit Disclaimer

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#325]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: 
 Two things to consider:
1. USWDS guidance says there should be exit links for any link not on your website.  Are we following this guidance?
2. Exit disclaimer is when you are leaving a government website. What does this look like?

### Description of Design request:
Is the USWDS icon sufficient? 
- Yes, but we may change the icon in future

And where does it show up?
- Guide Card with & without Image buttons
- Feature Card buttons
- Promo block buttons
- Cards (vertical 3-column & horizontal 2-column)
- Body links
- Footer links
- Lists
- Related Resources

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Add usage information

### Usage
*When to use component and when to use variant(s)*
- What needs an indicator for an external site?
- What needs to have a link to our linking policy?
- For every component we make, can this use the normal external indicator or does it need something else? (e.g. regardless of what is in Drupal)

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. On hover, cursor changes to pointer

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. https://publicis.invisionapp.com/share/P212EBBE7HJW#/464354622_Landing_Page_-_Desktop

##

**Comment by blilianyu** [comment]
2/22 Got Lynn & Fedora's approval for exit disclaimer. Under usage, we will not include USWDS's usage guidelines for external links

**Comment by VictoriaSunNIH** [comment]
@blilianyu - please create a component ticket
