### ISSUE TITLE
Spike: Usability test the current megamenu

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#33]
## In order to finalize requirements on the megamenu component, usability testing on the current megamenu needs to be completed so that we can answer questions about the content and mockup the megamenu. 

Thinking this effort should be coordinated with Ashley, the designers/IA/content strategists.
Discussion with clients will need to happen where we propose mirroring the mobile menu in the megamenu to decrease page load time.

*Examples:*
* *In order to split the collection curve wizard story, the tech lead needs to do some detailed design. (Just enough to split the story.)*
* *In order to estimate the content task story, the PO needs to do identify how many pages are affected. (Just detailed enough to estimate the story.)*

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Additional Notes:
* This came out of our 3/5 design demo.

### Results of Spike
*Enter the information or links to any (non-sensitive) files with the findings here*

### Related Tickets:
https://github.com/NCIOCPL/ncids/issues/9 - Design: Wireframes of Site Banner and Footer - Desktop and Mobile

**Comment by sewallaa** [comment]
I think there are lots of open questions here. One thing Claire and I were looking into is picking back up on the competitive assessment that was previously started on this topic and better understand both design best practices and the competitive landscape to aid in making some decisions here. Let's talk through an approach!

**Comment by mworrest** [comment]
Closed by new research ticket type: https://github.com/NCIOCPL/ncids/issues/59
