### ISSUE TITLE
DCEG Mockups

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#331]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: In order to describe the microsite roll-out plan, we will need a set of comps for DCEG:

### Description of Design request:

**[For dceg.cancer.gov](http://dceg.cancer.gov/) create mockups of the following by 2/11:**

- DCEG current state (no comps, just a screenshot of current site)
- DCEG turned to cgov current theme,  with the new header/footer/nav, etc. (I have swapped the theme on https://dceg-dev-acsf.cancer.gov/ for designers to get a sense of what it will look like, but we'll have to apply the new typography, and new shell)
- DCEG with new home/landing (we have this already)

This will show the progression from current theme, to interim theme, to new look/feel for home and landing pages. 

Please provide to Victoria to incorporate into a set of slides for the Redesign Stakeholder Update on 2/15.

**Current**
![scrnli_2_8_2022_10-20-45 AM](https://user-images.githubusercontent.com/87999420/153018940-1e0c4236-0397-45dd-9c9c-e1a152f2cf10.png)

**Interim**

**Future**
![image](https://user-images.githubusercontent.com/87999420/153019994-668b6a9c-2854-4eb7-8aa2-481c5a67efb4.jpeg)

**Comment by russellwyatt** [comment]
**Current**
![scrnli_2_8_2022_10-20-45 AM](https://user-images.githubusercontent.com/87999420/153018574-852e7a9e-9432-4eed-97bf-c97bc18d4ab9.png)
![scrnli_2_8_2022_10-23-53 AM](https://user-images.githubusercontent.com/87999420/153018580-a1353343-90cf-4077-914c-5451682b103c.png)

**Comment by VictoriaSunNIH** [comment]
this has been completed
