### ISSUE TITLE
Discovery: Back to Top best practices

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#333]
# Back to top practices

### Estimate: 1

We are looking at whether we should implement USWDS back to top (which is what we currently have) and determining our reasoning on why it should change if we feel there are other best practices to take into account for Back to Top.

I think we need to consider best practices and usability guidelines when applying components from USWDS. We should also include guidance from the WCAG site to see what other guidelines might be out there.

### List of sub-tasks:
*Add links to related tickets below*
- [x] Designers look into best practices to prepare conversation with client: https://app.mural.co/invitation/mural/publicissapient7269/1645199492750?sender=michellegallo6566&key=804ae6e3-50b4-4761-b9ad-44509879db86
- [x] 2/22 client meeting to discuss back to top best practices and determine next steps
- [x] Design WIP option: 
<img width="91" alt="Screen Shot 2022-02-22 at 12 18 41 PM" src="https://user-images.githubusercontent.com/4921685/155184510-3fd4d345-5468-4991-a80a-d74acbd0a092.png">
<img width="82" alt="Screen Shot 2022-02-22 at 12 18 47 PM" src="https://user-images.githubusercontent.com/4921685/155184511-6e60a3c4-05e1-4796-9133-815de08ddc39.png">

- [ ] We can use CSS to change the color of the icon depending on what background it is on so that we can produce one asset that can change (giving us more flexibility with the design).
- [ ] Can we do this functionality? (need to discuss in our meeting with devs) https://codepen.io/ig_design/pen/yrwgwO

##

**Comment by meglake** [comment]
Confirmed in 2/22 meeting that client wants to design new back to top option based on discovery and research presented in today's meeting. Created new ticket (#337) for Sprint 24 to complete this request.
