### ISSUE TITLE
Discovery: Review Survey Results for Cancer Types Landing

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#334]
# Review & Analyze Results from the Cancer Types Landing Page

Tasks:
- [ ] Set up and share dashboard view of results
- [ ] Internal sync to document actionable insights 
- [ ] Shareout with larger group (including stakeholders) (insights from survey, and painting the full picture of discovery we've done)
- [ ] Determine next steps (are we ready to conduct design burst?)

Link to the Discovery [Mural Board](https://app.mural.co/invitation/mural/publicissapient7269/1641826995692?sender=u9aaac5df27e56121c2bb6797&key=f82f84fd-e4c9-4f19-9b22-49e3c0545e88)

**Comment by VictoriaSunNIH** [comment]
Start with initial review, knowing our constraints around not having a lot of responses, and that they are mostly international at this point in time.

**Comment by nicolecrom** [comment]
[A-Z Survey 3.9.22 - Patients.pdf](https://github.com/NCIOCPL/ncids/files/8217618/A-Z.Survey.3.9.22.-.Patients.pdf)
[A-Z Survey 3.9.22 - All Responses.pdf](https://github.com/NCIOCPL/ncids/files/8217619/A-Z.Survey.3.9.22.-.All.Responses.pdf)
Attached are PDFs of the dashboard for the A-Z Survey as of 3/9 for all responses and filtered on just patients. If anyone would like to see the dashboard filtered in another way, let me know and I can provide that. 
So far the majority of respondents were looking for info on a specific cancer type. Also the top expectation for what they would see if they clicked on one of the links was info on symptoms.

**Comment by nicolecrom** [comment]
The survey is now closed. Here is the final dashboard 
[A-Z Survey 3.25.22 - All Responses.pdf](https://github.com/NCIOCPL/ncids/files/8351231/A-Z.Survey.3.25.22.-.All.Responses.pdf)
And here is an analysis of the results. 
[A-Z Survey.docx](https://github.com/NCIOCPL/ncids/files/8351248/A-Z.Survey.docx)

**Comment by VictoriaSunNIH** [comment]
Closing as complete
