### ISSUE TITLE
Design Back to Top Options

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#337]
> **ESTIMATE** Story Points 2

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Determine Back to Top options 
- [ ] Design comps with Back to Top options
- [ ] Review comps with client for approval/selection of final Back to Top solution to build

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. _To be added_

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. _To be added_

##

### Assets:
_To be added_

##

### Design Research & Inspiration:
See Discovery in ticket #333 
1. We can use CSS to change the color of the icon (not depending on what background it is on). https://css-tricks.com/basics-css-blend-modes/
Safari does not support luminosity
2. Can we do this functionality? (need to discuss in our meeting with devs) https://codepen.io/ig_design/pen/yrwgwO
This would be a future enhancement (**not for MVP**). Would need Paul A. to look into how to use as little js as possible.
3. Make it work for mobile (48 css pixels) and consider things it might compete with (CTS delighter).
4. PRODUCE ONE SVG IN BLACK AND WHITE. Tell devs what color it should be.
##

**Comment by meglake** [comment]
@mworrest to build out comp for internal page to ensure back to top solution works with page options on interior pages. Please send to the group on slack when comp is ready to review in advance of Tuesday. Thank you!!

**Comment by VictoriaSunNIH** [comment]
@mworrest to create build ticket.

**Comment by mworrest** [comment]
Build ticket created: https://github.com/NCIOCPL/ncids/issues/374
