### ISSUE TITLE
Determine and Design Padding Between Modules

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#338]
> **ESTIMATE** Story Points 3

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Determine appropriate amount of padding between modules on home/landing page
- [ ] Create comps to show padding between all possible module types that could go on home/landing page
- [ ] Review comps with client to get approval to build
- [ ] Update previous comps with updated padding as needed.

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. _To be added_

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. _To be added_

##

### Assets:
_To be added_

##

### Design Research & Inspiration:
_To be added_

##

**Comment by VictoriaSunNIH** [comment]
Scope: consider spacing across 2 comps before rolling it out across the rest to ensure we are heading in the right direction

**Comment by VictoriaSunNIH** [comment]
Completed and approved
