### ISSUE TITLE
Spike: Usability test the current mobile header

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#34]
## In order to mockup the mobile header component, usability testing on the current mobile header needs to be completed so that we can answer questions about the content and functionality of the mobile header.

Thinking this effort should be coordinated with Ashley, the designers/IA/content strategists.
A concern about the current functionality of 2 links opening overlays vs. 2 links opening links was discussed. Looking to get user feedback on that. 
![Screen Shot 2021-03-05 at 12 41 42 PM](https://user-images.githubusercontent.com/4921685/110152944-5e047a80-7db0-11eb-8fdc-6aca5d5b8521.png)

*Examples:*
* *In order to split the collection curve wizard story, the tech lead needs to do some detailed design. (Just enough to split the story.)*
* *In order to estimate the content task story, the PO needs to do identify how many pages are affected. (Just detailed enough to estimate the story.)*

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Additional Notes:
* This came out of our 3/5 design demo.

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

### Related Tickets:
https://github.com/NCIOCPL/ncids/issues/9 - Design: Wireframes of Site Banner and Footer - Desktop and Mobile

**Comment by sewallaa** [comment]
Hey. Let's talk through this a bit more. I want to understand what you are hoping to understand and then we can decide on the best way to get you answers!

**Comment by mworrest** [comment]
Closed by new research template ticket type: https://github.com/NCIOCPL/ncids/issues/58
