### ISSUE TITLE
Create Prototype template ticket

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#340]
*Description of what is to be accomplished.* Russell to create a ticket template for prototype work in GitHub and review with team to finalize.

Here is the outline of the template so far:

**Prototype Name:**
- Why we think this concept will work or improve that moment ...
	- Ex: girls are more comfortable learning from peers
- Our biggest question/unknown about this concept right now ...
	- Ex: will this be acceptable to parents and village leaders?
- Other things we want to learn about this concept ... 
	- Ex: What’s the right message? Do they use Whatsapp or Facebook more?

**Prior to Prototyping: Learning Plan**
- Top 3 learning questions this prototype is testing:
- Key metrics for success
- Testing Method
- Assumptions

**After Prototyping: Report Card**
- What we learned
	- What answers did we find to our learning questions? 
	- Did we see the results we wanted in our key metrics? 
	- Did we find out anything about our assumptions?
- Iterations
	- Based on our learnings, what do we need to change?
	- What are we taking forward from this prototype?
	- What do we need to learn next?

Link to Prototype:

	- ...

Related Issues:

	- ...

### Notes
Some PDF resources if anyone is interested:
[DesignKit_PrototypeMapping_Worksheet.pdf](https://github.com/NCIOCPL/ncids/files/8162692/DesignKit_PrototypeMapping_Worksheet.pdf)
[DesignKit_prototypereportcard_worksheet.pdf](https://github.com/NCIOCPL/ncids/files/8162694/DesignKit_prototypereportcard_worksheet.pdf)

**Comment by russellwyatt** [comment]
@meglake  I cannot add or create a new template because I do not have access to settings for the NCIDS repo.

**Comment by russellwyatt** [comment]
@meglake disregard last comment. Got it resolved.

**Comment by VictoriaSunNIH** [comment]
Done!
