### ISSUE TITLE
Redesign: Iconography Style

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#342]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: [Enter user story ticket association here] 

### Description of Design request:
Design utilitarian ("functional") and illustrative ("design") icons to align with the moodboard. Illustrative is used in infographics and for more decorative iconography like the icons on https://www.cancer.gov/about-cancer/treatment/clinical-trials/search
Utilitarian is more simplified UI icons. 
##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Meet with devs to align on next steps for icon style (new or pulling from USWDS)
- [ ] Pull in sprite and do an inventory: https://www.cancer.gov/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/dist/images/sprites/svg-sprite.svg?v=be661acc929ffdf2b03d8d9a9a5d4f5d
- [ ] Work with Aaron as he develops icon styles for factoids.

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. _InVision link TBD_

##

### Assets:
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

- Utilitarian (functional: print/email): https://publicis.invisionapp.com/d/main#/console/20597762/433527394/preview
- Illustrative (for illustration/infographic/CTS icons): https://publicis.invisionapp.com/d/main#/console/20597762/433534399/preview
- Want just paths for svgs, no bloat in the code like text or css. Paul A can review svg files to eliminate bloat.
- Icons we're using so far: https://designsystem-dev.cancer.gov/develop/components/icons
- Icons should be in single color (black) so color can be assigned on the dev side

##

**Comment by meglake** [comment]
Need to meet with devs to determine if we will be creating a new style or pulling from USWDS before moving forward with this ticket and storypointing.

**Comment by VictoriaSunNIH** [comment]
Background icons (if it's in the stylesheet) like up and down arrows in megamenu, and open/collapse in accordions, breadcrumbs, etc. are "locked in" from USWDS

If an icon conveys meaning like the search icon, we can reference whatever icon we want to.

Next steps: walk through the stylesheets together to gain understanding of what can be changed, and what is locked in

**Comment by meglake** [comment]
Next Steps - @ to look into and determine design for page options icons and social media icons. Please create these icons in single color black and connect with @mworrest on any questions. Once ready we'll review with Michelle, Paul A., Victoria, and me. If possible please complete by end of sprint (4/5) but let me know if you need more time!

**Comment by dcvijanovic1k** [comment]
Icons are ready for client review. 

Here is a page that shows the hover states of the page options + social icons: https://publicis.invisionapp.com/overview/page-options-cl1xnd9on0fwy010u2042hjob/screens

Here is a page showing static versions of these icons on the page, as well as an updated syndication icon: https://publicis.invisionapp.com/overview/Article---New-Icons-cl1xph39t0jnf010xawf25h44/screens

Advising to keep the USWDS icons in place for the Covid resources top bar; no changes have been made on these.

Any questions/comments @meglake @mworrest @VictoriaSunNIH please let me know!

**Comment by meglake** [comment]
Hi @dcvijanovic1k and @mworrest  - confirmed with Lynn that Instagram should be included in the social media icons for Cancer.gov footer. 

I see it is included in the links above so we should be good to go! @VictoriaSunNIH, any concerns with the hover states for development? If not I'll put in the change request for these new icons to be added to the footer.

**Comment by mworrest** [comment]
Did Lynn review the icons? We need client approval.

**Comment by meglake** [comment]
> Did Lynn review the icons? We need client approval.

Sorry I was jumping ahead ;) @VictoriaSunNIH, if you don't see any concerns with hover state then lets add this to the agenda for end of sprint demo to get client approval. Thanks!

**Comment by meglake** [comment]
Review set for 4/19 at 12:00pm at end of sprint meeting.

**Comment by VictoriaSunNIH** [comment]
Demo'd at 4/19 end of sprint and completed!
