### ISSUE TITLE
Design: Buttons

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#35]
## Design of atomic button element

> **Estimated Timeframe** *# of days for completion* 

### Expected Deliverables
Set of color comps for basic button types that displays all needed state  - default, active, hover, focus, disabled
Types
* Standard Button - Primary, Secondary, Accent Warm, Accent Cool, Outline, Inverse
* Button with icon - left

**Possible Needs** - May need an additional sprint?
- Button with icon - right
- Unstyled button (link)
- Icon only 

### Problems to Solve
- So. Much. Variation. 
- Need guidance to define use

### Questions to Answer
- do we need a button with icon right - usually an arrow

### Resources
- Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1611586427071/8906190b53768bef8fc4698d3c82a008cbc39439
- USWDS: https://designsystem.digital.gov/components/button/
- Comps:

### Additional Notes:
* note 1

**Comment by blilianyu** [comment]
Buttons have been updated for standard, buttons with icon left and buttons with icon right. Sketch symbols have been created.

https://publicis.invisionapp.com/share/A8UB2W74PRN
