### ISSUE TITLE
Enabler: Update the documentation site to use Gatsby 5

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#361]
# Title of Enabler
> **ESTIMATE** TBD

Gatsby 5 has been out since the end of 2022. 3.x had been unsupported since 5.x release in 2022. (Not that we have kept up to date with 3.x)

**Comment by sarinapadilla** [comment]
Moving this ticket to the MVP2 backlog, as it isn't needed for MVP1!

**Comment by bryanpizzillo** [comment]
## Investigation Notes

* `gatsby-plugin-react-helmet` has been deprecated in favor of https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/
