### ISSUE TITLE
Research: Page Option User Testing

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#367]
When reviewing back to top solution (#337) with client on 3/8 a request was made to see if location of page options location makes sense to users. Note - due to back to top solution, page options where moved to be left aligned on bottom of interior pages (top of page options are still right aligned).

### What do you want to learn from this research?
List the questions you would like to answer

1. Question
2. Question
3. Question

##

### User / Audience
Who will be using this design? What personas / audiences are you considering?

##

### Project Stage
- [ ] Discovery
- [ ] Design
- [ ] Development
- [ ] Live

##

### Timeline
When would you need findings / insights?

##

### Resources
* Link to product brief:
* Github link:
* Screens or site: 

##

### Additional Notes
*Any other comments or notes if needed:*

---
>Section to be completed by user research after ticket creation
### Research Activity
- [ ] Intake and Approach
- [ ] Research plan 
- [ ] Draft tasks, guides, materials
- [ ] Recruitment
- [ ] Study launch
- [ ] Analysis and report

**Comment by andyvanavery31** [comment]
Closed due to this being outdated.
