### ISSUE TITLE
Research: Look into user testing for images vs color/gradients

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#368]
When reviewing back to top solution (https://github.com/NCIOCPL/ncids/issues/337) with client on 3/8 a request was made to see if users are more likely to interact with content with images vs color gradients as it relates to the home and landing page design comps. Question came about as there is some concern that given the prominent use of images in this design, some DOCs might not have engaging images to use on their home/landing pages and might need to default to colors/gradients. 

### What do you want to learn from this research?
List the questions you would like to answer

1. Question
2. Question
3. Question

##

### User / Audience
Who will be using this design? What personas / audiences are you considering?

##

### Project Stage
- [ ] Discovery
- [ ] Design
- [ ] Development
- [ ] Live

##

### Timeline
When would you need findings / insights?

##

### Resources
* Link to product brief:
* Github link:
* Screens or site: 

##

### Additional Notes
*Any other comments or notes if needed:*

---
>Section to be completed by user research after ticket creation
### Research Activity
- [ ] Intake and Approach
- [ ] Research plan 
- [ ] Draft tasks, guides, materials
- [ ] Recruitment
- [ ] Study launch
- [ ] Analysis and report

**Comment by andyvanavery31** [comment]
Closing due to this being outdated.
