### ISSUE TITLE
Design: Graphic Styling Update

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#372]
> **ESTIMATE** Story Points TBD

##

### List of tasks:
- [x] Determine which existing graphics (6) to update and confirm with Lynn

1. Video thumbnails
2. Factoid (Colorectal factoids - CGOV-15886)
3. Factoid with icons
4. Infographic (From a past AP)
5. NCI At a Glance
6. Cancer Center Map

- [ ] Update agreed upon existing graphics to new color/style
- [ ] Determine next steps for graphics style guide and potential testing to conduct (note: this is just to determine the next steps and then additional tickets will be created for the additional work)

##

**Comment by VictoriaSunNIH** [comment]
Something to add to the list: video thumbnails

**Comment by VictoriaSunNIH** [comment]
This is complete
