### ISSUE TITLE
Spike: Usability test the current language toggle

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#38]
## In order to finalize requirements on the language toggle component, usability testing on the current language toggle needs to be completed so that we can answer questions about the content and mockup the language toggle. 

Consider a global dual-function or keep the toggle functionality page-specific. Consider comparing with competitors.
Thinking this effort should be coordinated with Ashley, the designers/IA/content strategists, Lynn and Fedora.

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Additional Notes:
This came out of our 3/9 design demo.

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

### Related Tickets:
https://github.com/NCIOCPL/ncids/issues/9 - Design: Wireframes of Site Banner and Footer - Desktop and Mobile

**Comment by sewallaa** [comment]
I think this would actually be best tackled through a design burst. I talk through my idea more in our Monday sync meeting, but I would not recommend usability testing at this point. It could be useful later on as a piece of a larger component. Thanks!

**Comment by mworrest** [comment]
Tracking in https://github.com/NCIOCPL/ncids/issues/47

**Comment by mworrest** [comment]
Should we reopen this ticket? @anthonycuellar @sewallaa

**Comment by sewallaa** [comment]
Hey Michelle. Are there questions around the language toggle that would answered through testing? I know Fedora had some concerns but I'm not sure those concerns are supported by what we know so far. But let's talk about if there is something that we could do to help alleviate these questions.
