### ISSUE TITLE
Create documentation page for inner pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#385]
Create a page within the NCI DS for documentation for inner pages like https://designsystem.digital.gov/templates/documentation-page/. It should include where page options go (but page options are not a DS component as part of MVP 1). We will work on page options as a component and update #215 with latest details for a future release.

Error pages are not in scope for phase 1.  This is a backlog item.

**Comment by andyvanavery31** [comment]
Closing due to it being outdated.
