### ISSUE TITLE
Enabler: Automate checks for css regression test reference images

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#387]
> **ESTIMATE** TBD

In #380 we enabled a BackstopJS config option that increases precise image pixel matching. To avoid any more issues in the future, we want to see if adding a check in GH Actions. 

1. Make a branch from #378
2. Add a commit before his with a change to the `workflow.yml` that:
    - Runs `backstop:reference` (without any changes to the error threshold)
    - Checks that no files were generated
3. Add that step to #349 for the backstop image tweaking

### Notes

> The idea is that if we have a threshold setting that we can’t commit code that would trigger a change in future commits

**Comment by olitharp-nci** [comment]
# Findings

From https://stackoverflow.com/questions/3882838/whats-an-easy-way-to-detect-modified-files-in-a-git-workspace

> If you just want a plain “Are there any differences from HEAD?”:
> `git diff-index --quiet HEAD`
> If the exit code is 0, then there were no differences.
> 
> If you want “What files have changed from HEAD?”:
> `git diff-index --name-only HEAD`
> If you want “What files have changed from HEAD, and in what ways have they changed (added, deleted, changed)?”:
> `git diff-index --name-status HEAD`

> `git status --porcelain` seems to give a nice parsable output.

> For git hooks, I found this command useful
> `git diff-index --exit-code --ignore-submodules HEAD`
> For example
> ```yml
> //run some static analysis check that can change the code
> something_changed=`git diff-index --exit-code --ignore-submodules HEAD`
> if [ -n "$something_changed" ]
> then
>     echo >&2 "Something changed in $local_ref, not pushing"
>     exit 1
> fi
> ```

The git hook example was very helpful in debugging this issue:
```yml
      - name: Check reference images
        id: reference
        run: |
          yarn test:reference
          git diff-index --exit-code --ignore-submodules HEAD
          something_changed=`git diff-index --exit-code --ignore-submodules HEAD`
          if [-n "$something_changed" ]; then
            echo "New reference files were generated"
            exit 1
          else
            echo "No new reference files"
          fi
```
Locally, `git diff-index` worked as expected, only outputting files that have been modified. GH actions outputted every single reference file.

[`git diff-index`](https://git-scm.com/docs/git-diff-index)

- Compares the content and mode of the blobs found in a tree object with the corresponding tracked files in the working tree, or with the corresponding paths in the index. When <path> arguments are present, compares only paths matching those patterns. Otherwise all tracked files are compared.
- `--exit-code`: Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.
- `--ignore-submodules[=<when>]`: Ignore changes to submodules in the diff generation. <when> can be either "none", "untracked", "dirty" or "all", which is the default. Using "none" will consider the submodule modified when it either contains untracked or modified files or its HEAD differs from the commit recorded in the superproject and can be used to override any settings of the ignore option in [git-config[1]](https://git-scm.com/docs/git-config) or [gitmodules[5]](https://git-scm.com/docs/gitmodules). When "untracked" is used submodules are not considered dirty when they only contain untracked content (but they are still scanned for modified content). Using "dirty" ignores all changes to the work tree of submodules, only changes to the commits stored in the superproject are shown (this was the behavior until 1.7.0). Using "all" hides all changes to submodules.

[`backstop reference`](https://github.com/garris/BackstopJS#creating-reference-files)

- This Utility command will by default delete all existing screen references and create new ones based on the referenceUrl or url config config. It will not run any file comparisons. Use this when you...
    - create references from another environment (e.g. staging vs prod)
    - or clean out your reference files and start fresh with all new reference
    - or just create references without previewing
- `--i` incremental flag: use if you don't want BackstopJS to first delete all files in your reference directory
- `--docker`: helps with consistency if when comparing references across multiple environments.

**Comment by VictoriaSunNIH** [comment]
Backlogging this for now - we tried something but need to put in a fix in the future!

**Comment by sarinapadilla** [comment]
Putting this in the MVP2 backlog as it is not needed for MVP1!
