### ISSUE TITLE
Enabler: Map mood board colors to JSON tokens

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#39]
# Map mood board colors to JSON tokens

*Description of what is to be accomplished.*
* Map mood board colors and styles to JSON tokens in CSS system

> **ESTIMATE** 3 story points

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
This was actually Issue #7 and closes as part of PR #60.
