### ISSUE TITLE
Design: Create Spanish version of Home and Landing Page Comps

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#395]
Design: [3 Solution Phase](https://lion.box.com/s/w5nalm9zjdt361bwke6fxys1duy8p9lp)

# Title of Solution Initiative
*Description of what is to be accomplished and hoped outcomes*
Design home and landing page comps for Spanish pages (Home and About Cancer) so that we have a reference for dev and can determine any font sizing, alignment, and dev requirements details that need to be noted to ensure modules are built to display properly across both English and Spanish pages.

We should do comps for desktop, tablet and mobile for Spanish pages.

### Links to related tickets
- Discovery Ticket: ...
- Direction Ticket: ...
- Build Ticket(s): ...

### Timeline
Comp(s) to be completed within 1 sprint

### Definition of Done/Complete
Complete 1-2 comps of Spanish home and landing pages using all modules (home and about nci?).  Grants & Training should be considered as a third comp, since this landing page is different from all the others, as there is no real grants and training section within spanish.  Discovery work for Grants and Training is being completed in this sprint so we won't get to comping that page in this sprint.

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Sub-Task
- [ ] Sub-Task
- [ ] Sub-Task

### Sketches
- Sketches link

### Wireframes
- Wireframes link

### Visual Design
- Comps link

#### Prototype
- Prototype link or Github ticket link

### Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

### Specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

#### Technical Constraints
*Technical constraints and dev questions to consider*
1. Constraint
2. Constraint
3. Constraint 

1. Dev question to be answered
2. Dev question to be answered
3. Dev question to be answered

**Comment by VictoriaSunNIH** [comment]
Completed in sprint 28

**Comment by blilianyu** [comment]
Spanish comps can be found here: https://publicis.invisionapp.com/overview/NCI-DS-Spanish-cl2qe0hwx001r01aa3ajtac6t/screens?share=&sortBy=1&sortOrder=1&viewLayout=2
