### ISSUE TITLE
Enabler: Storybook setup and composition approach

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#40]
Setup basic storybook configuration and figure out how to create a composable umbrella storybook instance for the documentation site. 

[ ] Create an umbrella storybook that pulls in story files from sibling packages (ncids-storybook?)
[ ] choose and install desired addons
[ ] install and configure for ncids sub packages (ncids-react, ncids-js, etc.)
[ ] figure out publishing of storybook for deployment/upload to netstorage

> **ESTIMATE** 3 story points

### Subtasks
[ ] create stories for components, etc.
[ ] set up storybook for subrepos as needed

### Resources:
- https://storybook.js.org/

**Comment by bryanpizzillo** [comment]
We are not going to publish storybooks at this time to the documentation site. Each project should still have one for testing purposes, but we will not need an umbrella one.
