### ISSUE TITLE
Update Spanish `aria-label`s

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#406]
Once we have received the updated aria-labels in Spanish, they need to be updated in the DS.
Additionally, documentation should be updated with these Spanish labels.

> **ESTIMATE** 3
-----------
`.usa-banner` update Spanish `aria-label`

`Official government website` should be `Un sitio oficial del Gobierno de Estados Unidos`

![Screen Shot 2022-04-07 at 9 43 17 AM](https://user-images.githubusercontent.com/85901679/162225923-45c109ce-d3de-4caa-a2c5-1a0dbb34e7c3.png)

### Aria Label Translations:
- Banner
-- Official government website: Un sitio oficial del Gobierno de los Estados Unidos
- Breadcrumbs
-- Breadcrumbs: Ruta de exploración
- Footer
-- Footer: Pie de página
-- Back To Top: Volver Arriba
- Subscribe (footer, but will also be on another page)
-- Subscribe: Suscríbase
-- Enter a valid email address: Ingrese su dirección de correo electrónico
- Header
-- Primary Navigation: Navegación primaria
-- Search Button: Botón de búsqueda
-- Cancel (for Search in Mobile): Cancelar
-- Home: Inicio
-- NIH National Cancer Institute: NIH Instituto Nacional del Cáncer
- For the mobile menu:
-- Menu: Menú
-- Main Menu: Menú principal
-- Back to Main: Volver al menú principal
- Sidenav
-- Side navigation: Navegación lateral
- Site Alert
-- Dismiss Alert: Cerrar notificación
-- Toggle alert message (open or close alert): Abrir o cerrar notificación

**Comment by meglake** [comment]
Aria label translations added to this ticket.
