### ISSUE TITLE
`.usa-banner` margins do not match grid

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#408]
`.usa-banner` margins do not match grid

> **ESTIMATE** TBD

The edges of the banner should line up with header, and all other content on the page.

Mockups:
![Screen Shot 2022-04-07 at 11 19 15 AM](https://user-images.githubusercontent.com/85901679/162250410-9f9cc6fe-f5d8-4a63-a422-dae71e5df562.png)

Drupal screenshots:

![Screen Shot 2022-04-07 at 11 18 01 AM](https://user-images.githubusercontent.com/85901679/162250146-a8330508-f236-4c63-9ba4-9f1096aa2f1f.png)
![Screen Shot 2022-04-07 at 11 18 26 AM](https://user-images.githubusercontent.com/85901679/162250233-52e501f2-5ada-4b30-8d42-e623a6ad3bb5.png)

**Comment by mworrest** [comment]
We are tracking the design bug with USWDS in ticket 4642 and awaiting their fix for the alignment of icons and text within the banner and alerts. They may also decide not to fix it :(
