### ISSUE TITLE
Spike: Adobe SofiaPro Typeface

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#41]
## Understand technical and licensing needs for use of Adobe SofiaPro typeface.
- Asset hosting: Adobe hosts the files.
- How people get it
- How we serve it: https://helpx.adobe.com/fonts/user-guide.html/fonts/using/embed-codes.ug.html
- Licensing: https://helpx.adobe.com/fonts/user-guide.html/fonts/using/font-licensing.ug.html#WebfontsfromAdobeFonts
- options/cost for licensing for anyone using the NCIDS, or free alternatives?

> **Estimated Timeframe** *# of days for completion* 

### Expected Deliverables:
* Solutions for hosting/availability
* Alternative options for design system (if necessary)
* If an alternate cannot be used, the reason why.

### Additional Notes:
* note 1

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by bryanpizzillo** [comment]
Additionally, there may be questions around even placing the font with the design system files. See https://pixelambacht.nl/2017/github-font-piracy/.

**Comment by mworrest** [comment]
We are proposing the Google font,Poppins as a replacement for Sofia Pro. 
![Uploading Sofia Pro and Poppins.jpg…]()

**Comment by anthonycuellar** [comment]
Dev will be implementing
