### ISSUE TITLE
Analytics:  Banner+Language Toggle and Notifications Area

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#410]
Provide analytics for 
- [ ] language toggle
- [ ] short notification alert area
- [ ] expandable notification alert area.

Please note if there is a difference in what is captured for spanish sites (not shown in comp)
Note: "This is a US government" banner isn't clickable, so I assume there are no analytics for that one.

Invision Mockups:

Language toggle is shown in the following mockups as well.

- Short Alert Message (can contain a single link): https://publicis.invisionapp.com/console/Alerts-and-Banners-cl179aofdezxx01yle47c8wd5/cl179aooc7cby01uqxg2wdj3v/play
- Expandable Notifications (can contain multiple links): https://publicis.invisionapp.com/console/Alerts-and-Banners-cl179aofdezxx01yle47c8wd5/cl179aooc7cbx01uqmwro4573/play
- Short Alert + Expandable Notification: https://publicis.invisionapp.com/console/Alerts-and-Banners-cl179aofdezxx01yle47c8wd5/cl179aooc7cc001uq8i66o1rv/play

Related Tickets:

- https://github.com/NCIOCPL/ncids/issues/262
- https://github.com/NCIOCPL/ncids/issues/261

**Comment by nicolecrom** [comment]
@VictoriaSunNIH I can't access any of the invision comps

**Comment by blilianyu** [comment]
@nicolecrom You should be able to access the links now. I've also added you to the proto.

**Comment by nicolecrom** [comment]
[Banner and Language Banner.docx](https://github.com/NCIOCPL/ncids/files/8690742/Banner.and.Language.Banner.docx)
Requirements for Banner section

**Comment by sarinapadilla** [comment]
I have added these ACs to https://github.com/NCIOCPL/cgov-digital-platform/issues/3238, so closing this ticket.
