### ISSUE TITLE
Spike: Determine how NCIDS will handle default HTML Elements

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#412]
> **Estimate** *# point* 

In the USWDS there is no definition for the correct styling of H1-H6 tags. There are mixins that allow site builders to define their own classes. There are definitions as part of the `usa-prose` class, but those elements must be a direct descendant of the containing element with the `usa-prose` class. (e.g., `<div class="usa-prose"><h1>the heading</h1></div>`) Additionally, the `usa-prose` class is meant to wrap CMS or WYSIWG content where content editors cannot easily add in classes to the markup. It does not seem designed to wrap an entire page, and would also not work for a lot of our CGDP templates. (e.g., the repeating sections within an article.) This "problem" applies to a few other default elements, (e.g., table, ul, li, etc), although USWDS provides classes for many of those elements. (e.g., `usa-table`, `usa-list`)

So there are a few options to take with NCIDS:
1. Follow the same approach, provide a way for sites to define their own specific-use classes for H* tags.
    * This really should be documented on how to use these to setup your site CSS. Also, I don't know how someone using the .css file would use this.
3. Follow the bootstrap approach of defining default styles for H1-6. (They also define some `h*` classes that can be applied to `<p>` tags, as well as some additional `display-*` classes to make headers stand out.)
    * This may get a bit annoying as headings are technically semantic to the page and not always used the same way. (E.g., the h2 of a section of a home/landing vs the H2 of a section of an article.)
5. Define some specific classes for headings that are consistent across all websites. For example `page-title` (for h1), or `section-heading` (for h2), etc. 
    * This may get a bit annoying as headings are technically semantic to the page and not always used the same way. (E.g., the h2 of a section of a home/landing vs the H2 of a section of an article.)

### Expected Deliverables:
* A decision on the approach and a NCIDS ticket

### Results of Spike
* Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by bryanpizzillo** [comment]
## Decisions
### Headings
For headings we decided they look like Bootstrap:
* Default <h*> tags (https://getbootstrap.com/docs/4.0/content/typography/#headings)
* Styles for elements like <p> so they *look* like headings
   * this shows up under headings section above.
* A set of bolder heading classes that can be applied to headings. (e.g., the page titles on home/landing are bigger than other page titles. (https://getbootstrap.com/docs/4.0/content/typography/#display-headings)
   * NOTE: these should get defined ahead of home/landing, and that we should say home and landing use that style. We should not just set the style for home/landing and randomly make a collection of sizes. :)

**Comment by dlescarbeau** [comment]
When floating an element (for example a card) within a `usa-prose` container, the max-width added via `measure` for paragraph tags has unexpected results. Essentially, if an element is floated left, the paragraph will not flow appropriately as part of the paragraph's container is behind the floated element, resulting in a very thin paragraph on the right of the floating image (due to the paragraph's max width not starting from the end of the image, but rather the start of the container). Removing the max width has the paragraph behave as expected, as the max width does not force the text to wrap prematurely. In these cases, margin will have to be applied to the paragraph to give it space from the floated element.

**Comment by andyvanavery** [comment]
Per discussion with Development Team on 02MAY2023: Decision made to close this ticket due to updates contained in other issues.
