### ISSUE TITLE
Analytics for Megamenu

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#414]
Provide analytics for 
- [ ] Megamenu on desktop

Please note if there is a difference in what is captured for spanish sites (not shown in comp)

Invision Mockups:

*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
  * Desktop: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062769_Header_-_Footer_-_Desktop
  * Desktop (no language toggle)::https://publicis.invisionapp.com/share/FA10EYZRDWP2#/458693996_Header_-_Footer_-_Desktop_-_No_Language_Toggle

Related Tickets:

- https://github.com/NCIOCPL/ncids/issues/205

**Comment by VictoriaSunNIH** [comment]
@nicolecrom  - I believe it only opens on click (but can't remember if its just the button or the whole area).  The button that says "Explore About NCI" takes the user to the page, and does not link directly to the page.  @mworrest to confirm this and also where users click to open the menu :)

**Comment by nicolecrom** [comment]
Requirements for Mega Menu
[Mega Menu.docx](https://github.com/NCIOCPL/ncids/files/8690737/Mega.Menu.docx)

**Comment by nicolecrom** [comment]
Requirement's for Mega Menu
[Mega Menu.docx](https://github.com/NCIOCPL/ncids/files/8690756/Mega.Menu.docx)

**Comment by sarinapadilla** [comment]
I have added these ACs to https://github.com/NCIOCPL/cgov-digital-platform/issues/3277, so closing this ticket.
