### ISSUE TITLE
Analytics for Mobile Menu

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#415]
Provide analytics for 
- [ ] Mobile Menu

Please note if there is a difference in what is captured for spanish sites (not shown in comp)

Invision Mockups:

*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
* Tablet mockup: (https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens/459263421)
* Mobile mockup:(https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens/459263421)

Related Tickets:

- https://github.com/NCIOCPL/ncids/issues/298

**Comment by nicolecrom** [comment]
Requirements for analytics 
[Mobile Menu.docx](https://github.com/NCIOCPL/ncids/files/8708960/Mobile.Menu.docx)

**Comment by sarinapadilla** [comment]
I have added these ACs to https://github.com/NCIOCPL/cgov-digital-platform/issues/3278, so closing this ticket.
