### ISSUE TITLE
Analytics for Breadcrumbs

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#416]
Provide analytics for 
- [ ] Breadcrumbs

Please note if there is a difference in what is captured for spanish sites (not shown in comp)

Invision Mockups:
![image](https://user-images.githubusercontent.com/31222859/163215436-8d0a8a59-e7ae-48af-89b8-b9d0aead48a6.png)

Related Tickets:

- https://github.com/NCIOCPL/ncids/issues/298

**Comment by nicolecrom** [comment]
Functionality question: Where did we end up on ellipse for longer breadcrumbs? May impact some of our analytics regarding level of link clicked

**Comment by VictoriaSunNIH** [comment]
@mworrest to confirm, we are not doing ellipses right?

**Comment by mworrest** [comment]
Correct. It may be a future enhancement but we are not launching with ellipses.

**Comment by nicolecrom** [comment]
[Breadcrumbs.docx](https://github.com/NCIOCPL/ncids/files/8611836/Breadcrumbs.docx)

**Comment by sarinapadilla** [comment]
I have added these ACs to https://github.com/NCIOCPL/cgov-digital-platform/issues/3242, so closing this ticket.
