### ISSUE TITLE
Analytics for Search + AutoComplete

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#420]
Provide analytics for 
- [ ] Autocomplete within site search on desktop and mobile
- [ ] Search bar

Please note if there is a difference in what is captured for spanish sites (not shown in comp)

Invision Mockups:
Desktop Sitewide Search: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/462742034_Autosuggest_-_Desktop
Mobile Sitewide Search: https://publicis.invisionapp.com/d/main#/projects/prototypes/21910496

Related Tickets:

- https://github.com/NCIOCPL/ncids/issues/277
- https://github.com/NCIOCPL/ncids/issues/280

**Comment by nicolecrom** [comment]
[Search and AutoComplete.docx](https://github.com/NCIOCPL/ncids/files/8614046/Search.and.AutoComplete.docx)

**Comment by sarinapadilla** [comment]
I have added these ACs to https://github.com/NCIOCPL/cgov-digital-platform/issues/3279, so closing this ticket.
