### ISSUE TITLE
Analytics for Back to Top

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#422]
Provide analytics for 
- [ ] Back to top
- [ ] 
Please note if there is a difference in what is captured for spanish sites (not shown in comp)

Invision Mockups:
Desktop mockup: https://publicis.invisionapp.com/share/J612GAGC8NRA#/464821665_Nano_Homepage_-_Desktop_In_Browser_1024
Tablet mockup: same as mobile
Mobile mockup: https://publicis.invisionapp.com/share/J612GAGC8NRA#/464822888_Mobile_Minimalist_Homepage_Copy_10

Related Tickets:
- https://github.com/NCIOCPL/ncids/issues/374

**Comment by nicolecrom** [comment]
Questions on the functionality: I see that the button will be sticky, but will it appear on page load or once the user scrolls down a portion of the way (like on the current site).

**Comment by VictoriaSunNIH** [comment]
Tagging @mworrest , @blilianyu , @lburack , @russellwyatt on this question!

**Comment by nicolecrom** [comment]
Still need to clarify about the on page load versus scroll but here are requirements
[Back to Top.docx](https://github.com/NCIOCPL/ncids/files/8611850/Back.to.Top.docx)

**Comment by sarinapadilla** [comment]
I have added these ACs to nciocpl/cgov-digital-platform#3348, so closing this ticket.
