### ISSUE TITLE
Home and Landing Page User Testing: 

### ISSUE THREAD

**Issue by lizsiciliano** [NCIOCPL/ncids#427]
# Home and Landing Page User Testing
*Task-based, unmoderated user testing on flat images. With general audience who identify as being impacted by cancer through either their own diagnosis or the diagnosis of a friend, family member or close contact. Respondents will be divided between those who evaluate the desktop experience versus those who evaluate the mobile experience. Total of 5 desktop users and 5 mobile users*

### Links to related tickets
*Add link to related tickets below.*
- Ticket Tile: #389

### Timeline
*Task design and Study Preparation: Week of 4/25*
*Recruit: Week of 5/2*
*Fielding Study: Week of 5/9*
*Reporting: 3 business days post study completion*

## Add remaining info below.
*https://lion.box.com/s/cwhepg3ripmttnrqfadrmpwpfx2ti6xv*

**Comment by meglake** [comment]
Findings reported: https://lion.box.com/s/gu7ujehwy2qnpfh9jokmxk1zqcnvg9pj will look into this testing as part of sprint 31 (#480). Closing this ticket now.
