### ISSUE TITLE
Change Request: Activate and deactivate USWDS breakpoints

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#429]
### Issue description
Designers need certain USWDS breakpoints activated and others deactivated.

> **ESTIMATE** TBD

### What's the expected change?
-We need 320, 480 and 640 turned off, 880 and 1400 turned on.
<img width="736" alt="USWDS Breakpoints" src="https://user-images.githubusercontent.com/4921685/164475961-ff0c47a7-8eb2-461c-abf0-5bfcb897cdb7.png">

### What's the current functionality?
-320, 480 and 640 are on and 880 and 1400 are off.
![Screen Shot 2022-04-21 at 10 05 55 AM](https://user-images.githubusercontent.com/4921685/164475868-dbf6f1f0-db16-4a18-98bb-ad9fb94881cc.png)

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by meglake** [comment]
Moving to Design backlog with placeholder label as this ticket needs more information and thought before proceeding. Will discuss with design team on 5/19 and update with next steps.

**Comment by meglake** [comment]
Closing as we have already addressed breakpoints and will be releasing widescreen next week.
