### ISSUE TITLE
Logo/Blended Logo Resizing For Development

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#433]
Design: [3 Solution Phase](https://lion.box.com/s/w5nalm9zjdt361bwke6fxys1duy8p9lp)

Based on today's meeting regarding logo sizing in the header, please look into sizing changes needed for the blended logos and determine what changes need to be made.

> Feature/Main User Story: [Enter user story ticket association here] 

### Links to related tickets
- Sub-branding comps: https://github.com/NCIOCPL/ncids/issues/287 (need to apply any sizing changes to comps in this ticket)

### Timeline
To be completed in sprint 28.

### Definition of Done/Complete
*Align on what done/complete means for the scope of the solution work.*

### Description of Design Direction:
All logos need to be in the same illustrator file and created at the same size artboards. Prioritize NCI (English and Spanish), DCEG, Nano, NCI-CONNECT (Spanish too), MyPART, PSON, SBIR. Microsite logos dependent on solution to #287. These will be in full color only. Note - This is a solution for redesign/platform dev purposes and is not a chance to logo/blended logo branding in general (ie we do not need to update files on L drive or change/remove any that current exist). This is a solution to keep in mind when any new microsite is created that has a blended logo (or will have a blended logo) at that time a resized svg will be created for the platform.

### List of sub-tasks:
*Add links to related tickets below*
- [x] Copy enterprise logo and all blended logos that have/will have sites on Cgov platform, see list above (full color only) into one master illustrator file. Make sure groups have distinct layer group names. This can be used to start: 
![CBIIT Logo COLOR](https://user-images.githubusercontent.com/4921685/165329882-08656d05-fefd-4a1a-80a7-1c4b570c8d0b.svg)

- [x] Find the worst case scenario then make all other logos that same width while maintaining a 38px height. Keep the same amount of padding as in the file attached here. All artboards need to be the same size.
- [x] Separate the NIH luggage tag layer group from the rest of the text so there are 2 groups in the illustrator file. One group for the NIH luggage tag and one group for the NCI and doc text. 
- [x] Save artboards svg Tiny 1.1 into Web folder for svgs on Box for internal reference. We no longer need to support png fallbacks because we do not support IE11. Please also place the latest svgs here for https://lion.box.com/s/74kvgh0yu0svumd70lcx8qwzi54jfoop development

### Visual Design
- Comps link

## Design Specs:
1. Specification 
2. Specification  
3. Specification 

### Specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

#### Technical Constraints
*Technical constraints and dev questions to consider*
1. Constraint
2. Constraint
3. Constraint 

1. Dev question to be answered
2. Dev question to be answered
3. Dev question to be answered

**Comment by meglake** [comment]
@acsnedegar  and @mworrest noting that blended logos for NCI-CONNECT and MyPART will be approved as part of https://github.com/NCIOCPL/ncids/issues/287 so those will need to be on hold within this ticket until approval is received.

**Comment by acsnedegar** [comment]
Hi @mworrest and @meglake - Even though this is still on hold due to waiting for approval of NCI-Connect and MyPart, noting that I've saved the master design file with all logos and latest svgs on box here while I'm out: https://lion.box.com/s/74kvgh0yu0svumd70lcx8qwzi54jfoop 

Currently the sizing is 385px x 38px with the NCI Spanish logo determining the max width.

**Comment by bryanpizzillo** [comment]
@mworrest can we also get a SVG for DCCPS as their PNG is:
1. Wider than 385
2. Looks like poo on a retina display

**Comment by mworrest** [comment]
![Logo_DCCPS](https://user-images.githubusercontent.com/4921685/169068987-3277f81c-e506-42bd-8e26-5c58670c186d.svg)
Spanish enterprise logo is still wider so DCCPS is contained within the size we've set: 385x38px

**Comment by meglake** [comment]
Moving to backlog until approval on CCR microsite logos.

**Comment by meglake** [comment]
@acsnedegar  We we have approval to move forward with CCR microsites using the following blended logo language:

NCI-CONNECT
MyPART
See approved stickies on Mural board: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1651597352249/cce47102ed422eb7d69b557f3ffeec56489ba83c?sender=meganlake7790

This ticket will be completed in Sprint 32. As part of Sprint 32, we'll create a dev ticket to implement these logos. CCing @sarinapadilla for awareness.

**Comment by acsnedegar** [comment]
Hi @mworrest @meglake - the MyPART logo and NCI-CONNECT logos in English and Spanish are up on box now: https://lion.box.com/s/74kvgh0yu0svumd70lcx8qwzi54jfoop The master AI file is updated as well.
Let me know if there's anything else needed for this to be considered complete. 

Ccing @sarinapadilla

**Comment by mworrest** [comment]
> Hi @mworrest @meglake - the MyPART logo and NCI-CONNECT logos in English and Spanish are up on box now: https://lion.box.com/s/74kvgh0yu0svumd70lcx8qwzi54jfoop The master AI file is updated as well. Let me know if there's anything else needed for this to be considered complete.
> 
> Ccing @sarinapadilla

Thank you, Annie!

**Comment by laurelthrash** [comment]
Ticket will be closed. Laurel and Megan to discuss next steps for a development ticket.

**Comment by meglake** [comment]
Noting that logos in header will be a manual task for MVP 1 release and is documented in this folder on Teams: https://teams.microsoft.com/_#/files/General?threadId=19%3A9297bd7e56e0472d9ae8f7dc102c16bd%40thread.skype&ctx=channel&context=MVP%25201%2520Manual%2520Clean%2520Up%2520Files&rootfolder=%252Fsites%252FNCI-OCPLNewCgovUXDesignSystem%252FShared%2520Documents%252FGeneral%252FMVP%25201%2520Manual%2520Clean%2520Up%2520Files

**Comment by laurelthrash** [comment]
Note: Documentation for SVG logo creation found in #555
