### ISSUE TITLE
Story: Pull in USWDS Icons into NCI DS

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#434]
We have made the decision to use the USWDS Icons within NCIDS, with the addition of icons that are not currently in the USWDS set (LinkedIn syndication icon).

We need to copy the USWDS icon set into the NCIDS, and set it up so that if USWDS icon set is updated/changed, we update/change the NCI DS set as well.

### Tasks

- [ ] @arcepaul to investigate how sites handle icons/sprites

1. Copy/paste icons in
2. Update webpack to use the icons correctly
  - Update Gatsby to reference the icons from NCIDS (they're currently just referenced locally because "it's STUPID" - Bryan)
  - NCIDS CSS testing (storybook)
  - NCIDS JS testing (webpack)
3. Update the NCIDS CSS to use a version of the mixins that works correctly for this
4. Update the NCIDS CSS to remove the old NCIDS icon sprite
5. Documentation (get creative)

Design Ticket: https://github.com/NCIOCPL/ncids/issues/431
Digital Platform Ticket: @sarinapadilla will write this ticket [Note: I don't think a digital platform ticket is needed for this, need to confirm when ticket is complete]

<img width="405" alt="Footer Icons" src="https://user-images.githubusercontent.com/41208873/172199152-ba64e815-e906-4250-85b3-1e8469617f19.png">

**Comment by meglake** [comment]
This ticket should replace https://github.com/NCIOCPL/ncids/issues/304, confirm when this ticket is completed, and if this ticket does replace 304 then close 304 as well.

**Comment by bennettcc** [comment]
Per Bryan - For MVP1, we can use the icons we need for cgov (footer). We need to determine how to reference all the USWDS icons

**Comment by andyvanavery** [comment]
Closed as this was OBE by the USWDS pull in's to NCIDS.
