### ISSUE TITLE
Spike: Identify all Aria Labels that need to be translated to spanish

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#435]
Please identify all of the aria labels that need to be translated to spanish, and provide it in this ticket so we can request the translations from Carolina/Fedora.

Related to: #407

**Comment by olitharp-nci** [comment]
Component list - need to verify the ones we have

- Banner
    - Official government website
    - Un sitio oficial del Gobierno de Estados Unidos
- Breadcrumbs
    - Breadcrumbs
- Footer
    - Footer
    - Twitter, Youtube, RSS feed, Facebook
- Subscribe (footer, but will also be on another page)
    - Subscribe
- Header
    - Primary Navigation
    - Logo
        - Should this be Home? NIH National Cancer Institute?
- Sidenav
    - Side navigation
- Skipnav
    - Skip to main content
    - Pasar al contenido principal

**Comment by meglake** [comment]
Awaiting translation due on 6/6.

**Comment by sarinapadilla** [comment]
From a dev standpoint, this ticket is done. A ticket has been created with the updated Spanish labels: #406

**Comment by meglake** [comment]
Noting Spanish Translations below and closing out ticket, will add to ticket 406 as well.

- Banner
-- Official government website
- Un sitio oficial del Gobierno de Estados Unidos
- Breadcrumbs
- Breadcrumbs
- Footer
- Footer
- Twitter, Youtube, RSS feed, Facebook
- Subscribe (footer, but will also be on another page)
- Subscribe
- There's text on this page that says "Enter a valid email address", but it isn't an aria-label.
- NOTE: This item can be changed as a component option, so they may not even need translations.
- Header
- Primary Navigation
- Search Button
- Sitewide (for form)
- Cancel (for Search in Mobile)
- Logo
- Should this be Home? NIH National Cancer Institute?
- For the mobile menu:
- Menu
- Main Menu
- Back to Main
- Sidenav
- Side navigation
- Skipnav
- Skip to main content
- Pasar al contenido principal
- Site Alert
- Dismiss Alert
- Toggle alert message
- NOTE: We're not sure if that's even the correct text for English
- NOTE: These items can be changed as a component option, so they may not even need translations.

**Comment by meglake** [comment]
All requested aria labels have been translated and noted above. Also added to ticket #406
