### ISSUE TITLE
`ncids-css` `nci-megamenu` design changes

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#436]
### Issue description
Update mega menu to match Invision styles

https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc/cl178079m77pc01uq24rw2787/inspect

> **ESTIMATE** 1

### What's the expected change?
- [x] Explore header: Poppins, 600, 22px
- [x] Explore header: Use chevron instead of arrow
- [x] Landing page header: Poppins, 600, 20px
- [x] Page links: Open Sans, 400 (normal), 16px
- [x] Remove custom grid. Use USWDS grid. (Remove custom grid from `_megamenu.scss` and dom)
- [x]  https://github.com/NCIOCPL/ncids/issues/294 doesn't change background color

![Screen Shot 2022-04-27 at 12 02 55 PM](https://user-images.githubusercontent.com/85901679/165575354-962605ed-7782-4819-96da-95c5560859d9.png)

### Notes
- Background should be: Primary dark, cerulean 70, #004971
  - Background color is currently correct, but  https://github.com/NCIOCPL/ncids/issues/294 might change the megamenu background color accidentally, so update this comment and add a task if needed.

### Related Tickets
* #296 
* #297

**Comment by mworrest** [comment]
The menu button should be primary dark which I am not seeing in https://github.com/NCIOCPL/ncids/pull/411

**Comment by VictoriaSunNIH** [comment]
This is no remaining work left, just waiting to be merged in Sprint 30.

**Comment by meglake** [comment]
Moving to 31 but no actual work, waiting on #297 to close.
