### ISSUE TITLE
Change ncids-js linter to use TS

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#448]
### Issue description
`ncids-js` eslint should typescript instead of javascript

### What's the expected change?
```ts
module.exports = {
  extends: [
    '@nciocpl/eslint-config-vanilla-ts',
  ],
...
};

```

### What's the current functionality?
```ts
module.exports = {
  extends: [
    '@nciocpl/eslint-config-vanilla-js',
  ],
...
};

```
### What's the updated acceptance criteria?
- [ ] eslint uses typescript package
- [ ]

**Comment by bennettcc** [comment]
Per discussion on 11/8 - this is complete
