### ISSUE TITLE
Design: Baseline Typography

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#45]
> **ESTIMATE** Story Points TBD

### Description of Design request:

Text color: (token: grey-cool.90)
Desktop

- Headings (H1-6)
- - H1: Poppins SemiBold 30px/40px line height
- - H2: Poppins SemiBold 26px/34px line height
- - H3: Poppins SemiBold 22px/29px line height
- - H4: Poppins SemiBold 20px/27px line height
- - H5: Poppins SemiBold 18px/25px line height
- - H6: Poppins SemiBold Italic 17px/24px line height
- Body: Open Sans Regular 16px/24px line height
- Link: Open Sans Regular 16px/24px line height (token: cerulean.50)
- UL: Open Sans Regular 16px/24px line height
- OL: Open Sans Regular 16px/24px line height

Mobile
- Headings (H1-6)
- - H1: Poppins SemiBold 24px/32px line height
- - H2: Poppins SemiBold 22px/30px line height
- - H3: Poppins SemiBold 18px/26px line height
- - H4: Poppins SemiBold 16px/23px line height
- - H5: Poppins SemiBold 16px/23px line height
- - H6: Poppins SemiBold Italic 16px/23px line height
- Body: Open Sans Regular 16px/24px line height 
- Link: Open Sans Regular 16px/24px line height (token: cerulean.50)
- UL: Open Sans Regular 16px/24px line height
- OL: Open Sans Regular 16px/24px line height

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Sub-Task
- [ ] Sub-Task
- [ ] Sub-Task

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by mworrest** [comment]
Ready to hand off the baseline typography to devs.

**Comment by karlikpj** [comment]
@anthonycuellar We'll need to make a dev ticket to implement said changes listed in this ticket. We can estimate during our next pointing session. Thanks!
