### ISSUE TITLE
Comp Research Landing Page

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#453]
*Description of what is to be accomplished.*

**Parent Issue:** #449

### Sub-Tasks
- [ ] Comp research landing page as we work on grid module

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by sarinapadilla** [comment]
@laurelthrash, we completed this work as part of #1000, so this ticket is no longer needed!
