### ISSUE TITLE
Draft Build Tickets for Feature Card Component on Home/Landing Pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#459]
Definition of Done: build ticket details for each variation of the Feature Card component defined and documented in `ncids` and `cgov-digital-platform` tickets.

- [X] Feature Card/Row with 3 Cards
  - [x] DS component ticket: #552 
  - [x] Drupal component ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/3492
- [ ] Multiple-Link Feature Card/Row
  - [ ] DS component ticket: 
  - [ ] Drupal component ticket: 
- [ ] Feature Card/Row with 2 Cards
  - [ ] DS component ticket: 
  - [ ] Drupal component ticket:

**Comment by meglake** [comment]
Moving to sprint 31 and reducing to sp 2, need to confirm with @blilianyu  as well.

**Comment by sarinapadilla** [comment]
@laurelthrash, we already have a meta ticket for building the different feature card components. We'll still have to discuss whether we are building all of the variants besides 3 Feature Card Row, but going to close this ticket out and keep the other open.
