### ISSUE TITLE
Design: Language Toggle

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#46]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: [Enter user story ticket association here] 

Enabler: Discovery Task: Language Toggle Exploration #47

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Sub-Task
- [ ] Sub-Task
- [ ] Sub-Task

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. Desktop: https://publicis.invisionapp.com/share/KN10COU5UYCW
2. Mobile: https://publicis.invisionapp.com/share/3C10NGGUXTYQ

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by anthonycuellar** [comment]
Design and Dev meeting on Monday April 5th

**Comment by mworrest** [comment]
After client demo today, we have added the simplified language toggle to the prototypes: 
Desktop: https://publicis.invisionapp.com/share/KN10COU5UYCW#/450121241_desktop_-_No_Dropdown
Mobile: https://publicis.invisionapp.com/share/3C10NGGUXTYQ#/450121813_2-Mobile

**Comment by mworrest** [comment]
Today we talked about needing usability testing on the current usage of the language toggle. Fedora asked if it is possible to link users over to generic content if there is no translation for the page.
