### ISSUE TITLE
Create YAML Content for Megamenu

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#460]
Create YAML Content for Megamenu - 

JSON: https://github.com/arcepaul/gatsby-nci/blob/new-prototype/src/components/molecules/data.js

- [ ] Ramu to recreate JSON content into YAML, breaking it into separate files for each of the tabs (6 files)
- [ ] Victoria to create YAML spanish content

Example: 
primary_nav_label: "Explore About Cancer"
primary_nav_url: "/about-cancer"
items:
  - type: list
    title: Treatment
    title_url: /about-cancer/treatment
    list_items:
      - label: Surgery
        url: /about-cancer/treatment/surgery

**Comment by VictoriaSunNIH** [comment]
Attaching About Cancer (El Cancer) and Types (Tipos) for Spanish.  Note, one label "Explore..." is awaiting client input on translation.

CC: @mworrest , @lburack 
[AboutCancer -- ElCancer (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8703280/AboutCancer.--.ElCancer.Spanish.txt)
[Types -- Tipos (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8703281/Types.--.Tipos.Spanish.txt)

**Comment by VictoriaSunNIH** [comment]
[Research -- Investigacion (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8703371/Research.--.Investigacion.Spanish.txt)

**Comment by ramu-nih** [comment]
Attaching YAML Content for the below mega menu items.

- [About Cancer](https://github.com/NCIOCPL/ncids/files/8703759/about_cancer.txt)
- [Cancer Types](https://github.com/NCIOCPL/ncids/files/8703760/about_nci.txt)
- [Research](https://github.com/NCIOCPL/ncids/files/8703761/cancer_types.txt)
- [Grants & Training](https://github.com/NCIOCPL/ncids/files/8703762/grants_training.txt)
- [News & Events](https://github.com/NCIOCPL/ncids/files/8703763/news_events.txt)
- [About NCI](https://github.com/NCIOCPL/ncids/files/8703764/research.txt)

**Comment by VictoriaSunNIH** [comment]
Some of these files are mislabeled - Cancer Types leads to About NCI, Research seems to be Cancer Types and About NCI is the research file for me.  There are also some misspellings in the About NCI section. I’ll look closer at them tomorrow but also wanted to ask if we are supposed to be using a single quote before the item name and the item URL?


From: "Ramu Challa" ***@***.******@***.***>>
Date: Monday, May 16, 2022 at 6:19:31 PM
To: "NCIOCPL/ncids" ***@***.******@***.***>>
Cc: "Sun, Victoria (NIH/NCI) [C]" ***@***.******@***.***>>, "Assign" ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [NCIOCPL/ncids] Create YAML Content for Megamenu (Issue #460)


Attaching YAML Content for the below mega menu items.

  *   About Cancer<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCIOCPL%2Fncids%2Ffiles%2F8703759%2Fabout_cancer.txt&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZaCwUeCBj85a6vhe%2F%2FFi8HWyZZgxIOAyFrOJujkzogQ%3D&reserved=0>
  *   Cancer Types<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCIOCPL%2Fncids%2Ffiles%2F8703760%2Fabout_nci.txt&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4LdWRTLSRAyZsfB07Et78RVzLL57RF6a06CsxFKqCkA%3D&reserved=0>
  *   Research<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCIOCPL%2Fncids%2Ffiles%2F8703761%2Fcancer_types.txt&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0aXwsjgQe6N%2FO7EfsZO9QzjRla4kB4nvPgViCHlJ69M%3D&reserved=0>
  *   Grants & Training<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCIOCPL%2Fncids%2Ffiles%2F8703762%2Fgrants_training.txt&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P5n8%2BOkha7PQmck79%2FXv%2BmurocM3TN1RgyinawBVq%2FY%3D&reserved=0>
  *   News & Events<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCIOCPL%2Fncids%2Ffiles%2F8703763%2Fnews_events.txt&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QYYw5LodOUHD1NsgmEzl%2FDUG0XYBPt8t9Vpi0tBGW%2Bg%3D&reserved=0>
  *   About NCI<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCIOCPL%2Fncids%2Ffiles%2F8703764%2Fresearch.txt&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JeSHpKYQvMYhmKULBzDnkLgmn51%2B71DjJiGIxGgb1Ys%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCIOCPL%2Fncids%2Fissues%2F460%23issuecomment-1128192810&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pK98nLffBFZyXpN2JKyTYixMc2JklExA0Gkb%2FJtDJAg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHOGYS6A67TONEG3LZPYI4TVKLCW5ANCNFSM5WCCUEHA&data=05%7C01%7Cvictoria.sun%40nih.gov%7C4543188af9b240c7d6fd08da378a24ef%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637883363711333505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s1g32rTeoQ4rEFBtnTvLS80HTcQo7HGcR7r%2F3l01IKY%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by VictoriaSunNIH** [comment]
Should all of the titles and urls be in single quotes 'url or title here'?
In About NCI:
- [ ] title: 'Senior Leradership' is spelled wrong (should be Leadership)
- [ ] There is a lot of space before title: '	Careers' (looks like an extra tab)
New & events
- [ ] Need to add a line for 2022

I'll have to check through more tomorrow, my guess is that Paul's original megamenu JSON might not be reflecting all of the changes we've made to Production. :)

**Comment by VictoriaSunNIH** [comment]
Re-attaching all updated YAML based on the translation provided.

CC: @mworrest , @lburack , @sarinapadilla , @bryanpizzillo  -- this is the starting point of YAML for production, but will be updated as needed.  Grants & Training (Subvenciones y capacitación) did not get a spanish file since there are no list items for it.

[About NCI -- Nuestro Instituto.txt](https://github.com/NCIOCPL/ncids/files/8709236/About.NCI.--.Nuestro.Instituto.txt)
[AboutCancer -- ElCancer (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8709237/AboutCancer.--.ElCancer.Spanish.txt)
[News -- Noticias (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8709238/News.--.Noticias.Spanish.txt)
[Research -- Investigacion (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8709239/Research.--.Investigacion.Spanish.txt)
[Types -- Tipos (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8709240/Types.--.Tipos.Spanish.txt)

**Comment by ramu-nih** [comment]
> @ramu-nih Should all of the titles and urls be in single quotes 'url or title here'? In About NCI:
> 
> * [ ]  title: 'Senior Leradership' is spelled wrong (should be Leadership)
> * [ ]  There is a lot of space before title: '	Careers' (looks like an extra tab)
> 
> New & events
> 
> * [ ]  Need to add a list item for 2022
> 
> I'll have to check through more tomorrow, my guess is that Paul's original megamenu JSON might not be reflecting all of the changes we've made to Production. :)


Victoria,

 Should all of the titles and urls be in single quotes 'url or title here? **single quotes are optional for string type fields in YAML**

Updated the **About NCI** and **News & Events** YAML data.
[about_nci.txt](https://github.com/NCIOCPL/ncids/files/8709627/about_nci.txt)
[news_events.txt](https://github.com/NCIOCPL/ncids/files/8709628/news_events.txt)

**Comment by VictoriaSunNIH** [comment]
This one is considered complete, closing.

**Comment by VictoriaSunNIH** [comment]
[Research -- Investigacion (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8711247/Research.--.Investigacion.Spanish.txt)
[AboutCancer -- ElCancer (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8711248/AboutCancer.--.ElCancer.Spanish.txt)
[Types -- Tipos (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8711249/Types.--.Tipos.Spanish.txt)
[News -- Noticias (Spanish).txt](https://github.com/NCIOCPL/ncids/files/8711250/News.--.Noticias.Spanish.txt)
[About NCI -- Nuestro Instituto.txt](https://github.com/NCIOCPL/ncids/files/8711251/About.NCI.--.Nuestro.Instituto.txt)

Re-uploading, Carolina came back and said that translating Explore would lead to 3 or more words per line, so she suggested we just use the section name and drop "Explore" for Spanish
