### ISSUE TITLE
Design: New Class for Raw HTML Block for H&L pages for Release 2

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#461]
# Define style for new class to use in raw HTML block to handle content on H&L pages for R2.1.
Per client request on 5/16 (see notes from #418 ), please document requirements for how this raw html block class should display the system of the text (plus links) on a landing page. You can use your Spanish Grants & Training comp as an example comp of what we expect this to look like.

Once a style is defined, then we'll work with the dev team to create the necessary class/HTML to make this display possible through the raw HTML block. This HTML code will then need to be documented for future "as needed" use.

Note: this will become a Drupal ticket, as this will not apply in the DS. 

### Timeline
Complete as part of sprint 40

### Definition of Done/Complete
Design/style requirements defined for class/html to use in a raw html block on home and landing pages for R2.1

### Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Heading should be theme token size XL
2. Body should be theme token sans L
3. Box shadow should be shadow-2 

### Specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. Widescreen: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40594017n0wlv2cg1/play
4. Desktop: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40595017ncuofhrc6/play
5. Tablet Large: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40596017ne0xu72cu/play
6. Tablet: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40597017ndfyq71j5/play
7. Mobile Large: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40598017n4qeid6e0/play
8. Mobile: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40599017ngry973ak/play

#### Technical Constraints
*Technical constraints and dev questions to consider*
1. Constraint
9. Constraint
10. Constraint 

1. Dev question to be answered
2. Dev question to be answered
3. Dev question to be answered

**Comment by meglake** [comment]
Noting that we currently have a content block option on Home & Landing pages but we'll need to determine look/feel for Release 2.

Also, need to keep Raw HTLM block as part of Release 2 because it is being used for various things like the Screen to Save: https://www.cancer.gov/about-nci/organization/crchd/inp/screen-to-save/connect

**Comment by mworrest** [comment]
![Cancer gov Homepage - Desktop - Raw HTML Block](https://user-images.githubusercontent.com/4921685/171218953-4aa97ef4-767b-4e82-bda2-1ee1201ae31d.jpg)

**Comment by meglake** [comment]
Moving to sprint 31 to finish internal conversations and various reviews and final approval before closing out ticket.

**Comment by meglake** [comment]
Confirmed edits made from 5/31 meeting, moving to sprint 32 (sp:1) for reviews with dev team

**Comment by meglake** [comment]
Noting that we'll probably want to use USWDS Prose for this: https://designsystem.digital.gov/components/prose/ Will be part of our discussion on 6/17 during sprint 32.

**Comment by laurelthrash** [comment]
Initially included in Sprint 32. Determined we would temporarily move this to the Approved Backlog to be picked up at a later time, in order to prioritize other development tickets in Sprint 32.

**Comment by laurelthrash** [comment]
Planning for a conversation with a devs sometime after sprint 35.

**Comment by meglake** [comment]
This will be a Drupal dev ticket for R2.1 will need to have a conversation around requirements with dev team in early Fall.

**Comment by laurelthrash** [comment]
Megan to review/revise the ticket and assign out for Sprint 40 @meglake

**Comment by laurelthrash** [comment]
Will review internally on 10/18 with the intention of closing out within Sprint 40.

**Comment by laurelthrash** [comment]
Moving to Sprint 42 and internal review slated for Tues. 11/8.

**Comment by laurelthrash** [comment]
Internal discussion on 11/8:
- Keep the comp as-is, and note that images can be available @blilianyu 
- @sarinapadilla to create a Drupal ticket for raw HTML block
- Raw HTML will be documented internally on the GH Wiki ([link here](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Drupal-HTML-Crib-Notes))

Notes:
- Videos added via the video component (not in the raw HTML block)
- Recommendation is that the raw HTL block would not include images, rather, if an image is desired that we consider using another one of the existing components
