### ISSUE TITLE
Draft Build Tickets for Text Card Component on Home/Landing Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#472]
*Description of what is to be accomplished.*

**Parent Issue:** #393 

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by andyvanavery** [comment]
Closing due to not being needed.
