### ISSUE TITLE
Additional Spanish Comp text updates

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#485]
*Description of what is to be accomplished.*

**Parent Issue:** #462 

### Sub-Tasks
- [x] Update Spanish comps with text edits (as needed)
- [x] Review internally to confirm all edits are made

### Spanish Footer Text & Links 
- Above Footer - Back to Top Icon
   - Volver arriba
- Main Link Area
   - About: Quiénes somos
      - [Acerca de este sitio web](https://www.cancer.gov/espanol/acerca-sitio)
      - [In English](http://[www.cancer,gov/espanol](http://www.cancer.gov))
      - [Derechos de autor](https://www.cancer.gov/espanol/politicas/derechos-de-autor-y-uso)
      - [Redes sociales](https://www.cancer.gov/espanol/redes-sociales)
   - Resources: Recursos
      - [Contacto](https://www.cancer.gov/espanol/contactenos)
      - [Publicaciones](https://www.cancer.gov/espanol/publicaciones)
      - [Diccionario de cáncer](https://www.cancer.gov/espanol/publicaciones/diccionarios/diccionario-cancer)
      - Note - There is no 'Find a Clinical Trial' in Spanish right now, but there might be plans to translate an intro page to CTS in the future. 
   - Policies: Políticas
      - [Accesibilidad](https://www.cancer.gov/espanol/politicas/accesibilidad)
      - [Ley de Libertad de la Información (FOIA)](https://www.cancer.gov/espanol/politicas/foia)
      - [Confidencialidad y seguridad](https://www.cancer.gov/espanol/politicas/confidencialidad-seguridad)
      - [Aviso legal](https://www.cancer.gov/espanol/politicas/exoneracion)
      ---- Note: There are plans to update this page, including the URL and H1. It is not a priority so it won’t be for a few months. Need to keep this in mind for MVP 1 launch depending on timeline. 
      - [Política de divulgación de vulnerabilidad](https://www.hhs.gov/es/vulnerability-disclosure-policy/index.html)
- Subscribe box
   - Sign up for email updates: Reciba actualizaciones por correo electrónico
      - Enter your email address: Ingrese su correo electrónico
      - Sign up [button]: Suscríbase
- Organization/DOC Name Area (I have no better name for this)
   - National Cancer Institute: Instituto Nacional del Cáncer
   - At the National Institute of Health: de los Institutos Nacionales de la Salud
- Contact Us: Comuníquese 
   - [Chat en vivo](https://livehelp-es.cancer.gov/)
      - This also is a popup 
   - 1-800-422-6237 (Telephone link)
   - NCIinfo@nih.gov (Mailto link)
   - Site Feedback: Comentarios y sugerencias
      - [Qualtrics Survey Link](https://nci.az1.qualtrics.com/jfe/form/SV_aeLLobt6ZeGVn5I)
- Follow Us Area
   - Facebook Icon: https://www.facebook.com/cancer.govEspanol
   - Twitter Icon: https://twitter.com/NCIespanol
   - YouTube Icon: https://www.youtube.com/playlist?list=PLYKy4VbxNln7Cy6K2hZvwHLIZAElio5ai
- Organization area (I have no better name for this)
   - [Departamento de Salud y Servicios Humanos (en inglés)](https://www.hhs.gov)
   - [Institutos Nacionales de la Salud](https://salud.nih.gov/)
   - [Instituto Nacional del Cáncer](http://www.cancer.gov/espanol)
   - [USA.gov en español](https://www.usa.gov/espanol/)  

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by meglake** [comment]
Awaiting feedback from Carolina, will need to update footer once we get footer content translations.

**Comment by laurelthrash** [comment]
May consider adding to Sprint 33.

**Comment by laurelthrash** [comment]
Footer text and links translation received from Carolina via JIRA ticket: [CGOV-16360](https://tracker.nci.nih.gov/browse/CGOV-16360)

**Comment by blilianyu** [comment]
@meglake @laurelthrash Spanish comps have been updated and on the Mural board for review.

https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1638306879101/4adb7154efb0319ee806fbcd3052a180a57fb137?sender=uf7d7cce75e812c2b5a084619
