### ISSUE TITLE
Design Solution: News & Events Landing Page

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#486]
Design: [3 Solution Phase](https://lion.box.com/s/w5nalm9zjdt361bwke6fxys1duy8p9lp)
> ESTIMATE SP: 5
> Related ticket: #482 

# News & Events Landing Page Comp
Create comp(s) of the News & Events landing page using available Release 2 components. Discussed during end of sprint on 10/4 with clients that we will move forward with designing comps for the News and Events landing page that utilize the components available in Release 2 at specific iterations (similar to #536). Consider Spanish and mobile, as necessary. 

While creating these comps determine the following:
* What R2 components would be best for the current content on this page?
* What R2 components would best incorporate feedback and research identified during the Discovery phase?
* Is there content on this page that doesn't work with the H&L components as they are currently defined (style & requirements) for which we need to discuss?
* How should the dynamic list component be styled (i.e., the press release listing) and how does that affect the style that is carried over for other dynamic lists (like blog series, PR listing on MRB page, etc.)? 

_Note: Dynamic list component functionality should remain the same and styling considerations should be considered holistically (i.e., style should work for both landing page and inner pages that use the dynamic list component). Consider how the style may change across all of it's use cases (News & Events landing page, blog series, MRB page, etc.). Spike #606 initiated to further consider dynamic lists in the future._

### Definition of Done/Complete
Complete all subtasks identified below

**Sprint 42 & 43 [SP:5]**
- [x] Determine which H&L page components to use to build the News & Events landing page comps/comps
- [x] Determine styling for dynamic lists (see considerations in ticket description above)
- [x] Create comp based on discovery from tasks above
- [x] Review with internal UX design team to determine revisions (met on 10/13/22)
- [x] Review with internal dev team to determine revisions and discuss dev considerations (11/3/22)
- [x] Make updates associated with internal team discussion
- [x] Review changes with with internal team (11/10/22)
- [x] Make changes to comps that came out of internal meeting on 11/10 (see comment below for specific changes)
- [x] Send to internal team and update link on this ticket
    - [x] Internal review by @adrianacastaneda + Team 
- [x] Walk through final changes internally on 11/15 & verify no further changes from team/finalize internally
    - [x] Address final changes
    - [x] Share via Slack 
    - [x] Receive final internal approval
    - [x] Update links and comment on the ticket

**DS Sprint 7 [SP: 3]**
- [x] Update comp to ensure comp is built using all USWDS tokens (font, color, spacing, shadow)
- [x] Verify (QA) comps uses all USWDS tokens
- [x] Send updated comp around internally for final review (@monika to share via Slack, noting that the only changes are refinement to the spacing/color/font tokens)

**DS Sprint 9 [SP: N/A]**
- [x] Schedule time to review comps with federal team [PM to schedule] (goal is to be completed in DS Sprint 8)
- [x] Conduct review with federal time
- [x] Align on next steps

**DS Sprint 10 [SP: 2]**
- [x] Update comp with feature card to have horizontal rule as-is, and version with promo block to remove horizontal rule [both reduce to 5 press releases from 10]
- [x] Share with federal team for review
- [x] Finalize comp
- [x] Verify alignment for bottom section of comp with federal team and update comp
- [x] Initiate DS Dev build ticket

### Sketches
- [Sketches in Figma (figjam)](https://www.figma.com/file/ShNJI22XmAmCAv7Bxj9yfE/New-%26-Events-Discovery?node-id=0%3A1)

### Wireframes
- [Wireframes link (InVision)](https://publicis.invisionapp.com/console/share/S5Z9QGNKXRC)

### Visual Design
- [Comps](https://publicis.invisionapp.com/console/share/S5Z9QGNKXRC)

#### Prototype
- Prototype link or Github ticket link

### Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  

### Specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. [InVision](https://publicis.invisionapp.com/console/News-&-Events-Landing-Page-cl94jgpau00oh014h7y6sgzsk/cl94jgpns03jc017m0alxflg9/inspect)

#### Technical Constraints
*Technical constraints and dev questions to consider*
1. Constraint
2. Constraint
3. Dev question to be answered
4. Dev question to be answered

**Comment by monika-jaeger** [comment]
Added figjam link under 'Sketches' (WIP)

**Comment by monika-jaeger** [comment]
Added InVision link under 'Wireframes'

**Comment by laurelthrash** [comment]
Next steps discussion on Thurs. 10/13 internal review meeting @monika-jaeger @meglake 
- [ ] Version 2 - change the width of the left column to match the width of the image above so it is the same throughout @monika-jaeger 
- [ ] Version 2 - add a third promo card and see how this looks @monika-jaeger 
- [ ] Setup meeting with devs for high-level considerations and gauge desire for customization (e.g., Modifying the USWDS components used for "Recent News Releases" and "Media Resources," tags, implementing horizontal lines) @laurelthrash 

Notes
- Guide card must appear at the top
- "Recent News Releases" and "Media Resources" borrowed from USWDS

**Comment by laurelthrash** [comment]
Will carry into Sprint 41 for continued work and review.

**Comment by monika-jaeger** [comment]
> Next steps discussion on Thurs. 10/13 internal review meeting @monika-jaeger @meglake
> 
> * [x]  Version 2 - change the width of the left column to match the width of the image above so it is the same throughout @monika-jaeger
> * [x]  Version 2 - add a third promo card and see how this looks @monika-jaeger

@laurelthrash & @meglake : Version 2 [Desktop](https://publicis.invisionapp.com/console/share/S5Z9QGNKXRC/962831929) & [Mobile](https://publicis.invisionapp.com/console/share/S5Z9QGNKXRC/963059277) have been updated per internal meeting review from 10/13.

**Comment by laurelthrash** [comment]
Moving to Sprint 41. Meeting scheduled for Wed. 10/19 postponed until week of 10/24/22. Cc: @monika-jaeger

**Comment by laurelthrash** [comment]
Moving to Sprint 42 to prioritize other time sensitive work in Sprint 41. Cc: @monika-jaeger

**Comment by laurelthrash** [comment]
(Comment in progress)

Met with dev team on 11/3. Next steps are: 

Notes
- USWDS Collection Component - may have different variations.

Questions answered: 

- Q: Can we customize border color? A: TBD
- Q: Can we hide certain content until we are ready? A: Yes, in most cases.

**Comment by laurelthrash** [comment]
(Comment in-progress)

Met internally with UX team on 11/10. Determined

**Comment by monika-jaeger** [comment]
@laurelthrash comps have been updated per feedback. [Invision Link with Comps](https://publicis.invisionapp.com/console/share/S5Z9QGNKXRC)

Figjam link with discovery notes.
[Discovery in Figma (figjam)](https://www.figma.com/file/ShNJI22XmAmCAv7Bxj9yfE/New-%26-Events-Discovery?node-id=0%3A1)

cc @blilianyu

**Comment by laurelthrash** [comment]
In Progress
Conducted final internal review with UX team on 11/15. Identified the following changes:
- [ ] Fix spacing on dates for recent news releases (v1 & v2)
- [ ] Verify that promo block on v2 is centered vertically (adjust padding on top and bottom)
- [ ] Under "Cancer Current Blog" swap headline with 
- [ ] Under "Cancer Current Blog," change "Latest Posts" to "View All Blogs"
- [ ] Lindsay to share comments on Invision board
- [ ] On mobile, adjust order of Cancer Current Blog and Media Resources so that Media Resources is first. 
- [ ] Confirm gray background is accurate on all version + mobile/desktop. Gray background should start from banner down. 

Otherwise, no other internal changes. Will follow next steps outlined in future sprints. Cc: @monika-jaeger

**Comment by laurelthrash** [comment]
Moving to Sprint 45 - did not prioritize in Sprint 44 given other MVP1 launch priorities.

**Comment by laurelthrash** [comment]
Confirmed internally via Slack on 1/3/23 that the comp is final. Next step is to schedule time with federal team for review.

**Comment by laurelthrash** [comment]
Review meeting scheduled for 1/24/23. Moving this card to the appropriate sprint.

**Comment by laurelthrash** [comment]
[Comment in Progress] 

2023.01.24 - Review with Federal Team

News & Events Landing Page

**Comment by monika-jaeger** [comment]
Updated **[InVision link](https://publicis.invisionapp.com/console/share/74CY3JBH6RK)** with horizontal rule options & reducing number of articles to 5. 
cc @laurelthrash @blilianyu

**Comment by laurelthrash** [comment]
Received - thank you @monika-jaeger! Going to move the A-Z list comp through federal approvals first, then move over to News and Events.

**Comment by laurelthrash** [comment]
Note: pulled from related ticket #482 that when data was pulled in July 2022, visits for this page were 84% on desktop and 14% on mobile. This breakdown was requested during review with federal team.

**Comment by laurelthrash** [comment]
Federal team approved comp with fewer horizontal rules. Need to update comps to represent this preference and can proceed with developing DS Dec tickets for estimation and prioritization.

**Comment by monika-jaeger** [comment]
[InVision comps](https://publicis.invisionapp.com/console/share/74CY3JBH6RK) updated with less horizontal rules. 
cc: @laurelthrash / @meglake

**Comment by laurelthrash** [comment]
Decisions made with federal team on 02/07: 

Left rail versus right rail
- Decision: Have Recent News Releases on left and Media Resources on right (with preference toward feature cards on top, which will be finalized later)

**Comment by monika-jaeger** [comment]
[InVision comps](https://publicis.invisionapp.com/console/share/74CY3JBH6RK) updated with Recent News Releases appears on the left and Media Resources appears on the right,

**Comment by laurelthrash** [comment]
Created #742 (slated for DS Sprint 11) to review additional information related to the Collection component. Closing out this ticket as the work on the comp is complete.
