### ISSUE TITLE
Incorrect HTML in Innerpage Storybook Story and Example site 

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#488]
### Issue description
> **ESTIMATE** 1

**ISSUES:**
* The language "link" in the banner markup is incorrect. It is `<button href="/" class="usa-button usa-button--nci-small">Español</button>`. This should be an `<a>` tag instead.

**Comment by bennettcc** [comment]
This ticket was completed via https://github.com/NCIOCPL/ncids/issues/912

No additional work needed
