### ISSUE TITLE
Design: Date Display

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#49]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: [Enter user story ticket association here] 

### Description of Design request:
Need to design for the different date displays we support on article, blog post, press release, etc.

Considerations: previous discussions around date displays and locations.
##

### List of sub-tasks:
*Add links to related tickets below*
- [x] Review findings from IA recommendations of date display (https://tracker.nci.nih.gov/browse/CGOV-10503) (analysis by @lburack ) - does the location of the date impact google, are there other considerations to how the date displays or is captured on the back end? 
- [ ] 

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Feature: https://tracker.nci.nih.gov/browse/CGOV-10503
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

##

## Context
From Fedora: 
I was talking to Lynn about this ticket. Back in December 2019 (and from time to time since then) SWRB and ODDC talked about adding different types of dates to their pages (posted, updated, reviewed) and asked us for IA recommendations, which Lindsay provided. reWe also talked about moving the date to the top of the page for EAT purposes. I don’t think we reached out any conclusions but we did mention “Dates will remain at the bottom of the page for now, but can discuss changing placement as part of future design changes." Do you think we could add the solution to this as part of the redesign?

**Comment by mworrest** [comment]
Undergoing usability testing on the article content type (at the bottom of the page).

**Comment by anthonycuellar** [comment]
Michelle and Lilian are OOO. Moving this into sprint 8 so we can close out sprint 7.

**Comment by mworrest** [comment]
This is still being debated by clients. Requirements need to be finalized.

**Comment by mworrest** [comment]
The qualifying text mentioned above was rejected. We will keep dates in the location that they currently are on the live site. We will standardize the styles for dates across the site.
