### ISSUE TITLE
Document all MVP 1 components and identify DS type

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#490]
*Create documentation for all MVP 1 items to identify what components are directly from USWDS, completely new custom component, or an alteration of a USWDS component.*

### Sub-Tasks
- [x] Compile list of components in MVP 1: https://lion.box.com/s/hrzays1pqf11py64qdnc16rkwsokftnn
- [x] For each item in the list document the following:
-- DS type (directly from USWDS, completely new custom component, or an alteration of a USWDS component)
-- If not directly from USWDS, document the following:
--- What does USWDS do (include link to their DS page)
--- What are we doing (include link to comps and/or our DS page)
--- Why?
--- Note any info about decision (ie when approved)
-- Any things to keep in mind for UAT or launch (ie cranberry rollovers, how USWDS wrapping breadcrumb creates horizontal scroll at certain breakpoints when there is a very long title (~100 characters or more)

**Comment by laurelthrash** [comment]
Meeting slated for 06/22/2022.

**Comment by laurelthrash** [comment]
Sprint points in Sprint 32: placeholder 
Sprint points estimated for Sprint 33: placeholder

**Comment by laurelthrash** [comment]
Standup update: on track for @blilianyu to perform work on this ticket ahead of OOO to hand off to @mworrest for completion.

**Comment by laurelthrash** [comment]
Complete, link in the description. @meglake take final look and then add to Teams 07/12.

**Comment by meglake** [comment]
Completed and shared with client on teams on 7/26
