### ISSUE TITLE
Design Direction: Cancer Types Landing Page (A-Z List)

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#491]
Design: [2 Direction Phase](https://lion.box.com/s/vo05p9fcn9i32h1bsu22v0ln5c55v1lj)

# Design Direction: Cancer Types Landing Page
Create design solution for Cancer Types landing page (A-Z list) based on empathy research discovery (https://github.com/NCIOCPL/ncids/issues/384).

Consider current styling and the connection to other A-Z list styling on the site.
A-Z list links at the top are on these PDQ list pages too (these are mini landing pages in Drupal): https://www.cancer.gov/publications/pdq/information-summaries/adult-treatment

Note: This would be for an iteration after release 2. During release 2 Cancer Types landing page will stay as is.

### Feature/Main User Story:
As a [role], I want [feature], so that [benefit]

### Links to related tickets 
- Discovery Ticket: #384 
- Direction Ticket (this ticket): #491
- Initial Prototypes Ticket: #525  
- Testing Prototypes Ticket: #570 
- Solution Ticket: #504 
- Build Ticket(s): TBD 

### Timeline
To be completed in Sprint 34

### Definition of Done/Complete
*Align on what done/complete means for the scope of the direction work.*

### Opportunities
- *Opportunity ONE*
- *Opportunity TWO*
- *Opportunity THREE*

### List of sub-tasks:
*Additional tasks that need to be completed.*
- [x] Review empathy research
- [x] Identify requirements, components and patterns
- [x] Visual design exploration (design burst on 7/20)
- [x] 7/26 @ 1pm meeting - Review with internal design team [If all aligned then this ticket can be closed]

Next step: 8/2 @ 9:30am meeting - Review with clients and incorporate feedback into design solution ticket https://github.com/NCIOCPL/ncids/issues/504 [to be started in sprint 35]

#### Assets:
* Design Burst: https://app.mural.co/invitation/mural/publicissapient7269/1657120692658?sender=michellegallo6566&key=e4578125-b875-4382-92cc-ddc35114138a
* Sketch File(s): https://lion.app.box.com/folder/159087400037
* Mockups: https://publicis.invisionapp.com/console/share/6MWXYCBU4RJ
* Web Page: https://www.cancer.gov/types
#### Design Research & Inspiration:
[See design burst mural]

### Future State Exploration
*Identifying the requirements, components and patterns that will create the future experience for the project.*

#### Design specs/requirements:
*Design specs indicated below.*
1. Spec/Requirement
2. Spec/Requirement
3. Spec/Requirement

#### Design Components, Patterns, and Modules:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

#### Technical Constraints
*Align with developers to establish any technical constraints and a viable direction for solutions*
1. Constraint
2. Constraint
3. Constraint 

1. Can we change A-Z list class across the various pages this class is on or can we just target Cancer Types landing page
-- What is easiest/least amount of tech debt?
2. Dev question to be answered
3. Dev question to be answered

**Comment by laurelthrash** [comment]
Michelle will prepare for the design burst, and plan for the design burst to replace our 07/20 our regular backlog grooming meeting.

**Comment by laurelthrash** [comment]
7/12: Team to prepare by reviewing stakeholder interviews and usability testing (located in Mural board), as well as bring examples of other A-Z lists found on other sites (e.g., American Cancer Society, phone book).

**Comment by laurelthrash** [comment]
7/18: On track for @mworrest to share expectations with the team via email for review/preparation ahead of Design Direction meeting on 07/20.

**Comment by laurelthrash** [comment]
7/19: Note: plan to pull together Mural board to summarize Design Solution results to review during 07/26 client meeting.

**Comment by laurelthrash** [comment]
7/20: Design Direction meeting complete. Team agreed to establish three low-fidelity (e.g., wire frame) options for discussion/alignment on 7/26. @blilianyu @mworrest @dcvijanovic1k each complete one (different) wireframe approach.

**Comment by meglake** [comment]
@laurelthrash @mworrest - given schedules and OOO lets plan on the following review times:
7/26 at 1pm meeting - Review with internal design team [If all aligned then this ticket can be closed]
8/2 at 9:30am meeting - Review with clients and incorporate feedback into design solution ticket #504 [to be started in sprint 35]

**Comment by mworrest** [comment]
3 wireframes accessible through https://publicis.invisionapp.com/console/share/6MWXYCBU4RJ

**Comment by acsnedegar** [comment]
@mworrest - Just updating with the latest set of comps in the share link since @blilianyu  and I added the mobile ones to the others: https://publicis.invisionapp.com/console/share/6X8U25KCJHE Thanks!

**Comment by laurelthrash** [comment]
Closing this ticket as we are progressing with the next steps in the design project (associated tickets linked in the description).
