### ISSUE TITLE
At 1024 the menu goes wonky and alignment is off

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#492]
### Issue description
At the 1024 breakpoint, the menu goes wonky, and alignment is off.

> **ESTIMATE** 3

### Steps to reproduce the issue

1.  Go to storybook https://designsystem-dev.cancer.gov/pr-455/storybook/iframe.html?id=components-nci-header--nci-extended-desktop-longer-primary-item&globals=backgrounds.grid:false&viewMode=story
2. Open nci-extended-desktop-longer-primary-item
3. If needed, open in new window to see at 1024 breakpoint

### What's the expected result?
COMP: https://publicis.invisionapp.com/overview/NCI-DS-Spanish-cl2qe0hwx001r01aa3ajtac6t/screens
- Menu items don't wrap at 1024 (per comp with actual content, nav labels don't wrap) [Bug]
- Menu items should all be center aligned horizontally [Change Request]

### What's the actual result?
- Menu items wrap at 1024
- Menu items are top aligned

### Additional details / screenshot
-![Screen Shot 2022-06-15 at 3 53 59 PM](https://user-images.githubusercontent.com/4921685/173915593-e1ae9b92-ea7e-4132-b821-a8dcc6941718.png)

### Related Tickets
* Issue #455

**Comment by bennettcc** [comment]
2 SP accomplished in S35, 1 remaining in S36
