### ISSUE TITLE
Side Nav arrow should be center aligned with nav text

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#496]
### Issue description
During https://github.com/NCIOCPL/ncids/issues/312 the side nav was built but the arrow (>) was built to be aligned with the first line of nav text, however the expected behavior is meant to have the (>) center align with the full text (even when it's multiple lines)

> **ESTIMATE** 2

### Steps to reproduce the issue

1. Look at side nav built as part of #312 
2. View side nav item that as a nav text that wraps to multiple lines, 
3. The arrow (>) only stays aligned with the first line of nav text

### What's the expected result?
- The arrow (>) in the side nav should center align with the nav text even when it wraps multiple lines

### What's the actual result?
- The arrow (>) in the side nav aligns with the first line of nav text (even if the nav text wraps multiple lines) 

### Additional details / screenshot
Expected Result comps: https://publicis.invisionapp.com/console/share/SY11BOIJQK4T/897679492 

Current Result Example:
![Side Nav Example](https://user-images.githubusercontent.com/41208873/174887685-d90a714e-fc66-4740-ad85-7cc9f9f50315.png)

Note: The expected outcome is what is seen on the mobile nav: https://github.com/NCIOCPL/ncids/pull/446
See screenshot: 
![Mobile Nav Example](https://user-images.githubusercontent.com/41208873/174887750-614cd1c3-3ba2-42e7-bb15-b04afe875e57.png)

### Related Tickets
* Issue #312 
* Issue #397

**Comment by olitharp-nci** [comment]
Completed in https://github.com/NCIOCPL/ncids/pull/557
