### ISSUE TITLE
Spike: Content review of footer links

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#5]
## In order to understand what should be included in the footer, we need to conduct a content review of all of the footer links (including analytics of usage of the links) to determine what is needed.

Determine if we can streamline footer content.

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* Proposed footer content based on analysis of current state

### Additional Notes:
* Some links may be mandated by governance (determine which ones are required, and which ones can be removed)
* Look back at digital strategy and what NCI policy requires DOCs to include in their footers
![DOC - Annotated Homepage](https://user-images.githubusercontent.com/4921685/107684122-66194080-6c70-11eb-8c5b-de97db37de26.jpg)

### Results of Spike
*Enter the information, or links to any (non-sensitive) files with the findings here*

**Comment by claireblaustein** [comment]
Content audit can be found on box: https://lion.box.com/s/wyd8vo9lqszpqjkj3mj7c7qykud8hbrh
