### ISSUE TITLE
Design Solution: Cancer Types Landing Page (A-Z List)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#504]
Design: [3 Solution Phase](https://lion.box.com/s/w5nalm9zjdt361bwke6fxys1duy8p9lp)

# Design Solution: Cancer Types Landing Page (A-Z List)
*Use visual sketches and alignment that came out of the design burst (#491) in order to build comp or prototype that we can test as the design solution. Scope of testing can be determined after we complete the design burst.*

> Feature/Main User Story: [Enter user story ticket association here] 

### Links to related tickets
- Discovery Ticket: #384 
- Direction Ticket: #491 
- Initial Prototypes Ticket: #525  
- Testing Prototypes Ticket: #570 
- Solution Ticket (this ticket): #504 
- Build Ticket(s): TBD 

### Timeline
*Work will begin on this ticket after the conclusion of the design direction/burst conducted in #491.*

### Definition of Done/Complete
*Align on what done/complete means for the scope of the solution work.*

### Considerations to take into account when designing:
- Does this design element work for the same needs on Spanish pages?
- What is the Tablet/Mobile display for this design element?
- Is this element a re-envisioned version of something we currently have? (like the new guide cards for example) If so, what of the current Drupal functionality will remain in place? What would need to change in implementation?
- If this is a new component, what is the purpose of the component/how is it used?
- What other content types would this component work on? Which ones do we exclude it from and why?
- What is the guidance or tooltips we would use for this component in Drupal?
- Are there limitations we might want - like character limit, or only for use with media items, or only for use with internal links, etc?
- How would someone outside of our system use this component? Getting back to the overall purpose of a component - is it to link to other content? Highlight content? - - What is the ultimate goal for a user when a component is used on a page?

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Create inventory of pages (does not have to specifically be landing pages) that use the index and/or A-Z list.
- [ ] Use sketches to create mock-up/prototype at various breakpoints (note: minimal prototyping)
- [ ] Internal review /updating of mock-ups (design and devs)
- [ ] Client review of mock-ups
- [ ] Testing (scope TBD) 
- [ ] Updates made after testing results received

### Sketches
- Sketches link

### Wireframes
- Wireframes link

### Visual Design
- Comps link

#### Prototype
- Prototype link or Github ticket link

### Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 

### Specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link

#### Technical Constraints
*Technical constraints and dev questions to consider*
1. Constraint

1. Dev question to be answered

**Comment by laurelthrash** [comment]
07/27 update on timing: 
- Create new ticket for Sprint 35 that includes meeting with the client to demo wireframes, make updates, and create prototypes. SP the prototyping ticket after meeting with client. 
- Create new ticket for Sprint 35, 36 (start Aug 9), and 37 (start Aug 23) - testing **need to check-in before slating testing**
- Move this ticket to after above concludes (Sprint 38)

**Comment by laurelthrash** [comment]
08/30 update: Moving this ticket to Sprint 39 to slot in Testing ticket in Sprint 38.

**Comment by laurelthrash** [comment]
Moving this ticket to "approved backlog" until after testing and we are in a position to slot the design into an active sprint.

**Comment by sarinapadilla** [comment]
@laurelthrash, we have completed design for the Cancer Types Landing Page ([Figma comps here](https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&node-id=0-1&mode=design&t=qFqrMhfU23POid7H-0)) so closing this ticket!
