### ISSUE TITLE
Update all Release 2 comps to remove breadcrumbs 

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#509]
*Description of what is to be accomplished.*

Based on breadcrumbs requirements: https://github.com/NCIOCPL/cgov-digital-platform/issues/3242 landing pages will not have breadcrumbs. This aligns with USWDS guidance as well: https://designsystem.digital.gov/components/breadcrumb/

Please remove the breadcrumbs from all release 2 comps and update screenshots on stakeholder design board: https://app.mural.co/invitation/mural/publicissapient7269/1652804277768?sender=meganlake7790&key=1bc9c527-9e14-4d2c-b775-4e8c71f8c9be

### Sub-Tasks
- [x] Update release 2 landing page comps to remove breadcrumbs
- [x] Update screenshots on stakeholder design Mural Board

**Comment by dcvijanovic1k** [comment]
Hi @meglake and @blilianyu - I've made the necessary updates in the Sketch files and on the Mural that is linked in this ticket. Do you two mind taking a look and letting me know if we are good to go please? Thank ya much!

**Comment by meglake** [comment]
@dcvijanovic1k looks great to me! Deferring to @blilianyu for official sign off and closing of ticket :)

**Comment by blilianyu** [comment]
@dcvijanovic1k Looks great, thank you! @meglake we can close this ticket!
