### ISSUE TITLE
Email sign up doesn't work (opens a 'about:blank' page)

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#510]
### Issue description
*Description of the issue*

> **ESTIMATE** 2

### Steps to reproduce the issue

1. Use `nci-big` footer component
2. Add valid email address
3. New tab opens with 'about:blank' as url

### What's the expected result?
- Form submits

### What's the actual result?
- Form doesn't submit

_Originally posted by @meglake in https://github.com/NCIOCPL/cgov-digital-platform/issues/3435#issuecomment-1189154130_

**Comment by bennettcc** [comment]
This needs @arcepaul and @bryanpizzillo  approval!
