### ISSUE TITLE
NCIDS Header Does not allow for setting a menu link's current state

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#512]
### Issue description
> **ESTIMATE** TBD

Not every item will have a mega menu and thus we need to be able to set the "on" state (`usa-current`) for a primary nav. This is not possible now as it only works for mega menu buttons.

See the screen shot below when on the About NCI page
<img width="994" alt="image" src="https://user-images.githubusercontent.com/11215649/180283419-696d4834-100d-42d8-a657-1a6503476fcf.png">

This was for the markup:
(Note: I even tried adding `usa-current` to the `li` tag.)
<img width="777" alt="image" src="https://user-images.githubusercontent.com/11215649/180283672-62ad58c9-c4be-4fdb-a395-2032f4fe18c3.png">

**Comment by bennettcc** [comment]
2 SP accomplished in S35, 1 remaining in S36
