### ISSUE TITLE
Banner Print Style

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#514]
## As a user, I want to have any banners hidden on print pages, so the printed page is more focused on content.

Update print stylesheet to exclude language toggle banner, dictionary banner, and any alert banners when printing a webpage. See current cancer.gov print style as an example.

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: Banners are not shown on print
  Given a user goes to the Types of Cancer page on CGov
  When the user clicks the Print icon
  Then the Print page modal displays
    And the Print styles are used
    And the language toggle banner does not display
    And the dictionary banner does not display
    And the site alert(s) banner does not display
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: https://www.cancer.gov/about-cancer/treatment/types and click the print icon

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by olitharp-nci** [comment]
Completed with https://github.com/NCIOCPL/ncids/pull/517
