### ISSUE TITLE
Fix the Primary Navigation on the NCI Header to be more like USWDS

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#518]
>**TL;DR;** We did not follow USWDS see [What Needs to be Done](https://github.com/NCIOCPL/ncids/issues/518#issuecomment-1195584541).

This ticket is now a rollup of all the Primary Nav issues that have the same root cause. We strayed too far from the USWDS for the primary nav of the NCI Header.

### Limited Nav Items Look Weird

Bryan found an issue where NCI CONNECT Spanish site only has 2 top nav items and the two nav items are seen on the opposite page of each other (see screenshots)

DS:
<img width="1052" alt="image (18)" src="https://user-images.githubusercontent.com/41208873/180514048-3791d689-0d12-4fd6-92ea-e8e6fb2c91ba.png">

PROD:
<img width="1221" alt="image (19)" src="https://user-images.githubusercontent.com/41208873/180514085-72ef3216-af33-4dce-8a2b-90e26ae3b869.png">

Need to look at different sites on the platform that have smaller site nav:
| Site  | # of Nav Items |
| ------------- | ------------- |
| Cancer.gov ([English](https://www.cancer.gov/) & [Spanish](https://www.cancer.gov/espanol)) (English & Spanish)  | 6 |
| [NCI CONNECT](https://www.cancer.gov/rare-brain-spine-tumor/)  | 5  |
| [NCI CONNECT (Spanish)](https://www.cancer.gov/rare-brain-spine-tumor/espanol)  | 2  |
| [MyPART](https://www.cancer.gov/pediatric-adult-rare-tumor/)  | 6  |
| [DCEG](https://dceg.cancer.gov/)  | 5  |
| [Physics](https://physics.cancer.gov/)  | 5  |
| [Nano](https://www.cancer.gov/nano/)  | 5  |
| [CCG](https://ccg-cms.cancer.gov/ccg/)  | 4  |
| [SBIR](https://sbir-cms.cancer.gov/)  | 5  |

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/rare-brain-spine-tumor/espanol and compare the nav spacing in the mega menu to DS screenshot above

### What's the expected result?
- To align with USWDS nav items should align left and add padding based on USWDS: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=components-header--extended-megamenu&args=&viewMode=story (per Bryan it's 1rem of padding

Screen shot of cancer.gov nav items with this expected result:
<img width="1054" alt="image (23)" src="https://user-images.githubusercontent.com/41208873/180565862-abf326d0-6d63-49b4-bf46-ce817fb39a98.png">

### What's the actual result?
- the nav items are not left aligned

### Additional details / screenshot
- see above

### Related Tickets
* #436 
* #492 
* [#3277](https://github.com/NCIOCPL/cgov-digital-platform/issues/3277)
* [#3268](https://github.com/NCIOCPL/cgov-digital-platform/issues/3268)

**Comment by bryanpizzillo** [comment]
## What Needs to be Done?
The over all comment is our menu items should be just like USWDS' extended header with mega menu.
1. First the menu items need to be left justified the same as USWDS
2. The menu items should have 1rem of padding, not .5rem
3. The text of the first menu item should line up with the header, but the clickable area/active should extend past the header to the left. See the image below. The USWDS header accounts for this working correctly, so we have done something to break this. Also to note their text of the header aligns with the flag in the official site banner.
     ![image](https://user-images.githubusercontent.com/11215649/180796391-ec420c79-12f6-4691-a955-51b300ee236e.png)
4. USWDS menu items do not have a max length. We have constrained ours at 200px for some reason. This should follow the USWDS way. (Michelle is checking)

**Comment by bennettcc** [comment]
2 SP accomplished in S35, 1 remaining in S36
