### ISSUE TITLE
MegaMenu html is incorrect in the stories and the example site

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#522]
### Issue description
> **ESTIMATE** TBD

In the Example site HTML all but the first section heading link is missing the `nci-megamenu__list-item-link` class. See
[example-data-1](https://github.com/NCIOCPL/ncids/blob/43338c78ec82278db14d5f9fe540432c6b0f2f34/testing/ncids-js-testing/public/data/mega-menu/example-data-1.html#L22) for an example. 

This is also missing from the nci-header-primary.js used by some stories in Storybook as well.

**Comment by olitharp-nci** [comment]
Completed with https://github.com/NCIOCPL/ncids/pull/523
