### ISSUE TITLE
Prototype: Cancer Types Landing Page (A-Z List)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#525]
> **ESTIMATE** SP8 (placeholder)

Summary: Determined in Design Backlog Grooming meeting on 0727/22 that we would create a stand-alone ticket for Sprint 35 to include the following: 

- [x] Update wireframes based on 07/26 internal meeting @blilianyu @mworrest @acsnedegar (related to #491 
- [x] Share initial wireframe ideas with the client on Tues. 08/02 @ 9:30am
- [x] Arrange stakeholder meeting with content owners and CIS @meglake 
- [x] Share wireframes with content owners on 08/16 @ 10:00am **[Sprint 36]**
- [x] Make updates to wireframe for option 3 based on client feedback (see [Mural Board](https://app.mural.co/invitation/mural/publicissapient7269/1659450122858?sender=meganlake7790&key=4659fc1e-588a-4c18-b7d9-27daf7378fa2)) and share wireframes during end of sprint demo on 08/23 @ 12pm; **[Sprint 36]**
	- Note:  https://tracker.nci.nih.gov/browse/CGOV-16746 will capture data for Cancer Types megamenu that will help with determining related information link to include on the landing page.
- [x] Establish alignment on wireframe; and **[Sprint 37]**
- [x] Create the prototypes for the concepts **[Sprint 37/38]**
- [x] Obtain internal review of prototypes for concept and subsequent updates **[Sprint 37/38]**

Immediately following the completion of this ticket will be testing on the prototypes.

### Links to related tickets:
- Discovery Ticket: #384 
- Direction Ticket: #491 
- Initial Prototypes Ticket (this ticket): #525  
- Testing Prototypes Ticket: #570 
- Solution Ticket: #504 
- Build Ticket(s): TBD 

**Prototype Name:**
- Why we think this concept will work or improve that moment ...
	- Ex: girls are more comfortable learning from peers
- Our biggest question/unknown about this concept right now ...
	- Ex: will this be acceptable to parents and village leaders?
- Other things we want to learn about this concept ... 
	- Ex: What’s the right message? Do they use Whatsapp or Facebook more?

**Prior to Prototyping: Learning Plan**
- Top 3 learning questions this prototype is testing:
- Key metrics for success
- Testing Method
- Assumptions

**After Prototyping: Report Card**
- What we learned
	- What answers did we find to our learning questions? 
	- Did we see the results we wanted in our key metrics? 
	- Did we find out anything about our assumptions?
- Iterations
	- Based on our learnings, what do we need to change?
	- What are we taking forward from this prototype?
	- What do we need to learn next?

Link to Prototype:

	- ...

Related Issues:

	- ...

### Notes
Some PDF resources if anyone is interested:
[DesignKit_PrototypeMapping_Worksheet.pdf](https://github.com/NCIOCPL/ncids/files/8162692/DesignKit_PrototypeMapping_Worksheet.pdf)
[DesignKit_prototypereportcard_worksheet.pdf](https://github.com/NCIOCPL/ncids/files/8162694/DesignKit_prototypereportcard_worksheet.pdf)

**Comment by meglake** [comment]
Content owner convo on 8/16 and then we'll determine next steps for prototyping for testing.

**Comment by meglake** [comment]
@acsnedegar and @blilianyu, we received data on the Cancer Type's megamenu usage: https://tracker.nci.nih.gov/browse/CGOV-16746 Given the data, lets just use lorem ipsum links in the "Related Information" "area" of the wireframe for review on 8/23 end of sprint.

**Comment by laurelthrash** [comment]
Update 8/17: Plan to show updated wireframe for option 3 during end of sprint 08/23. Will add SPs for the prototype following end of sprint discussion.

**Comment by meglake** [comment]
Update 8/23: @blilianyu  and @acsnedegar please update the wireframe based on end of sprint meeting feedback:

- Revise header area to be consistent with other home/landing page styling (if it's a component then it should be on the grey page background, but the component itself can have it's own container color if desired)
- Update links in the first two boxes:
**Common Cancer Type:**
Bladder Cancer
Breast Cancer
Colorectal Cancer
Endometrial Cancer
Kidney (Renal Cell)  
Lung Cancer
Melanoma Cancer
Non-Hodgkin Lymphoma Cancer
Pancreatic Cancer
Prostate Cancer
**Related Information:**
Childhood Cancer
Adolescents and Young Adults with Cancer
Metastatic Cancer
Recurrent Cancer

Once wireframe is updated, please share with internal team for a quick review and then we'll find a time to review with clients before moving to prototype build out.

**Comment by laurelthrash** [comment]
Sprint 36: completed XX SP, carrying issue over to Sprint 37 and assigning new SPs

**Comment by laurelthrash** [comment]
Update 09/30: Reviewed with federal team during 9:30am meeting. Federal team approved wireframe. Team to begin creating the prototype.

**Comment by laurelthrash** [comment]
Update 08/31: Start prototype in Sprint 37, finish in Sprint 38. Does not prevent us from starting on a testing plan.

**Comment by laurelthrash** [comment]
Update: slated to review the prototype internally on Mon. 09/19. Annie to share the prototype internally by Fri. 09/16 ahead of the meeting.

**Comment by laurelthrash** [comment]
Changes to prototype following internal review 09/19 @acsnedegar: 

- [ ] Change search function to reflect the combo box (both desktop and mobile).
- [ ] Add breadcrumb on mobile for user to navigate back to the A-Z list. 
- [ ] Add small return in between cancer type names to more clearly separate cancer types names, especially for those with longer names that wrap (reference current list on Prod). 
- [ ] Implement auto-focus where user clicks and automatically shifts to the top of the page to show more results. 
- [ ] Add cursor in search functionality to indicate where the user is in the experience (desktop and mobile). 

Next steps:
- Demo at 09/20 end of sprint
- Get sign-off that we can move to the next step

Notes on alignment: 
- Search is a combo box where you start typing and search reflects both contained and begins after 1 letter typed (instead of 3 letters typed).

**Comment by acsnedegar** [comment]
Hey @laurelthrash - I made the above updates to the comps below. I will update on slack too so others can take a look if they want to before sharing tomorrow. 
[Desktop](https://publicis.invisionapp.com/console/share/WJGB3DQV2A5)
[Mobile](https://publicis.invisionapp.com/console/share/HFUZXEPB2TA)

**Comment by laurelthrash** [comment]
Demoed prototype at end of sprint on 09/20/22. Final prototype links listed above. Closing this ticket as we are progressing with the next steps in the design project (associated tickets linked in the description).
