### ISSUE TITLE
Atomic Component: Development Button (React)

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#53]
### NCIDS Button component and Storybook documentation

> **ESTIMATE** TBD

### Acceptance Criteria
Component for NCIDS react package.
Storybook page for Component inspection and Documentation.

*Specs can include:  Link to Invision with all states* 

```gherkin
Scenario: Primary button looks like comp
  Given User is viewing primary button on NCIDS-react storybook
  Then the button will show the default state
  Given the primary button is passed an onClick function
  Then that function is called when the button is clicked
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

This ticket is dependent on the color tokens for theme and system being approved and integrated to validate the listed items above.

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by meglake** [comment]
Closing ticket as work is complete through other tickets.
