### ISSUE TITLE
Build: Hero - B. Hero with Light Primary Call to Action

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#535]
### Build Hero with Light Primary Call to Action variation of hero component based on design specs/requirements documented in this ticket.

> **ESTIMATE** 5

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
- Hero image height will be fixed at 427px on widescreen, desktop & tablet large at 641px or larger
- Hero image will swap out with a 16:9 image on tablet & mobile large at 640px and less
- Hero image will swap out with a 1:1 image on mobile at 320px
- Light text box button will be fixed position so that it is always halfway between the image

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0282013t7d5l1urr/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0283013t4nhh03fd/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0284013t4aj381ri/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0285013tb131hhax/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0286013tckea7wt7/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0287013t51y80sss/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see a hero image without a button and a light text box, so that I can get a visual introduction to the page.  

Scenario: User views a landing page with a Hero Image w/Button & Light Text Box on Widescreen or Desktop
Given a user is viewing a landing page with a Hero Image w/Button & Light Text Box 
  And the browser width is 1400px or less  
Then the hero image will appear 
  And the height of the image will be fixed 
  And the light text box will appear on top of the image 
  And the text will appear on the left and should be font size theme token 3XL
  And the button will appear on the right with our primary button style at a fixed position
  And on hover, the button will follow our primary button hover style
  And clicking on that button will take the user to the corresponding page

Scenario: User views a landing page with a Hero Image w/Button & Light Text Box on Tablet Large
Given a user is viewing a landing page with a Hero Image w/Button & Light Text Box 
  And the browser width is 880px or less 
Then the hero image will appear 
  And the height of the image will be fixed 
  And the light text box will appear on top of the image and should be font size theme token 2XL
  And the button will appear on the right with our primary button style at a fixed position
  And on hover, the button will follow our primary button hover style
  And clicking on that button will take the user to the corresponding page

Scenario: User views a landing page with a Hero Image w/Button & Light Text Box on Tablet 
Given a user is viewing a landing page with a Hero Image w/Button & Light Text Box 
  And the browser width is 640px or less 
Then the 16:9 hero image will appear 
  And the light text box will appear on top of the image and should be font size theme token XL
  And the button will appear on the right with our primary button style at a fixed position
  And on hover, the button will follow our primary button hover style
  And clicking on that button will take the user to the corresponding page

Scenario: User views a landing page with a Hero Image w/Button & Light Text Box on Mobile Large
Given a user is viewing a landing page with a Hero Image w/Button & Light Text Box 
  And the browser width is 480px or less 
Then the 16:9 hero image will appear 
  And the light text box will appear on top of the image and should be font size theme token XL
  And the button will stack with our primary button style
  And on hover, the button will follow our primary button hover style
  And clicking on that button will take the user to the corresponding page

Scenario: User views a landing page with a Hero Image w/Button & Light Text Box on Mobile 
Given a user is viewing a landing page with a Hero Image w/Button & Light Text Box 
  And the browser width is 320px or less 
Then the 1:1 hero image crop will appear stack
  And the light text box will appear on top of the image 
  And the text will stack and should be font size theme token XL
  And the button will be full-width and stack
```

---

### Scenarios
- Short Tagline: NCI is the nation's leader in cancer research
- Long Tagline: Funding for small businesses with next-generation cancer technologies.
- Spanish Tagline: El NCI es el líder nacional en investigación del cáncer
- Button: Learn More 
- Spanish Button: Aprende más

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Used for landing pages with a singular call-to-action
- [ ] *When to consider something else*
  * If multiple call-to-actions are needed, look at hero component variations
- [ ] *Usability Guidance*
  * Cannot have multiple call-to-actions

**Comment by sarinapadilla** [comment]
@blilianyu the InVision comp has the primary button style as the Call to Action button, but the requirements say secondary button style. Which button style are we using?

For the time being, we're assuming that the tagline is a H2 styled as an H1.

**Comment by blilianyu** [comment]
@sarinapadilla thanks for catching! It should be primary button style. And yes, the tagline is a H2 styled as an H1. I've updated the ACs to reflect both of these.
