### ISSUE TITLE
[META] Video

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#539]
### Build inline video component variations based on design specs/requirements documented in this ticket:

**R2.1:**
- [x] A. Video #551 

> **ESTIMATE** TBD

### Design Definition of Done
*When all criteria below are met.*

**Comment by blilianyu** [comment]
Overall Guidance for Video components here
(each build ticket will have a specific guidance for the variation)

**Comment by bennettcc** [comment]
Closing this meta - video is not needed in the DS
