### ISSUE TITLE
Feature Kickoff: Search

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#54]
## Possible components for investigation
- Navigation Search Bar
- Dictionary Search
- Clinical Trials Search
- R4R Search

Notion: https://www.notion.so/Search-Bars-8a8c835ba00c4440aa2c8a4615c0c672

### **Enabler Tasks**

- [ ]  Inventory and analysis of content type features
- [ ]  Creation of Mural board to capture discovery

### **Follow Tasks**

- [ ]  Create tickets based on kickoff decisions
- [ ]  Update Notion entries according to groupings (as needed)

### **Decisions and Directions**

*List of decided components and links to subsequent tickets*

**Comment by anthonycuellar** [comment]
Split out "Navigation Search Bar" into a separate Github ticket

**Comment by VictoriaSunNIH** [comment]
Dictionary Search, Clinical Trials Search, R4R Search functionality should be split into their own apps. Closing this ticket as it will be replaced by others related specifically to each app.
