### ISSUE TITLE
[META] Content Grid

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#541]
### Build content grid component variations based on design specs/requirements documented in this ticket:

**R2.3:**
- [ ] D. 4 links - 1 large image & title only #714 

> **ESTIMATE** TBD

### Design Definition of Done
*When all criteria below are met.*

**Comment by blilianyu** [comment]
### Content Grid
Content Grid, usually at the bottom of the page, contains content and actions about a group of content as a final resort consisting of a visual image and 4 call-to-actions.

### Content Grid
**When to use Content Grid with 1 large image and 4 links variation**
- To promote a group of content at the bottom of the page before the user exits the page

**When to consider something else**
- If you want to promote content higher up the page, consider using a promo block, feature cards or guide cards



### Accessibility
- [Dev & UX]


### Additional considerations
- [guideline]

**Comment by sarinapadilla** [comment]
Closing this, as we aren't building this component for Home and Landing pages.
