### ISSUE TITLE
[META] Factoid Card

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#543]
### Build factoid card component variations based on design specs/requirements documented in this ticket:

**R2.5:**
- [ ] A. Factoid with Image (no link)
- [ ] B. Factoid with link to Infographic

> **ESTIMATE** TBD

### Design Definition of Done
*When all criteria below are met.*

**Comment by sarinapadilla** [comment]
Closing this, as we aren't building this component for Home and Landing pages.
