### ISSUE TITLE
Build: Guide Cards - A. Audience Guide Card Row

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#549]
### Build Audience Guide Card Row variation of guide card component based on design specs/requirements documented in this ticket

> **ESTIMATE** 5

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
- 16:9 image on all breakpoints
- If description is longer on one card, the buttons will align top for each card
- Cards should be the same height at all times on widescreen, desktop and tablet large (1400 and less)
- When cards stack on 640 and less, the card height will grow (does not have to be the same height)
- The heading should be styled as theme-h2-font-size
- Card shadow drops on Mobile 320

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0282013t7d5l1urr/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0283013t4nhh03fd/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0284013t4aj381ri/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0285013tb131hhax/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0286013tckea7wt7/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0287013t51y80sss/play
### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see an audience guide card row, so that I can quickly scan the call-to-actions.  


Scenario: User views a page with an audience guide card row on Widescreen or Desktop
Given a user is viewing the Cancer.gov home page 
  And the browser width is 1400px or less  
Then an audience guide card row will appear  
  And two cards will appear 
  And the title of the guide card should be font size theme token2XL
  And a 16:9 image will appear following our image guidance rules
  And a description will appear 
  And the buttons will appear with the secondary button style outline and align top 
  And the first buttons in the cards will align top
  And on hover, the buttons will appear with the secondary button style
  And clicking on the button will take the user to the corresponding page 

Scenario: User views a page with an audience guide card row on Tablet Large
Given a user is viewing the Cancer.gov home page 
  And the browser width is 880px or less  
Then an audience guide card row will appear  
  And two cards will appear 
  And the title of the guide card should be font size theme token XL
  And a 16:9 image will appear following our image guidance rules
  And a description will appear 
  And the buttons will appear with the secondary button style outline and align top 
  And the first buttons in the cards will align top
  And on hover, the buttons will appear with the secondary button style
  And clicking on the button will take the user to the corresponding page 

Scenario: User views a page with a guide card row on Tablet  
Given a user is viewing a home and landing page 
  And the browser width is 640px or less 
Then the cards in the audience guide card row will stack 
  And the title of the guide card should be font size theme token XL
  And a 16:9 image will appear 
  And the buttons will appear with the secondary button style outline and align top 
  And the buttons will align top
  And on hover, the buttons will appear with the secondary button style
  And clicking on the button will take the user to the corresponding page 

Scenario: User views a page with a guide card row on Mobile Large or Mobile  
Given a user is viewing a home and landing page 
  And the browser width is 640px or less 
Then the cards in the audience guide card row will stack 
  And the title of the guide card should be font size theme token LG
  And a 16:9 image will appear 
  And the buttons will appear with the secondary button style outline and align top 
  And the buttons will align top
  And on hover, the buttons will appear with the secondary button style
  And clicking on the button will take the user to the corresponding page 
```

---

### Scenarios
- Short description: Deaths from uterine cancer are rising in the United States, according to a new study led by researchers at NCI.
- Long description: Deaths from uterine cancer are rising in the United States, and are highest among non-Hispanic Black women, according to a new study led by researchers at NCI, part of the National Institutes of Health. 
- Spanish description: Las muertes por cáncer de útero están aumentando en los Estados Unidos, según un nuevo estudio dirigido por investigadores del NCI.
- Short button text: Support a program
- Long button text: Support an existing NCI-funded program
- Spanish button text: Apoyar un programa

- Audience guide card by itself
  - All description types and languages
- Audience guide card in a container with other card(s)
  - One card with shorter description, one with longer
  - One card with more buttons, one with fewer
  - Ugliest scenario possible: one card with really long description and two links, one card with a really short description and 6 links 

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * When you want to direct users to two specific groups of content
  * 2 cards are required 
- [ ] *When to consider something else*
  * If you do not have multiple audiences, use a feature card, promo card or guide cards components
- [ ] *Usability Guidance*
  * Minimum of 2 buttons and a max of 6

**Comment by sarinapadilla** [comment]
Closing this ticket, as we have the individual component tickets that cover the row scenarios.
