### ISSUE TITLE
Build: Promo Block - B. Dark Promo Block with Image

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#550]
## User Story:
**As a** developer,
**I want to** have the Development Solution from the DS,
**so that I** can implement the Promo Block component in a website

> **ESTIMATE** 5

Build Dark Promo Block with Image variation of Promo Block component based on design specs/requirements documented in this ticket.

### Guidance
* The first promo card should be set with the image aligned on the left  
* The second promo card should be set with the image aligned on the right  
* The following items should follow the alternating pattern
* Promo Block with Image

**When to use Dark Promo Block with Image variation**

* Used for promotional content to highlight a single subject with left-anchored or right-anchored visual
* Dark text box variation is meant for lighter images or illustrations

**When to consider something else**

* If multiple links are needed, look at guide card component variations
Variations
* If using darker images or illustrations, look at Light Promo Block with Image variation

**Additional considerations**

* Maximum of 10 cards on a page
* Image on the left is always the first card unless there is an alternating guide card above
* If there is an alternating guide card in between 2 promo blocks, the pattern will restart

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
- 1:1 image on Widescreen, Desktop & Tablet Large (880px or larger)
- 16:9 image on Tablet, Mobile Large & Mobile (879px or smaller)
- Image will alternate left and right positioning
- The heading should be styled as theme-h2-font-size

### Comps
Figma **(WIP)**: https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?node-id=0%3A1&t=jFhZBNr4nRIuKNBp-0
InVision:
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0282013t7d5l1urr/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0283013t4nhh03fd/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0284013t4aj381ri/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0285013tb131hhax/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0286013tckea7wt7/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0287013t51y80sss/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User views a page with a Dark Promo Block with Image
Given a user is viewing a landing page with a Dark Promo Block with Image
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Dark Promo Block with Image on the example site
  And the Dark Promo Block with Image on the example site will match the comp
  And the button will have the secondary button style 
  And the button on the Dark Promo Block with Image will be clickable
  And the button will be linked to its corresponding content
When the user hovers over the button
Then the button will have the secondary button hover style

Scenario: User views a page with a Dark Promo Block with Image on Widescreen, Desktop, or Tablet Large
Given a user is viewing a landing page with a Dark Promo Block with Image
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is at least 880px
Then the user will be able to view the Dark Promo Block with Image on the example site
  And the image will have a 1:1 aspect ratio

Scenario: User views a page with a Dark Promo Block with Image on Tablet, Mobile Large, or Mobile
Given a user is viewing a landing page with a Dark Promo Block with Image
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 880px
Then the user will be able to view the Dark Promo Block with Image on the example site
  And the image will have a 16:9 aspect ratio

Scenario: User views a page with more than one (1) Dark Promo Blocks with Image
Given a user is viewing a landing page with more than one (1) Dark Promo Blocks with Image
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Dark Promo Blocks with Image on the example site
  And the top-most Dark Promo Block with Image should have the image on the left
  And the following Dark Promo Block with Image should have the image on the right
  And each subsequent Dark Promo Block with Image should alternate the side of the image following the above pattern
```

---

### Scenarios
**Expected use case:**
- Short Title: Resources for Researchers 
- Long Title: NCI awards $23 million to study telehealth
- Spanish Title: Recursos para investigadores
- Short description: Check out this directory of NCI-supported tools and services for cancer researchers.
- Long description: Results from the NCI-supported ANCHOR study show that treating anal precancerous growths known as high-grade squamous intraepithelial lesions, or HSIL, reduces the chance that anal cancer will develop by more than half.
- Spanish description: Consulte este directorio de herramientas y servicios respaldados por el NCI para investigadores del cáncer.
- Short button text: Learn about funding 
- Long button text: Learn more about funding for research projects
- Spanish button text: Más información sobre la financiación

**Long title/button edge case:**
- Title: Study identifies novel genomic changes in the most common type of lung cancer; TCGA finds mutations in a key cancer-causing pathway, expanding targets for existing drugs
- Description: Researchers from The Cancer Genome Atlas (TCGA) Research Network have identified novel mutations in a well-known cancer-causing pathway in lung adenocarcinoma, the most common subtype of lung cancer.
- Button: Click Here to Learn More and to Learn More Click Here

**Long description edge case:**
- Title: NCI Center to Reduce Cancer Health Disparities (CRCHD)
- Description: The Center to Reduce Cancer Health Disparities (CRCHD) is central to NCI’s efforts to reduce the unequal burden of cancer in our society via basic and community research, as well as networks, and to train the next generation of competitive researchers from diverse populations in cancer and cancer health disparities research.
- Button: Learn More
**All-around bad edge case:**
- Title: Un nuevo análisis de los subtipos de cáncer de seno podría llevar a una mejor estratificación del riesgo; Informe Anual a la Nación indica que la mortalidad y la incidencia de la mayoría de los cánceres continúan disminuyendo
- Description: Por primera vez, los investigadores han usado datos a nivel nacional para determinar la incidencia de los cuatro subtipos moleculares principales de cáncer de seno (mama) por edad, raza y grupo étnico, nivel de pobreza y varios otros factores. El informe mostró una continua reducción en las muertes por cáncer tanto en hombres, mujeres y niños, y para los cánceres que afectan a casi todos los lugares principales del cuerpo.
- Button: 

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Used for promotional content to highlight a singular event, case study or program
- [ ] *When to consider something else*
  * If multiple links, look at alternating guide card component
- [ ] *Usability Guidance*
  * Image on the right is always the first card 
  * If there is an alternating guide card in between 2 promo blocks, then the pattern will restart 
  * Optional title for alternating promo block if it is a list 
  * Max of 10 promo cards

**Comment by bennettcc** [comment]
@dlescarbeau 
Next steps for promo blocks [[ex. site link](https://designsystem-dev.cancer.gov/pr-683/example-site/example-pages/cgov-home.html)] & features cards [[ex. site link](https://designsystem-dev.cancer.gov/pr-594/example-site/example-pages/cgov-home.html)] below determined during 1pm requirements mtg.:

**Promo Blocks:**  Change clickable components from Button, Title, and Image, to Button only.
**Feature Cards:** Change so that titles are underlined at all times.

Believe our current design meets accessibility needs on desktop since the entire card is what the user interacts with (not the title) so the card is the clickable item. [Example supporting this from Neilson Norman Group](https://www.nngroup.com/consulting/).

However, there is not a way to distinguish a link on mobile/tablet. We will see what it looks like for card titles to be underlined at all times to mitigate this.

**Comment by sarinapadilla** [comment]
This promo block variant was created with PR #683 , so closing this ticket as it has been merged to `develop`!
