### ISSUE TITLE
Build: Video - A. Inline Video

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#551]
### Build **Inline Video** variation of video component based on design specs/requirements documented in this ticket

> **ESTIMATE**3

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
- Ability to upload video in Drupal

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406h701203aau3iau/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406h8012084nn6b5m/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406h9012085ar4gy3/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406ha012009l906i9/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406hb01209rmf8b93/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406hc0120hlg6frb7/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see an inline video so that I can view the video on the page. 


Scenario: User views a page with an inline video
Given a user is viewing a landing page with a video
  And the browser width is 320px or greater  
Then an inline video will appear 
  And clicking on the video will play on the page
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Used to feature a video
- [ ] *When to consider something else*
  * If multiple videos are needed, use the video gallery component (future enhancement)
- [ ] *Usability Guidance*
  * Must be a singular video

**Comment by sarinapadilla** [comment]
From a 1/10/23 client meeting:
Bryan recommends we focus on a video player for the platform vs developing a generic one that anyone using the NCIDS can use. (Note: USWDS doesn't provide a video component either)
Client approved - moving forward with just building the component for the platform. 
Closing this ticket!
