### ISSUE TITLE
Bug: Menu button and search box shouldn't wrap at smaller screensizes

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#558]
### Issue description
Starting at screen sizes 409px and below the mobile menu button and the search box wrap to different lines in the header. They should always bee on the same line and the text box of the search box should get smaller.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Reduce screen size to 409 or less
2. Screenshot below of what you'll see:
![Header wrapping](https://user-images.githubusercontent.com/41208873/185198732-595d8862-323d-40e5-85c7-70466c9d7f27.png)

### What's the expected result?
- When a user is looking at the header at a screen size of 409px or less the mobile menu button and the search box should be on the same line.
- Screenshot of what is expected below:
![Header Mock Up](https://user-images.githubusercontent.com/41208873/185198247-b46c1898-23cc-4864-b2a6-a559b65864f2.jpg)

### What's the actual result?
- See screenshot in steps to reproduce

### Related Tickets
* #3268

**Comment by meglake** [comment]
Assigning to @blilianyu for sprint 37 to comp how the search looks at 320 when a user starts typing into the text box.

**Comment by blilianyu** [comment]
@meglake @laurelthrash  Here are the updated comps at mobile 320

- Mobile 320: https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc/cl178079m77pb01uqf1nw8ccb/play
- Focus: https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc/cl7f1449e0c1l013244wx4b3a/play
- Search: https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc/cl7f1449d0c1k01329qd3a5pu/play

**Comment by laurelthrash** [comment]
The comps look good/are approved from @meglake and me. Next steps is for devs to review and ensure it looks good/there are no red flags. Cc: @blilianyu @bennettcc

**Comment by meglake** [comment]
Per team meeting on 9/13 - at around 480 and below we when a user clicks into the search box to search, the search box entry expands and covers the menu button.
