### ISSUE TITLE
["Short Name"]

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#562]
### Issue description
*Description of the issue*

> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by sarinapadilla** [comment]
Closing :)
