### ISSUE TITLE
Enabler: Make Cypress work with Storybook

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#57]
# Make Cypress work with Storybook for ncids-css

This enabler encompasses the items needed to have Cypress available to test storybook. For this item we will just implement Cucumber & Gherkin for Behavioral Tests; however, it should be flexible enough for any future visual regression tests. This does not include creating stories or integration tests. (However you might want to have *something* in order to make sure it is working :) )

The types of "behavioral" tests would be validating the dom element's computed styles.

> **ESTIMATE** 5 story points

**Comment by VictoriaSunNIH** [comment]
related to #211
