### ISSUE TITLE
Update page options icons in storybook

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#572]
### Issue description
Regression tests for inner pages use the wrong page option icons. We should be using USWDS.

> **ESTIMATE** TBD

### What's the expected change?
- use uswds print.svg and mail_outline.svg
- regression images for the inner page template for desktop and tablet. mobile should not change as page options is hidden

### What's the current functionality?
- custom icons

### What's the updated acceptance criteria?
- n/a

### Additional details / screenshot
- ![Screenshot]()
![Screen Shot 2022-09-07 at 1 29 19 PM](https://user-images.githubusercontent.com/85901679/188951950-97e7bfee-10dc-4a95-accd-8a138dada298.png)
![Screen Shot 2022-09-07 at 1 29 41 PM](https://user-images.githubusercontent.com/85901679/188951996-cf9c1bea-985d-443e-bae6-678b299af14c.png)

### Related Tickets
* Updated in https://github.com/NCIOCPL/cgov-digital-platform/issues/3256

Svgs as of v2.13.2
```svg
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 8H5c-1.66 0-3 1.34-3 3v6h4v4h12v-4h4v-6c0-1.66-1.34-3-3-3zm-3 11H8v-5h8v5zm3-7c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm-1-9H6v4h12V3z"/></svg>
```

```svg
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 14H4V8l8 5 8-5v10zm-8-7L4 6h16l-8 5z"/></svg>
```

**Comment by bennettcc** [comment]
Closing ticket per above comment
