### ISSUE TITLE
Spike: Investigate USAgov header and if styles are applicable to NCIDS header

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#575]
## In order to improve the design of the NCIDS header, a developer needs to look into what USAgov did to make their header items wrap nicely/other improvements, so that we can make enhancements.
> **Estimate** *# point* 

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Additional Notes:
* note 1

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by bryanpizzillo** [comment]
@sarinapadilla we looked into it already and it was posted to the chat for the header convo:

> usa.gov is using the 2.0 version of USWDS, which does not support change the rollover color of the mega menu indicator (i.e. the down arrow)
> If you zoom in they are using the gray-black arrow and not blue
> We used the 3.0 version of the primary nav which now results in the extra spacing, but supports the color change
> (p.s. and the USA.gov version has some overrides, one of which would break menus with only 2 items)

**Comment by bennettcc** [comment]
Closing ticket as no longer needed per 9/8 meeting
