### ISSUE TITLE
Discovery: Mobile Menu

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#58]
> Feature/Main User Story: https://github.com/NCIOCPL/ncids/issues/9 - Design: Wireframes of Site Banner and Footer - Desktop and Mobile

### What do you want to learn from this research?
List the questions you would like to answer

1. Do users have a difficult time using the mobile header considering 2 actions open an overlay and 2 actions go to other pages?
2. Do users have a difficult time with the sticky menu?
3. Do users prefer top or bottom sticky menu?

##

### User / Audience
Who will be using this design? What personas / audiences are you considering?
Every user with a phone.
##

### Project Stage
- [x] Discovery
- [ ] Design
- [ ] Development
- [ ] Live

##

### Timeline
When would you need findings / insights?
April 2021
##

### Resources
* Link to product brief:
* Github link: https://github.com/NCIOCPL/ncids/issues/9 - Design: Wireframes of Site Banner and Footer - Desktop and Mobile
* Screens or site: ![Screen Shot 2021-03-05 at 12 41 42 PM](https://user-images.githubusercontent.com/4921685/110152944-5e047a80-7db0-11eb-8fdc-6aca5d5b8521.png)

##

### Additional Notes
*Any other comments or notes if needed:*

**Comment by sewallaa** [comment]
Putting this on hold until we have more clarity on the scope of what will actually be in the mobile header and a better sense of if there are remaining questions
