### ISSUE TITLE
Build: Guide Cards - B. Guide Card with Background Image

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#597]
### Build Guide Card with Background Image variation of guide card component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
- 4:3 image on Widescreen & Desktop
- No image on Tablet Large, Tablet, Mobile Large & Mobile

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406h701203aau3iau/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406h8012084nn6b5m/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406h9012085ar4gy3/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406ha012009l906i9/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406hb01209rmf8b93/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7fbj88406hc0120hlg6frb7/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User views a page with a Guide Card with Background Image on Widescreen or Desktop
  Given a user is viewing a landing page with a Guide Card with Background Image
    And the browser width is 1400px or less
  Then a Guide Card with Background Image card will appear
    And the 4:3 crop of the image associated with the selected list item should appear
    And the title of the a Guide Card with Background Image should appear as a 2XL
    And the buttons will appear with the secondary button style outline
    And on hover, the buttons will appear with the secondary button style hover
    And clicking on the button will take the user to the corresponding page
    And the first guide card will have the image aligned on the right
    And the second guide card will have the image aligned on the left
    And the following items will follow the alternating pattern

Scenario: User views a page with a Guide Card with Background Image on Tablet Large, Tablet, Mobile Large or Mobile
  Given a user is viewing a landing page with a Guide Card with Background Image
    And the browser width is 880px or less
  Then a Guide Card with Background Image will appear
    And the image will not display
    And the title of the Guide Card with Background Image should appear as a 2XL
    And the buttons will appear with the secondary button style outline
    And on hover, the buttons will appear with the secondary button style hover
    And clicking on the button will take the user to the corresponding page
```

---
### Scenarios
Long Title & 6 Buttons
- Card Title: Cancer & Nanotechnology
- Button 1: Benefits of Nanotechnology
- Button 2: Detection & Diagnosis
- Button 3: Treatment & Therapy
- Button 4: Safety of Nanotechnology
- Button 5: Learn more about cancer and nanotechnology
- Button 6: Partners & Collaborators

Short Title & 2 Buttons
- Card Title: Research
- Button 1: NCI Alliance for Nanotechnology
- Button 2: Data Sharing

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### Guide Card with Background Image
**When to use Guide Card with Background Image variation**
- When you want to promote a group of content with a large visual image

**When to consider something else**
- If there is only one call to action, use a Promo block variation

** Additional considerations
- Minimum of two buttons and a maximum of 6 buttons for each variation
- No more than 10 Guide Card with Background Images on a landing page
- Background Images should alternate from left and right to allow the user to scan the page easily and not get image blocked

**Comment by sarinapadilla** [comment]
Closing this, as we aren't building this component for Home and Landing pages.
