### ISSUE TITLE
Build: Feature Cards - D. Thumbnail Card Optional Description

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#599]
### Build Thumbnail Card - Optional Description variation of Feature Card component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors

- 1:1 image on Widescreen, Desktop & Tablet Large
- No image on Tablet, Mobile Large & Mobile

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7gomaon03op010de5n6djs3/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7gomaon03oq010d1iaecatd/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7gomaon03or010d3g8t375p/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7gomaon03os010d7eti4ylw/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7gomaon03ot010deng75fvr/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl7gomaon03ou010d1s0efavk/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see a Thumbnail card row, so that I can quickly scan the promo content. 

Scenario: User views a page with a thumbnail card row on Widescreen or Desktop  
Given a user is viewing a landing page with a thumbnail card row 
  And the browser width is 1400px or less
Then a thumbnail card row will appear 
Then the title of the thumbnail card row will appear and should theme token 2XL
  And the 1:1 crop of the image associated with the feature card should appear (following our image rules)  
  And clicking on the image will take the user to the corresponding page
  And the title of the feature card should be font size theme token MD
  And the optional description will appear 
  And the button will appear with the secondary button style
  And on hover, the buttons will appear with the secondary button hover style 
  And clicking on the button will take the user to the corresponding page 

Scenario: User views a page with a thumbnail card row on Tablet Large
Given a user is viewing a landing page with a thumbnail card row 
  And the browser width is 880px or less
Then the thumbnail card row will stack 
Then the title of the thumbnail card row will appear and should theme token XL
  And the 1:1 crop of the image will appear
  And clicking on the image will take the user to the corresponding page
  And the title of the thumbnail card should be font size theme token MD
  And the optional description will appear 
  And the button will appear with the secondary button style
  And on hover, the buttons will appear with the secondary button hover style 
  And clicking on the button will take the user to the corresponding page 

Scenario: User views a page with a feature card row on Tablet, Mobile Large or Mobile
Given a user is viewing a landing page with a feature card row 
  And the browser width is 640px or less
Then the thumbnail card row will stack 
  And the image will not appear
  And the title of the thumbnail card should be font size theme token MD
  And the optional description will appear 
  And the button will appear with the secondary button style
  And on hover, the buttons will appear with the secondary button hover style 
  And clicking on the button will take the user to the corresponding page 
  And the container shadow will not appear 
```

---
### Scenarios
Card 1 w/ Description
- Title: NCI Cancer Centers Webinar
- Description: September 8, 2021 1:00 PM - 2:30 PM
- Button: View Event

Card 2 w/ Description
- Title: SBIR x FDA Contract Solicitation Webinar
- Description: August 24, 2021 2:00 PM - 3:00 PM
- Button: View Event

Card 1 w/o Description
- Title: Divisions, Offices & Centers
- Button: View NCI Organization

Card 2 w/o Description
- Title: Director & Senior Leadership
- Button: View NCI Senior Leadership

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### Thumbnail Card
**When to use Thumbnail Card) variation**
- Used to showcase a collection of events, organization links or promotional content

**When to consider something else**
- If a lengthier description is needed, use the feature card variation or promo block

**Comment by sarinapadilla** [comment]
Closing this, as we aren't building this component for Home and Landing pages.
