### ISSUE TITLE
Define Design Tokens for Line Height

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#604]
### Issue Description
Designers to confirm that line height don't need to change. Met during weekly Design System Maintenance meeting on 09/29 and defined the desired shadow, and associated tokens. At that time, defined the theme tokens for font size/weight as well as shadow tokens. Made a note that we must visit the line height with the design team. 
- USWDS line height information: https://designsystem.digital.gov/design-tokens/typesetting/line-height/
- Internal Mural board with documentation: https://app.mural.co/invitation/mural/publicissapient7269/1663767031504?sender=uc8881d65820946a13d002641&key=2ff3109f-918a-408f-bd1b-51abeeef3e6e

### Sub-Tasks
- [ ] TBD

### Notes
* Will be an R3 item, so not priority now but should be addressed at the same time we define the usa-prose H1-H6 headings (#610)
* Related ticket being addressed for NCIDS Launch: #1332

**Comment by sarinapadilla** [comment]
@laurelthrash the description says that the line height tokens need to be defined when we work on #610, which has been completed. However, we are currently working on #1332 - is this ticket something we can complete along with that?

**Comment by laurelthrash** [comment]
Closing this ticket per the above comment.
