### ISSUE TITLE
User Story: Build Feature Card - A. Card

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#605]
## User Story:
**As a** developer, 
**I want to** have the Development Solution from the DS, 
**so that I** can implement the feature card component in a website

> **ESTIMATE** TBD

### Feature Card Row
**When to use Feature Card Row variation**
- Used to showcase a collection of related content

**When to consider something else**
- If there is only 1 or 2 featured content, use an alternating promo card or an alternating guide card

Build default variation of card component based on design specs/requirements documented in this ticket.

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
Images:
- 4:3 image on Widescreen, Desktop (1024px and larger)
- 16:9 image on Tablet Large, Tablet (640px to 1023px)
- No image on Mobile Large & Mobile (639px and smaller)

Cards:
- Horizontal row on Widescreen and Desktop and the cards will be the same heights (1024px and larger)
- Stack on Tablet Large, Tablet, Mobile Large, and Mobile (1023px and smaller)

### Comps:
Figma (**WIP**): https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?node-id=0%3A1&t=z08109Zqe1jTN2Yh-0

InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0282013t7d5l1urr/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0283013t4nhh03fd/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0284013t4aj381ri/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0285013tb131hhax/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0286013tckea7wt7/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0287013t51y80sss/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User views a page with three (3) Feature Cards
Given a user is viewing a landing page with three (3) Feature Cards 
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the three (3) Feature Cards on the example site
  And the Feature Cards on the example site will match the comp
  And the Feature Cards will be held within a container called the "Feature Card Row"
  And the entirety of each card will be clickable
  And each card will be linked to its corresponding content
  And the title will have variable height to fit the text
  And the description will have variable height to fit the text
When the user hovers over the card
  And the card is displaying an image
Then the image will zoom while remaining the same height and width

Scenario: User views a page with three (3) Feature Cards on Widescreen or Desktop
Given a user is viewing a landing page with three (3) Feature Cards 
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is at least 1024px
Then the user will be able to view the three (3) Feature Cards on the example site
  And each image will have a 4:3 aspect ratio
  And each card will be of equal height to the tallest card

Scenario: User views a page with three (3) Feature Cards on Tablet Large or Tablet
Given a user is viewing a landing page with three (3) Feature Cards 
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 1024px and at least 640px
Then the user will be able to view the three (3) Feature Cards on the example site
  And each image will have a 16:9 aspect ratio

Scenario: User views a page with three (3) Feature Cards on Mobile Large or Mobile
Given a user is viewing a landing page with three (3) Feature Cards 
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 640px
Then the user will be able to view the three (3) Feature Cards on the example site
  And each card will not display an image
```
---

#### Single card:
- Title: Monica Bertagnolli, M.D., Begins Tenure as Director of NCI
- Description: The cancer surgeon is the institute's 16th director and the first woman to hold the position.

- Spanish title: Bienvenida a la nueva directora Monica Bertagnolli 
- Spanish description: La cirujana de cáncer es la primera mujer que ocupa este cargo.

#### 3 card row:
*Card 1*
- Title: Shorter, More Intensive Radiation Safe after Surgery for Prostate Cancer
- Description: Shorter duration, higher dose radiation doesn't harm quality of life, trial shows.

*Card 2*
- Title: Gentler Approach to Treating Pediatric Acute Promyelocytic Leukemia
- Description: Drug combination avoids or minimizes the use of conventional chemotherapy.

*Card 3*
- Title: NCI Updates Training Programs to Support Cancer Researchers of the Future
- Description: Adding ibrutinib to chemotherapy may improve survival for some people with a specific form of DLBCL.

---

## Solution
We will do the following:
1. `nci-card-group` will become an element since it will apply to cards and guide cards
2. A group of cards would look like:
    ```
    <ul class="nci-card-group" aria-label="what this group represents?">
       <li class="nci-card tablet:grid-col-X">...</li>
    </ul>
    ```
3. The cards will be based on the USWDS card
4. Don't messup the prose crap (the override-prose looks to fix specificity
5. Cards should be able to be added to a block of text with `float-right` as well as appearing in the list.
6. Each card public export will import the `nci-card-group` partial from elements.

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by bennettcc** [comment]
@dlescarbeau
Next steps for promo blocks [[ex. site link](https://designsystem-dev.cancer.gov/pr-683/example-site/example-pages/cgov-home.html)] & features cards [[ex. site link](https://designsystem-dev.cancer.gov/pr-594/example-site/example-pages/cgov-home.html)] below determined during 1pm requirements mtg.:

Promo Blocks: Change clickable components from Button, Title, and Image, to Button only.
Feature Cards: Change so that titles are underlined at all times.

Believe our current design meets accessibility needs on desktop since the entire card is what the user interacts with (not the title) so the card is the clickable item. [Example supporting this from Neilson Norman Group](https://www.nngroup.com/consulting/).
However, there is not a way to distinguish a link on mobile/tablet. We will see what it looks like for card titles to be underlined at all times to mitigate this.
