### ISSUE TITLE
MVP 1 Updates to Digital Style Guide on MyNCI

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#607]
Based on updates to Cancer.gov for MVP 1 release, update digital style guide: https://mynci.cancer.gov/topics/nci-digital-style-guide

### Sprint 41 [Sprint Points: 2]
- [x] Discovery/pre-work to determine the scope of updating the digital style guide

### Sprint 42 [Sprint Points: 5]
- [x] Update digital style guide based on MVP 1 updates
     - [x] Should include: maximum width (597 pixels) for blended logos, to denote at what size logos should wrap
- [x] Review internally and make necessary edits (scheduled for 11/3)
- [x] Make changes from internal discussion (specific changes outlined in comment from 11/3 & 11/10)
    - [x] Confirm change regarding H1-H6 
- [x] Share updated version internally & post to the ticket
- [x] Walk through final changes internally on 11/15 & verify no further changes from team/finalize internally
    - [x] Update date on page 3 to "December 2022"
    - [x] Update final page from "November 2022" to "December 2022"
- [x] Add to 'Sprint 43' to slot into future sprint to review with the federal team, when timing is best considering other time-sensitive MVP1 items

### Sprint 44 | [Sprint Points: 2]
- [x] Schedule time to discuss with the federal team (Leave as "On Hold" until timing is best considering other time-sensitive MVP1 items - PM to schedule) - **TBD (rescheduled from 11/29, new date 12/6)**
- [x] Make necessary edits based on federal review
- [x] Submit for copy edits

### Sprint 45 [Sprint Points: N/A]
- [x] Finalize digital style guide 
- [x] Once MVP1 is released, update file on MyNCI

### Notes
*Files for Style Guide found here: https://lion.box.com/s/20l396vitv11x6axk46muxrvkt33i8fh*
*Note: Future plan is that the NCI DS documentation ultimately replaces sections from the Digital Style Guide*

**Comment by laurelthrash** [comment]
Pulling into Sprint 41 as time permits.

**Comment by laurelthrash** [comment]
Determined during Thurs. @1pm meeting that we will review internally on Thurs. 11/3. From there, identify a time to share with the federal team.

**Comment by laurelthrash** [comment]
Discussed next steps on 11/3:

First:
- [ ] Add section that is specifically about the NCI DS (e.g., how we are using it, what we are basing this off of, include a link to how to go to the NCI DS documentation site) - @meglake to send over verbiage **[Sprint 42]**
- [ ] Once ACSF is setup, take screenshots to reflect actual images (e.g., megamenu) **[Sprint 42]**
- [ ] Once ACSF is setup, make a new page in ACSF-Test and create the H1-H6 headings to ensure what is present in the style guide is accurate **[Sprint 42]**

Then,
- [ ] Chuck/internal team review
- [ ] Schedule time with the federal team for review (goal to have this ready and approved by client just before launch, then post to MyNCI at launch)

Final
- [ ] Update any last screenshots 
- [ ] Post right after launch

Notes: 
- Document intended to provide context for what specific component looks like with defined vernacular (to all use the same language). 
- Removed most specs, with exception of logos for which we annotate the size
- Idea is that at MVP1, this would complement the NCI DS documentation site

**Comment by laurelthrash** [comment]
(Comment in-progress)

Reviewed with internal UX team. Changes to make:
- [ ]

**Comment by a-heirtzler** [comment]
Attaching the latest PDF
[NCI Digital Style Guide-112022.pdf](https://github.com/NCIOCPL/ncids/files/10005037/NCI.Digital.Style.Guide-112022.pdf)

**Comment by laurelthrash** [comment]
Conducted final internal review with UX team on 11/15. Identified two date changes (listed in description). Otherwise, no other internal changes. Will follow next steps outlined in future sprints. Cc: @a-heirtzler @monika-jaeger

**Comment by laurelthrash** [comment]
Moving to sprint 44, due to presentation mtg. being pushed from 11/29.

**Comment by laurelthrash** [comment]
(In progress) 

Notes from 12/6 conversation with the federal team:

Actions:
- [ ] ODDC gives language to add to the header slide to specify how logos are created. 
- [ ] Goal is to have this posted to MyNCI on Fri. 12/16

Notes:
- Bringing this from more pf a spec document to a document that aligns on language

**Comment by a-heirtzler** [comment]
@laurelthrash / @meglake updated Reference guide post 12/06 meeting:

[NCI_Digital_Reference_Guide-V1_12-2022.pdf](https://github.com/NCIOCPL/ncids/files/10169718/NCI_Digital_Reference_Guide-V1_12-2022.pdf)

**Comment by laurelthrash** [comment]
Sent to federal team for review/approval on Tues. 12/6. Requested review by Fri. 12/9.

**Comment by meglake** [comment]
Received client feedback morning of 12/12 (attached). @a-heirtzler  working on revisions and @monika-jaeger reviewing: https://www.cancer.gov/digital-standards and https://mynci.cancer.gov/sites/mynci.cancer.gov/files/field/file/NCI-Branding-and-Logo-Use-Guide-November-2020_1.pdf for potential updates needed for MVP 1 launch.

Client Feedback PDF: 
[NCI_Digital_Reference_Guide-V1_12-2022-ae_ML.pdf](https://github.com/NCIOCPL/ncids/files/10209758/NCI_Digital_Reference_Guide-V1_12-2022-ae_ML.pdf)

**Comment by laurelthrash** [comment]
Final version, to include 508 compliance remediation, completed by federal team and posted to MyNCI on 12/14: Downloaded from MyNCI: [NCI-Digital-Reference-Guide-FINAL.pdf](https://github.com/NCIOCPL/ncids/files/10237970/NCI-Digital-Reference-Guide-FINAL.pdf)
