### ISSUE TITLE
Atomic Component: Development Button Style (CSS)

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#61]
### NCIDS Button component and Storybook documentation

> **ESTIMATE** TBD

### Acceptance Criteria
Component for NCIDS package SCSS & CSS.
Storybook page for Component inspection and Documentation.

*Specs can include:  Link to InVision comp.*

```gherkin
N/A see InVision
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

This ticket is dependent on the color tokens for theme and system being approved and integrated to validate the listed items above.

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
Needs to be rewritten with the new component template and salient details

**Comment by bryanpizzillo** [comment]
This appears to be a dupe of #257. Putting on hold

**Comment by VictoriaSunNIH** [comment]
> This appears to be a dupe of #257. Putting on hold

You would be correct. We can close this out - I had said we need to rewrite it in the new template, and it looks like that was started as #257.
