### ISSUE TITLE
Define usa-prose Headings (H1-H6)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#610]
### Description
Define usa-prose headings (H1-H6). This will be needed for inner pages, so should be preparation work for Release 3 (R3).

**Parent Issue:** #587 
**Related Issue:** #702

### DS Sprint 9
- [x] Set up team working session meeting to initiate conversation and confirm definitions, estimated 30 min **slated for Wed. 01/18** [design and dev]
- [x] Captured initial determination for headings (below)

### Sprint TBD
- [ ] Considering to build out example page before we complete comps/solidifying the heading determinations (e.g., page title changes at desktop breakpoint, so want to see this). Devs currently conducting spike tickets that will influence this.
    - [ ] Review and approve internally 
    - [ ] Obtain federal approval
- [ ] Update styles in Sketch/Figma according to the definitions [design]
- [ ] Update on Documentation Site/Storybook according to the definitions [devs]
- [ ] Create comp for inner page (includes H1-H6 and paragraph styles from #702) (NOTE: does not include feature cards, images, etc. Should just be header and paragraph text)

### Notes

- This is prepping for NCI DS rollout

**Comment by laurelthrash** [comment]
Plan to meet Wed. 01/18

**Comment by laurelthrash** [comment]
Counting SP 3 in DS Sprint 9 and moving to "on deck backlog" for future conversations.

**Comment by meglake** [comment]
During 5/23/23 meeting, while reviewing Figma files to align with what was built in the NCIDS and confirmed typography sizing (Figma: https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?type=design&node-id=63%3A49&t=tTQWXfAu6SReyIPj-1) 

This ticket can now be closed
