### ISSUE TITLE
Change Request: Make logo larger in site header [Design]

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#625]
Per feedback from client on 10/17, they would like to see the logo larger in the site header. Please investigate and determine a recommended size for the site logo given all possible logos (ie enterprise site logo, blended logos). Use CBIIT, DCCPS, MyPART, DCEG, and Cancer.gov English & Spanish as use cases. Keep in mind that currently the header is built with the site logo staying the the same size across breakpoints. This change request might require a change to this in dev so be sure to define size if changes need to be made to mobile.

Note: Current site logo is set to 385x38, examples:
- https://www-test-acsf.cancer.gov/
- https://www-test-acsf.cancer.gov/pediatric-adult-rare-tumor/
- https://www-test-acsf.cancer.gov/nano/
- https://dceg-test-acsf.cancer.gov/

Tasks:
- [x] 1. Determine new logo size
-- Widescreen/Desktop: 50px
-- Tablet/Mobile: 38px (logo is wrapped to two lines where necessary - for DS dev this includes: Cgov English, Cgov Spanish, DCCPS, and DCEG) 
[Approved via email on 10/17]
- [x] 2. Add logo sizes as a requirement to this ticket: #626 and https://github.com/NCIOCPL/cgov-digital-platform/issues/3605
- [x] 3. Create DS Dev logo svgs for widescreen/desktop at 50px and tablet/mobile at 38px for the storybook site:
-- Cancer.gov (English)
-- Cancer.gov (Spanish) 
-- CBIIT
-- DCCPS 
-- MyPART 
-- DCEG 
- [x] 4. Create Drupal Dev logo svgs for widescreen/desktop at 50px and tablet/mobile at 38px (see exception below where mobile needs a new stacked logo) for all sites on platform:
-- Cancer.gov (English) 
-- Cancer.gov (Spanish)  
-- NCI-CONNNECT
-- MyPART 
-- DCEG 
-- Nano 
-- Physics 
-- SBIR
-- CCG
_Note: If SVGs created for DS dev are approved then you wont need to make those again for Drupal dev (can use same ones) will just need the microsite logos that were not part of DS Dev use cases_
- [x] 5. Revisit logo creation documentation to verify that the steps are correct and align with required dev requirements. 

**DUE: Tasks 1-2: Due ASAP Tuesday 10/18 | Task 3: ASAP Wednesday 10/19 | Task 4: TBD - ASAP after DS dev ticket approved by clients**
> **ESTIMATE** TBD

### Related Tickets
DS Dev: #626 
Drupal Dev: https://github.com/NCIOCPL/cgov-digital-platform/issues/3605

**Comment by meglake** [comment]
Updated ticket to include next steps from approval of mobile logo size. Task 3 is due ASAP on Wednesday 10/19. Message sent on Slack with same instructions.

**Comment by blilianyu** [comment]
The logos can be found here: https://lion.box.com/s/ybht4smjtlhif4blkx77rocaqw7ih4ig

**Comment by blilianyu** [comment]
Documentation has been updated with the latest.
cc: @monika-jaeger

**Comment by monika-jaeger** [comment]
[Revised logo documentation here.](https://lion.box.com/s/pf8png87jebcry3qvq7gezpi1vezt49a)
