### ISSUE TITLE
Match mobile menu back button to designs

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#635]
### Issue description
* Arrow is not blue **[Request to fix]**
* Button should be in line with close button **[Accept as is built]**

> **ESTIMATE** TBD

Below are screenshots of designs:

![Screen Shot 2022-10-20 at 1 52 03 PM](https://user-images.githubusercontent.com/85901679/197033361-e42c4428-2258-4da1-925a-8a82b0244ee2.png)
![Screen Shot 2022-10-20 at 1 52 33 PM](https://user-images.githubusercontent.com/85901679/197033448-a8050b5e-9c29-4333-ada8-aa1ac44693a5.png)

_Note: The arrows on the mockups face inward, but should face out._ **[Accept as Built]**

Here are the current regression tests on develop:

![ncids_nci-header_nci-extended_mobile_first_level_0_document_0_mobile](https://user-images.githubusercontent.com/85901679/197034317-008a4478-3aa4-41c7-b711-e9fd58ace482.png)
![ncids_nci-header_nci-extended_mobile_active_section_root_0_document_0_mobile](https://user-images.githubusercontent.com/85901679/197034329-5a48d5f5-d7fb-4c69-b11a-6695b955eda1.png)

### Additional details / screenshot
- https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc/cl9ha03m80ct0014k23l0eeie/play

**Comment by bennettcc** [comment]
@meglake to follow up with Lillian: is the current state on the example site acceptable? If so, we should update the comps to match what is on the example site

**Comment by meglake** [comment]
Discussed with Lillian and adding next steps below:
* Back / Main Menu arrows are black instead of blue **[Proceed with fix to make blue]**
* Back / Main Menu arrows face away from words vs towards words **[Accept as is]**
* Mobile Menu close button doesn't align with the Back /Main Menu text **[Accept as is]**

@blilianyu will update comps per next steps noted above and add link here for reference.

**Comment by blilianyu** [comment]
@meglake @olitharp-nci Comps have been updated and can be found here: https://publicis.invisionapp.com/overview/Header---Footer-Wireframes-cl17806xjx3ho01x42xix33gc/screens
