### ISSUE TITLE
Feature Kickoff: Lists

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#64]
Discovery for Lists and uses 
Flavors of List items
- Basic with Image
- Basic no image
- Basic title only
- Alternating Image

Notion: https://www.notion.so/List-Items-42562492d678406a96e11921ee252e51

### **Enabler Tasks**

- [ ]  Inventory and analysis of content type features
- [ ]  Creation of Mural board to capture discovery

### **Follow Tasks**

- [ ]  Create tickets based on kickoff decisions
- [ ]  Update Notion entries according to groupings (as needed)

### **Resources**

- 

### **Decisions and Directions**

*List of decided components and links to subsequent tickets*

**Comment by VictoriaSunNIH** [comment]
When we get to this, we should convert to a discovery ticket.
