### ISSUE TITLE
NCIDS Breadcrumb wrap partial is setting a theme setting directly in the file

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#655]
### Issue description
> **ESTIMATE** TBD

The public export (`_wrap.scss`) has the below css. The $theme variable should just be set in our settings file and not in the partial. The `_breadcrumb.scss` partial does not have it, which is a little more concerning since the order of these two would change the breadcrumb visually if it were not already set. 

There should also be an _all partial to be able to import both.

```
$theme-breadcrumb-font-size: "2xs";
@import 'uswds/dist/scss/components/breadcrumb';
@import './internal/print';
```

**Comment by sarinapadilla** [comment]
This was fixed with USWDS 3.0
