### ISSUE TITLE
Spike: Investigate USWDS 3.0

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#656]
## Investigate USWDS 3.0 to determine LOE to update to this new version.
> **Estimate** *# point* 

## Expected Deliverables:
* The approach to take to import USWDS 3.0
* A list of approaches investigated -- e.g. an Analysis of Alternatives deck
* Github tickets for what to do
* Estimation of the effort

## Initial Investigation Notes:
* **USWDS has moved to `@uswds/uswds`.** so _all_ of our references to it must change.
   * They also require include [includePaths](https://designsystem.digital.gov/documentation/developers/#sass-load-paths) be setup to their "packages" path.
* USWDS uses the new [Sass Module System](https://sass-lang.com/blog/the-module-system-is-launched).
   * All component partials import `uswds-core`. 
      * This means system settings, mixins and functions cannot be overridden when exporting a partial.
         * Only default variables can be redefined.
      * From the SASS lead:
         > One of Sass's design principles is to avoid adding features targeted at using dependencies in ways their authors didn't intend them to be used. Doing so is always going to be brittle, and it's almost always a better long-term strategy to either contribute changes upstream, to work the way the dependency expects, or to fork it and explicitly maintain it yourself. 

### Rejected Approach
* We could fork and republish as @nciocp/uswds 
    * This will cause pain and suffering as a change to ncids that impacts our overrides (infrequent, but does happen) would require a lot of package publishing to test.
    * Someone could attempt to use NCIDS & USWDS at the same time.
    * All USWDS reference needs to be updated to `@nciocpl/uswds`. (There are a lot of these... think testing tools, documentation site, etc)
    * Re-updating is rebasing, so easy-ish way to handle that.

#### Make a local `uswds-core` module
**IDEA:**
* this takes advantage of the fact that _`@use` only ever loads each file once. This ensures you don’t end up accidentally duplicating your dependencies’ CSS many times over._ 
   * Following the [documentation by USWDS for setting up your entry point](https://designsystem.digital.gov/documentation/settings/#where-to-include-your-configuration), we would:
      * make our own local `uswds-core` export. 
      * setup our required package with something like 
         ```
         @forward 'uswds-core';
         @forward 'uswds';
         @forward 'uswds-theme-custom-styles';
         ```
   * Since our uswds-core will be in [the load path](https://sass-lang.com/documentation/at-rules/use#load-paths), it will be found ahead of USWDS core's version. Any subsequent reference to a `uswds-core` will use our loaded version. 
   * This is probably the most brittle, but would force the use of our core. We would need to re-forward EVERYTHING in core, which is a lot.
   * This also requires that others setup SASS correctly in a large number of build tools. 

**ISSUE**
Sass must determine the file path when it determines if the module has already been loaded. So the local `uswds-core` referenced by `ncids-core` is different from the `uswds-core` referenced within the `@uswds/uswds` package.

--------------------
#### Patch USWDS for others
**IDEA**
* We could use the [patch-package](https://github.com/ds300/patch-package#benefits-of-patching-over-forking) to create patches to USWDS dist files.
   * Over 1mil downloads a week on npmjs, so it is not unknown.
   * Can we include a patch in `@nciocpl/ncids-css` that imports `uswds` and then patches uswds when some other project adds it??
      * What odd effects would this have?

**ISSUE** 
The patch only applies to the module (e.g. ncids-css) that has the patches when it downloads other modules (e.g. `npm ci`. When someone downloads your published package, it will not apply any of those patches to dependencies. 

>**_NOTE:_** It is stupid easy to make a patch. Maybe too easy. You just edit the files in the node_modules/package folder, and then run `npx patch-package @uswds/uswds` and it makes the patch for you. Commit the new patch file. When anyone else does a `npm ci` it downloads the dependency again and patches it. Super easy.
 

----------------
#### Use the patch-package module, republishing `@uswds/uswds` as files within the NCIDS package
This was prototyped at:
* [NCIDS Prototype](https://github.com/bryanpizzillo/ncids-with-uswds-patch-sync) - this mimicked publishing the NCIDS
* [Example website](https://github.com/bryanpizzillo/test-ncids-patch) - This mimics a website consuming our NCIDS.

**IDEA**
* `patch-package` was able to patch USWDS and the patches seem fairly maintainable.
* USWDS requires you to add USWDS to your Node include paths, so it is not a great ask to just reference NCIDS folders instead.
* On Postinstall where you normally add patch-package we can run other scripts, e.g. one to sync the files. These files would be untracked to git, and whenever USWDS is installed/reinstalled, the process would make sure the files are up to date. So there is no manual syncing or cases where it is easy to break things.
* Our publishing would mimick a structure used by USWDS and users would set their Sass search path to be `./node_modules/@nciocpl/ncids-css/packages`.
* We will need to handle 3 different use cases:
   1. NCIDS replaces a component completely and we need to not copy USWDS. e.g. nci-banner
   2. NCIDS augments the USWDS component, e.g. nci-banner, nci-button
   3. The untouched USWDS component should be passed through.
* The prototype demonstrates a way of handling the 3 use cases.

**Comment by bennettcc** [comment]
Discussed spike results with ODDC feds on 1/24 - moving forward with effort

**Comment by bennettcc** [comment]
Closing this ticket - ongoing 3.0 work is tracked here: https://github.com/NCIOCPL/ncids/issues/656
