### ISSUE TITLE
Create Documentation on the DS Site Regarding Home & Landing Pages

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#657]
### Description
This ticket is a placeholder ticket to remind us to create documentation on the DS site regarding home and landing pages. This is similar to issue #385. Generally, team needs to determine the best way to internally account for documentation on the DS site and establish what both designers and devs need to create necessary documentation. 

Leaving as "No Milestone" for the time being until we can give further consideration to this ticket. 

**Related Issues:** #385 

### Sub-Tasks
- [ ] TBD
- [ ] TBD

### Notes
*TBD

**Comment by sarinapadilla** [comment]
Closing this ticket, as we are using example site pages ([CGov home page](https://designsystem-dev.cancer.gov/develop/example-site/example-pages/cgov-home.html) and [landing page](https://designsystem-dev.cancer.gov/develop/example-site/example-pages/landing-page-with-title.html)) as documentation for home and landing page components. We also have documentation for each of the individual components and their patterns on the documentation site.
