### ISSUE TITLE
Cleanup NCI Header mobile menu `_navigation-mobile.scss`

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#664]
In order to pass style-lint rules, this needs to be updated.

```
// indentation for the mobile menu is nested
// and as such we need to be very specific about what
// list item gets padding for proper indentation
.nci-header-mobilenav__list > li > ul > li.nci-header-mobilenav__list-node:not(.active) button,
.nci-header-mobilenav__list > li > ul > li.nci-header-mobilenav__list-item:not(:first-child) > a,
.nci-header-mobilenav__list > li > ul > li > ul > li.nci-header-mobilenav__list-node:not(.active) button,
.nci-header-mobilenav__list > li > ul > li > ul > li.nci-header-mobilenav__list-item:not(:first-child) > a {
	padding-left: units(3);
}
```
      
---

Dev notes:
- This should be refactored to be more readable and use sass
- We would like to use [no-descending-specificity](https://stylelint.io/user-guide/rules/no-descending-specificity/) and [no-duplicate-selectors](https://stylelint.io/user-guide/rules/no-duplicate-selectors/) in stylelint, see #773. This code block, among others, do not follow these rules.

**Comment by sarinapadilla** [comment]
If we ever get back to this ticket, and we don't remember anything other than that is yucky, let's close it.
