### ISSUE TITLE
Enabler: Enable Cypress and Pa11y Testing for NCIDS-JS

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#671]
# Enable Cypress and Pa11y Testing for NCIDS-JS
> **ESTIMATE** TBD

Now that the ncids-js-testing site has gotten more complicated javascript, we should add in Cypress testing in order to ensure the behaviors are working as expected. Additionally, we really need to add in Pa11y testing to ensure we are meeting accessibility requirements. For example, there were issues with the autocomplete not including all the necessary roles. This type of issue should have been found with Pa11y.

**Comment by olitharp-nci** [comment]
Splitting out Cypress https://github.com/NCIOCPL/ncids/issues/692
