### ISSUE TITLE
Fix code coverage

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#672]
We want to increases code coverage for NCIDS to n percent. Each file cannot be lower than 50%.

_Originally posted by @olitharp-nci in https://github.com/NCIOCPL/ncids/issues/670#issuecomment-1324210480_

Related tickets
- https://github.com/NCIOCPL/cgov-digital-platform/issues/4152

**Comment by bennettcc** [comment]
No work should be needed on this ticket - it will be closed by https://github.com/NCIOCPL/ncids/issues/1136 (needs to be review, merged, and released)

**Comment by andyvanavery31** [comment]
Being closed by #1136.
