### ISSUE TITLE
Updates (If Applicable) to Drupal Guide on MyNCI to Reflect MVP1 Release

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#676]
### Description
Determine if updates need to be made to the Drupal Guide on myNCI (https://mynci.cancer.gov/topics/drupal-guide) based on changes to Drupal during Redesign project - specifically, following MVP1. If changes are needed, make changes and implement the updated information to MyNCI.

Presently, we do not believe that changes will be required in association with MVP1, however, we want to double check to verify that everything in the Drupal Guide will still be accurate. 

**Parent Issue:** https://github.com/NCIOCPL/cgov-digital-platform/issues/3317

### Sprint 44 [SP: 3]
- [x] Review Drupal Guide and determine if updates need to be made
- [x] Outline specific updates
- [x] Make specified updates
- [x] Obtain internal team approval of updates
- [x] Create Jira ticket to implement changes on MyNCI on Fri. 12/16

### Sprint 45 [SP: N/A]
- [x] Implement changes to MyNCI

### Notes
- Enter as needed

**Comment by adrianacastaneda** [comment]
- **Content formatting and styling:** 
> - Update "Embedding content in body section" screenshots for image and video carousels (to make sure the new font is update to date in screenshots)
 
- **Content features:** 
> - Update "On this page" section screenshot
> - Update "Related resources" section screenshot
> - Update "Citations/References" section screenshot
> - Update "Linked text to a citation" section screenshot. Is this interaction still available on MVP1? Doesn't seem to show in the dev environment on Chrome, Safari, or FF

-  **Translations page:** 
> - Type spotted under "Translating Media" section. Within third paragraph, "doens't" should be "doesn't"

**Comment by laurelthrash** [comment]
(In Progress) 

To-dos from internal 12/8 conversation:

- [ ] Replace screenshot for citations that does not include hover state
- [ ] Sarina to create ticket for hover state bug @sarina
- [ ] Remove "Compact list" from the guide

**Comment by adrianacastaneda** [comment]
Please see the approved MyNCI Drupal Guide updates for MVP1 in the Word doc attached. Screenshots are also attached here. Let me know if any questions come up! 

[MyNCI Drupal Guide MVP1 Release Updates.docx](https://github.com/NCIOCPL/ncids/files/10188686/MyNCI.Drupal.Guide.MVP1.Release.Updates.docx)



[Redesign MVP1 screenshots.zip](https://github.com/NCIOCPL/ncids/files/10188688/Redesign.MVP1.screenshots.zip)

Thanks!

**Comment by adrianacastaneda** [comment]
Hi @laurelthrash I've updated the attached MyNCI Drupal Guide updates Word doc and the screenshots folder below! Let me know if there are any questions. Thanks!

[Redesign MVP1 screenshots.zip](https://github.com/NCIOCPL/ncids/files/10228589/Redesign.MVP1.screenshots.zip)

[MyNCI Drupal Guide MVP1 Release Updates.docx](https://github.com/NCIOCPL/ncids/files/10228593/MyNCI.Drupal.Guide.MVP1.Release.Updates.docx)

**Comment by laurelthrash** [comment]
Changed implemented on MyNCI on 12/15. Closing ticket.
