### ISSUE TITLE
nci-autocomplete event details

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#678]
### Issue description
*Update nci-autocomplete event details*
-  `selectedOptionIndex` returns 0 when nothing selected, 0 is a valid index so this won't work
- `selectedOptionSetSize` option set size should always return a number of options are found, will pass 0 even if option is not selected

> **ESTIMATE** TBD

#### Related
- https://github.com/NCIOCPL/cgov-digital-platform/issues/3667

**Comment by bennettcc** [comment]
Closing ticket - this was in MVP1
