### ISSUE TITLE
MVP 1 Updates to Branding/Logo Guide on MyNCI

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#688]
### Description
Determine required updates to the Branding/Logo Guide on MyNCI (https://mynci.cancer.gov/topics/nci-branding-and-logo-use-guide) based on changes made during Redesign project - specifically, following MVP1. Then, make changes to the PDF and implement the updated information on MyNCI following the MVP 1 launch.

**Parent Issue:** N/A

### Sprint 44/45 [SP: 3]
- [x] Review Branding/Logo Guide to determine needed updates
- [x] Outline specific updates
- [x] Obtain federal approval of updates (discussion with federal team occurred on 12/13 @ 9:30am mtg.) 
- [x] Make specified changes following federal team review
- [x] Obtain final approval
- [x] Include final document in Jira ticket Thurs. 12/14

### Resources
- Insert final updated guide once complete: [NCI-Branding-and-Logo-Use-Guide-December-2022_FINAL.pdf](https://github.com/NCIOCPL/ncids/files/10238001/NCI-Branding-and-Logo-Use-Guide-December-2022_FINAL.pdf)

**Comment by laurelthrash** [comment]
Update the following pages in the guide based on discussion with federal team on 12/13: @monika-jaeger @meglake 

- [ ] Page 4
- [ ] Page 6 (web items)
- [ ] Page 10
- [ ] Page 11
- [ ] Page 12
- [ ] Page 15
- [ ] Page 17-19
- [ ] Any color/font references throughout the doc
- [ ] Content info (awaiting from Anna E. before we can implement)

**Comment by monika-jaeger** [comment]
Attached is the updated Branding and Logo usage guide. 

[NCI-Branding-and-Logo-Use-Guide-Dec-2022-1 - MJ.pdf](https://github.com/NCIOCPL/ncids/files/10222956/NCI-Branding-and-Logo-Use-Guide-Dec-2022-1.-.MJ.pdf)

**Comment by monika-jaeger** [comment]
@meglake & @laurelthrash : Updates to Branding and Logo usage guide:

- Page 1 - updated screenshot of ACSF Test for laptop (including the usa banner/language toggle at top)
- Page 10 - theme color grid first like in the style guide PDF
- Page 15 - video thumb templates updated from Sharepoint (added 16:9 & 1:1)
- Page 17 - replaced with screenshots from ACSF Test and include the USA banner/language toggle

[NCI-Branding-and-Logo-Use-Guide-Dec-2022-2 - MJ.pdf](https://github.com/NCIOCPL/ncids/files/10229164/NCI-Branding-and-Logo-Use-Guide-Dec-2022-2.-.MJ.pdf)

**Comment by laurelthrash** [comment]
Final version, to include 508 compliance remediation, completed by federal team and posted to MyNCI on 12/14: Downloaded from MyNCI: [NCI-Branding-and-Logo-Use-Guide-December-2022_FINAL.pdf](https://github.com/NCIOCPL/ncids/files/10238003/NCI-Branding-and-Logo-Use-Guide-December-2022_FINAL.pdf)

Cc: @monika-jaeger @meglake
