### ISSUE TITLE
Enabler: Enable Cypress Testing for NCIDS-JS

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#692]
Enable Cypress Testing for NCIDS-JS
> ESTIMATE TBD

Now that the ncids-js-testing site has gotten more complicated javascript, we should add in Cypress testing in order to ensure the behaviors are working as expected.

Dev note:

https://www.npmjs.com/package/cypress-cucumber-preprocessor

```json
  "cypress": "^10.9.0",
  "cypress-cucumber-preprocessor": "^4.3.1",
```

## Related
* https://github.com/NCIOCPL/ncids/issues/671

**Comment by andyvanavery** [comment]
#671 has been merged. Closing this ticket.
