### ISSUE TITLE
Document Accessibility Processes

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#693]
Requested by Lakshmi and ODDC Feds:

Please document team processes, testing measures, and standards as it relates to accessibility and 508 compliance. What processes or steps does our team take to ensure that design and development on the platform (redesign specifically) is done in an accessible way and meets the required 508 controls.

Estimated Completion date: 12/22

**Comment by meglake** [comment]
[NCI Redesign Accessibility Testing.docx](https://github.com/NCIOCPL/ncids/files/10354561/NCI.Redesign.Accessibility.Testing.docx)

**Comment by bennettcc** [comment]
This PPT was presented to ODDC Feds on 1/25 

As discussed @arcepaul - please a condensed version on this deck as a one pager to show how these 508 tools and processes are used to help deliver a story or release.  ODDC is looking for a way to quantify and prove we're working with accessibility at the forefront during our day to day. Feel free to throw a few ideas my way to help shape this doc. Thanks!

**Comment by bennettcc** [comment]
Final document approved by Anna: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Accessibility%20and%20508%20Compliance/Digital%20Platform%20Accessibility%20Process%20Guide.docx?d=wd681451dc1fd43658b0c697cd9e913dc&csf=1&web=1&e=uAT6RC
