### ISSUE TITLE
Enabler: Map mood board colors to DS tokens

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#7]
# Map mood board colors and styles to DS 

*Description of what is to be accomplished.*
* Map mood board colors and styles to DS
* Deliverable: Sketch file of colors; theme and system tokens
* Colors to include system/theme tokens.

> **ESTIMATE** 1 story point

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by anthonycuellar** [comment]
In PR, to be completed today
