### ISSUE TITLE
Content Type Kickoff: Special Report

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#71]
Discovery around components for the special report content type
## Possible components for investigation

- Title-First Feature Cards
- Borderless Feature cards
- Alternating Image List

- 
Notion: 

### **Enabler Tasks**

- [ ]  Inventory and analysis of content type features
- [ ]  Creation of Mural board to capture discovery

### **Follow Tasks**

- [ ]  Create tickets based on kickoff decisions
- [ ]  Update Notion entries according to groupings (as needed)

### **Resources**

- 

### **Decisions and Directions**

*List of decided components and links to subsequent tickets*

**Comment by VictoriaSunNIH** [comment]
Convert to discovery when we are ready to work on this

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
