### ISSUE TITLE
Build: Hero - F. Hero Image w/o Button, Light Text Box & CTA Strip 

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#710]
### Build Hero without button, Light Text Box and CTA Strip variation of hero component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
- Hero image height will be fixed at 427px on widescreen, desktop & tablet large at 880px or larger
  - Widescreen: 1400px width
  - Desktop: 1024px width
  - Tablet large: 880px width
- Hero image will swap out with a 16:9 image on tablet & mobile large at 879px and less
  - Tablet: 640 x 360 px
  - Mobile large: 480 x 270 px
- Hero image will swap out with a 1:1 image on mobile at 320px
  - Mobile: 320 x 320px
- CTA strip buttons on Tablet will be larger and at fixed width (400px)
- Light text box button will be fixed position so that it is always halfway between the image & CTA Strip background color

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j301679pfo48ht/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j4016777sl73pf/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j50167c0pxgh43/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j60167bssrahrw/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j701674fv2d1k9/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j801674mecbadi/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see a hero without a button, a light tagline and a CTA strip, so that I can get a visual introduction to the page with quick call-to-actions.  

Scenario: User views a landing page with a Hero without a button, Light Tagline & CTA Strip on Widescreen, Desktop or Tablet Large
Given a user is viewing a landing page with a Hero without a button, Light Tagline & CTA Strip
  And the browser width is 1400px or less  
Then the hero image will appear 
  And the height of the image will be fixed 
  And the light text box will appear on top of the image 
  And the text will appear centered and size should be XL

Scenario: User views a landing page with a Hero without a button, Light Tagline & CTA Strip on Tablet
Given a user is viewing a landing page with a Hero without a button, Light Tagline & CTA Strip
  And the browser width is 640px or less 
Then the 16:9 hero image will appear 
  And the light text box will appear on top of the image
  And the text will be centered and appear as a XL

Scenario: User views a landing page with a Hero without a button, Light Tagline & CTA Strip on Mobile 
Given a user is viewing a landing page with a Hero without a button, Light Tagline & CTA Strip
  And the browser width is 320px or less 
Then the 1:1 hero image crop will appear stack
  And the light text box will appear on top of the image
  And the text will be centered and should be a XL
```

---
### Scenarios
- Short Tagline: NCI is the nation's leader in cancer research
- Long Tagline: Funding for small businesses with next-generation cancer technologies.
- Spanish Tagline: El NCI es el líder nacional de investigación del cáncer
- CTA button 1: Programs
- CTA button 2: Resources
- CTA button 3: Success Stories
- CTA button 1 long: NCI Alliance for Nanotechnology in Cancer
- CTA button 2 long: Nanotechnology Characterization Laboratory 
- CTA button 3 long: Cancer Nanotechnology Plan
- Spanish CTA button 1: El NCI para la Nanotecnología en el Cáncer
- Spanish CTA button 2: Laboratorio de Caracterización de Nanotecnología
- Spanish CTA button 3: Plan de Nanotecnología del Cáncer

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### Hero Image w/o Button, Light Text Box & CTA Strip
**When to use Hero Image w/o Button, Light Text Box & CTA Strip variation**
- When there is no main call-to-action
- When you need to include multiple quick links
- When you need to have a longer tagline

**When to consider something else**
- When you need to display groups of information or long chunks of text

**Comment by sarinapadilla** [comment]
Closing this ticket as it was completed with #737!
