### ISSUE TITLE
Build: Promo Block - D. Full-width Promo Block Dark 

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#712]
### Build Full-width Promo Block Dark variant of promo block component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
- Promo Image height fixed at 400px on Widescreen, Desktop & Tablet Large
- 16:9 Promo Image at Tablet, Mobile Large & Mobile

### InVision: 
  * Widescreen mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40594017n0wlv2cg1/play
  * Desktop mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40595017ncuofhrc6/play
  * Tablet Large mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40596017ne0xu72cu/play
  * Tablet mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40597017ndfyq71j5/play
  * Mobile Large mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40598017n4qeid6e0/play
  * Mobile mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl9ftyfm40599017ngry973ak/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see a full-width promo block dark to break up the content on the page

Scenario: User views a landing page with a Full-width Promo Block Dark on Widescreen, Desktop or Tablet Large
Given a user is viewing a landing page with a Full-width Promo Block Dark
  And the browser width is 1400px or less  
Then the promo image will appear 
  And the height of the image will be fixed 
  And the dark text box will appear on top of the image 
  And the title will appear centered and size should be 3XL
  And the text will appear centered
  And the button will appear with our secondary button style centered

Scenario: User views a landing page with a Full-width Promo Block Dark on Tablet
Given a user is viewing a landing page with a Full-width Promo Block Dark
  And the browser width is 640px or less 
Then the 16:9 promo image will appear 
  And the dark text box will appear stacked below the image 
  And the title will appear centered and size should be 2XL
  And the text will appear centered
  And the button will appear with our secondary button style centered

Scenario: User views a landing page with a Full-width Promo Block Dark on Mobile Large
Given a user is viewing a landing page with a Full-width Promo Block Dark
  And the browser width is 480px or less 
Then the 16:9 promo image will appear 
  And the dark text box will appear stacked below the image 
  And the title will appear centered and size should be 2XL
  And the text will appear centered
  And the button will appear full-width with our secondary button style

Scenario: User views a landing page with a Full-width Promo Block Dark on Mobile 
Given a user is viewing a landing page with a Full-width Promo Block Dark
  And the browser width is 320px or less 
Then the 16:9 promo image will appear 
  And the dark text box will appear stacked below the image 
  And the title will appear centered and size should be XL
  And the text will appear centered
  And the button will appear full-width with our secondary button style
```

---
### Scenarios
- Short Title: Driving Discovery
- Long Title: Signed, Sealed, and Delivered: The National Cancer Act of 1971
- Spanish Title: Estadísticas del cáncer
- Short Description: NCI enables advances in cancer by investing in a broad portfolio of research, supporting the cancer research workforce, and sustaining the infrastructure that enables cutting-edge research to succeed.
- Long Description: The National Cancer Act of 1971 gave our country a holistic approach to addressing cancer and its many challenges. This broad legislation gave new authority to the National Cancer Institute and established some of the programs that form the backbone of today’s cancer research enterprise.
- Spanish Description: Información básica sobre las estadísticas del cáncer, las cuales describen las tendencias en grupos grandes de personas y ofrecen una imagen a través del tiempo de la carga que representa el cáncer en la sociedad.
- Short Button: Learn more 
- Long Button:
- Spanish Button: 

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### Full-width Promo Block
**When to use Full-width Promo Block variation**
- Used to break up the page visually on a content heavy landing page
- Used as an intro to a section of content

**When to consider something else**
- Use an alternating promo block if there is multiple promotional content items

**Variations**
- Light text box variation is meant for darker images or illustrations
- Dark text box variation is meant for lighter images or illustrations

**Comment by sarinapadilla** [comment]
Internal decision was made to not implement the full-width promo block as it is basically just a hero.
