### ISSUE TITLE
Build: Feature Cards - C. Multiple Link Feature Card Row (dynamic)

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#713]
### Build Multiple Link Feature Card Row variation of feature card component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
Images:
- 4:3 image on Widescreen, Desktop (1024px and larger)
- 16:9 image on Tablet Large, Tablet (640px to 1023px)
- No image on Mobile Large & Mobile (639px and smaller)

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j301679pfo48ht/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j4016777sl73pf/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j50167c0pxgh43/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j60167bssrahrw/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j701674fv2d1k9/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cld91pce300j801674mecbadi/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see a multiple link feature card row, so that I can quickly scan the featured content and go to the series page. 

Scenario: User views a page with a multiple link feature card row on Widescreen or Desktop  
Given a user is viewing a landing page with a feature card row 
  And the browser width is 1400px or less
Then a feature card row will appear 
  And the 4:3 crop of the image associated with the feature card should appear (following our image rules)  
  And the title of the feature card should be font size theme token LG
  And the description will appear 
  And clicking anywhere on the card will take the user to the corresponding page
  And below the container an additional link will appear with a horizontal rule
  And clicking on the link will take the user to the corresponding page 

Scenario: User views a page with a feature card row on Tablet Large or Tablet
Given a user is viewing a landing page with a feature card row 
  And the browser width is 880px or less
Then the feature card row will stack 
  And the 16:9 crop of the image will appear
  And the title of the feature card should be font size theme token LG
  And the description will appear 
  And clicking anywhere on the card will take the user to the corresponding page
  And below the container an additional link will appear with a horizontal rule
  And clicking on the link will take the user to the corresponding page 

Scenario: User views a page with a feature card row on Mobile Large or Mobile
Given a user is viewing a landing page with a feature card row 
  And the browser width is 480px or less
Then the feature card row will stack 
  And the image will not appear
  And the title of the feature card should be font size theme token LG
  And the description will appear 
  And the container shadow will not appear 
  And clicking anywhere on the card will take the user to the corresponding page
  And below the container an additional link will appear with a horizontal rule
  And clicking on the link will take the user to the corresponding page 
```

---
### Scenarios
**Card 1**
  - Title: Shorter, More Intensive Radiation Safe after Surgery for Prostate Cancer
  - Description: Shorter duration, higher dose radiation doesn’t harm quality of life, trial shows.
  - Link: Go to Cancer Currents Blog
  - Spanish title: La FDA aprobó el brentuximab para el linfoma de Hodgkin de riesgo alto en niños y adolescentes
  - Spanish description: La aprobación se basó en un estudio clínico que patrocinó el NCI y que llevó a cabo el Grupo de Oncología Infantil.
  - Spanish Link: Ir a Blog Temas y Relatos

**Card 2**
  - Title: Gentler approach to treating pediatric acute promyelocytic leukemia
  - Description: Drug combination avoids or minimizes the use of conventional chemotherapy.
  - Link: Go to NCI Press Releases
  - Spanish title: Radioterapia más breve para algunas personas con cáncer de mama en estadio temprano
  - Spanish description: Un curso de tratamiento condensado fue tan eficaz y seguro como el curso de tratamiento estándar para las mujeres con cáncer de mama en estadio temprano de mayor riesgo que tuvieron una lumpectomía.
  - Spanish Link: Ir a Comunicados de prensa

**Card 3**
  - Title: NCI Updates Training Programs to Support Cancer Researchers of the Future
  - Description: Adding ibrutinib to chemotherapy may improve survival for some people with a specific form of DLBCL. 
  - Link: Go to Bottom Line Blog
  - Spanish title: ¿Imnunoterapia más barata para todo el mundo?
  - Spanish description: Según un estudio en India, una dosis muy baja de nivolumab es eficaz para tratar el cáncer de cabeza y cuello.
  - Spanish Link: Ir a Subvenciones capacitacion
 
### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Example: Use a card when featuring content
- [ ] *When to consider something else*
  * Example Use a list when you have multiple pieces of content, and will display too many cards*
- [ ] *Usability Guidance*
  * Example: Don't have 1 button in CTA strip

**Comment by blilianyu** [comment]
### Multiple Link Feature Card Row (Dynamic)
**When to use Multiple Link Feature Card Row (Dynamic) variation**
- Used when dynamic feature cards are needed and need to link to series page

**When to consider something else**
- If manual featured content is needed, use the Feature Card Row 
- If mixed groups of content need to be curated, use the Feature Card Row

**Comment by sarinapadilla** [comment]
Closing this, as we aren't building this component for Home and Landing pages.
