### ISSUE TITLE
Change Request: Add Link Color Change to Hover, Active, and Visited States on Feature Cards

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#720]
Request to change link colors on H2s on feature cards to align with our defined link tokens. Notably, this includes a color change to the link on hover, active, and visited states. Presently, there is no change in links on hover, active, or visited states. 

Specifically, request to change feature cards to use the defined tokens for the hover and active states:

- `$theme-link-visited-color` to `violet-70v`
- `$theme-link-hover-color` to `primary-dark`
- `$theme-link-active-color` to `primary-darker`

Request to verify (and subsequently update, as needed) that the card component uses the defined tokens for their associated states:

- `$theme-link-color` to `primary`
- `$theme-link-visited-color` to `violet-70v`
- `$theme-link-hover-color` to `primary-dark`
- `$theme-link-active-color` to `primary-darker`

**Related ticket:** #702 

### DS Sprint 10 [SP: 3]
- [x] Create prototype (copy Cancer.gov home page comp with R2.1 components) to demonstrate what happens to title link in feature cards for all of the following interactions:
    - [x] Hover state
    - [x] Visited content
    - [x] Question to answer: the rule we create here, does this apply to other link states across the site? A: yes, these are aligned across components (e.g., inner pages)
- [x] Internal review/agreement + Bryan for preliminary approval
- [x] Federal team review **(Slated for 02/07)**

### Future Sprint [SP TBD]
- [x] Pass ticket to @sarinapadilla to create DS dev tickets

### Notes

- 02/06/23: Determined that our link tokens are already defined using NCI colors. With this in mind, only need to update feature cards so as to match our link tokens as already defined for various states. Initially, thought we may need to retroactively apply the updated tokens to existing components (e.g., breadcrumbs). 
- 01/24/23: Received approval from federal team on DS dev for Feature Card component. Determined we will move forward with underlines for Feature Card titles. In a future sprint, wish to investigate/test a change to add color to the Feature Card title links on hover, as represented in this ticket.

**Comment by blilianyu** [comment]
Prototype can be viewed here: https://publicis.invisionapp.com/overview/Cancer-gov-Home-Page-R2-1-clcul8x0q0au801augpgc56df/screens

**Comment by laurelthrash** [comment]
Received approval from federal team on 02/07 to move forward with specified link color updates. Cc: @meglake @blilianyu

**Comment by laurelthrash** [comment]
Closing this ticket since design portion of the ticket is complete. Passing to @sarinapadilla to take next steps with regard to the DS Dev ticket creation.
