### ISSUE TITLE
Compiling Guidance for R2.1 Components

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#721]
**Description:** Define and document content strategy guidance for R2.1 components to implement into existing R2 Details PPT stakeholder deck. The goal of this guidance is to complement the wireframe example with content strategy to better understand how these components will be used on the platform. This guidance should be written for a federal user audience. 

**META:** https://github.com/NCIOCPL/cgov-digital-platform/issues/3317

### DS Sprint 10 [SP: 2]
- [x] Begin with initial meeting to discuss deeper goals of this ticket (Laurel/Lindsay/Adriana) **Scheduled for 1/31**
- [x] Resume conversation **Thurs. 02/03**
- [x] Create GH Wiki architecture for components in GH and add component sections @sarinapadilla @lburack @adrianacastaneda 
    - [x] Define one component to show the architecture example

### DS Sprint 11 [SP: 3]
- [x] Define content strategy at documentation site level for each R2.1 component:
    - [x] Alternating Promo Block - Dark Text Box
    - [x] CTA Strip Only
    - [x] Feature Card Row - 3 Cards
    - [x] Guide Card with Image & Description
    - [x] Hero Image w/Button & Light Text Box
    - [x] Hero Image w/Button, Light Text Box & CTA Strip
    - [x] Hero Image without Button - Light Text Box [added 02/08]
    - [x] Hero Image without Button, Light Text Box & CTA Strip [added 02/08]
    - [x] Inline Video 
    - [x] Promo Block - No Image - Dark Text Box [added 02/08]
- [x] Guidance to include:  
    - [x] Word counts or character limits
    - [x] Scenarios
    - [x] + incorporate existing guidance already included on R2.1 DS Dev 
- [x] Review guidance internally
- [x] Receive approval from federal team
- [x] Submit for formal copy edit: https://tracker.nci.nih.gov/browse/CGOV-18381
- [x] Document guidance in GH Wiki

### Guidance Working Documentation
Guidance Word Document: [Insert here]

### Notes
- Ticket initiated with desire to ensure IA/content strategy is presented hand in hand with design elements. 
- [Stakeholder R2 Details PPT deck](https://nih.sharepoint.com/:p:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/Redesign_Release%202%20Overview.pptx?d=wa22a327d91fd427f86aead7e2d095518&csf=1&web=1&e=aZyOrL)

**Comment by laurelthrash** [comment]
Notes from 1/26/23 internal meeting:

- Answer the questions of "Why you would use this component?"
- Recommendations for language, character counts, etc. 
- See this as elevator pitch for the component (e.g., name of component and 1-2 sentences with purpose of component + bulleted list of specific best practices)
- Keep existing scope slide, with individual slide for each component 
- Language needs to be consistent across guidance on myNCI/with stakeholders/internal team/etc.
- Cheat sheet for using the same language

**Comment by laurelthrash** [comment]
Determined 1/31 we will document component guidance in [GH Wiki](https://github.com/NCIOCPL/ncids/wiki). We will include the following in the GH guidance:

- 1-2 lines to describe what this component is for
- Guidance
    - When to use this component [Incorporate image strategy, if applicable] 
    - When to consider another component [Incorporate image strategy, if applicable]
    - Usability Guidance / Content Required
    - Accessibility

Outstanding questions:

- Do we define a singular card guidance when applicable (e.g., feature card for a feature card row)?
- Who is updating the actual documentation site?
- Need to consider overall image guidance? Is this more appropriate for a style guide? 

Cc: @lburack @adrianacastaneda @sarinapadilla @andyvanavery

**Comment by laurelthrash** [comment]
Update: @adrianacastaneda @lburack creating structure in GH. To connect with @andyvanavery @sarinapadilla once complete for review.

**Comment by laurelthrash** [comment]
Completed SP 2 in DS Sprint 10. Moving remaining card to DS Sprint 11.

**Comment by laurelthrash** [comment]
Discuss internally on Tues. 02/14.

**Comment by laurelthrash** [comment]
[In Progress Comment] Actions from 2/14 internal meeting:

- [ ] Add blanket note that these recommendations are for best practices as well as optimize the visual display to achieve a better display.
- [ ] Generate 'dos' and 'don'ts' images that represent the guidance. 

Notes:
- Will be part of the DS documentation site, the Drupal guide on MyNCI, our internal GH Wiki, and the external PPT.

**Comment by adrianacastaneda** [comment]
Guidance was updated to reflect internal feedback from 2/14 meeting. Here's the link to the latest guidance document: 
![image](https://user-images.githubusercontent.com/114433873/219799025-91a69dbe-1fb7-466b-8110-75992cd9e53c.png)

**Comment by laurelthrash** [comment]
Anna to provide final feedback by COB Wed. 02/22. From there, final step is to add to the GH Wiki and then this ticket can be closed. Cc: @lburack @adrianacastaneda

**Comment by laurelthrash** [comment]
Determined during knowledge share on 02/21 that we will:

- [ ] Remove mention of future releases (e.g., xx component will be available in Release 2.3) in the document guidance

**Comment by laurelthrash** [comment]
Goal for completion of adding to the GH Wiki is Fri. 04/21 Cc: @adriancofie

**Comment by laurelthrash** [comment]
Added to GH Wiki - closing this ticket.
