### ISSUE TITLE
Update Home Page Banner Images Ahead of Widescreen Launch 

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#724]
**Description:** It was discovered that on ACSF-dev (contains code for widescreen), that the Cancer.gov homepage (both English and Spanish) banner text does not meet 508 compliance standards. 

Additionally, need to check the MyPART home page to verify the banner contrast meets 508 compliance standards. 

In Drupal, home and landing pages only have a desktop and mobile upload (not a widescreen specific upload) so the updated banner needs to work for both desktop and widescreen.

#### Cancer.gov Home Page (https://www-dev-acsf.cancer.gov)
- [x] Create updated banner image for English home page
    - [x] Test on ACSF-dev to ensure banner meets 508 compliance standards 
    - [x] Save final file to ticket
- [x] Create updated banner image for Spanish home page
    - [x] Test on ACSF-dev to ensure banner meets 508 compliance standards 
    - [x] Save final file to ticket (same as English)

#### MyPART (https://www-dev-acsf.cancer.gov/pediatric-adult-rare-tumor/)
- [x] Verify the contract on the MyPART banner meetings 508 compliance standards (verified existing banner is not compliant)
    - [x] If it does not, create updated banner image for MyPART home page
    - [x] Test on ACSF-dev to ensure banner meets 508 compliance standards 
    - [x] Save final file to ticket

#### All
- [x] Review internally
- [x] Federal team review
- [ ] Upload new banner images to production so that they are in place for the widescreen release

### Steps to Reproduce
1. Navigate to home page on ACSF-dev (currently contains widescreen code): https://www-dev-acsf.cancer.gov
2. See that the home page banner image text does not left justify on the darker gradient background, so does not have enough contrast

### Screenshots (ACSF-dev that includes widescreen update)

**Spanish: https://www-dev-acsf.cancer.gov/espanol**
![Cancer gov Banner Issue - Spanish](https://user-images.githubusercontent.com/102998716/214959307-0f9e0687-fae6-408d-a7f1-f0199942783c.jpg)

**English: https://www-dev-acsf.cancer.gov/**
![Cancer gov Banner Issue - English](https://user-images.githubusercontent.com/102998716/214959406-61b4058a-a22a-4182-888e-b60a572d782a.jpg)

**Comment by dcvijanovic1k** [comment]
![cancer-gov-hero-widescreen](https://user-images.githubusercontent.com/102183929/215157623-15203795-75f9-4ddc-b0a2-c9023d530f07.jpg)
Widescreen image attached cc @laurelthrash

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here's a new banner. Using WebAIM, it is passing all checks. Please let me know if you run into any other issues.
![MyPART-homepage-banner-013023](https://user-images.githubusercontent.com/102183929/215526701-a825cf40-cf15-4237-980a-0ece7c02ae4f.jpg)

**Comment by laurelthrash** [comment]
Update: Determined at 9:30am federal team meeting we would like to make development changes so as to left align the tagline in the hero. With this in mind, we would like to return to the original hero image, if possible. Federal team comfortable with an update to the gradient if needed, but would prefer if it were less intense. No action needed from designers at this time, but we will stay tuned with the development updates. Cc: @meglake @dcvijanovic1k

**Comment by dcvijanovic1k** [comment]
Updated widescreen homepage banner attached, MyPART header to come tomorrow 2/1 cc: @meglake @laurelthrash 
![cancer-gov-hero-widescreen](https://user-images.githubusercontent.com/102183929/215891352-8fbd4227-397c-4c5f-818e-91ca8e6edf69.jpg)

**Comment by laurelthrash** [comment]
Shared above banners with Anna for approval via Teams. Once approved, will add images to the production site ahead of the widescreen launch slated for 02/02.

**Comment by laurelthrash** [comment]
The banner image on the Cancer.gov (English and Spanish) homepage and MyPART home page are updated in production to include the new banner images ahead of the widescreen release slated for Thurs. 02/02. Closing this ticket as complete. Cc: @dcvijanovic1k
