### ISSUE TITLE
Discovery Kickoff: Blog Post

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#73]
Break down and categorize components of a Blog Post

### Possible components for investigation
- Clickbait Cards
- Date/Author Attribution - small
- Post Navigation (newer/older)
- Subscribe Link 
- Right Rail Categories

### **Enabler Tasks**

- [x]  Inventory and analysis of content type features
- [x]  Creation of Mural board to capture discovery

### **Follow Tasks**

- [x]  Create tickets based on kickoff decisions
- [x]  Update Notion entries according to groupings (as needed)

### **Resources**
- Notion: https://www.notion.so/Blog-Post-280acddd57694d90a299701fa3cd4326
- Platform Wiki: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Posts
- myNCI guidance: https://mynci.cancer.gov/topics/drupal-guide-common-content-types#blogpost

### **Decisions and Directions**

*List of decided components and links to subsequent tickets*

Subscribe Button
- new ticket for baseline discovery work: Baseline Discovery: Subscribe Blog Button #129 

Blog Publishing Info (Date and Author)
- identified and named - no additional work needed

Blog Right Rail (unit containing up to three lists - featured posts, categories, and archive)
- baseline discovery (analytics and heuristics) for the whole group  - Baseline Discovery: Blog Right Rail (category and filter) #131
- Larger exploration of Filtering functionality site-wide: Discovery + Analysis: Filtering functionality #133

Intro Text
- Discussion with blog authors about current use - Conversation with Blog Team about intro text #130
- Synthesize and document Drupal reporting on intro text usage #132

Blog Post Pagination (older and newer posts with title preview)
- Consider as a part of a larger exploration of pagination: Discovery + Analysis: Pagination #134
- Sub tickets for catalog ( #135) and analytics on current use (#136)

Related Content Cards - content preview in card form  - Consider as part of related resources and recommended content component
- basic analysis complete and available on Notion: [Related Resources and Recommended Content](https://www.notion.so/Related-Resources-and-Recommended-Content-baafce07e4364532879d548abd74461f)

**Comment by claireblaustein** [comment]
Completed
