### ISSUE TITLE
CTA strip buttons should start stacking at Tablet Large 880

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#749]
### Issue description
CTA strip buttons should start stacking at Tablet Large 880 
And change padding on widescreen to 3rem and desktop to 5rem

> **ESTIMATE** TBD

### What's the expected change?
- CTA strip buttons should start stacking at Tablet Large 880
- Padding on widescreen change from 0.5rem to 3rem and desktop from 0.5rem to 5rem

### What's the current functionality?
- CTA strip buttons start stacking at Mobile Large 480

### What's the updated acceptance criteria?
```gherkin
Scenario: User views a landing page with a CTA Strip on Tablet Large, Tablet, Mobile Large or Mobile
Given a user is viewing a landing page with a CTA Strip 
  And the browser width is tablet-lg or less
Then the CTA strip will appear 
  And the buttons will appear with the primary button style and stack
  And the buttons will have the same width
  And the buttons will have the same margin between them
  And on hover, the buttons will appear with the primary button hover style 
  And clicking on each button will take the user to the corresponding page 
```

### Additional details / screenshot
<img width="882" alt="Screenshot 2023-02-08 at 12 29 54 PM" src="https://user-images.githubusercontent.com/51677926/217606841-401832d3-c74e-4f55-9350-6ee85a6ff081.png">

### Related Tickets
* Original Story Ticket #548

**Comment by bennettcc** [comment]
Additional work needed to update padding on large tablet breakpoint - reopening ticket

**Comment by bennettcc** [comment]
This story was merged yesterday
