### ISSUE TITLE
Content Type Kickoff : Dictionary of Cancer Terms

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#76]
## Possible components for investigation
-Dictionary search (radio, autocomplete, A-Z nav)
- audio play/pause

Notion: 

### **Enabler Tasks**

- [ ]  Inventory and analysis of content type features
- [ ]  Creation of Mural board to capture discovery

### **Follow Tasks**

- [ ]  Create tickets based on kickoff decisions
- [ ]  Update Notion entries according to groupings (as needed)

### **Resources**

- 

### **Decisions and Directions**

*List of decided components and links to subsequent tickets*

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
