### ISSUE TITLE
Content Type Kickoff: Biography

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#77]
## Possible components for investigation
- Profile Panel - Biography Block (top block with image, personal info, links, etc.) - class="profile-panel"

Notion: 

### **Enabler Tasks**

- [ ]  Inventory and analysis of content type features
- [ ]  Creation of Mural board to capture discovery

### **Follow Tasks**

- [ ]  Create tickets based on kickoff decisions
- [ ]  Update Notion entries according to groupings (as needed)

### **Resources**

- 

### **Decisions and Directions**

*List of decided components and links to subsequent tickets*

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
