### ISSUE TITLE
Fix stylelint for ncids-css

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#773]
### Issue description
> **ESTIMATE** TBD

In #11 we said we turned on the linter. Technically it is. However, it does not lint any of our files. 
BAD package.json scripts
```
		"lint": "stylelint scss/**/*.scss",
		"lint:fix": "stylelint scss/**/*.scss --fix",
```

GOOD package.json scripts
```
		"lint": "stylelint \"packages/**/*.scss\"",
		"lint:fix": "stylelint \"packages/**/*.scss\" --fix",
```

You will need to go fix all the things too.

All the things:
* file path should be set to packages since uswds 3.0
* wrap glob in escaped quotes
* change stylelint file to js
* keep `selector-class-pattern`, `no-descending-specificity: null`, and `no-duplicate-selectors: null` from [18f](https://www.npmjs.com/package/@18f/identity-stylelint-config?activeTab=code).  see [comment below](https://github.com/NCIOCPL/ncids/issues/773#issuecomment-1808532187)
* remove "ignoreFiles": "./src/stylesheets/lib/**/*"

should be something like this 

```js
module.exports = {
	"extends": [
		"stylelint-config-recommended-scss",
		"stylelint-prettier/recommended"
	],
	"rules": {
		"no-descending-specificity": null,
                "no-duplicate-selectors": null,
    'selector-class-pattern': [
      '^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$',
      {
        message:
          'Class selectors should be named using "Two Dashes Style" BEM format. See: https://en.bem.info/methodology/naming-convention/#two-dashes-style',
      },
    ],
	}
}
```
  
once this is complete please see [Enabler: Create Stylelint Rule Package #27](https://github.com/NCIOCPL/cgov-standards-xt/issues/27)

**Comment by olitharp-nci** [comment]
USWDS rules:
```
{
  "extends": [
    "@18f/identity-stylelint-config"
  ],
  "rules": {
    "unit-no-unknown": null,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null
  },
}
```

[@18f/identity-stylelint-config](https://www.npmjs.com/package/@18f/identity-stylelint-config?activeTab=code) rules 
```
module.exports = {
  extends: ['stylelint-config-recommended-scss', 'stylelint-prettier/recommended'],
  rules: {
    'no-descending-specificity': null,
    'scss/comment-no-empty': null,
    'scss/no-global-function-names': null,
    'scss/operator-no-newline-after': null,
    'scss/operator-no-newline-before': null,
    'scss/operator-no-unspaced': null,
    'selector-class-pattern': [
      '^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$',
      {
        message:
          'Class selectors should be named using "Two Dashes Style" BEM format. See: https://en.bem.info/methodology/naming-convention/#two-dashes-style',
      },
    ],
  },
};
```

18f and uswds are removing a lot of rules that we should keep for ncids, namely:

- https://stylelint.io/user-guide/rules/unit-no-unknown/
- https://stylelint.io/user-guide/rules/no-duplicate-selectors/
- https://stylelint.io/user-guide/rules/comment-no-empty/
- https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/no-global-function-names/README.md
- https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/operator-no-newline-after/README.md
- https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/operator-no-newline-before/README.md
- https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/operator-no-unspaced/README.md

We may need to adjust later, but let's set [no-descending-specificity](https://stylelint.io/user-guide/rules/no-descending-specificity/) to null for now as it may cause more issues than needed to get this up and running. Additionally, for later, we might want to look into [selector-nested-pattern](https://stylelint.io/user-guide/rules/selector-nested-pattern/).
