### ISSUE TITLE
Create 'Do's' and 'Don'ts' Visual Examples for R2.1 Component Guidance 

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#779]
> Related Ticket: #721 
> DEPENDENT ON: #808 

### Description
Team created guidance for R2.1 components in #721. Determined we want visuals to accompany the guidance that demonstrates 1) an example of the component being used as recommended, and 2) an example of the component not being used as recommended. 

Do's and don'ts images intended to be placed on the Drupal Guide on MyNCI to accompany new component Drupal guidance. Per outline in the associated META ([#3317](https://github.com/NCIOCPL/cgov-digital-platform/issues/3317)).

### Tickets/Sub-tasks
- [ ] Create do's and don't comps for each of the components outlined on the R2.1 guidance doc:
    - [ ] Card (Feature Card)
    - [ ] CTA Strip
    - [ ] Hero Image with or without Button (Light)
    - [ ] Guide Card with Image & Description
    - [ ] Promo Block with Image (Dark)
    - [ ] Promo Block without Image (Dark)
- [ ] Review comps internally
- [ ] Make adjustments as needed
- [ ] Add graphics to GH Wiki along with R2.1 guidance

### Notes
- [Insert notes as needed]

**Comment by laurelthrash** [comment]
Established during backlog grooming we will keep the scope of this ticket for Drupal Guide. Forthcoming ticket for NCIDS for all. Consider using images created in this ticket for NCIDS for all / Example Site.

**Comment by andyvanavery31** [comment]
Closing due to the Drupal Guide being updated with sufficient information.
