### ISSUE TITLE
Change Request: Feature Cards Adjust Vertical Stack Starting Breakpoint

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#780]
### Change Request Description
**Raised by Client:**
The breakpoint at which the Feature Cards in a 3 Feature Card Row switch from being side-by-side to vertically stacked is considered too high and the image is too big on the screen. The Feature Cards begin to be vertically stacked at a breakpoint less than 1024px. The request is to change the breakpoint which starts the vertical stacking from less than 1024px to less than 880px. This change request is from the client and was agreed to be implemented by the internal team on February 21, 2023.

### What's the expected change?
- The breakpoint where the Feature Cards in an NCIDS 3 Feature Card Row begin to stack vertically will start at a breakpoint less than 880px.

### What's the current functionality?
- The breakpoint where the Feature Cards in an NCIDS 3 Feature Card Row stack vertically at a breakpoint less than 1024px.

### Tasks
- [x] Update comps at the impacted breakpoints (880px > breakpoint > 1024px)
- [ ] Change DS so that it reflects this request

### Updated Acceptance Criteria
**DS Development (#605 )**
```gherkin
Scenario: User views a page with three (3) Feature Cards on Widescreen, Desktop, or Tablet Large
Given a user is viewing a landing page with three (3) Feature Cards 
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is at least 880px
Then the user will be able to view the three (3) Feature Cards on the example site
  And each image will have a 4:3 aspect ratio
  And each card will be of equal height to the tallest card

Scenario: User views a page with three (3) Feature Cards on Tablet
Given a user is viewing a landing page with three (3) Feature Cards 
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 880px and at least 640px
Then the user will be able to view the three (3) Feature Cards on the example site
  And each image will have a 16:9 aspect ratio

Scenario: User views a page with three (3) Feature Cards on Mobile Large or Mobile
Given a user is viewing a landing page with three (3) Feature Cards 
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 640px
Then the user will be able to view the three (3) Feature Cards on the example site
  And each card will not display an image
```

### Related Tickets
* Original Story Ticket Feature Card - A. Card #605
* Original Story Ticket: NCIDS Feature Card Internal [#3611](https://github.com/NCIOCPL/cgov-digital-platform/issues/3611)
* Original Story Ticket: NCIDS Feature Card External [#3612](https://github.com/NCIOCPL/cgov-digital-platform/issues/3612)
* Original Story Ticket: NCIDS Feature Card Multimedia [#3637](https://github.com/NCIOCPL/cgov-digital-platform/issues/3637)

**Comment by blilianyu** [comment]
Comps have been updated: https://publicis.invisionapp.com/console/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0284013t4aj381ri/play
