### ISSUE TITLE
Feature Kickoff: Resources for Researchers

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#79]
Explore R4R, including landing page, category pages, and individual entries. 

## Possible components for investigation
- Category Navigation (left rail)
- R4R search
- Category Listings
- 

Notion: 

### **Enabler Tasks**

- [ ]  Inventory and analysis of content type features
- [ ]  Creation of Mural board to capture discovery

### **Follow Tasks**

- [ ]  Create tickets based on kickoff decisions
- [ ]  Update Notion entries according to groupings (as needed)

### **Resources**

- 

### **Decisions and Directions**

*List of decided components and links to subsequent tickets*

**Comment by meglake** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
