### ISSUE TITLE
Change Request: Increase Padding on Top and Bottom of CTA Strip

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#796]
### Change Request Description
**Internal Change Request - Needs Acceptance from Client** **[Client approved on 3/7/23]**
The buttons on the CTA strip are considered too close to the Hero when the CTA Strip is used with it as a Hero variant at Desktop or Widescreen breakpoints. Request is to increase the padding on the top and bottom of the buttons on the CTA Strip from 24px to 32px.

### What's the expected change?
- The padding above and below the CTA Strip buttons is to be increased from 24px to 32px on breakpoints >=1024px (Widescreen and Desktop).

### What's the current functionality?
- The padding above and below the CTA Strip buttons is 24px on breakpoints >= 1024px (Widescreen and Desktop).

### What's the updated acceptance criteria?
```gherkin
Scenario: User views a landing page with a CTA Strip on Widescreen and Desktop  
Given a user is viewing a landing page with a CTA Strip 
  And the browser width is desktop or widescreen
Then the CTA strip will appear 
  And the buttons will appear with the primary button style and vertically align
  And the buttons will have the same width
  And the buttons will have the same margin between them
  And the padding above and below the tallest button will be 32px
  And on hover, the buttons will appear with the primary button hover style 
  And clicking on each button will take the user to the corresponding page 
```

### Related Tickets
* Original Story Ticket: #548 
* Original PR: #650z
* Hero with CTA Strip Variant Ticket: #547

**Comment by bennettcc** [comment]
This needs to be discussed with the client before we begin working on this

**Comment by meglake** [comment]
Client approved during 3/7/23 meeting.
