### ISSUE TITLE
Enabler: Understanding of Breakpoints

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#8]
## In order to know what breakpoints we need to design for, we need to understand how many are required. .

*Examples:*
* What does USWDS currently use
* Do we want to follow their example
* Can we simplify? 

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*  Dev recommendations on current platform needs
*  Design considerations 

### Additional Notes:
* https://designsystem.digital.gov/utilities/layout-grid/#responsive-variants
*

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by VictoriaSunNIH** [comment]
Completed:
Desktop: 1024 and higher
Tablet: 1023 to 768
Mobile:  767 and lower
