### ISSUE TITLE
Atomic Component: Dev Button Component Documentation 

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#81]
### Documentation for handoff of button component from design to development

> **ESTIMATE** TBD

### Acceptance Criteria
*Include specs:  List of colors (hex, token name), variants, and states.* 

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Atomic Component: Development Button Style (CSS) #61 https://github.com/NCIOCPL/ncids/issues/61
* Atomic Component: Development Button (React) #53 https://github.com/NCIOCPL/ncids/issues/53
* Atomic Component: UX Button Component Documentation #80
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
@anthonycuellar This ticket has some predecessors from #61 (Make button CSS) and #53 (Make react buttons). Both of these tickets are currently marked as placeholders. @arcepaul and @karlikpj do not have any requirements to create the buttons that they would have to document as part of this ticket.
