### ISSUE TITLE
Determine if Meta Data is Accessible for Components/Design Tokens for Documentation Site

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#814]
## In order to group the components/design tokens on the Documentation Site, the meta data or equivalent must be accessible. This Spike will be to investigate how the components/design tokens can be group on the Documentation Site.

*Examples:*
* Each component/design token may have meta data that can be accessed so they can be sorted and grouped

### Expected Deliverables:
* Determine if meta data is accessible
* If meta data is not accessible, is there another way to organize the components/design tokens
* If components/design tokens are able to be grouped, bring that information to #809 

### Additional Notes:
* Related to Enabler Ticket: #809 

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by bennettcc** [comment]
This spike has been completed - the development of the main navigation will be tracked on https://github.com/NCIOCPL/ncids/issues/809
