### ISSUE TITLE
Design: Icon Only Buttons

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#82]
## Design of atomic button element 
**[Continuation of Basic Button #35]**

> **Estimated Timeframe** *# of days for completion* 

### Expected Deliverables
- Icon only buttons

Current icon-only buttons
- Page options
- social media footer links
- Covid banner close (open has text, but close is just an X)
- close Xs on modals (Like dictionary popup)
- Left/Right buttons on multimedia sliders
- compressed search button

Current styles used
- floating on the background
- reverse in a circle
- outlined in a circle

### Problems to Solve
- So. Much. Variation. 
- Need guidance to define use

### Questions to Answer
- how do we define and treat these - as buttons (with same rules), or as links?

### Resources
- Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1611586427071/8906190b53768bef8fc4698d3c82a008cbc39439
- USWDS: https://designsystem.digital.gov/components/button/
- Basic Button Comps: https://publicis.invisionapp.com/share/A8UB2W74PRN#/screens

**Discovery Ticket: Discovery: Buttons #30**

### Additional Notes:
* note 1

**Comment by meglake** [comment]
Closing out ticket as this work is being handled in other tickets.
