### ISSUE TITLE
Fix guide card documentation 

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#822]
# Fix guide card documentation 

Rename the component to Guide Card. The component is not called Guide Card Row.

Guide card should be combined to one page. Image and description is a variant of guide card

* https://designsystem-dev.cancer.gov/develop/components/guide-card-row
* https://designsystem-dev.cancer.gov/develop/components/guide-card-with-image-and-description

**Comment by sarinapadilla** [comment]
We've got this documented on the documentation site, so closing!
