### ISSUE TITLE
"Tweet This" Drupal Report - Sharing Options

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#84]
Need to know how often 

<div class="materials-to-share">

https://www.cancer.gov/about-nci/organization/crchd/inp/screen-to-save/connect

Is used, and how it's implemented

**Comment by VictoriaSunNIH** [comment]
Do we need to consider a design for this? I think it depends on usage, right now its only on one page

**Comment by laurelthrash** [comment]
Closing, will create a new ticket with new ticket template when this item is ready to be worked on.
