### ISSUE TITLE
Character Count USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#841]
### USWDS Component Name
[Character Count](https://designsystem.digital.gov/components/character-count/)

### USWDS Component Packages
* Package usage: `@forward "usa-character-count";`
* Dependencies: `uswds-input`
* Dependencies: `uswds-textarea`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by karlikpj** [comment]
on hold till text input and textarea are complete
