### ISSUE TITLE
Checkbox USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#842]
### USWDS Component Name
[Checkbox](https://designsystem.digital.gov/components/checkbox/)

### USWDS Component Packages
* Package usage: `@forward "usa-checkbox";`
* Dependencies: `usa-input-list`, `usa-fieldset`, `usa-legend`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by olitharp-nci** [comment]
Moved to on hold because radio needs to get in first before checkbox (similar dependencies, we decided on a radio first)
