### ISSUE TITLE
Date Picker USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#847]
### USWDS Component Name
[Date Picker] (https://designsystem.digital.gov/components/date-picker/)

### USWDS Component Packages
* Package usage: `@forward "usa-date-picker";`
* Dependencies: `uswds-fonts`, `usa-fonts`, `usa-input`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by olitharp-nci** [comment]
Surprise blocker #851
