### ISSUE TITLE
Date Range Picker USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#848]
### USWDS Component Name
[Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/)

### USWDS Component Packages
* Package usage: `@forward "usa-date-range-picker";`
* Dependencies: `uswds-date-picker`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by olitharp-nci** [comment]
on hold for now - issues with javascript and need to pivot to analytics

**Comment by sarinapadilla** [comment]
This is color meeting dependent. @bennettcc will schedule that meeting for the week of 6/12.
