### ISSUE TITLE
File Input USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#849]
### USWDS Component Name
[File Input] (https://designsystem.digital.gov/components/file-input/)

### USWDS Component Packages
* Package usage: `@forward "usa-file-input";`
* Dependencies: `uswds-fonts`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by sarinapadilla** [comment]
This is color meeting dependent. @bennettcc will schedule that meeting for the week of 6/12.

**Comment by bennettcc** [comment]
Moving back to on-hold, color story still in progress

**Comment by bennettcc** [comment]
Moving back to in progress - luminance color story has been merged
