### ISSUE TITLE
Memorable Date USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#853]
### USWDS Component Name
[Memorable Date](https://designsystem.digital.gov/components/memorable-date/)

### USWDS Component Packages
* Package usage: `@forward "usa-memorable-date";`
* Dependencies: `uswds-fonts`, `usa-form-group`, `usa-input`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by bennettcc** [comment]
This is ready for review - moving to On Hold during 2.1 release crunch
