### ISSUE TITLE
Site Title USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#871]
### USWDS Component Name
[Site Title] *No documentation page on USWDS*

### USWDS Component Packages
* Package usage: *To be found*
* Dependencies: *To be found*

### Subtasks
- [ ] Make a folder with the component name under uswds-native
- [ ] Copy USWDS twig and any JSON
- [ ] Make an index.scss for the stories
- [ ] Copy and hack up USWDS stories.js file to use our story format
- [ ] Create scenarios.js by adding a scenario for each story in stories.js
- [ ] Add link to the USWDS documentation on the NCIDS documentation site

**Comment by sarinapadilla** [comment]
Per decision made by Anna on 4/3, we are not passing this component through. Closing this ticket!
