### ISSUE TITLE
Spike: Determine NCIDS Documentation Site Navigation and Dynamic Upload

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#895]
# Enable NCIDS Documentation Site Navigation and Dynamic Upload

**The goal of this enabler story is to make the navigation and dynamic upload functional on the NCIDS Documentation Site**

*Features/Functionalities*
* Top navigation function and appear similar to USWDS
* Side navigation function and appear similar to USWDS
* Make the upload and organization of files and the directory dynamic

### Resources:
* Web Page: https://designsystem-dev.cancer.gov/develop/

### Parent Ticket
* #809

**Comment by karlikpj** [comment]
dev/spike branch 
- [ticket/809-docsite-navigation](https://github.com/NCIOCPL/ncids/tree/ticket/809-docsite-navigation)
- [draft pr](https://github.com/NCIOCPL/ncids/pull/893)

**Comment by bennettcc** [comment]
Closing out this spike - the work will be completed as a part of https://github.com/NCIOCPL/ncids/issues/809
