### ISSUE TITLE
Design: Wireframes of Site Banner and Footer - Desktop and Mobile

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#9]
> **ESTIMATE** Story Points TBD

> Feature/Main User Story: [Enter user story ticket association here] 

### Description of Task to be worked on
Preliminary wireframes of solutions to current navigation issues with the site banner and the footer.

**Problems to solve:**
1. Make search more prominent
2. Remove stickiness of header - contrary to best practice but we've had usability and tech issues with the sticky header
3. Remove hover on L1 - 50-60% of clicks are on primary nav vs. links in megamenu so remove hover on L1. Addition of link to L1 needed in megamenu.
- Even though best practices says not to have split buttons, we would have to repeat every parent label for each section on mobile (i.e. explore about cancer, explore understanding cancer, explore causes & prevention, etc.). On mobile, we propose split buttons.

4. Remove layer cake, allow more space for content.
6. Phone number doesn't call a number
7. Conflicting social media URLs in footer
8. Make labeling consistent for chat in utility and footer

**Questions to answer:**
1. Does sticky menu on mobile pose a technical issue? https://publicis.invisionapp.com/d/main?origin=v7&redirHash=#/console/21156092/446183469/preview?scrollOffset=818
2. Will cards in megamenu slow page load time? https://publicis.invisionapp.com/d/main?origin=v7&redirHash=#/console/21156092/446183607/preview?scrollOffset=479
3. Content Strategy: Can we mirror the contents of the mobile menu in the megamenu? Need to test current megamenu: https://github.com/NCIOCPL/ncids/issues/33
4. Content Strategy: Can the linkback to C.gov go in the footer and not the header?
5. Can we have a dual function for the Spanish button? https://publicis.invisionapp.com/d/main?origin=v7&redirHash=#/console/21156092/446183469/preview?scrollOffset=818
6. OR should we keep the toggle functionality page-specific vs. global? Consider usability testing
7. Consider some actions of mobile menu opening overlays vs. linking to other pages. Test our current mobile menu which does this: https://github.com/NCIOCPL/ncids/issues/34

### Related Tickets
#5   - Spike: Content review of footer links
#33 - Spike: Usability test the current megamenu
#34 - Spike: Usability test the current mobile header
https://github.com/NCIOCPL/ncids/issues/38 - Spike: Usability test the current language toggle

### Resources:
* Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1602095625783/fa27d5eda78546183c03d428ffee7dc1acfd7fa8
* Wireframes: https://publicis.invisionapp.com/share/KN10COU5UYCW

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Technical Notes
- More notes, or technical nuances/direction

**Comment by anthonycuellar** [comment]
Closing this ticket, we'll be opening a discovery ticket for [indicating other Spanish Language content for pages that do not have a language toggle], and one ticket for footer content strategy, ticket for CIS
