### ISSUE TITLE
Re-review the Open PR's for Updates Needed for Accessibility

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#903]
### Key Items for Re-Review
* Review the components using `div` or `section`, and confirm that the proper one is being used for the component
* Confirm that correct sections have a heading for accessibility purposes

### Expected Deliverables:
* A list of tickets/PR that require updates to the requirements and solution to meet accessibility requirements

### Resulting List of Tickets/PR's to be Updated:
* *To be added during re-review*

**Comment by sarinapadilla** [comment]
@arcepaul says this is part of our standard process now!
