### ISSUE TITLE
Update Wireframe for Feature Card Row Component (R2.1)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#913]
### Description
On 04/14, determined with federal team that the Feature Card Row component will have a required heading. We need to update the wireframe version of this component that is used on the ["Redesign_Release 2 Overview" PPT (slide 5)](https://nih.sharepoint.com/:p:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/Redesign_Release%202%20Overview.pptx?d=wa22a327d91fd427f86aead7e2d095518&csf=1&web=1&e=DGHx5x).

### Tickets/Sub-tasks
- [x] Update existing wireframe graphic for the Feature Card Row component to include a reference to the "Required Feature Card Row Title"
- [ ] Review update internally
- [ ] Make adjustments as needed
- [ ] Add graphics to Redesign PPT doc
 
### Deliverables
- Link to final wireframe graphic for Feature Card Row: [Box Link](https://lion.box.com/s/nhdro4wot6uujjvz6qpx1nhxyus2y7vo)
- Link to source file in Figma: [Figma Link](https://www.figma.com/file/5edx1ALiid9bxjYswrnEdG/Wireframe-Components?node-id=0%3A1&t=xlmejmUMz5blOmx9-1)

### Related Screen Shots
**Current Wireframe Graphic**
![Image](https://user-images.githubusercontent.com/102998716/232152816-83dab7d0-449f-4123-abaa-6c35f8062765.png)

**Should Account for Required Heading:**

![Image](https://user-images.githubusercontent.com/102998716/232152888-a39d35ac-08aa-4959-9eae-0c9828d0523e.png)

**Comment by monika-jaeger** [comment]
Updated [MVP2 Landing Page comps](https://www.figma.com/proto/rYMEQ6MM3KlG9cpY36CEA7/MVP2-Landing-Pages?page-id=1%3A17&node-id=9-6787&viewport=-1584%2C2072%2C1&scaling=min-zoom) with headers above feature card row 

cc: @laurelthrash

**Comment by monika-jaeger** [comment]
Here is the feature card graphic in Box: https://lion.box.com/s/craz4ee10t838metzkadej3uodr2uq0z
cc @laurelthrash

**Comment by laurelthrash** [comment]
Thank you, @monika-jaeger - will you please make the below changes?

- [ ] Change "Feature Card Row Title" to "Required Feature Card Row Title"
- [ ] Swap the image placeholder for "[Image]" to keep it consistent with the other wireframes in the PPT

**Comment by monika-jaeger** [comment]
Updated feature card row title & added placeholder [image] to components with images
https://lion.box.com/s/e8u3uoa4vhfxuftgpsn18dota7v521po

**Comment by meglake** [comment]
Added updated wireframe to R2 overview deck in Teams and the R2 Planning Mural Board. Closing out ticket now.
