### ISSUE TITLE
Spike: Backstop regression scrollbars

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#917]
### Expected Deliverables:
* Does BackstopJS support this? What are our options? Does this affect all of the regression images? Can we enable this feature per story?

### Additional Notes:
* By default, playwright headless hides scrollbars. There is a config setting to ignore default args:
   ```js
   ignoreDefaultArgs: [
       '--hide-scrollbars'
     ],
   ```

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

So while this works and does add the scroll bars to component screenshots there are some odd effects on other component tests.

- 146 current tests fail because of slight differences
- Differences so far include

1. Tripping breakpoints and switching layouts.
2. Slight movement of text/boxes and spacing but very minor

![Screenshot 2023-04-17 at 3 04 21 PM](https://user-images.githubusercontent.com/66697447/232587645-58ae28d9-e19b-44b5-ba80-be0c4fa2ee7d.png)
![Screenshot 2023-04-17 at 3 04 08 PM](https://user-images.githubusercontent.com/66697447/232587647-a8340075-63fc-461b-885c-d2b969fee339.png)

**Comment by bennettcc** [comment]
This spike was completed - closing ticket. The work needed will be tracked here: https://github.com/NCIOCPL/ncids/issues/921
