### ISSUE TITLE
Create Template(s) for component usability documentation

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#92]
*Ticket to create a template for individual component usability documentation.*

### Sub-Tasks
- [x] Draft template
- [ ] Send for review

### Notes

*Reference links:*
* Atomic Component: UX Button Component Documentation
https://github.com/NCIOCPL/ncids/issues/80
* Atomic Component: Development Button Style (CSS) https://github.com/NCIOCPL/ncids/issues/61
* Atomic Component: Development Button (React) https://github.com/NCIOCPL/ncids/issues/53

**Comment by claireblaustein** [comment]
Current template:

## When to Use [OBJECT]

- 

## When to Consider Something Else

- 

## Usability Guidance

- 

## Accessibility

- 

## Examples and Use Cases

-

**Comment by claireblaustein** [comment]
Sent to slack today - requested review by EOD Thursday.

**Comment by claireblaustein** [comment]
No further feedback.
