### ISSUE TITLE
Add focus references for usa-table scrollable and sortable variants

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/ncids#920]
Please generate reference images for the sortable and scrollable variants of usa-table.  Looking at the code for those two variants, it was noticed that they received a tabindex="0" to denote that the element is interactive.  Please add focus(via focusSelector) in the scenarios for the variants to show that they are focusable for regression testing.

> **ESTIMATE** 1

### Notes
* default: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-table--default
* scrollable: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-table-scrollable--default
* https://allyjs.io/data-tables/focusable.html#table-elements
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#accessibility_concerns

**Comment by bennettcc** [comment]
Per @dlescarbeau - this has already been completed. Closing ticket
