### ISSUE TITLE
Design: Intro Text

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#93]
> **ESTIMATE** Story Points TBD

> Discovery Kickoff: https://github.com/NCIOCPL/ncids/issues/62

Linked Parent Epics:
* Design Epic: Article Page https://github.com/NCIOCPL/ncids/issues/140
* Design Epic: Blog Post https://github.com/NCIOCPL/ncids/issues/141

### Description of Design request:

Design for intro text - used in both articles (unstyled) and blogs.

Component details: https://www.notion.so/Intro-Text-0ab24b99fad24864b731a81a951f71e1

##

### List of sub-tasks:
*Add links to related tickets below*
- [ ] Sub-Task
- [ ] Sub-Task
- [ ] Sub-Task

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by mworrest** [comment]
@claireblaustein is there some examples of articles with intro text that we could look at?

**Comment by claireblaustein** [comment]
@mworrest yep, there's a Drupal report on box: https://lion.box.com/s/puo2hecb66lzcm4u6wb7dhg1h6y6atyz

**Comment by mworrest** [comment]
Thank you!

**Comment by anthonycuellar** [comment]
Note: This may be shifting from Sprint 5 to 6
