### ISSUE TITLE
NCIDS For All Pilot - Figma Page on Documentation Site

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#933]
## As a designer, I want to be able to access the design system in Figma, so that I can utilize components to create compositions.

NCIDS is already mostly set up in Figma, so this ticket will involve fine-tuning and adding design notes/documentation.

* Providing link to Figma that is specific for outside organizations
  * Creating community link for others to download the library
* Draft definition and explanation of what the Figma is and how to use it
* QA testing from designers

Markdown file:
https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Figma_Guide_markdown.txt?csf=1&web=1&e=EN4xID

[Figma_Guide_markdown.txt](https://github.com/NCIOCPL/ncids/files/12730845/Figma_Guide_markdown.txt)

Images: 

![figma-guide_color-styles01](https://github.com/NCIOCPL/ncids/assets/22639543/04854088-0893-42ae-a78f-29bbeaac6acd)
![figma-guide_color-styles02](https://github.com/NCIOCPL/ncids/assets/22639543/87c97a37-944a-4390-835d-238ddd0ab7c6)
![figma-guide_components-resources01](https://github.com/NCIOCPL/ncids/assets/22639543/4214d326-09f1-4116-8717-e2ebbdf30a08)
![figma-guide_components-resources02](https://github.com/NCIOCPL/ncids/assets/22639543/570e8b25-fbdf-4e03-8ab8-05f67ec7efc0)
![figma-guide_components-resources03](https://github.com/NCIOCPL/ncids/assets/22639543/9d97cdfb-728f-42ac-a3e7-44cc277207c5)
![figma-guide_components-spacers01](https://github.com/NCIOCPL/ncids/assets/22639543/5b2b42c5-b1fe-43cc-a2f6-567797e6aa8e)
![figma-guide_components-spacers02](https://github.com/NCIOCPL/ncids/assets/22639543/5fd61dc4-e285-4a87-9952-31dd18fa1115)
![figma-guide_grid-styles](https://github.com/NCIOCPL/ncids/assets/22639543/cfc54e80-d013-440f-9dca-ea694810d748)
![figma-guide_includes](https://github.com/NCIOCPL/ncids/assets/22639543/7c3d0236-3967-4a62-a5b0-8b1a4d895800)
![figma-guide_publish-changes](https://github.com/NCIOCPL/ncids/assets/22639543/4146bf28-eb42-44a5-a389-1a065803463c)
![figma-guide_text-styles](https://github.com/NCIOCPL/ncids/assets/22639543/f6b991e1-82e6-4d39-b9ed-1625713df2f5)

### Requirements

- The Figma link shall be added to the "Figma Guide" subpage under the "Get Started" page.
- Information about using the Figma Guide shall be added as text to the "Figma Guide" page around the link
- The link shall be of the visual component selected by the Design team to be reflective of the standard design of the Documentation Site for consistency

### Notes

---

### Prerequisites
- None Identified

### Tasks
- None Identified

**Comment by sarinapadilla** [comment]
For the hard launch: component pages will link to specific component documentation in Figma (not just the overall Figma link).

**Comment by laurelthrash** [comment]
Includes Figma guide and specific documentation for each component.

**Comment by laurelthrash** [comment]
@blilianyu @monika-jaeger to start creating this language (may comp as well). @adrianacastaneda send example to share all information needed. (Example here: https://design.gs.com/designers)

**Comment by laurelthrash** [comment]
Note from 08/28 meeting with Anna regarding how federal users can obtain a Figma file. 
- Notes: In order to download a community file and use the file to create comps or prototypes, they need to download the Figma software and have some sort of license (e.g., individual or part of a team).
- Decision: For now (for Pilot), assume that people have the tools/software they need to work with the assets we are providing and use opportunity to get input from the piloting folks. Don't provide instructions regarding how to obtain a license, but monitor to see if this becomes a barrier for DOCs to use the design system

**Comment by blilianyu** [comment]
@dcvijanovic1k this is ready for review!

cc: @monika-jaeger @laurelthrash

**Comment by dcvijanovic1k** [comment]
Document reviewed and notes have been left. cc @blilianyu @monika-jaeger

**Comment by laurelthrash** [comment]
Doc updated per @dcvijanovic1k feedback. Sharing with Brianna for designer review. Cc: @blilianyu @monika-jaeger

**Comment by laurelthrash** [comment]
Brianna provided feedback. With @blilianyu @monika-jaeger for updates.

**Comment by laurelthrash** [comment]
Brianna's feedback resolved.

**Comment by bennettcc** [comment]
This page is ready to be added into the documentation site. The markdown file and images have been attached to the desc

**Comment by dcvijanovic1k** [comment]
Hi @dlescarbeau - here are all the images for the Figma guide, saved out at 2x. Filenames are the same. If you run into any other issues, please let me know! 
[figma-guide-images_2x.zip](https://github.com/NCIOCPL/ncids/files/12795464/figma-guide-images_2x.zip)

**Comment by dlescarbeau** [comment]
@dcvijanovic1k That folder of images was perfect! Much more clear. However, there are only 10 images where the page is using 11, I think I am missing `figma-guide_grid-styles.png`

**Comment by dcvijanovic1k** [comment]
@dlescarbeau - Glad to hear they work! Here's the missing image (apologies for that); if you need anything else, please let me know. 
<img width="753" alt="figma-guide_grid-styles" src="https://github.com/NCIOCPL/ncids/assets/102183929/f8a427d2-c50b-442a-ba21-dcf5e3fb024d">

**Comment by dcvijanovic1k** [comment]
Hello again @dlescarbeau - here's a zip file of JPGs for the Figma Guide page. Any issues with these, don't hesitate to reach out!
[figma-guide-static-images-jpgs.zip](https://github.com/NCIOCPL/ncids/files/12807762/figma-guide-static-images-jpgs.zip)

**Comment by dcvijanovic1k** [comment]
Hiya @dlescarbeau - here's an updated version of figma-guide_components-resources02.jpg, with a white background this time. Hopefully this resolves it! 
![figma-guide_components-resources02](https://github.com/NCIOCPL/ncids/assets/102183929/c73182e5-fd74-4c83-8c5e-af87ec490917)
