### ISSUE TITLE
NCIDS For All Pilot - Design Principles

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#935]
## As a designer/site owner, I want to see the design principles utilized, so that I don't create compositions that go against the principles.

* Create a page of considerations made for creating compositions (benchmark against other design systems)
* Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BAB22DBD8-0726-48E2-B552-8A83AA4DA28B%7D&file=Design%20Principles.docx&wdLOR=cB7694553-9FCF-F648-AB98-50A437B71553&action=default&mobileredirect=true)
* How we used UX research to drive our design decisions
* Bring in some documentation from Figma
* Accessibility section (see #941 for details)

Markdown:
https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/design_principles_markdown.txt?csf=1&web=1&e=SA7bPZ
[design_principles_markdown (1).txt](https://github.com/NCIOCPL/ncids/files/12819963/design_principles_markdown.1.txt)

Note – svg's not being directly consumed in our doc site. However we do have an icon component in src/components/icon/ that could be re-used for this purpose. Sprite path needs to be updated and some tweaking.  

 

SVG code for icons  

<svg class="usa-icon" aria-hidden="true" focusable="false" role="img"> 

        <use xlink:href="/assets/img/sprite.svg#image"></use> 

      </svg> 

 

<svg class="usa-icon" aria-hidden="true" focusable="false" role="img"> 

        <use xlink:href="/assets/img/sprite.svg#accessibility_new"></use> 

      </svg> 

 

<svg class="usa-icon" aria-hidden="true" focusable="false" role="img"> 

        <use xlink:href="/assets/img/sprite.svg#chat"></use> 

      </svg> 

 

<svg class="usa-icon" aria-hidden="true" focusable="false" role="img"> 

        <use xlink:href="/assets/img/sprite.svg#code"></use> 

      </svg> 

 

<svg class="usa-icon" aria-hidden="true" focusable="false" role="img"> 

        <use xlink:href="/assets/img/sprite.svg#people"></use> 

      </svg>

**Comment by laurelthrash** [comment]
Not blocked and available for pickup. Will pick up in conjunction with Figma page content.

**Comment by blilianyu** [comment]
Figma comp for "[Design Principles](https://www.figma.com/file/8qu1psEjnehVDoZyWrH7ny/NCIDS-For-All?type=design&node-id=406%3A2703&mode=design&t=q5JrQKW8m7WaWh89-1)" page.

@monika-jaeger and I will be adding content in this document: [Design Principles Document](https://www.figma.com/file/8qu1psEjnehVDoZyWrH7ny/NCIDS-For-All?type=design&node-id=406%3A2703&mode=design&t=q5JrQKW8m7WaWh89-1).

cc: @laurelthrash

**Comment by blilianyu** [comment]
@dcvijanovic1k this is ready for review! We kept this fairly short based on what other design systems have for their design principles. 
cc: @monika-jaeger @laurelthrash

**Comment by laurelthrash** [comment]
Doc updated per @dcvijanovic1k feedback. Sharing with Brianna for designer review. Cc: @blilianyu @monika-jaeger

**Comment by laurelthrash** [comment]
Brianna reviewed and did not have any feedback. Considering this "Complete" from drafting perspective. Assigning to @lburack to review for voice and tone.
