### ISSUE TITLE
NCIDS For All Pilot - Utilities Page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#936]
## As a developer (someone who creates content on the site), I want to be able to view the utilities pages, so that I can quickly reference the utilities provided.

* Determine which items are classified as utilities
* Where are they referenced across USWDS
* Can this just be a utilities page within the design tokens? (if there aren't that many)
  * Based on this, it may be included in #934 

We need to document things that USWDS did not document, and things that we've created.
* Didn't document: place icon, etc
* We created: external link, loader spinner, etc

### Notes

---

### Prerequisites
- None Identified

### Tasks
- None Identified

**Comment by laurelthrash** [comment]
Utilities are no longer a stand-alone page, so utilities would be associated with design tokens.

**Comment by blilianyu** [comment]
@laurelthrash We created a combine Tokens & Utilities page. This ticket can be closed.

cc: @monika-jaeger @dcvijanovic1k

**Comment by sarinapadilla** [comment]
Updating #934 to indicate that it is for the combined design tokens and utilities page. Closing this ticket!

**Comment by laurelthrash** [comment]
Thank you, @blilianyu. I am marking this ticket as "done" from design side and will make a notation on #934, where we address design tokens. Cc: @monika-jaeger @andyvanavery @sarinapadilla
