### ISSUE TITLE
NCIDS For All Pilot - Accessibility

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#941]
## As a site owner, I want to know what accessibility has been considered in NCIDS, so that my website is legally compliant.

This does not need to be full documentation, but a section listing accessibility considerations. Also allows for us to get feedback if anyone bothers to read. 

This will probably be five words and then cross-linking to the accessibility documentation on individual components for the pilot. Anywhere that we want to reference accessibility, we will link to this section on the design principles page.

* Individual components: #944 
* Design principles parent page: #935

**Comment by bennettcc** [comment]
Moving to On Hold - the text will be copy edited by OCC then updated on this ticket

**Comment by andyvanavery** [comment]
Decision to not have a standalone Accessibility page on the NCIDS for All documentation site. Will move the Introductory paragraph to the Design Principles page. Requirements Meeting on 26JUL2023.
