### ISSUE TITLE
NCIDS For All Pilot - Accessibility on Component Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#944]
## As a developer, I want to know what accessibility features are available, so that I can make my website accessible.

Accessibility comes in two forms: conformance and compliance. Right now we have compliance, but we need to discuss conformance on our component pages.

This ticket is related to #935, which will need to link to accessibility information.

> **ESTIMATE** TBD

**Comment by laurelthrash** [comment]
Notes from 7/13 UX internal conversation regarding IA/design involvement:

- @arcepaul to initiate work on this ticket and tag in @monika-jaeger @adrianacastaneda (and other IA/design) as needed
- Presently, there is not a standalone accessibility section within the site map. @adrianacastaneda to slot in location on Mural site map for standalone a11y page. 

Cc: @bennettcc @sarinapadilla

**Comment by bennettcc** [comment]
Following 8/9 PM/PO discussion - closing this ticket, the review of accessibility content will be included as a part of the broader IA review of the document site and its content
