### ISSUE TITLE
NCIDS For All Pilot - Documentation Site Navigation

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#946]
## As anyone who uses NCIDS For All, I want to be able to navigate through the documentation site, so that I can easily reference and move between information.

* What do we want the navigation to be?
* ADD LIST OF TICKETS THAT ARE GOING TO BE PAGES/SUBPAGES/ETC. FOR THE NAVIGATION

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bennettcc** [comment]
Per standup 7/13: We will review this proposed site structure with the Feds, then move forward to development following approval

**Comment by laurelthrash** [comment]
No immediate changes needed on the site navigation based on 07/18 conversation. Passing to development to being building site. Cc: @lburack @adrianacastaneda @sarinapadilla @andyvanavery

**Comment by bennettcc** [comment]
As discussed in 7/25 backlog meeting, this ticket will not be used to track the dev work of the navigation. We'll be using https://github.com/NCIOCPL/ncids/issues/809

Will remove this from the dev board in favor of #809 

cc: @laurelthrash

**Comment by laurelthrash** [comment]
Per above comment, going to close this ticket since the initial site structure is complete. We will track further changes via #809. Cc: @adrianacastaneda @lburack @bennettcc
