### ISSUE TITLE
Design: Media Blocks 

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#95]
> **ESTIMATE** Story Points TBD

> Discovery Ticket: Discovery Kickoff: Article and Related Inline Content Features #62

## Description of Design request
Design for media blocks - made up of the media item (image, infographic, or video) and the attribution block (currently grey background with caption/credit)
Flavors of component:
- featured/article image
- inline image
- inline infographic
- inline video

### Component Details

- Caption/Credit block: https://www.notion.so/Caption-Credit-Media-Attribution-Block-0788723052ee4b26a6f9288eabae800c
- Media Block - Image: https://www.notion.so/Media-Block-Image-d29c3b8b29e340f492a391856500e577
- Media Block - Infographic: https://www.notion.so/Media-Block-Infographic-52ded72f631a43e593fc7befe32a0ced
- Media Block - Video: https://www.notion.so/Media-Block-Video-cc1fe825e6fd40a7bf33aae92eab276f

Drupal Report: https://lion.box.com/s/pgjtg7g1c42njajiqvljpq7mxu21l2hm

##

### List of sub-tasks:
*Add links to related tickets below*
- [x] Pull initial Drupal usage report for examples (Claire/Min)
- [ ] Wireframes
- [ ] Comps

##

### Design Functionality:
*Describe how the design should function, e.g. color changes on hover*
1. Specification 
2. Specification  
3. Specification 

##

### Design specs / InVision:
*Design specs indicated in the InVision links below. Please view in the inspect mode along with the comments panel*
1. InVision link
2. InVision link
3. InVision link

##

### Assets:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

##

### Design Research & Inspiration:
*Space to add inspiration, moodboards,etc*

##

**Comment by VictoriaSunNIH** [comment]
These have been separated into their own design tickets for #157 , #160 , #161 , #209 , #210
