### ISSUE TITLE
Update styles for subheading on NCIDS home and landing pages with titles

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#962]
We need to update the font styling for the subheading that displays under the title on home and landing pages.

**Comment by andyvanavery31** [comment]
@blilianyu @monika-jaeger to investigate the next steps for this ticket.

**Comment by monika-jaeger** [comment]
@andyvanavery31 Looking back at the Home and Landing Page comps, we were talking about bolding the subheading.

Here is a [former comp ](https://www.figma.com/design/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?node-id=2937-18509&t=joNBg3vjJrwoVrWx-1) with the spacers and bolded styling for the subheading in Open Sans

cc: @blilianyu
