### ISSUE TITLE
fix all regressions

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#975]
While debugging issues with our workflow, regressions were found for nci-header search:

![failed_diff_ncids_nci-header_nci-extended_search_0_document_2_tablet](https://user-images.githubusercontent.com/85901679/236078361-6d152c2c-0da8-49f6-bad7-aa67a38f1018.png)

Search input appears smaller. 28 failed images all show similar issue. 

In addition, there are still bad images for table see #972.

Developer findings/notes:
- Commits from a month ago are now showing the same error while passing before
- No styles seemed to have changed in either nci-autocomplete, nci-header packages or in header stories 
- uswds package `usa-form` has been included since v2.0.0
- uswds package `usa-input` has been included since v2.0.0

Related:
- #972 
- #976

**Comment by bryanpizzillo** [comment]
This was closed in #979
