### ISSUE TITLE
NCIDS For All Pilot - Patterns

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#993]
## As a designer, I want to see NCIDS component patterns, so that I can reference suggestions for how group components.

* Create pages for component patterns (feature card row, 2 guide card row, alternating promo blocks with image, hero with CTA strip)
  * Includes guidance and component pattern code
* Cross link to these pages from the component pages

**Comment by laurelthrash** [comment]
Question to address: do we want to remove Patterns from the Documentation Site to instead pull patterns into the specific component page.

**Comment by laurelthrash** [comment]
Slated for discussion during UX team meeting Tues. 08/22.

**Comment by bennettcc** [comment]
Discussed on 8/22: The patterns page will be removed from the site structure of the the documentation site. There is not enough content to include within the section to warrant its own list of pages. Specific feature card, guide card, and home land landing pages will house relevant patterns content.
